### ISSUE TITLE
get the numpy value of an tensor variable parameter to optimize

### ISSUE THREAD

**Issue by cxz260** [lululxvi/deepxde#100]
Hi Lu, 

Similar setting in 97, I have a global constant 1D array C, whose index is my 1-D ode's input x(which are integers), however, this time I have an parameter for the initial index i0 to optimize(find the best i0 such that the ode matches the observed data points best):

i0=tf.Variable(10)

 in ode I have sth like(where C will a function call):

dy/dx=C[x+i0]*y

Here again I encountered how to get the numpy value of tensor variable i0. Is it possible to do such an optimization?

Thanks again for your help.

Eddie

**Comment by lululxvi** [comment]
No, numpy array cannot take tf variable as the input. You can try to convert the np array to tf array, but I am not sure whether this works. Also, if i0 is an integer, then I am not sure whether gradient descent can work correctly, because the local gradient is also 0.

**Comment by cxz260** [comment]
Thanks Lu, will try that out.
