### ISSUE TITLE
Incorrect Time Dependent Navier Stokes Equation for Inverse Problem

### ISSUE THREAD

**Issue by elliot-hicks** [lululxvi/deepxde#1000]
Hi @lululxvi ,

I think there is an error in your inverse example for the 2D Navier Stokes flow. If I am correct, you have taken the time derivatives outside of the density multiplication which actually simplifies the problem and leaks the correct density:

The DeepXDE *inverse* implementation:

![image](https://user-images.githubusercontent.com/92870956/199541421-0fa870d4-03ed-4126-8ea0-1b55d85f004f.png)

The Navier Stokes Equation:

![image](https://user-images.githubusercontent.com/92870956/199541828-51e6c57c-b0bb-4fea-97e9-57bebbded573.png)

The corrected Navier Stokes *inverse* in DeepXDE:

![image](https://user-images.githubusercontent.com/92870956/199541949-a5648c78-b1a5-4370-aeb8-50bdd9539bc8.png)

In removing the time derivative from the bracket, it is accidentally given a coefficient which happens to be the correct density value (1). This makes the problem a lot easier (pinning a scale on the rest of the terms) and, when corrected, the example no longer works.

Please let me know what you think of this as it would also mean there's an error in the original Raissi paper?  Or have I made a mistake here?

**Comment by elliot-hicks** [comment]
The output of the example when the corrected Navier Stokes equation is put in instead. Everything the else including data is the same.

![image](https://user-images.githubusercontent.com/92870956/199563147-2bbb22e2-b82b-4509-83fd-985cf28f2cfb.png)

**Comment by lululxvi** [comment]
This example is contributed by @zyz-rise 
It seems to me the code is consistent with the description of Section 4.1.1 in the original Raissi paper.

**Comment by elliot-hicks** [comment]
Interesting, as this extends from Raissi, I will close this issue. Thanks for the response @lululxvi , always a pleasure working with DeepXDE.

**Comment by elliot-hicks** [comment]
Interesting, as this extends from Raissi I will close this issue. Thanks for the response @lululxvi , always a pleasure working with DeepXDE.
