### ISSUE TITLE
Result Output of Time Dependent Problem

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#101]
Dear @lululxvi,
     I have a time-dependent problem that changes its result with time. 

Can I visualize the result at a particular time for the problem?

**Comment by lululxvi** [comment]
See "Q: What is the expected output of DeepXDE? How can I plot the results?" and "Q: How can I use a trained model for new predictions?" in FAQ

**Comment by SanjuSoni** [comment]
Thanks @lululxvi , it helps.
