### ISSUE TITLE
Code Compilation Error

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#102]
While running code, I am getting such error. Why this error is arising?

```
2020-08-16 23:16:09.267130: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Using TensorFlow 2 backend.

WARNING:tensorflow:From C:\Users\SUMANT\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:88: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

Process returned 0 (0x0)        execution time : 6.003 s
Press any key to continue . . .
```

**Comment by lululxvi** [comment]
Could you try run in CPU?

**Comment by SanjuSoni** [comment]
Thanks for your prompt reply,
I am using TensorFlow 1.15. and TensorFlow 2.0 GPU version.

- Is there a method for running code in CPU instead of installing TensorFlow of GPU version.
-  All code is working well that is taken from example [ODE example](https://github.com/lululxvi/deepxde/blob/master/examples/ode_system.py) after inserting path code.

inserted code for path is:

```
import sys
sys.path.insert( 0, "D:/DIAT_PhD/PhD_Content/Coding_Script/DeepXDECode/deepxde-master/deepxde-master")

```

kindly, comment on it.

**Comment by lululxvi** [comment]
Did you solve the problem?

Use the following to run on CPU
```
$ CUDA_VISIBLE_DEVICES=-1 python xx.py
```

**Comment by SanjuSoni** [comment]
Unfortunately, not, it does not help.

In command prompt after typing this 
`CUDA_VISIBLE_DEVICES=-1 python DarcyPorous.py`

a message appears as: 
`CUDA_VISIBLE_DEVICES' is not recognized as an internal or external command, operable program, or batch file.`


FYI: I was using the previous version of deepxde which was working fine but after downloading this new version of code, such error occurring.

I am working on Windows 10 OS.

I have attached a file with you that is not working correctly with the code.

**Comment by lululxvi** [comment]
I don't know how to run in Windows.

You code has some problem, everything is defined in `pde`. You may mixuse tabs and empty spaces.

**Comment by SanjuSoni** [comment]
Thanks @lululxvi 

It was my indentation and code error. I successfully figure it out.
Now, it is working well after rectifying my code with proper indentation.


Thanks.

**Comment by SanjuSoni** [comment]
dear @lululxvi 

- can we solve the integral problem using DeepXDE

- also please suggest me for defining dT_xy.

I have coded it as:


```
def pde(x,y):
     T = y[:, 0:1]
     dT_x = tf.gradients(T , x)[0]
      dT_x , dT_y = dT_x[:, 0:1 ], dT_x[:, 1:2]
     
     dT_xy = tf.gradients(  dT_y, x) [0][ : , 0:1 ]                 # dT_xy  stands for d2T/dxdy
      dT_yx = tf.gradients( dT_x, x) [0] [ : , 1:2]                 # dT_yx stands for d2T/dydx
```

Please suggest me for dT_xy and dT_yx

Am I doing right or any modification required.

**Comment by lululxvi** [comment]
Check DeepXDE full paper and Volterra_IDE.py in example for the integral PDE.

`tf.gradients(dT_y, x) [0][ : , 0:1]` is `d(dT/dy)/dx`

**Comment by SanjuSoni** [comment]
Thanks Sir

**Comment by SanjuSoni** [comment]
Dear Lu Sir
I am compiling  a code which is bases on your latest code including grad and jacobian method but I am getting an error.

Kindly suggest for fixing it.

code has  been included herewith

[problem7.zip](https://github.com/lululxvi/deepxde/files/5763218/problem7.zip)

**Comment by lululxvi** [comment]
Use `tf.sin` not `np.sin` when defining the PDE.

**Comment by SanjuSoni** [comment]
Thanks Sir,
After replacing np.sin with tf.sin, the error occurs at the gradients line.

error is:
 ```
File "C:\Users\SUMANT\Downloads\problem7\problem7.py", line 22, in pde
    dpsi_xx = dde.grad.hessian(y, x, i = 0, j = 0)
  File "D:/deepxde-master/deepxde-master\deepxde\gradients.py", line 162, in hessian
    return hessian._fn(ys, xs, component=component, i=i, j=j, grad_y=grad_y)
  File "D:/deepxde-master/deepxde-master\deepxde\gradients.py", line 132, in __call__
    key = (y.ref(), xs.ref(), _component)
AttributeError: 'Tensor' object has no attribute 'ref'
```


Also,
- can we perform the usual way of defining the auto gradient method with using tf.gradients that we used it before for definig the differential terms.

**Comment by lululxvi** [comment]
Use TensorFlow >= 2.2. You can also use `tf.gradients` as before

**Comment by SanjuSoni** [comment]
Thanks sir.

can we say that "results should not change after introducing the gradients or grad.hessian or Jacob in tensorflow".

**Comment by lululxvi** [comment]
No. the Results will be the same.
