### ISSUE TITLE
Get, save, load weights and biases from a trained PINN

### ISSUE THREAD

**Issue by SujithSrinivaas** [lululxvi/deepxde#103]
I would like to get the trained weights from the NN, make few alterations to the weights and again load them to the same NN and predict the outcome.
 
Generally, in KERAS it is possible to get weights from the trained NN using **"model.get_weights()"** and also use similar syntax to save and load weights. Is it possible to do the same in DeepXDE package? If so, can you let me know how to do that?

**Comment by lululxvi** [comment]
See "Q: How can I save a trained model and then load the model later?" at FAQ

**Comment by SujithSrinivaas** [comment]
Thank you Lululxvi for the prompt reply. 

I took a look at the FAQ. It just has methods to save and load the **model**. I don't have any problem with that.
The actual problem is to retrieve the **values** of the **weights and biases.**  I would like to see the numerical values of the stored weights and biases.

For example, I would like to train a NN for a problem, save just the weights and use those weights as an initial guess for training some other neural network. I would also like to change the values of the trained weights and biases and see how that affects the performance of the NN.

Please take a look at the below picture for reference from a keras program. I would like to take a look at each and every weight and bias of the trained neural network.

Please let me know. Thanks in advance.

![Annotation 2020-08-17 141357](https://user-images.githubusercontent.com/67124556/90429564-f5fc7a00-e093-11ea-8eee-33059aa9a625.jpg)

**Comment by lululxvi** [comment]
You can use `model._print_model()`

**Comment by SujithSrinivaas** [comment]
Thank you Lululxvi. I am able to take a look at the weights and biases.

Now, I would like to save these values into a variable (array) and then use those as an initial guess to solve a different NN with the same architecture. Basically, I would like to save these weights and load them back and forth into the model.

(i.e) Instead of using initializer = "Glorot Uniform", I would like to use those weights as the initial guess.

Is it possible to do that? Thanks in advance.

**Comment by lululxvi** [comment]
If you want to save the weights, and later load them back, you don't need to do it by yourself. There are examples at "Q: How can I save a trained model and then load the model later?" at FAQ.

**Comment by SujithSrinivaas** [comment]
Thanks for the advice Lululxvi. I went through all the four issues described under that question.

I am facing a problem when I try to restore a model and then train further.

If I am using the command model.restore(...) after model.train(...) like shown below, it works fine.
![before](https://user-images.githubusercontent.com/67124556/90443573-7af28e00-e0aa-11ea-98d4-04eaf5722fd0.jpg)

But when I use the command before model.train(...), I get the following error.
![after](https://user-images.githubusercontent.com/67124556/90443824-de7cbb80-e0aa-11ea-9100-b9f9d37fb19e.jpg)
![error1](https://user-images.githubusercontent.com/67124556/90443663-9a89b680-e0aa-11ea-8c0b-e8a870795d09.jpg)
![error2](https://user-images.githubusercontent.com/67124556/90443667-9d84a700-e0aa-11ea-96d4-b6efad7d4c0f.jpg)

If I use the command shown below, I still get the above error.
![restore_path](https://user-images.githubusercontent.com/67124556/90443700-ae351d00-e0aa-11ea-978d-33c0f70472b5.jpg)

I am not sure why this is happening. Please let me know.

FYI: I am using Windows

**Comment by lululxvi** [comment]
You need to call `model.compile` before `train` or `restore`.

**Comment by SujithSrinivaas** [comment]
I used model.compile before restore. Sorry that it was not on the snippet of the code that I have attached. Please find below, the snippet of the code.
![restore](https://user-images.githubusercontent.com/67124556/90529140-61e8ec00-e141-11ea-92d9-8143f12ffb7d.jpg)

It still shows the same error as I mentioned above.

Even when I use model.compile only once instead of twice as shown above, it still throws out the same error. 

Is there any work around for it? If required I am ready to share the code with you.

Thanks in advance.

**Comment by SujithSrinivaas** [comment]
I am just using the code available for Poisson_Dirichlet_1d code with slight modifications to the pde.

**Comment by lululxvi** [comment]
Could you show the code?

**Comment by SujithSrinivaas** [comment]
Sure. Please find my code below.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np

import deepxde as dde
from deepxde.backend import tf

def pde(x, y):
    dy_x = tf.gradients(y, x)[0]
    dy_xx = tf.gradients(dy_x, x)[0]
    total = 0
    for k in range(1,6):
        l = 2 * k * (tf.sin(2 * k * x))
        total = total + l
    return -dy_xx - total

def boundary(x, on_boundary):
    return on_boundary

def func(x):
    total = 0
    for k in range(1,6):
        l = (np.sin(2 * k * x)) / (2 * k)
        total = total + l
    return total

geom = dde.geometry.Interval(-np.pi, np.pi)
bc = dde.DirichletBC(geom, func, boundary)
data = dde.data.PDE(geom, pde, bc, 500, 2, solution=func, num_test=100)

layer_size = [1] + [20] * 4 + [1]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=0.0001, metrics=["l2 relative error"])
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, callbacks = [checkpointer])
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
The code is working fine until here. But now after training, I would like to make changes to the pde and run 'data' again keeping the network the same. **I get the same error even if I don't make any changes to data.**

```
# Make changes to the 'data' variable keeping the 'net' constant and then restore the model and train again
model = dde.Model(data, net)
model.compile("adam", lr=0.0001, metrics=["l2 relative error"])
model.restore("model/model.ckpt-5000")
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, callbacks = [checkpointer])
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
Here model.restore produces the following error
![error1](https://user-images.githubusercontent.com/67124556/90586778-00a73400-e1a6-11ea-9cad-6dd9191e49d9.jpg)
![error2](https://user-images.githubusercontent.com/67124556/90586786-03a22480-e1a6-11ea-83fe-d458f9e47cb5.jpg)

The rest of the code is just plotting
```
# Plot PDE residue
x = geom.uniform_points(1000, True)
y = model.predict(x, operator=pde)
plt.figure()
plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("PDE residue")
plt.show()
```
Please let me know. Thanks in advance.

**Comment by lululxvi** [comment]
Could you check if there is "model/model.ckpt-5000" file?

**Comment by SujithSrinivaas** [comment]
Yes. I have.

![ckpt](https://user-images.githubusercontent.com/67124556/90643243-5c52db00-e201-11ea-8971-11c2c1b1f62f.jpg)


`model.restore(...)` works when I call it immediately after training. It does not work if I call `model = dde.Model(data, net)` after training and before calling restore.

For example:
```
model = dde.Model(data, net)
model.compile("adam", lr=0.0001, metrics=["l2 relative error"])
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, callbacks = [checkpointer])
model.restore("model/model.ckpt-5000")
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```

The above code works fine without any problems. But the code found below throws the error showed in my previous message.

```
model = dde.Model(data, net)
model.compile("adam", lr=0.0001, metrics=["l2 relative error"])
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, callbacks = [checkpointer])
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

model = dde.Model(data, net) 
# If I use the above line of code after training and before calling restore, error shows up in the line model.restore(...)
model.compile("adam", lr=0.0001, metrics=["l2 relative error"])
model.restore("model/model.ckpt-5000")       #Thows error over here.
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, callbacks = [checkpointer])
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
Please let me know. Thanks in advance.

**Comment by lululxvi** [comment]
- Could you try not to use `model.restore`, and instead use `model.train(..., model_restore_path="...")` which will restore first and then train?
- Also, if it is possible, try to run the code in Linux.

**Comment by SujithSrinivaas** [comment]
Thank you so much Lululxvi.

`losshistory, train_state = model.train(epochs=10000, model_restore_path = "./model/model.ckpt-5000", callbacks = [checkpointer])`

The above code works perfectly today for windows (I did not try it in LINUX).
I tried the same thing 2 days back [(Last image in the comment)](https://github.com/lululxvi/deepxde/issues/103#issuecomment-675111934)  it did not work then. Not sure why that happened.

I hope that this works throughout.

**Comment by SanjuSoni** [comment]
@SujithSrinivaas 
could you please share the last code snippet implemented for storing and restoring the saved model parameters.

**Comment by SujithSrinivaas** [comment]
@SanjuSoni 
You can use `model._print_model()` to look at the weight and biases of your FNN. Refer [comment](https://github.com/lululxvi/deepxde/issues/103#issuecomment-675042986)

Find the code that I used to store and restore model below.

```
geom = dde.geometry.Interval(-np.pi, np.pi)
bc = dde.DirichletBC(geom, func, boundary)
data = dde.data.PDE(geom, pde, bc, 100, 2, solution=func, num_test=100)

layer_size = [1] + [20] * 4 + [1]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=l_r, metrics=["l2 relative error"])
checkpointer = dde.callbacks.ModelCheckpoint("./model/model.ckpt", verbose=1, save_better_only=True)
losshistory, train_state = model.train(epochs=5000, model_restore_path = "./coeff/amp_1divided30_k_cube-50000", callbacks = [checkpointer])

dde.saveplot(losshistory, train_state, issave=True, isplot=True)
model.save("./coeff/amp_1divided2e3_k_powerfive")
```

**Comment by AlirezaPa** [comment]
Thank you @lululxvi  for your library. It is very helpful for our research. My issue seems very simple, and I checked all the comments in the FAQ but could not figure out this problem. The trained model was successfully saved but cannot be restored. For your convenience, I present here your Poisson_Dirichlet_1d. py to see the error. Thank you.

The error says: The passed save_path is not a valid checkpoint: /content/gdrive/MyDrive/codes/model.ckpt-8000

Below is the code:

def pde(x, y):
    dy_xx = dde.grad.hessian(y, x)    
    return -dy_xx - np.pi ** 2 * tf.sin(np.pi * x)
 
def boundary(x, on_boundary):
    return on_boundary

def func(x):
    return np.sin(np.pi * x)

geom = dde.geometry.Interval(-1, 1)
bc = dde.DirichletBC(geom, func, boundary)
data = dde.data.PDE(geom, pde, bc, 16, 2, solution=func, num_test=100)

layer_size = [1] + [50] * 3 + [1]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=0.001, metrics=["l2 relative error"])

checkpointer = dde.callbacks.ModelCheckpoint("/content/gdrive/MyDrive/codes/model.ckpt", verbose=1, save_better_only=True )

losshistory, train_state = model.train(epochs=10000, callbacks=[checkpointer])

dde.saveplot(losshistory, train_state, issave=True, isplot=True)

model.restore("/content/gdrive/MyDrive/codes/model.ckpt-" + str(train_state.best_step), verbose=1)


![image](https://user-images.githubusercontent.com/93855073/150733639-dc9aa68f-22e2-42ab-9c98-4362dd56c846.png)
