### ISSUE TITLE
Incorrect tag - typo

### ISSUE THREAD

**Issue by PallHaraldsson** [lululxvi/deepxde#1031]
At https://github.com/lululxvi/deepxde

I see "tesnorflow", and it doesn't help with discoverability. I didn't know, and was intrigued to learn you can make same code for different backends, even paddle.

**Comment by lululxvi** [comment]
Do you suggest to remove all backend tags: tensorflow, pytorch, etc.?

**Comment by PallHaraldsson** [comment]
No just letting you know you have a typo (the main message), so add "tensorflow" and I suppose drop the corresponding tag with the typo. I see though many others also use the tag with the typo, just way more with correct spelling. I doubt that's a good argument to keep the one with the typo...

The comment on backends was redundant, just what I found intriguing. Since you support them all I suppose they should stay, unless you want to drop some backends or maybe if one is the best supported?

**Comment by lululxvi** [comment]
Typo fixed. Thanks.
