### ISSUE TITLE
"RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead" when calculating boundary_normal

### ISSUE THREAD

**Issue by Decem5150** [lululxvi/deepxde#1046]
Dear @lululxvi,
Thank you for your wonderful framework.
I am solving the 2D compressible Euler equation for the flow around a cylinder, where I have to define the slip wall boundary condition for velocity, i.e., the normal component of velocity on the surface of the cylinder is equal to zero.
This is how I define the bc
```python
cylinder = dde.geometry.Disk([0, 0], 1.0)
rectangular = dde.geometry.Rectangle([-3, -2], [3, 2])
def inner(x, on_boundary):
    return on_boundary and cylinder.on_boundary(x)
def normal_vel(inputs, outputs, X):
    velocity = outputs[:,1:3]
    normal = cylinder.boundary_normal(inputs)
    return torch.sum(velocity * normal, 1, keepdim=True)
geom = rectangular - cylinder
bc_inner_velocity = dde.icbc.OperatorBC(
    geom, normal_vel, inner
)
```
Then I get this error
```
in boundary_normal
    _n = x - self.center
  File "/home/user/anaconda3/lib/python3.9/site-packages/torch/_tensor.py", line 757, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
I also tried running on macOS, and it gave me a different error
```
in normal_vel
    normal = cylinder.boundary_normal(inputs)
  File "/Users/decem/miniconda3/envs/env1/lib/python3.10/site-packages/deepxde/geometry/geometry_2d.py", line 40, in boundary_normal
    _n = x - self.center
  File "/Users/decem/miniconda3/envs/env1/lib/python3.10/site-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```
It seems the problem is where I calculate the normal vector, but I don't know how to fix it.
I also tried running the Helmholtz equation over a 2D square domain with a hole example, where boundary_normal is also called, but no error popped up.

**Comment by Decem5150** [comment]
I think this is caused by defining the geometry's center as ndarray. Therefore subtraction from `inputs` (tensor) by `self.center` (ndarray) may raise an error. I fixed it by casting `self.center` to a tensor manually and it runs well now.

**Comment by elliot-hicks** [comment]
@Decem5150  you should apply boundary.normal to `X` as it is the np version of `inputs`.

**Comment by Decem5150** [comment]
@elliot-hicks Thanks for replying. I tried replacing `inputs` with `X`, but it would raise another error as this makes 
```python 
normal = cylinder.boundary_normal(inputs)
```
return a `numpy.ndarray` and in the next line
```python
return torch.sum(velocity * normal, 1, keepdim=True)
```
multiplication between `velocity`(`torch.tensor`) and `normal`(`numpy.ndarray`) is not defined.

**Comment by elliot-hicks** [comment]
@Decem5150 you need to cast `normal` as a torch tensor - multiplication between Tensor and np arrays is not supported by pytorch.  use `normal = torch.from_numpy(normal)` or something along those lines

**Comment by elliot-hicks** [comment]
@Decem5150 Luckily I did the exact same function a few weeks ago.  Dont forget to close this issue - happy coding!

**Comment by giakbottacini** [comment]
Hi,
I'm also solving a 2D Euler Problem around a cylinder but the way to impose the no penetration BC proposed above doesn't run on Colab (where i'm working). Do you know why?
Thanks

**Comment by elliot-hicks** [comment]
Please could you show your code and the traceback message?

**Comment by giakbottacini** [comment]
This is the code

```python
!pip install deepxde
import deepxde as dde
import matplotlib.pyplot as plt
import numpy as np
import torch
import tensorflow as tf
tf.compat.v1.enable_eager_execution()
input_shape  = 2
output_shape = 5
u_inf = 0.2 # 136.12
rho_inf = 0.1 
E_inf = 1 
learning_rate_phase1 = 10**-3
iterations_phase1 = 30000
nu_glob = 2.
def pde_cost(x, y):
    u   =     y[:, 0:1]
    v   =     y[:, 1:2]
    E   =     y[:, 2:3]
    rho =     y[:, 3:4]
    nu  =     y[:, 4:5]

    #Ratio of specific heats for the air
    k = 1.4

    #Equation of state of ideal gases
    p = rho * (k-1) * (E - rho * (u**2 + v**2) / 2)

    du_x = dde.grad.jacobian(y, x, i=0, j=0)
    du_y = dde.grad.jacobian(y, x, i=0, j=1)
    dv_x = dde.grad.jacobian(y, x, i=1, j=0)
    dv_y = dde.grad.jacobian(y, x, i=1, j=1)
    dE_x = dde.grad.jacobian(y, x, i=2, j=0)
    dE_y = dde.grad.jacobian(y, x, i=2, j=1)
    drho_x = dde.grad.jacobian(y, x, i=3, j=0)
    drho_y = dde.grad.jacobian(y, x, i=3, j=1)

    dp_x = (k-1) * drho_x * (E - rho * (u**2 + v**2) / 2) + (k-1) * rho * (dE_x - drho_x * u**2 / 2 - rho * du_x - drho_x * v**2 / 
    2 - rho * dv_x)
    dp_y = (k-1) * drho_y * (E - rho * (u**2 + v**2) / 2) + (k-1) * rho * (dE_y - drho_y * u**2 / 2 - rho * du_y - drho_y * v**2 / 
    2 - rho * dv_y)

    nu_tilde = nu_glob

    #L_visc = my_abs(nu-nu_tilde)
    L_visc = abs((nu - nu_tilde))
    # L_visc = (nu - nu_tilde)**2

    continuity =  ( u * drho_x + rho * du_x ) + ( v * drho_y + rho * dv_y )
    x_momentum =  ( u**2 * drho_x + 2*u*rho * du_x + dp_x) + ( u*v*drho_y + v*rho*du_y + rho*u*dv_y )
    y_momentum =  ( u*v*drho_x + v*rho*du_x + rho*u*dv_x ) + ( v**2 * drho_y + 2*v*rho * dv_y + dp_y )
    energy_conservation = ( ( E*u*drho_x + rho*u*dE_x + rho*E*du_x ) + ( u * drho_x + rho * du_x ) ) + ( ( E*v*drho_y + 
    rho*v*dE_y + rho*E*dv_y ) + ( v*drho_y + rho*dv_y ) )
    return [continuity, x_momentum, y_momentum, energy_conservation, L_visc]

Lx_min, Lx_max = -1.0, 1.0
Ly_min, Ly_max = -1.0, 1.0
outer = dde.geometry.Rectangle([Lx_min, Ly_min], [Lx_max, Ly_max])
R = 0.1
cylinder = dde.geometry.Disk([0, 0], R)

spatial_domain = dde.geometry.CSGDifference(outer, cylinder)    

bc_o1 = dde.icbc.DirichletBC(spatial_domain, lambda x: u_inf, boundary_outer, component=0)
bc_o2 = dde.icbc.DirichletBC(spatial_domain, lambda x: 0, boundary_outer, component=1)
bc_o3 = dde.DirichletBC(spatial_domain, lambda x: E_inf, boundary_outer, component=2)
bc_o4 = dde.DirichletBC(spatial_domain, lambda x: rho_inf, boundary_outer, component=3)

def inner(x, on_boundary):
    return on_boundary and cylinder.on_boundary(x)

def normal_vel(inputs, outputs, X):
    velocity = outputs[:, 0:2]
    normal = cylinder.boundary_normal(X)
    normal = np.array(normal)
    normal_velocity = tf.reduce_sum(tf.multiply(velocity, normal), axis=1, keepdims=True)
    return normal_velocity

bc_c1 = dde.icbc.OperatorBC(spatial_domain, normal_vel, inner)

data = dde.data.PDE(
    spatial_domain,
    pde_cost,
    [bc_o1,bc_o2,bc_o3,bc_o4,bc_c1],
    num_domain=10000,        
    num_boundary=1000,      
    num_test=100, 
    train_distribution = 'pseudo'
    )
    
layer_size = [input_shape] + [30] * 7 +[output_shape]activation = "tanh"
initializer = "Glorot uniform"
net = dde.nn.FNN(layer_size, activation, initializer)
model = dde.Model(data, net)
loss_weights = [1,1,1,1, 5, 1,1,1,1,1]   
early_stopping = dde.callbacks.EarlyStopping(min_delta=1e-4, patience=2000)

s = list()
t = list()
model.compile(
    "adam", lr=learning_rate_phase1,  loss_weights=loss_weights #,metrics=["l2 relative error"]
)
losshistory, train_state = model.train(iterations=iterations_phase1,callbacks=[early_stopping])
s.append(losshistory)
t.append(train_state)

**Comment by giakbottacini** [comment]
And the error given to me from dde.nn.FN is 

RuntimeError                              Traceback (most recent call last)
[<ipython-input-14-88d5088922e8>](https://localhost:8080/#) in <cell line: 6>()
      4 activation = "tanh"
      5 initializer = "Glorot uniform"
----> 6 net = dde.nn.FNN(layer_size, activation, initializer)
      7 model = dde.Model(data, net)
      8 loss_weights = [1,1,1,1, 5, 1,1,1,1,1]    # 4 weights for PDE, 1 for viscosity, 5 for BC

2 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py](https://localhost:8080/#) in placeholder(dtype, shape, name)
   3269   """
   3270   if context.executing_eagerly():
-> 3271     raise RuntimeError("tf.placeholder() is not compatible with "
   3272                        "eager execution.")
   3273 

RuntimeError: tf.placeholder() is not compatible with eager execution.

Thanks

**Comment by giakbottacini** [comment]
@elliot-hicks this is the error that i have. It's the same that i obtained even using the same code you suggested to @Decem5150. Thanks for your time

**Comment by elliot-hicks** [comment]
Hi @giakbottacini , I dont recognise this line: `tf.compat.v1.enable_eager_execution()`, is it needed? Apologies I'm not entirely sure otherwise.

**Comment by giakbottacini** [comment]
I had inserted it to try to solve the problem
Now that i cancelled it gives me error in model.compile 
The error is:
Compiling model...
'compile' took 2.246765 s

Training model...

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1401     try:
-> 1402       return fn(*args)
   1403     except errors.OpError as e:

10 frames
InvalidArgumentError: 2 root error(s) found.
  (0) INVALID_ARGUMENT: Incompatible shapes: [13551,2] vs. [2651,2]
	 [[{{node mul_185}}]]
	tf2xla conversion failed while converting cluster_1[_XlaCompiledKernel=true,_XlaHasReferenceVars=true,_XlaNumConstantArgs=0,_XlaNumResourceArgs=0]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[cluster_1_1/xla_compile]]
	 [[cluster_1_1/merge_oidx_1/_9]]
  (1) INVALID_ARGUMENT: Incompatible shapes: [13551,2] vs. [2651,2]
	 [[{{node mul_185}}]]
	tf2xla conversion failed while converting cluster_1[_XlaCompiledKernel=true,_XlaHasReferenceVars=true,_XlaNumConstantArgs=0,_XlaNumResourceArgs=0]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[cluster_1_1/xla_compile]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1419                     '\nsession_config.graph_options.rewrite_options.'
   1420                     'disable_meta_optimizer = True')
-> 1421       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1422 
   1423   def _extend_graph(self):

InvalidArgumentError: Graph execution error:

Detected at node 'mul_185' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
    File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    File "<ipython-input-14-e7839966d52f>", line 4, in <cell line: 4>
    File "/usr/local/lib/python3.10/dist-packages/deepxde/utils/internal.py", line 22, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/deepxde/model.py", line 137, in compile
    File "/usr/local/lib/python3.10/dist-packages/deepxde/model.py", line 187, in _compile_tensorflow_compat_v1
    File "/usr/local/lib/python3.10/dist-packages/deepxde/model.py", line 172, in losses
    File "/usr/local/lib/python3.10/dist-packages/deepxde/data/data.py", line 17, in losses_test
    File "/usr/local/lib/python3.10/dist-packages/deepxde/data/pde.py", line 175, in losses
    File "/usr/local/lib/python3.10/dist-packages/deepxde/icbc/boundary_conditions.py", line 162, in error
    File "<ipython-input-9-cbacf51f6e4e>", line 9, in normal_vel
    
    Thanks a lot for your time

**Comment by giakbottacini** [comment]
sorry @elliot-hicks, the error is in model.train not in model.compile

**Comment by elliot-hicks** [comment]
@giakbottacini The code snippet appears to be incomplete so I cant run it myself, first guess is that ```tf.reduce_sum(tf.multiply(velocity, normal), axis=1, keepdims=True)``` throws an error because one is a np.array and one is a Tensor.

**Comment by elliot-hicks** [comment]
See the above comment:

> @elliot-hicks Thanks for replying. I tried replacing `inputs` with `X`, but it would raise another error as this makes
> 
> ```python
> normal = cylinder.boundary_normal(inputs)
> ```
> 
> return a `numpy.ndarray` and in the next line
> 
> ```python
> return torch.sum(velocity * normal, 1, keepdim=True)
> ```
> 
> multiplication between `velocity`(`torch.tensor`) and `normal`(`numpy.ndarray`) is not defined. So I rewrote it this way and it worked
> 
> ```python
> def normal_vel(inputs, outputs, X):
>     velocity = outputs[:,1:3]
>     normal = cylinder.boundary_normal(X)
>     normal = torch.from_numpy(normal).cuda()
>     return torch.sum(velocity * normal, 1, keepdim=True)
> ```

**Comment by giakbottacini** [comment]
Using the function that you @elliot-hicks  suggested to @Decem5150 i have an error in model.compile.
The error is 
Compiling model...
Building feed-forward neural network...
'build' took 0.167001 s

/usr/local/lib/python3.10/dist-packages/deepxde/nn/tensorflow_compat_v1/fnn.py:116: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  return tf.layers.dense(
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-14-e7839966d52f>](https://localhost:8080/#) in <cell line: 4>()
      2 s = list()
      3 t = list()
----> 4 model.compile(
      5     "adam", lr=learning_rate_phase1,  loss_weights=loss_weights #,metrics=["l2 relative error"]
      6 )

9 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py](https://localhost:8080/#) in _ExtractInputsAndAttrs(op_type_name, op_def, allowed_list_attr_map, keywords, default_type_attr_map, attrs, inputs, input_types)
    559           raise err
    560         else:
--> 561           raise TypeError(
    562               f"Expected {dtypes.as_dtype(dtype).name} passed to parameter "
    563               f"'{input_arg.name}' of op '{op_type_name}', got "

TypeError: Expected float32 passed to parameter 'y' of op 'Mul', got tensor([[-0., -0.],
        [-0., -0.],
        [0., 0.],
        ...,
        [-0., 0.],
        [-0., 0.],
        [0., 0.]], device='cuda:0') of type 'Tensor' instead. Error: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by giakbottacini** [comment]
I don't know if it's due to the fact i'm using a different gpu. I'm using colab with the T4

**Comment by giakbottacini** [comment]
So now the i have no problem on the function normal_vel but model.train gives me this error

Compiling model...
Building feed-forward neural network...
'build' took 0.108202 s

/usr/local/lib/python3.10/dist-packages/deepxde/nn/tensorflow_compat_v1/fnn.py:116: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  return tf.layers.dense(
TIPO VELOCITY
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION VELOCITY
(None, 2)
DIMENSION NORMAL
(13444, 2)
TIPO NORMAL
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION NORMAL
(13444, 2)
DIMENSION MULTIPLIED
(13444, 2)
TIPO RESULT
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION RESULT
(13444, 1)
DIMENSION INPUTS
(None, 2)
TIPO VELOCITY
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION VELOCITY
(None, 2)
DIMENSION NORMAL
(13444, 2)
TIPO NORMAL
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION NORMAL
(13444, 2)
DIMENSION MULTIPLIED
(13444, 2)
TIPO RESULT
<class 'tensorflow.python.framework.ops.SymbolicTensor'>
DIMENSION RESULT
(13444, 1)
DIMENSION INPUTS
(None, 2)
'compile' took 2.179216 s

Training model...

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1401     try:
-> 1402       return fn(*args)
   1403     except errors.OpError as e:

10 frames
InvalidArgumentError: 2 root error(s) found.
  (0) INVALID_ARGUMENT: Incompatible shapes: [13444,2] vs. [2544,2]
	 [[{{node Mul_1132}}]]
	tf2xla conversion failed while converting cluster_17[_XlaCompiledKernel=true,_XlaHasReferenceVars=true,_XlaNumConstantArgs=0,_XlaNumResourceArgs=0]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[cluster_17_1/xla_compile]]
	 [[cluster_17_1/merge_oidx_1/_9]]
  (1) INVALID_ARGUMENT: Incompatible shapes: [13444,2] vs. [2544,2]
	 [[{{node Mul_1132}}]]
	tf2xla conversion failed while converting cluster_17[_XlaCompiledKernel=true,_XlaHasReferenceVars=true,_XlaNumConstantArgs=0,_XlaNumResourceArgs=0]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[cluster_17_1/xla_compile]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1419                     '\nsession_config.graph_options.rewrite_options.'
   1420                     'disable_meta_optimizer = True')
-> 1421       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1422 
   1423   def _extend_graph(self):

InvalidArgumentError: Graph execution error:
