### ISSUE TITLE
How to solve for coefficients for simple functions using Deepxde

### ISSUE THREAD

**Issue by apapados** [lululxvi/deepxde#105]
Suppose I have data to a simple function e^(-x)sin(0.2x), for x is in [0,3pi]. If I know the form of the function Aexp(B*x)*sin(C*x), is it possible to use Deepxde to solve for these coefficients, if so, how may I do this? I've solved various inverse PDE problems using Deepxde, but attempted to solve an inverse problem for a simple function and could not figure this out. Thank you ahead of time for your assistance!

**Comment by lululxvi** [comment]
Do you mean you just want to solve A, B and C? Then there is no neural network here and no need to use DeepXDE. I may suggest to use grid search or Bayesian optimization to find A, B and C.

**Comment by apapados** [comment]
Thank you for your response. I am familiar with these approaches. I was curious if Deepxde could solve for these coefficients. The reason I ask is that Deepxde has function dde.data.Func, which can fit a provided function, so I was curious if it could solve the inverse problem.

**Comment by lululxvi** [comment]
DeepXDE will always use a neural network to represent a function. It is doable to use DeepXDE by defining a "dummy" network, but didn't use it at all. Specifically, define a "fake" PDE which is Aexp(B*x)sin(Cx), and then this is a inverse PDE problem.

**Comment by apapados** [comment]
HAHA! It's funny you mention this approach. I tried this originally and it worked well, I wasn't sure if this was the correct approach though. Thank you Lu Lu
