### ISSUE TITLE
New publication based on DeepXDE

### ISSUE THREAD

**Issue by Kostap7** [lululxvi/deepxde#1051]
Dear Lu Lu,

Thank you for your excellent framework and documentation. DeepXDE is great, and we use it in multiple projects in our research.

Here is the link to our most recent publication:
https://www.mdpi.com/1996-1073/15/20/7697

We are currently working on more publications where DeepXDE is utilized as well. 

Best regards,
Konstantinos

**Comment by lululxvi** [comment]
@eslee1685

**Comment by Kostap7** [comment]
Dear Lu Lu,

This is our newest publication that utilizes the DeepXDE library:
https://www.nature.com/articles/s41598-023-43325-1

Best regards,
Konstantinos
