### ISSUE TITLE
Governing equation for the contrast agent concentration

### ISSUE THREAD

**Issue by iMTimmyyy** [lululxvi/deepxde#108]
Dear @lululxvi, 

Hi I am trying to model and solve the following equation : 
![image](https://user-images.githubusercontent.com/66316241/90794193-13a13c00-e33f-11ea-880a-c48cca2816f5.png)
over a rectangle domain like this (20mm by 2mm):
![image](https://user-images.githubusercontent.com/66316241/90794967-12244380-e340-11ea-8ae4-3aa2839b00ff.png)
where there are zero-gradient boundary conditions at the upper, lower walls and outlet and a Dirichlet boundary condition at the inlet for the concentration. And for initial condition, it is zero everywhere. And velocity is 0.2 m/s in the x-direction

And my script is as follow:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import deepxde as dde
from deepxde.backend import tf

def main():

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_y, dy_t = dy_x[:, 0:1], dy_x[:, 1:2], dy_x[:, 2:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_yy = tf.gradients(dy_y, x)[0][:, 1:2]
        return dy_t + 0.2 * dy_x - 0.01 * (dy_xx + dy_yy)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 20e-3)

    def boundary_up(x, on_boundary):
        return on_boundary and np.isclose(x[1], 2e-3)

    def boundary_low(x, on_boundary):
        return on_boundary and np.isclose(x[1], 0)

    def func_zero(x):
        return np.zeros((len(x), 1))

    def func_one(x):
        return np.ones((len(x), 1))

    def func(x):
        return np.sin(x[:, 2:]/0.005)**2

    geom = dde.geometry.Rectangle(xmin=[0, 0], xmax=[20e-3, 2e-3])
    timeDomain = dde.geometry.TimeDomain(0, 0.5)
    geomtime = dde.geometry.GeometryXTime(geom, timeDomain)

    bc_l = dde.DirichletBC(geomtime, func, boundary_l)
    bc_r = dde.NeumannBC(geomtime, func_zero, boundary_r)
    bc_up = dde.NeumannBC(geomtime, func_zero, boundary_up)
    bc_low = dde.NeumannBC(geomtime, func_zero, boundary_low)
    ic = dde.IC(geomtime, func_zero, lambda _, on_initial: on_initial)

    data = dde.data.TimePDE(
        geomtime, pde, [bc_l, bc_r, bc_up, bc_low, ic], num_domain=5000, num_boundary=10000,  num_initial=150)

    layer_size = [3] + [50] * 4 + [1]
    activation_func = "tanh"
    initializer = "Glorot uniform"

    net = dde.maps.FNN(layer_size, activation_func, initializer)
    model = dde.Model(data, net)

    model.compile("adam", lr=1.5e-3)
    model.train(epochs=30000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train(model_save_path=r"C:\Users\timmy\PycharmProjects\examples\New\sin5D10Bdot5")
    dde.saveplot(losshistory, train_state, issave=False, isplot=True)

if __name__ == "__main__":
    main()

Originally, I was using a fixed value for the Dirichlet condition (func_one, 5000 Domain and 3000 boundary points) and it worked fine. However, when I changed the Dirichlet condition to sin^2(t/0.005), it behaved strangely. The test loss is much lower than train loss (e.g. train loss: 1e-1, test loss: 1e-4/-5) and the prediction I obtained is very different from numerical solutions.

The Prediction:
![image](https://user-images.githubusercontent.com/66316241/90796766-51ec2a80-e342-11ea-8b69-e51d75ea4ad2.png)
Numerical Solutions:
![image](https://user-images.githubusercontent.com/66316241/90796182-8f03ed00-e341-11ea-89b9-b5ad4d9ccd79.png)
 
Besides, when I tried to add the "num_test" argument in TimePDE I got the following error:

Traceback (most recent call last):
  File "C:/Users/timmy/PycharmProjects/examples/CA_Conc.py", line 111, in <module>
    main()
  File "C:/Users/timmy/PycharmProjects/examples/CA_Conc.py", line 51, in main
    geomtime, pde, [bc_l, bc_r, bc_up, bc_low, ic], num_domain=5000, num_boundary=3000,  num_initial=150, num_test=1000)
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\data\pde.py", line 162, in __init__
    num_test=num_test,
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\data\pde.py", line 45, in __init__
    self.test()
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\utils.py", line 23, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\data\pde.py", line 89, in test
    self.test_x = self.test_points()
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\data\pde.py", line 191, in test_points
    return self.geom.uniform_points(self.num_test)
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\geometry\timedomain.py", line 53, in uniform_points
    nt = int(np.ceil(n / nx))
ZeroDivisionError: division by zero

Process finished with exit code 1

And I got this error when I tried to add metrics = ["l2 relative error"] to model.complie("adam", lr=1.5e-3):
  File "C:\Users\timmy\AppData\Roaming\Python\Python37\site-packages\deepxde\metrics.py", line 15, in l2_relative_error
    return np.linalg.norm(y_true - y_pred) / np.linalg.norm(y_true)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

Could you help me identify what might be wrong?
Thank you in advance.

**Comment by lululxvi** [comment]
- The train loss includes all the loss terms, and the test loss only includes the PDE loss. Your train loss is large, and I suspect the IC loss term is large. You can check each loss term, and find out which one is large. 
- Try a small time domain firs, e.g., (0, 0.1), more training points, longer training
- `num_test` you used may be too small
- You need to pass the reference solution to the `solution` argument to compute "l2 relative error"

**Comment by iMTimmyyy** [comment]
Hi lulu, 

I have sort of figured out how to solve my problem by adjusting the ratio of my number of domain, boundary and initial condition point and using the argument `loss_weights` in `model.compile`.

Thank you for making this awesome deep learning library.

**Comment by katayooneshkofti** [comment]
@iMTimmyyy  is it possible to upload your final code?

**Comment by iMTimmyyy** [comment]
> @iMTimmyyy is it possible to upload your final code?

Sure, here you go.

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import deepxde as dde
from deepxde.backend import tf

def main():

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_y, dy_t = dy_x[:, 0:1], dy_x[:, 1:2], dy_x[:, 2:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_yy = tf.gradients(dy_y, x)[0][:, 1:2]
        return dy_t + 0.2 * dy_x - 0.01 * (dy_xx + dy_yy)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 20e-3)

    def boundary_up(x, on_boundary):
        return on_boundary and np.isclose(x[1], 2e-3)

    def boundary_low(x, on_boundary):
        return on_boundary and np.isclose(x[1], 0)

    def func_zero(x):
        return np.zeros((len(x), 1))

    def func_one(x):
        return np.ones((len(x), 1))

    def func(x):
        return np.sin(x[:, 2:3]/0.005)**2

    geom = dde.geometry.Rectangle(xmin=[0, 0], xmax=[20e-3, 2e-3])
    timeDomain = dde.geometry.TimeDomain(0, 0.1)
    geomtime = dde.geometry.GeometryXTime(geom, timeDomain)

    bc_l = dde.DirichletBC(geomtime, func, boundary_l)
    bc_r = dde.NeumannBC(geomtime, func_zero, boundary_r)
    bc_up = dde.NeumannBC(geomtime, func_zero, boundary_up)
    bc_low = dde.NeumannBC(geomtime, func_zero, boundary_low)
    ic = dde.IC(geomtime, func_zero, lambda _, on_initial: on_initial)

    data = dde.data.TimePDE(
        geomtime, pde, [bc_l, bc_r, bc_up, bc_low, ic], num_domain=10000, num_boundary=15000,  num_initial=3300)

    layer_size = [3] + [60] * 4 + [1]
    activation_func = "tanh"
    initializer = "Glorot uniform"

    net = dde.maps.FNN(layer_size, activation_func, initializer)
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3, loss_weights=[1, 60, 1, 1, 1, 1])
    model.train(epochs=50000)
    model.compile("L-BFGS-B", loss_weights=[1, 60, 1, 1, 1, 1])
    losshistory, train_state = model.train(model_save_path=r"C:\Users\timmy\PycharmProjects\examples\60-4_sin\10D15B3C60wdot1")`

**Comment by katayooneshkofti** [comment]
@iMTimmyyy Thank you
