### ISSUE TITLE
how to obtain the weight matrices and bias vectors of FNN in Deepxde, so that I can obtain the analytical approximation solution of PDE

### ISSUE THREAD

**Issue by zxw4688** [lululxvi/deepxde#110]
Hello @lululxvi 
     I would like to obtain the expression of function trained by  FNN,  so that I can get the  analytical approximation solution of PDE. In fact, when the train of FNN stopped, then the weight matices and bias vectors can be given. Therefore, I would like to know how to get them and save them as cell array like as in Matlab.

**Comment by lululxvi** [comment]
See #103
