### ISSUE TITLE
Predictions at all points are zeroes

### ISSUE THREAD

**Issue by sai-karthikeya-vemuri** [lululxvi/deepxde#1114]
Dear Prof. Lu,

I am trying to solve 2d wave equation with source term given as :

```
def pde(x,u):
    u_xx= dde.grad.hessian(u,x,i=0,j=0)
    u_yy= dde.grad.hessian(u,x,i=1,j=1)
    u_tt= dde.grad.hessian(u,x,i=2,j=2)
    A= tf.constant(1, dtype = tf.float32)
    freq = tf.constant(1, dtype = tf.float32)
    sigma = tf.constant(0.2, dtype = tf.float32)

    source_x = tf.constant(0.5, dtype = tf.float32)
    source_y = tf.constant(0.5, dtype = tf.float32)

    GP = A * tf.exp(-0.5*( ((x[:,0:1]-source_x)/sigma)**2 + ((x[:,1:2]-source_y)/sigma)**2 ))
    
    S = GP * tf.sin( 2 * tf.constant(math.pi)  * freq * x[:,2:3] )
    return u_xx + u_yy - u_tt + S

```

And u=0 at t=0 and boundaries (dirichlet BC)

I implemented this as output transform:
```

def output_transform(x,u):
    x_in= x[:,0:1]
    y_in= x[:,1:2]
    t_in= x[:,2:3]
    return x_in*(a-x_in)*y_in*(b-y_in)*t_in*u
```

The Neural Network is like this:
```
data = dde.data.TimePDE(
    space_time_domain,
    pde,
    [],
    num_domain=10000,
    num_initial=1000,
    num_boundary=1000,
    train_distribution="Sobol"
)
nn = dde.nn.FNN(
   [3]+[100]*4 + [1],
    f"LAAF-2 tanh",
    "Glorot uniform"

)
nn.apply_output_transform(output_transform)
```

I trained for 10000 Adam iterations (lr=1e-3) and further with L BFGS steps .

Loss seems to be very low: 

Step      Train loss    Test loss     Test metric
0         [5.02e-02]    [5.02e-02]    []  
1000      [1.00e-04]    [1.00e-04]    []  
2000      [3.78e-05]    [3.78e-05]    []  
3000      [2.06e-05]    [2.06e-05]    []  
4000      [2.21e-05]    [2.21e-05]    []  
5000      [4.89e-05]    [4.89e-05]    []  
6000      [3.19e-05]    [3.19e-05]    []  
7000      [5.55e-06]    [5.55e-06]    []  
8000      [4.55e-06]    [4.55e-06]    []  
9000      [3.64e-05]    [3.64e-05]    []  
10000     [4.50e-05]    [4.50e-05]    []  

Best model at step 8000:
  train loss: 4.55e-06
  test loss: 4.55e-06
  test metric: []

'train' took 5411.390663 s

Compiling model...
'compile' took 1.773400 s

```
Training model...

Step      Train loss    Test loss     Test metric
10000     [4.50e-05]    [4.50e-05]    []  
11000     [2.68e-07]    [2.68e-07]        
12000     [1.18e-07]    [1.18e-07]        
13000     [7.09e-08]    [7.09e-08]        
14000     [4.92e-08]    [4.92e-08]        
15000     [3.66e-08]    [3.66e-08]        
16000     [3.02e-08]    [3.02e-08]        
17000     [2.60e-08]    [2.60e-08]        
18000     [2.29e-08]    [2.29e-08]        
19000     [2.08e-08]    [2.08e-08]        
INFO:tensorflow:Optimization terminated with:
  Message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  Objective function value: 0.000000
  Number of iterations: 9381
  Number of functions evaluations: 9823
19823     [1.94e-08]    [1.94e-08]    []  

Best model at step 19823:
  train loss: 1.94e-08
  test loss: 1.94e-08
  test metric: []

'train' took 6221.435486 s
```

But all the predicted output values at all points is only zero.

Could you please give some hints as to where this might have gone wrong.

With best regards,
Sai

**Comment by hualihus** [comment]
Dear sai,

Have you resolved the issue with the predicted value？
