### ISSUE TITLE
how to tune the hyperparameters to obtain the coefficients of the KDV euqation.

### ISSUE THREAD

**Issue by zxw4688** [lululxvi/deepxde#112]
Hello @lululxvi 
 I revised the example diffusion_1D_inverse.py in Deepxde,  so that it can solve the inverse problem of KDV equation. The KDV equation is : 
![image](https://user-images.githubusercontent.com/65707421/91102290-b8f93000-e61d-11ea-9505-e8c7c745dc35.png)
My code can run, however, it can not obtain the right value of B, and both A and C are right.  My code is : 
`# -*- coding: utf-8 -*-
"""
Created on Mon Aug 24 00:12:44 2020

@author: Administrator
"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    A = tf.Variable(0.6)
    B = tf.Variable(0.2)
    C = tf.Variable(0.8)

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_xxx = tf.gradients(dy_xx, x)[0][:, 0:1]
        return (
            dy_t + A*y*dy_x +B*dy_xxx
            +C*(-0.5*tf.sin(2*x[:, 0:1])*(tf.sin(x[:, 1:]))**2
            +0.0025*tf.cos(x[:, 0:1])*tf.sin(x[:, 1:])
            -tf.sin(x[:, 0:1])*tf.cos(x[:, 1:]))
        )
    def func(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(geomtime, func, lambda _, on_initial: on_initial)

    observe_x = np.vstack((np.linspace(0, 1, num=21), np.full((21), 1))).T
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(func(observe_x)), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc, ic, observe_y],
        num_domain=400,
        num_boundary=20,
        num_initial=10,
        anchors=observe_x,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [32] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([A,B,C], period=1000)
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()
`

**Comment by zxw4688** [comment]
I have try many times  by tuning the intial value of A,B and C, and the hidden layers and neurons, but it did not make it.

**Comment by lululxvi** [comment]
There are lots of possible reasons, e.g., is the network trained well? are all loss terms small enough? Is the training points enough? etc. See "Q: I failed to train the network or get the right solution, e.g., the training loss is large."

**Comment by zxw4688** [comment]
Thank you very much! From the result of it, the training loss or all loss terms are small, the result as follow:
![image](https://user-images.githubusercontent.com/65707421/91104156-0d061380-e622-11ea-8b43-4383a487f136.png)

**Comment by lululxvi** [comment]
Try to use more training points. It is hard to tell whit is wrong without trying. Read the examples and learn from others in "Q: I failed to train the network or get the right solution, e.g., the training loss is large." at FAQ.

**Comment by zxw4688** [comment]
Thank you very much! I have tried it by adding more training points, but it  failed.

**Comment by zxw4688** [comment]
LuLu博士，你好！非常感谢你的Package，我很想学会它。
我在用它进行KDV方程的反问题时，我将kdv方程改写为：
![image](https://user-images.githubusercontent.com/65707421/91276784-d7068380-e736-11ea-932f-8177161f431d.png)
也就是我现在需要Deepxde以向量的形式学出KDV的系数，我把以前用分量形式代码改为了向量，可是运行出错了，麻烦你帮我看一下。另外我想训练结束了把方程的系数拿出来，我采用了代码C=model.get_VariableValue( )，想得到学习的系数。可是出错了，麻烦LuLu博士帮我看看应该怎么改啊？谢谢！我的具体代码如下：
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf


def main():
    #A0 = tf.Variable(0.01)
    #A1 = tf.Variable(0.8)
    #A2 = tf.Variable(0.01)
    #A3 = tf.Variable(0.8)
    A = tf.Variable([[0.01,0.8,0.01,0.8]])

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_xxx = tf.gradients(dy_xx, x)[0][:, 0:1]
        return (
            dy_t-tf.matmul(tf.constant([[1,0.5*tf.sin(2*x[:, 0:1])*(tf.sin(x[:, 1:]))**2
            -0.0025*tf.cos(x[:, 0:1])*tf.sin(x[:, 1:])
            +tf.sin(x[:, 0:1])*tf.cos(x[:, 1:]), dy_xxx, y*dy_x]]), tf.transpose(A))
            
        )
    def func(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])
    
    def funcy(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])   #+0.01*np.random.normal(0.0, 1.0,1)

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(geomtime, func, lambda _, on_initial: on_initial)

    observe_x = np.vstack((np.linspace(0, 1, num=21), np.full((21), 1))).T
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(funcy(observe_x)), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc, ic, observe_y],
        num_domain=400,
        num_boundary=20,
        num_initial=10,
        anchors=observe_x,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [32] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue(A, period=1000)
    losshistory, train_state = model.train(epochs=5000, callbacks=[variable])
    C=model.get_VariableValue()
    print(C)
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()`

**Comment by zxw4688** [comment]
LuLu博士，你好。我用的你的Deepxde 进行学习KDV方程的系数，我是这样算的：第一步：构造一组以真解（或带有扰动）为标签的训练集，拟合出一个DNN函数，然后根据最小二乘形式给出一个KDV方程的系数C, 计算出该系数与真实系数P的误差，并判断是否满足给定的精度，第二步，将系数C的值代入到需要学习的KDV方程中，进行KDV方程的求解，得到新的DNN函数，再次根据最小二乘形式给出KDV方程的新系数nC, 计算出系数nC与真实系数P的误差，判断是否满足给定的精度，满足则找到了系数并得出了KDV方程的解，若不满足给定的精度，则将nC赋给C再次进行第二步。直到满足为止。
  我根据上述的算法，按照你给求解PDE和拟合数据的方法，编写了该代码，但是代码报错了，我认真看了代码报错的原因，主要是数据传入的类型及tensorflow和python对应的numpy数据类型的不匹配问题，我也在网上搜了，可是没有解决。
麻烦LuLu博士帮我看一下，看看怎么改，非常感谢！具体的算法如下：
![image](https://user-images.githubusercontent.com/65707421/91293849-80587400-e74d-11ea-85ce-49d58bdec232.png)
代码的具体错误为：
![image](https://user-images.githubusercontent.com/65707421/91294089-daf1d000-e74d-11ea-83ab-e68a079e7750.png)
我的代码为：
`# -*- coding: utf-8 -*-
"""
Created on Tue Aug 26 03:40:25 2020

@author: Administrator
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
from functools import reduce

import deepxde as dde
from deepxde.backend import tf

#首先进行DNN函数的数据拟合
Nx=21 
Nt=11
Xx=np.linspace(-np.pi,np.pi,Nx)
Tt=np.linspace(0,1,Nt)
INt=np.ones(Nt)
X=np.kron(INt,Xx)
INx=np.ones(Nx)
T=np.kron(Tt,INx)
Input_data=np.transpose(np.array([X,T]))
#以上是构造出meshgrid形式的数据

#构造标签并加入误差扰动
Label_data=np.sin(X)*np.sin(T)
#noise_data=0.1*np.random.normal(0.0, 1.0, Nx*Nt)
#Label_data=np.transpose(Label_data+noise_data)
Label_data=Label_data.reshape(Nx*Nt,1)
print(np.shape(Input_data))
print(np.shape(Label_data))
data = dde.data.DataSet(
    X_train=Input_data,
    y_train=Label_data,
    X_test=Input_data,
    y_test=Label_data,        
    standardize=False,
)

layer_size = [2] + [10] * 6 + [1]
activation = "tanh"
initializer = "Glorot normal"
net = dde.maps.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=0.001, metrics=["l2 relative error"])
#losshistory, train_state = model.train(epochs=50000)
model.train(epochs=5000)
#dde.saveplot(losshistory, train_state, issave=True, isplot=True)
#以上数据拟合完毕

#开始计算DNN函数的函数值及其各阶导数
#给出各阶导数自动微分计算
def f(x,y):
    dy=tf.gradients(y,x)[0]                     
    dy_x,dy_t=dy[:,0:1],dy[:,1:]
    dy_xx=tf.gradients(dy_x,x)[0][:,0:1]
    dy_xxx=tf.gradients(dy_xx,x)[0][:,0:1]                
    return dy_t, dy_x, dy_xx, dy_xxx
Dt,Dx,Dxx,Dxxx = model.predict(Input_data, operator=f)
print(Dt,np.shape(Dt))

#定义计算右端项的函数
def fun(x):
    return (-0.5*np.sin(2*x[:, 0:1])*(np.sin(x[:, 1:]))**2
            +0.0025*np.cos(x[:, 0:1])*np.sin(x[:, 1:])
            -np.sin(x[:, 0:1])*np.cos(x[:, 1:]))
F=fun(Input_data)#计算右端项的函数值

D=model.predict(Input_data)#计算DNN函数的函数值
EN1=np.ones([Nx*Nt,1])#给出全为1的列向量
#A=np.concatenate((EN1,D,F,Dx,Dxx,Dxxx,D*Dx,D*Dxx,D*Dxxx),1)

AA=np.concatenate((EN1,F,Dxxx,D*Dx),1)#按照备选库组装成矩阵

#C=reduce(np.matmul,[np.linalg.inv(np.matmul(A.T,A)),A.T,Dt])
C=reduce(np.matmul,[np.linalg.inv(np.matmul(AA.T,AA)),AA.T,Dt])#按照Ridge回归方法计算出初始系数

P=np.array([[0],[1],[-0.0025],[-1]])#给出KDV方程的真实系数
err=np.linalg.norm(C-P) #计算初始误差
ES=1e-7 #给出停止迭代的误差
n=1
Q=np.insert(C,0,[[err],[n]],axis = 0)#将误差，迭代次数放入到系数列向量的顶端

while err>ES:
    #将系数C导入
    A0 = tf.constant(C[0])
    A1 = tf.constant(C[1])
    A2 = tf.constant(C[2])
    A3 = tf.constant(C[3])
    
    #下面开始求解系数C确定的KDV方程
    
    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_xxx = tf.gradients(dy_xx, x)[0][:, 0:1]
        return (
            dy_t - A0 -A1*(0.5*tf.sin(2*x[:, 0:1])*(tf.sin(x[:, 1:]))**2
            -0.0025*tf.cos(x[:, 0:1])*tf.sin(x[:, 1:])
            +tf.sin(x[:, 0:1])*tf.cos(x[:, 1:])) -A2*dy_xxx -A3*y*dy_x 
            )
    def func(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])
    
    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)
    
    bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(geomtime, func, lambda _, on_initial: on_initial)
    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc, ic],
        num_domain=400,
        num_boundary=200,
        num_initial=100,
        solution=func,
        num_test=1000,
    )
    
    layer_size = [2] + [50] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)
    
    model = dde.Model(data, net)
    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    #losshistory, train_state = model.train(epochs=50000)
    model.train(epochs=5000)
    #dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    #上述求解完毕
    
    #开始计算所得的DNN函数的各阶导数及其函数值
    
    nDt,nDx,nDxx,nDxxx = model.predict(X, operator=f)  #计算所得的DNN函数的各阶导数
    nF=fun(X)  #计算右端项的函数值
    nD=model.predict(Input_data)
    nEN1=np.ones(nD.shape)
    nAA=np.concatenate((nEN1,nF,nDxxx,nD*nDx),1)
    nC=reduce(np.matmul,[np.linalg.inv(np.matmul(nAA.T,nAA)),nAA.T,nDt])
    err=np.linalg.norm(nC-P)
    C=nC
    n=n+1
    CC=np.insert(nC,0,[[err],[n]],axis = 0)#将误差，迭代次数放入到系数列向量的顶端
    Q=np.concatenate((Q,CC),1) #记录误差,迭代的次数及其相应的x系数列向量
    
print(Q)`

**Comment by lululxvi** [comment]
- Do not use vector form. Use the original form, i.e.,
```python
dy_t - A0 - A1 * f ...
```
- Use `dde.callbacks.VariableValue` to get the variables, see example Lorenz_inverse.py

**Comment by zxw4688** [comment]
Hello @lululxvi 
Thank you very much for your reply. Another question, I would like to enhance the speed of the code running by means of the jit in  numba, when I add `@jit` to the  front of the function of `def main()`, but some error happened. Can you tell me how to do it.

**Comment by zxw4688** [comment]
the error is KeyError: "Failed in object mode pipeline (step: inline calls to locally defined closures)\ni code'"

**Comment by lululxvi** [comment]
The code uses Tensorflow which is in C++. You don't need numba. If it is slow, try GPU.

**Comment by zxw4688** [comment]
Thank you very much!, but I install tensorflow in the form of CPU, I did  not install GPU, how to do it to enhance the speed. Thank you very muc!

**Comment by zxw4688** [comment]
Hello @lululxvi 
I have used your pakcage Deepxde to learn the coefficients of KDV PDE, and I tune all kind of  hyperparameters, but I can not obtain the well result, the coefficient of third   derivative is very bad, nearly impossible to equal  -0.0025. I would like to know why? And the other paper about PINN can get good result. I want to know what happened?
My code is: 
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf


def main():
    A0 = tf.Variable(0.01)
    A1 = tf.Variable(-0.8)
    A2 = tf.Variable(-0.01)
    A3 = tf.Variable(-0.8)
    

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_xxx = tf.gradients(dy_xx, x)[0][:, 0:1]
        return (
            dy_t - A0 -A1*(-0.5*tf.sin(2*x[:, 0:1])*(tf.sin(x[:, 1:]))**2
            +0.0025*tf.cos(x[:, 0:1])*tf.sin(x[:, 1:])
            -tf.sin(x[:, 0:1])*tf.cos(x[:, 1:])) -A2*dy_xxx -A3*y*dy_x 
            )
    def func(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])
    
    def funcy(x):
        return np.sin(x[:, 0:1]) * np.sin(x[:, 1:])   #+0.01*np.random.normal(0.0, 1.0,1)

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(geomtime, func, lambda _, on_initial: on_initial)

    observe_x = np.vstack((np.linspace(0, 1, num=21), np.full((21), 1))).T
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(funcy(observe_x)), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc, ic, observe_y],
        num_domain=1000,
        num_boundary=80,
        num_initial=30,
        anchors=observe_x,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [50] * 6 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    #variable = dde.callbacks.VariableValue([A0,A1,A2,A3], period=1000,filename="myvariables.dat")
    variable = dde.callbacks.VariableValue([A0,A1,A2,A3], period=1000)
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
`

**Comment by lululxvi** [comment]
Could you try few parameters? also read https://www.biorxiv.org/content/10.1101/865063v2 to learn some experience

**Comment by zxw4688** [comment]
Hello @lululxvi
我在用Deepxde的过程中，我发现迭代的次数不一定要很多，也就是不一定要到五万次，其实有可能一万次就够了，能否通过给定误差（损失函数值的大小，或是拟合函数与真实值的误差）的大小来决定迭代的次数，怎么设置啊？

**Comment by lululxvi** [comment]
The number of iterations is a hyperparameter you need to select before training. Of course, you can do early stopping, see `dde.callbacks.EarlyStopping` in Burgers_RAR.py

**Comment by zxw4688** [comment]
Hello @lululxvi 
In matlab feedforwardnet， Levenberg-Marquardt algorithm is much better than other algorithm. Therefore, I would like to know why  you do not use the algorithm, and how to add other algorithm to your package, such as Levenberg-Marquardt algorithm.
Thank you very much!

**Comment by lululxvi** [comment]
The method that works for traditional problems may not work well for neural networks. Gradient descent is almost the only optimization method in deep learning. Of course, you can choose to use other methods, e.g., "L-BFGS-B" used in Burgers.py. You can use any methods in  https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

**Comment by zxw4688** [comment]
我是想表达：在MATLAB中，LM算法应用到全连接的Feedforwardnet里面很好，相对二范数的误差很小啊，基本可以达到10^(-7)，怎么你这的使用FNN拟合的函数，还是求解PDE，相对二范数误差，怎么之多达到10^(-3)啊。而且matlab中是LM的确很好啊，我认为你的package-Deepxde对KDV方程系数没有学出来的原因应该就是相对二范数误差太大。怎么解释Matlab中的LM算法，这个现象？

**Comment by zxw4688** [comment]
我是想表达：在MATLAB中，LM算法应用到全连接的Feedforwardnet里面很好，相对二范数的误差很小啊，基本可以达到10^(-7)，怎么你这的使用FNN拟合的函数，还是求解PDE，相对二范数误差，怎么之多达到10^(-3)啊。而且matlab中是LM的确很好啊，我认为你的package-Deepxde对KDV方程系数没有学出来的原因应该就是相对二范数误差太大。怎么解释Matlab中的LM算法，这个现象？
另外我看了"L-BFGS-B" used in Burgers.py，可是他是使用了两个算法adam和L-BFGS-B这个啊，这个怎么理解啊，谢谢！

**Comment by zxw4688** [comment]
我是想表达：在MATLAB中，LM算法应用到全连接的Feedforwardnet里面很好，相对二范数的误差很小啊，基本可以达到10^(-7)，怎么你这的使用FNN拟合的函数，还是求解PDE，相对二范数误差，怎么之多达到10^(-3)啊。而且matlab中是LM的确很好啊，我认为你的package-Deepxde对KDV方程系数没有学出来的原因应该就是相对二范数误差太大。怎么解释Matlab中的LM算法，这个现象？
另外我看了"L-BFGS-B" used in Burgers.py，可是他是使用了两个算法adam和L-BFGS-B这个啊，这个怎么理解啊，谢谢！
![image](https://user-images.githubusercontent.com/65707421/91628593-1373f280-e976-11ea-8196-3314dde5afb5.png)

**Comment by zxw4688** [comment]
我用的是matlab2014版的，使用的函数为feedforwardnet, net, train 和sim基本就可以实现数据拟合了，拟合的NN函数与真实值的误差基本达到了10^(-6)，而且是仅使用一个隐藏层10个神经元的，训练也就一千次以内，而你的package训练到50000次，也就最多达到10^(-3),这是为什么啊？

**Comment by lululxvi** [comment]
Here are many things:

- DeepXDE by default uses `float32`, which means the precision is 10^{-6} ~10^{-7}. For the L2 relative error, there is an extra square root, so the precision becomes 10^{-3}~10^{-4}. See FAQ how to use `float64`.
- I don't think the error is from L2 relative error. L2 relative error is just a metric. It does not make sense to say "large L2 relative error induces wrong results." The correct way should be "My training loss is too large, i.e., the optimization algorithm has not found a good solution yet, and thus the result is bad".
- I think 10^{-3} L2 relative error for inverse problems actually is very good. Of course, in the mean while, you need to check each loss term. If all loss terms are quite small, e.g., < 10^{-5}, then I think the optimization does a good job. (Of course, the problem itself should be O(1).)
- It does not make too much sense to aim for a very small loss, like 10^{-7}. For example, if data has noise, 10^{-7} is totally over-fitting.
- As mentioned earlier, in practice, almost GD is only used in deep learning. Although other algorithms like LM works well for some small toy problems, for real large problems, they usually failed. As you can see here https://www.tensorflow.org/api_docs/python/tf/keras/optimizers , in TensorFlow only these optimization algorithms are implemented. Matlab is still a traditional numerical tool, and has lots of other traditional methods.
- The Burgers example: we first use Adam to find a roughly good solution, and then use L-BFGS to search a local minimum. See [DeepXDE paper](https://arxiv.org/abs/1907.04502) page 5 for the reason.
- For the comparison with Matlab, you may use the same setup, e.g. network size, data points, in DeepXDE to have a comparison. Larger network does not mean better result. I am also curiously about the comparison, although it is impossible to make the setup exactly the same, because we cannot see Matlab code and don't know what Matlab does.
