### ISSUE TITLE
AttributeError: module 'deepxde' has no attribute 'models' 

### ISSUE THREAD

**Issue by engineergit** [lululxvi/deepxde#1134]
@lululxvi 
Hi Lu,

I'm trying to run my steady rainfall case problem in google code lab. somehow, it gave me attribute error.

AttributeError: module 'deepxde' has no attribute 'models' 

here is my code : 

```
model = dde.models.PDE(
    geometry=geomtime,
    pde_fn=func_pde,
    bc_fn=func_bc,
    init_fn=func_initial,
    num_domain=100,
    num_boundary=100,
    num_initial=100
)
```

then, I updated the version of deepxde but issue is still same.

is it possible for you to look into this issue and let me know how can i resolve this?
Thanks

**Comment by lululxvi** [comment]
See https://deepxde.readthedocs.io/en/latest/demos/pinn_forward.html
