### ISSUE TITLE
The reference solution in deepxde/examples/dataset

### ISSUE THREAD

**Issue by Philosober** [lululxvi/deepxde#1135]
In some examples(just like Burgers equation), the final step of the pinn will use the 'Burgers.npz' to test the model. I was wondering where is this `Burgers.npz` comes from and can I regard it as the ground truth?

**Comment by lululxvi** [comment]
From traditional numerical methods.

**Comment by Philosober** [comment]
Thanks for your reply, Lu. So, we can see the traditional numerical methods as the ground truth to train PINN, right?

**Comment by lululxvi** [comment]
Yes.
