### ISSUE TITLE
Request to add my paper to the list of research papers.

### ISSUE THREAD

**Issue by praksharma** [lululxvi/deepxde#1136]
Hi, we recently published a paper which investigates the performance of Baseline PINN, DeepXDE' Baseline PINN and NVIDIA Modulus on a 2D and 3D problem with discontinuous BCs.

Let me know if you are able add this to the list of research papers.

The paper : https://link.springer.com/article/10.1007/s11831-023-09890-4
Ready reference :  Prakhar Sharma, Llion Evans, Michelle Tindall, and Perumal Nithiarasu. Stiff-PDEs and Physics-Informed Neural Networks. Arch Computat Methods Eng, February 2023.

**Comment by lululxvi** [comment]
Feel free to submit a PR to update https://github.com/lululxvi/deepxde/blob/master/docs/user/research.rst

**Comment by praksharma** [comment]
#1139 Done
