### ISSUE TITLE
Enable versioned builds for DeepXDE's documentation

### ISSUE THREAD

**Issue by Saransh-cpp** [lululxvi/deepxde#1148]
DeepXDE's documentation currently only serves the latest (HEAD) documentation. The latest/HEAD/develop documentation usually does not correspond to the latest stable release.

It would be nice to enable versioned builds for the documentation to ensure that the users read the documentation corresponding to the DeepXDE version they are using.

I think this can be enabled via the RTD admin dashboard and will not require updating anything in the GitHub repository.

For example, PyBaMM's documentation has versioned builds - https://pybamm.readthedocs.io

**Comment by lululxvi** [comment]
Enabled the latest version.

**Comment by Saransh-cpp** [comment]
Thanks, @lululxvi! Closing this.
