### ISSUE TITLE
AdamW optimizer with PyTorch

### ISSUE THREAD

**Issue by jmtucny** [lululxvi/deepxde#1151]
Hello,

I'm trying to use the AdamW optimizer with PyTorch backend. I'm using these lines of code for model compilation and training.

`model.compile("adamw", lr=0.0001, loss_weights=[0.1, 1], loss="mse", decay=("step", 100, 0.97))`
`losshistory, train_state = model.train(iterations=6000, display_every=1000)`

Then I get these errors:

------------------------
~\Documents\Postdoctorat_Rome\Programmes\ExtendedNS_Slit1D\ExtendedNS_Slit1D.py:100 in <module>
    model.compile("adamw", lr=0.0001, loss_weights=[0.1, 1], loss="mse", decay=("step", 100, 0.97))

  File ~\anaconda3\lib\site-packages\deepxde\utils\internal.py:22 in wrapper
    result = f(*args, **kwargs)

  File ~\anaconda3\lib\site-packages\deepxde\model.py:129 in compile
    self._compile_pytorch(lr, loss_fn, decay, loss_weights)

  File ~\anaconda3\lib\site-packages\deepxde\model.py:307 in _compile_pytorch
    self.opt, self.lr_scheduler = optimizers.get(

  File ~\anaconda3\lib\site-packages\deepxde\optimizers\pytorch\optimizers.py:47 in get
    raise ValueError("AdamW optimizer requires non-zero weight decay")

ValueError: AdamW optimizer requires non-zero weight decay

-------------------------------

I don't understand how to put the weight decay. When I use the adam optimizer, my code works perfectly. Can you help me ?

Thanks in advance,

**Comment by OverKit** [comment]
Try `net.regularizer=("l2", your_decay_num)`?

**Comment by jmtucny** [comment]
> Try `net.regularizer=("l2", your_decay_num)`?

Thank you ! It worked.
