### ISSUE TITLE
Implementing 3D Navier Stokes with deepxde

### ISSUE THREAD

**Issue by debneilroy** [lululxvi/deepxde#116]
Hi Lu,

Thanks for sharing your work on deepxde. I am trying to model 3d incompressible navier stokes equations in velocity-vorticity form and was wondering if you have any inputs on if deepxde can be used for this. Is there any similar 3d code I can refer to for my understanding?

**Comment by lululxvi** [comment]
No. I currently don't have 3D case, but this can be done almost the same as 1D/2D case. You can check the examples, and will see that the code for 1D/2D/3D are almost the same.

**Comment by debneilroy** [comment]
Thank you for your reply. I will take a look at the examples.

Also, will it be possible to use the library for a 2 fluid flow problem?
Something like a bubble or Rayleigh-Taylor instability with an evolving
internal boundary.

**Comment by lululxvi** [comment]
Yes, DeepXDE works for 2d flow problem. But for the Rayleigh-Taylor instability, I am not sure what the performance is.

**Comment by mariusmerkle** [comment]
@debneilroy Did you succeed in modeling the 3D Navier-Stokes problem? I would be interested in your results and would like to know how you did it.

**Comment by lululxvi** [comment]
I haven't modeled 3D NS problem, but there are works on it, see https://arxiv.org/abs/2003.06496. Nothing new on algorithms, but requires some engineering work.
