### ISSUE TITLE
User defined functions input/output/operations – meaning, type, dimension?

### ISSUE THREAD

**Issue by david-egri-smlb41** [lululxvi/deepxde#1185]
Dear DeepXDE team,

I have the following questions about the usage of the DeepXDE package after some experimentation:

Assume the following notation:
- N: is the neural network input dimension
- M: is the neural network output dimension
- L: is the number of training points

Let’s take these classes:
- deepxde.icbc.boundary_conditions.RobinBC(geom, func, on_boundary, component=0)
- deepxde.icbc.boundary_conditions.NeumannBC(geom, func, on_boundary, component=0)
- deepxde.icbc.boundary_conditions.DirichletBC(geom, func, on_boundary, component=0)
- deepxde.data.pde.PDE(geometry, pde, bcs, num_domain=0, num_boundary=0, train_distribution='Hammersley', anchors=None, exclusions=None, solution=None, num_test=None, auxiliary_var_function=None)

The following functions must be defined by the user to specify a problem:
- func
- pde
- auxiliary_var_function

Could you please help specify what are the inputs and outputs of these functions? Regarding the meaning, type, dimensionality and the type of operations inside them.

For example:

```
def pde (x, y, auxiliary_var_function):

    type of operations inside? (tensorflow or numpy operations etc.)

    return z
```

x, y, z – meaning (NN input/output etc.), type (tensorflow tensor or numpy array etc.), dimension (LxN etc.)

**Comment by lululxvi** [comment]
Check the examples and demos.
