### ISSUE TITLE
Solving external flow past object

### ISSUE THREAD

**Issue by zonexo** [lululxvi/deepxde#119]
Hi,

Is it possible to use DeepXDE to solve external flow past an object e.g. flow past airfoil or cylinder (2D,3D) and using the NS eqns with PINN?

If so, is there any examples or guides?

Thanks!

**Comment by lululxvi** [comment]
See "Q: Examples collected from users." at FAQ.

**Comment by zxw4688** [comment]
Hello @lululxvi 博士你好，
我有个关于积分的问题想向你请教一下，对于给定的Stokes 方程， 由于方程中对压力没有给边值条件，为此我想在方程中加入一个压力在区域的积分为零的条件，以使得压力是唯一的，这应该如何处理啊，非常感谢！即：
![image](https://user-images.githubusercontent.com/65707421/94330189-faf7f780-ff76-11ea-8692-f7a55eccdf6a.png)

**Comment by lululxvi** [comment]
The integral equation is possible to add, but is not easy. Based on our experience, you don't enforce this in the training, but instead after the training, you do a post-processing to compute c = \int p dxdy, and then compute the p as p - c.
