### ISSUE TITLE
Use derivative values as anchor points

### ISSUE THREAD

**Issue by voloddia** [lululxvi/deepxde#120]
Hi Lu, 
Is there a way to use derivative values as anchor points? 
Thanks in advance.

**Comment by lululxvi** [comment]
I am not sure what you mean "use derivative values as anchor points". Could you provide more details?

**Comment by voloddia** [comment]
Hi Lu, 
I mean instead using function values `y(X)`, is there a way to use derivative values `dy/dx(X)` as anchor points?

**Comment by lululxvi** [comment]
Anchor points are only `X` locations, which has nothing to do with the loss. See #39 .

**Comment by voloddia** [comment]
Thanks, Lu for clarifying this detail. 
With this I guess there's no way to include observations (in the form of `[X, y(X)]` or `[X, y'(X)]`) in the training?

**Comment by lululxvi** [comment]
You can. `[X, y(X)]` is just Dirichlet BC on discrete points, and you can see in the code I just use Dirichlet BC to define observations. Similar, `[X, y'(X)]` is just Neumann BC.

**Comment by voloddia** [comment]
I see. Observations can be input as additional discrete BC. 
I will temporarily close this and will reopen if I have other questions. 
Thanks, Lu.
