### ISSUE TITLE
PointCloud.boundary_normal to be implemented

### ISSUE THREAD

**Issue by athtareq** [lululxvi/deepxde#1201]
Hello, I defined a PointCloud to use a geometry, but I get this error. Does this mean that it hasn't yet been implemented for Neumann condition ? I also get this same error using the geometry defined in https://github.com/lululxvi/deepxde/issues/1138.

**Comment by lululxvi** [comment]
It seems so. @mitchelldaneker I thought we have implemented this.

**Comment by Gregouare** [comment]
Hello,

@athtareq, did you manage to get past this error message ? I created a geometry using Pointcloud, and even though I added the boundary_normals vectors, it looks like the compilation calls PointCloud.boundary_normal hence the error message.

@lululxvi Should I try and modify the source code or do you think there is a way to avoid such a hustle ?

Thanks a lot for your help !

Greg

**Comment by athtareq** [comment]
> Hello,
> 
> @athtareq, did you manage to get past this error message ? I created a geometry using Pointcloud, and even though I added the boundary_normals vectors, it looks like the compilation calls PointCloud.boundary_normal hence the error message.
> 
> @lululxvi Should I try and modify the source code or do you think there is a way to avoid such a hustle ?
> 
> Thanks a lot for your help !
> 
> Greg

hello Greg, I am sorry to say that I could not get past it and had to even change the domain iirc. Maybe the devs changed things up from last year. Good luck !

**Comment by mitchelldaneker** [comment]
> Hello,
> 
> @athtareq, did you manage to get past this error message ? I created a geometry using Pointcloud, and even though I added the boundary_normals vectors, it looks like the compilation calls PointCloud.boundary_normal hence the error message.
> 
> @lululxvi Should I try and modify the source code or do you think there is a way to avoid such a hustle ?
> 
> Thanks a lot for your help !
> 
> Greg

Hi Greg, let me take another look at the code I can try to be of help. I won't get a chance until tomorrow but can test on my end and either make changes or give suggestions on a temporary solution.

**Comment by Gregouare** [comment]
Hello,

Looks like it has been added on recent versions since updating the library made it work (after a bit of debugging of course). I still find a different result than with 'classic' geometry, but I am pretty sure it comes from my end !

Thanks for the quick answers !
