### ISSUE TITLE
How to solve the Euler equations？

### ISSUE THREAD

**Issue by ajogajog** [lululxvi/deepxde#124]
Hi Lulu,

I appreciate the author shares his code with us.
Recently I tried to use the DeepXDE to model the solve the compressible Euler equations, i.e.
![无标题](https://user-images.githubusercontent.com/24715878/93587635-c74c2900-f9dc-11ea-9043-1ce331c7ea17.png)

How to deal with the term like ![image](https://user-images.githubusercontent.com/24715878/93587756-f2367d00-f9dc-11ea-8f16-3bd7153c069b.png), they're both variables. How to define it in PINN?

I went through all the examples and didn't see anything relevant.  Hope to get some advice from you.

Thanks!

**Comment by lululxvi** [comment]
Let the network output be y = (rho, u, E), then rho = y[:, 0:1], u = y[:, 1:2], rhou = rho * u

**Comment by Rahulx084** [comment]
Hi Lulu, How do we define the gradient of it? Let's say I want to express d(rho * u)_dt; I'll write dde.grad.jacobian(rho * u ,x ,i=0 ,j=1), I get that if the input is x=[x,t] , j=1 for t. But what defines the i ? What value to take there?

**Comment by lululxvi** [comment]
https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant
