### ISSUE TITLE
Enhancement: add tests, pre-commit, and coverage support

### ISSUE THREAD

**Issue by Saransh-cpp** [lululxvi/deepxde#1244]
This is a placeholder issue for testing related developments of DeepXDE. Things I am planning to work on in the next couple of months -

- [ ] Add pre-commit support for better linting, formatting, and readability of the codebase
- [x] Add integration tests (test all examples)
- [x] ~Add basic testing infrastructure using `pytest`~
- [x] ~Add basic coverage infrastructure using `pytest-cov`~
- [x] ~Add [Codecov](https://about.codecov.io) integration for better coverage statistics on GitHub~
- [x] ~Add more and more tests to bring the coverage value up~
- [x] ~Add docs about testing and encourage developers to add a test with every new feature added to DeepXDE~

**Comment by pescap** [comment]
Happy to help! This would greatly improve the package!

**Comment by Saransh-cpp** [comment]
Thanks @pescap! Apologies for abandoning this. I'll start some discussions here next week, along with finishing up the open PR.

**Comment by Saransh-cpp** [comment]
I think this can now be closed. The unchecked point aimed at adding automatic formatters, static code checkers, and linters using [pre-commit](https://pre-commit.com) and [pre-commit.ci](https://pre-commit.ci) in DeepXDE's CI, but I would wait for everyone's opinion on that. I'll be happy to add them to the CI if they are needed!

**Comment by lululxvi** [comment]
Sounds good. I don't have experience on [pre-commit](https://pre-commit.com/) and [pre-commit.ci](https://pre-commit.ci/). So feel free to close.
