### ISSUE TITLE
identify a function (parameter) in an elliptic equation with homogeneous dirichlet boundary

### ISSUE THREAD

**Issue by liuhuanhuansky** [lululxvi/deepxde#125]
Hi,lulu
I want to identify the parameter q(x) in elliptic equation -du_xx + q(x)u =f, x\in [-1,1], where true solution u=sin(pi*x^2), q(x)=cos(x) is unknown. The following is the code: the train loss and test loss  decrease to 5.0e-5. It seems correct. I want to plot the function q(x) to check, but I don't know where the data of q(x).

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import scipy.io

import deepxde as dde
from deepxde.backend import tf

def gen_traindata():
    data = scipy.io.loadmat('../examples/dataset/reaction_test10.mat')
    return data["x"], data["y"]

def main():
    q = tf.Variable(0.0)

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
            -dy_xx + q * y + 2*np.pi * tf.cos(np.pi* x[:, 0:1]**2)
              - x[:, 0:1]**2 * 4*np.pi**2
              * tf.sin(np.pi* x[:, 0:1]**2)
              - tf.cos(x) * tf.sin(np.pi*x[:, 0:1]**2)
        )                                                          

    def func(x):
        return np.sin(np.pi * x[:, 0:1]**2 )

    geom = dde.geometry.Interval(-1, 1)

    bc = dde.DirichletBC(geom, func, lambda _, on_boundary: on_boundary)

    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc, observe_y],
        num_domain=400,
        num_boundary=2,
        anchors=observe_x,
        #solution=func,
        num_test=10000,
    )

    layer_size = [1] + [50] * 3 + [2]          #[1] + [[50,50],[50,50],[50,50]] + [2]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)
    #net_q = dde.maps.FNN(layer_q, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    #variable = dde.callbacks.VariableValue([q], period=1000,filename="variable.dat")
    losshistory, train_state = model.train(epochs=30000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()

The result:
......
23000     [1.29e-04, 7.04e-07, 1.55e-05]    [1.09e-04, 0.00e+00, 0.00e+00]    []  
24000     [1.23e-03, 9.19e-06, 1.65e-05]    [1.13e-03, 0.00e+00, 0.00e+00]    []  
25000     [7.53e-05, 1.35e-07, 1.21e-05]    [6.41e-05, 0.00e+00, 0.00e+00]    []  
26000     [1.02e-04, 1.45e-07, 1.08e-05]    [9.04e-05, 0.00e+00, 0.00e+00]    []  
27000     [3.14e-04, 2.79e-06, 1.04e-05]    [2.74e-04, 0.00e+00, 0.00e+00]    []  
28000     [1.83e-04, 9.64e-07, 9.03e-06]    [1.74e-04, 0.00e+00, 0.00e+00]    []  
29000     [2.46e-04, 8.10e-07, 7.84e-06]    [2.18e-04, 0.00e+00, 0.00e+00]    []  
30000     [5.55e-04, 4.28e-06, 8.30e-06]    [5.20e-04, 0.00e+00, 0.00e+00]    []  

Best model at step 22000:
  train loss: 8.22e-05
  test loss: 5.31e-05
  test metric: []

**Comment by liuhuanhuansky** [comment]
Hello,lulu
Thank you for your contribution to the deepxde. I employ the deepxde to solve the inverse problem. 
I have revised the code and plot q(x), the result is uncorrect. Could you tell me where the error?


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import scipy.io

import deepxde as dde
from deepxde.backend import tf


def gen_traindata():
    data = scipy.io.loadmat('../examples/dataset/reaction_test10.mat')
    return data["x"], data["y"]

def main():
    q = tf.Variable(0.0)

    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
            -dy_xx + q * y + 2*np.pi * tf.cos(np.pi* x[:, 0:1]**2)
              - x[:, 0:1]**2 * 4*np.pi**2
              * tf.sin(np.pi* x[:, 0:1]**2)
              - tf.cos(x[:, 0:1]) * tf.sin(np.pi*x[:, 0:1]**2)
        )                                                          

    
    def func1(x):
        return np.cos(x[:, 0:1])
    
    def func2(x):
        return np.sin(np.pi * x[:, 0:1]**2)
    
    def func(x):
        return np.hstack((np.cos(x[:, 0:1]), np.sin(np.pi * x[:, 0:1]**2)))


    geom = dde.geometry.Interval(-1, 1)

    #bc1 = dde.DirichletBC(geom, func1, lambda _, on_boundary: on_boundary,component=0)
    bc2 = dde.DirichletBC(geom, func2, lambda _, on_boundary: on_boundary,component=1)


    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc2, observe_y],
        num_domain=40,
        num_boundary=2,
        anchors=observe_x,
        solution=func,
        num_test=100,
    )

    layer_size = [1] + [50] * 3 + [2]          #[1] + [[50,50],[50,50],[50,50]] + [2]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)
    #net_q = dde.maps.FNN(layer_q, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    #variable = dde.callbacks.VariableValue([q], period=1000,filename="variable.dat")
    losshistory, train_state = model.train(epochs=30000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()

The result:
26000     [1.28e-02, 8.42e-07, 3.14e-05]    [1.33e-02, 0.00e+00, 0.00e+00]    [7.30e-01]    
27000     [4.50e-03, 2.57e-07, 2.16e-05]    [3.44e-03, 0.00e+00, 0.00e+00]    [7.30e-01]    
28000     [1.56e-02, 2.58e-06, 3.58e-05]    [1.66e-02, 0.00e+00, 0.00e+00]    [7.30e-01]    
29000     [2.13e-03, 2.43e-07, 9.95e-06]    [3.87e-03, 0.00e+00, 0.00e+00]    [7.29e-01]    
30000     [1.12e-03, 9.68e-06, 1.27e-05]    [2.49e-03, 0.00e+00, 0.00e+00]    [7.31e-01]    

Best model at step 21000:
  train loss: 3.03e-04
  test loss: 1.48e-03
  test metric: [7.30e-01]

**Comment by lululxvi** [comment]
`q = tf.Variable(0.0)`, so `q` is only a scalar. If you want `q` is a function of `x`, see https://github.com/lululxvi/deepxde/issues/114

**Comment by liuhuanhuansky** [comment]
Hi Lulu,

Thank you from your prompt response. Now q is a function, so the initial value should be a vector. Then how to set the dimension.

**Comment by lululxvi** [comment]
No need to set the dimension. Learn the function directly, instead of vector, see #114

**Comment by liuhuanhuansky** [comment]
Hi,lulu
I see. I saw the inverse problem as a positive one, so I don't need the initial value. I obtain the correct u(x), but uncorrect q(x). I have try different learning rate, more iterations, it doesn't work! Could you tell me what's wrong? The code is:

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 23 09:09:28 2020

@author: liuhuanhuansky
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import scipy.io

import deepxde as dde
from deepxde.backend import tf


def gen_traindata():
    data = scipy.io.loadmat('../examples/dataset/test.mat')
    return data["x"], data["y"]

def main():
    
    #q = tf.Variable(np.zeros([], np.float32))

    def pde(x, y):
        y, q = y[:, 0:1], y[:, 1:]
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
            - dy_xx + q * y 
            - np.pi**2 * tf.sin(np.pi* x[:, 0:1])
            - x[:, 0:1]**2 * tf.sin(np.pi*x[:, 0:1])
        )                                                          

    
    def func1(x):
        return x[:, 0:1]**2
    
    def func2(x):
        return np.sin(np.pi * x[:, 0:1])
    
    def func(x):
        return np.hstack((x[:, 0:1]**2, np.sin(np.pi * x[:, 0:1])))


    geom = dde.geometry.Interval(-1, 1)

    bc2 = dde.DirichletBC(geom, func2, lambda _, on_boundary: on_boundary)

    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 0:1]), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc2, observe_y],
        num_domain=200,
        num_boundary=2,
        anchors=observe_x,
        solution=func,
        num_test=100,
    )

    layer_size = [1] + [50] * 4 + [2]          #[1] + [[50,50],[50,50],[50,50]] + [2]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=30000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    

if __name__ == "__main__":
    main()

**Comment by liuhuanhuansky** [comment]
Hi,lulu
I see. I saw the inverse problem as a positive one, so I don't need the initial value. I obtain the correct u(x), but uncorrect q(x). I have try different learning rate, more iterations, it doesn't work! Could you tell me what's wrong? The code is:

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 23 09:09:28 2020

@author: liuhuanhuansky
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import scipy.io

import deepxde as dde
from deepxde.backend import tf


def gen_traindata():
    data = scipy.io.loadmat('../examples/dataset/test.mat')
    return data["x"], data["y"]

def main():
    
    #q = tf.Variable(np.zeros([], np.float32))

    def pde(x, y):
        y, q = y[:, 0:1], y[:, 1:]
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
            - dy_xx + q * y 
            - np.pi**2 * tf.sin(np.pi* x[:, 0:1])
            - x[:, 0:1]**2 * tf.sin(np.pi*x[:, 0:1])
        )                                                          

    
    def func1(x):
        return x[:, 0:1]**2
    
    def func2(x):
        return np.sin(np.pi * x[:, 0:1])
    
    def func(x):
        return np.hstack((x[:, 0:1]**2, np.sin(np.pi * x[:, 0:1])))


    geom = dde.geometry.Interval(-1, 1)

    bc2 = dde.DirichletBC(geom, func2, lambda _, on_boundary: on_boundary)

    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 0:1]), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc2, observe_y],
        num_domain=200,
        num_boundary=2,
        anchors=observe_x,
        solution=func,
        num_test=100,
    )

    layer_size = [1] + [50] * 4 + [2]          #[1] + [[50,50],[50,50],[50,50]] + [2]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=30000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    

if __name__ == "__main__":
    main()

**Comment by liuhuanhuansky** [comment]
In addition, Is the loss function the same in all your examples. if I want to modify the loss, where I can modify it.

**Comment by lululxvi** [comment]
Your code looks good. Could you provide some details/results to figure out what could be wrong here?

The default loss function is MSE. You can modify the loss in `model.compile()` (DeepM&Mnet: Inferring the electroconvection multiphysics fields based on operator approximation by neural networks) Also see https://github.com/lululxvi/deepxde/blob/master/deepxde/losses.py You can define a new loss and pass in the function name.

**Comment by liuhuanhuansky** [comment]
file:///Users/liuhuanhuansky/Desktop/deepxde_new/Figure_1.png

**Comment by liuhuanhuansky** [comment]
Hi,lulu, these are the results
![figure_1](https://user-images.githubusercontent.com/68001725/94646437-d27a4f80-0320-11eb-84d8-29f55b920da9.png)

![figure_2](https://user-images.githubusercontent.com/68001725/94646544-02c1ee00-0321-11eb-912a-d8ebe684259d.png)
![figure_3](https://user-images.githubusercontent.com/68001725/94646562-0b1a2900-0321-11eb-83d1-aaba75c7321f.png)

**Comment by lululxvi** [comment]
In `bc2 = dde.DirichletBC(geom, func2, lambda _, on_boundary: on_boundary)`. Should it be func1?

**Comment by liuhuanhuansky** [comment]
q(x) should not have boundary condition




Best regards,
Liu Huan
On 10/01/2020 13:17, Lu Lu wrote:

In bc2 = dde.DirichletBC(geom, func2, lambda _, on_boundary: on_boundary). Should it be func1?

**Comment by liuhuanhuansky** [comment]
Hi,lulu
 I have revised the boundary condition, but the train loss doesn't decrease. The observation data are 50 uniformly distributed points in [-1,1]. In the train loss, there are four columns, what loss is each? The second and the fourth colunm don't decrease. I have tried many kinds of network, it doesn't work.
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 23 09:09:28 2020

@author: liuhuanhuansky
"""


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt
import scipy.io

import deepxde as dde
from deepxde.backend import tf


def gen_traindata():
    data = scipy.io.loadmat('../examples/dataset/test.mat')
    return data["x"], data["y"]

def main():
    
    #q = tf.Variable(np.zeros([], np.float32))

    def pde(x, y):
        y, q = y[:, 0:1], y[:, 1:]
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
            - dy_xx + q * y 
            - np.pi**2 * tf.sin(np.pi * x[:, 0:1])
            - x[:, 0:1]**2 * tf.sin(np.pi * x[:, 0:1])
        )                                                          
    def boundary(x, on_boundary):
        return on_boundary
    
    def func1(x):
        return x[:, 0:1]**2
    
    def func2(x):
        return np.sin(np.pi * x[:, 0:1])
    
    def func(x):
        return np.hstack((x[:, 0:1]**2, np.sin(np.pi * x[:, 0:1])))


    geom = dde.geometry.Interval(-1, 1)

    bc1 = dde.DirichletBC(geom, func1, boundary, component=0)
    bc2 = dde.DirichletBC(geom, func2, boundary, component=1)


    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 0:1]), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc1, bc2, observe_y],  # 
        num_domain=200,
        num_boundary=2,
        anchors=observe_x,
        solution=func,
        num_test=100,
    )

    layer_size =  [1] + [150] * 3 + [2]      #  [1] + [[50,100],[50,100],[50,50]] + [2]  
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"]) #loss=dde.losses(), 
    losshistory, train_state = model.train(epochs=20000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    

if __name__ == "__main__":
    main()

Step      Train loss                                  Test loss                                   Test metric   
0         [5.13e+01, 1.00e+00, 2.14e-04, 4.97e-01]    [5.11e+01, 0.00e+00, 0.00e+00, 0.00e+00]    [9.94e-01]    
1000      [5.52e-03, 4.20e-02, 2.70e-05, 1.38e-01]    [5.63e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [2.19e+00]    
2000      [2.06e-03, 3.40e-02, 1.69e-05, 1.42e-01]    [2.11e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [2.29e+00]    
3000      [1.91e-03, 3.51e-02, 3.88e-06, 1.39e-01]    [1.95e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [2.29e+00]    
4000      [7.07e-04, 3.25e-02, 7.29e-06, 1.41e-01]    [7.27e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [2.40e+00]    
5000      [1.89e-01, 3.74e-02, 3.08e-02, 1.49e-01]    [1.89e-01, 0.00e+00, 0.00e+00, 0.00e+00]    [2.39e+00]    
6000      [2.69e-04, 3.14e-02, 4.65e-06, 1.40e-01]    [2.76e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [2.56e+00]    
7000      [2.19e-04, 3.15e-02, 4.87e-06, 1.39e-01]    [2.25e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [2.59e+00]    
8000      [1.48e-02, 3.67e-02, 3.66e-03, 1.35e-01]    [1.49e-02, 0.00e+00, 0.00e+00, 0.00e+00]    [2.70e+00]    
9000      [2.29e-03, 3.66e-02, 1.26e-03, 1.34e-01]    [2.29e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [2.75e+00]    
10000     [1.87e-04, 3.08e-02, 3.19e-05, 1.38e-01]    [1.87e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [2.80e+00]    
11000     [1.68e-04, 3.00e-02, 1.21e-06, 1.38e-01]    [1.70e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [2.91e+00]    
12000     [2.78e-03, 3.36e-02, 1.46e-03, 1.33e-01]    [2.80e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [2.99e+00]    
13000     [5.03e-04, 2.87e-02, 1.60e-04, 1.37e-01]    [5.08e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [3.04e+00]    
14000     [2.24e-03, 3.27e-02, 1.60e-03, 1.32e-01]    [2.26e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [3.14e+00]    
15000     [1.66e-04, 2.89e-02, 7.96e-06, 1.35e-01]    [1.68e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [3.25e+00]    
16000     [1.59e-04, 2.86e-02, 9.79e-06, 1.34e-01]    [1.60e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [3.34e+00]    
17000     [3.27e-03, 2.76e-02, 2.46e-05, 1.33e-01]    [3.23e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [3.37e+00]    
18000     [8.28e-03, 3.33e-02, 1.13e-03, 1.28e-01]    [8.20e-03, 0.00e+00, 0.00e+00, 0.00e+00]    [3.51e+00]    
19000     [2.88e-04, 2.80e-02, 7.94e-06, 1.31e-01]    [2.92e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [3.61e+00]    
20000     [1.17e-04, 2.76e-02, 8.92e-07, 1.31e-01]    [1.20e-04, 0.00e+00, 0.00e+00, 0.00e+00]    [3.70e+00]    

Best model at step 20000:
  train loss: 1.59e-01
  test loss: 1.20e-04
  test metric: [3.70e+00]
![Figure_1](https://user-images.githubusercontent.com/68001725/95281897-d0694100-088a-11eb-890c-bcb2b58ddee4.png)
![Figure_2](https://user-images.githubusercontent.com/68001725/95281930-e119b700-088a-11eb-9287-a0bbf12d2dd1.png)
![Figure_3](https://user-images.githubusercontent.com/68001725/95281940-e6770180-088a-11eb-8a22-d5fabd1d87a6.png)

could you give any suggestions to solve it?

**Comment by lululxvi** [comment]
For the losses, the order is [pde, bc1, bc2, observe_y].

As far as I can see, your solution (y=x^2, q=sin(\pi x)) does not satisfy the PDE.

**Comment by liuhuanhuansky** [comment]
no, no, here y=sin(\pi x) , q=x^2 satisfy the PDE

**Comment by liuhuanhuansky** [comment]
In fact, because the ill-posedness, in order to identify the parameter, I should add the regularization term of parameter q(x) in the total loss. But I don't know how to add. 
In addition, generally speaking, we use boundary measurement data to solve the inverse problem. I still don't get good results using internal measurements here.

**Comment by lululxvi** [comment]
`y, q = y[:, 0:1], y[:, 1:]`: the first is `y`.

```
def func(x):
    return np.hstack((x[:, 0:1]**2, np.sin(np.pi * x[:, 0:1])))
```
 
Your code is not consistent with what you want. This problem should be easy to solve.

To use L2 regularization, e.g., `net = dde.FNN(... regularization=['l2', 1e-5]). Or just use many measurements first.

**Comment by liuhuanhuansky** [comment]
Thank you very much, lulu. I've reversed the order, now it's settled. 
By the way, is there any code about convolution neural network to solve pde problem in deepxde?

**Comment by lululxvi** [comment]
No. PINN approach does not need convolution.

**Comment by liuhuanhuansky** [comment]
hi,lulu
now I want to identify a highly oscillatory function q(x) in equation -du_xx + q(x)u =f, x\in [-1,1] with homogeneous Dirichlet boundary. for example q(x)= sin(20*x), I use the PINN method, fully connected network. even q(x)=sin(5*x), I tried 2000 training points,  I can't obtain a good result. using the code, I can get a good result for q(x)=sin(x).
So do you have any idea about the determination of highly oscillatory function, for example, try a CNN?

**Comment by lululxvi** [comment]
Try a large network, and make sure the loss is well trained.

**Comment by 979736316** [comment]
> 非常感谢，露露。我撤消了订单，现在已经解决了。
> 顺便说一句，是否有任何有关卷积神经网络的代码来解决Deepxde中的pde问题？

Hi, liuhuanhuansky and LuLu, Inversion function, this is an interesting idea, but I have a few questions about the code you defined:
1. Here, your ob_y should be the solution of the func1 corresponding to X in [-1,1]. Why did I run your code and there was an error？
![image](https://user-images.githubusercontent.com/52651366/116339163-8a1c0500-a80f-11eb-86e9-8b89c8c06b9d.png)
```
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt

import deepxde as dde
from deepxde.backend import tf
```

def gen_traindata():
    data = np.load("../../dataset/fun.npz")
    return data["arr_0"], data["arr_1"]

def main():
    def pde(x, y):
        y, q = y[:, 0:1], y[:, 1:]
        dy_x = tf.gradients(y, x)[0]
        dy_x = dy_x[:, 0:1]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        return (
                - dy_xx + q * y
                - np.pi ** 2 * tf.sin(np.pi * x[:, 0:1])
                - x[:, 0:1] ** 2 * tf.sin(np.pi * x[:, 0:1])
        )

    geom = dde.geometry.Interval(-1, 1)

    def boundary(x, on_boundary):
        return on_boundary

    def func1(x):
        return np.sin(np.pi * x[:, 0:1])

    def func2(x):
        return x[:, 0:1] ** 2

    def func(x):
        return np.hstack((np.sin(np.pi * x[:, 0:1]), x[:, 0:1] ** 2))

    bc1 = dde.DirichletBC(geom, func1, boundary, component=0)
    bc2 = dde.DirichletBC(geom, func2, boundary, component=1)

    observe_x, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 0:1]), lambda x, _: ptset.inside(x)
    )

    data = dde.data.PDE(
        geom,
        pde,
        [bc1, bc2, observe_y],  #
        num_domain=200,
        num_boundary=2,
        anchors=observe_x,
        solution=func,
        num_test=100,
    )

    layer_size = [1] + [150] * 3 + [2]

    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])  # loss=dde.losses(),
    losshistory, train_state = model.train(epochs=20000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

```
if __name__ == "__main__":
    main()
```


`
2. observe_y = dde.DirichletBC(geom, ptset.values_to_func(ob_y[:, 0:1]), lambda x, _: ptset.inside(x))，Don't you need to define the variable "component" here？Why not use pointsetbc?
