### ISSUE TITLE
Euler Equations - Sod Problem - Shock Capturing Issue

### ISSUE THREAD

**Issue by axledos100** [lululxvi/deepxde#126]
Hello!

I hope all is well. 

I need some advice on how to obtain better results for the Sod problem. I have looked through the FAQ on how to train the network better when training fails. I've introduced loss weights, increased the number of points in the domain and increased the number of iterations. Unfortunately, I am not able to capture the proper solutions to this problem. Each solution to rho,u, and p experiences too much dissipation or solutions have random jumps. I have attached my code below. Any advice moving forward would be greatly appreciated. 

[Euler_Eq.py.zip](https://github.com/lululxvi/deepxde/files/5276611/Euler_Eq.py.zip)

**Comment by lululxvi** [comment]
Euler Equation is not easy to learn because of the shock. You may try put more points near the shock, see https://doi.org/10.1016/j.cma.2019.112789

**Comment by kmache** [comment]
Dear Lu Lu
Please I am also working on PDEs with shock, how can I put more points near the shock? can you provide a piece of code?

**Comment by lululxvi** [comment]
See FAQ Q: How does DeepXDE choose the training points? How can I use some specific training points?
