### ISSUE TITLE
can we install deepxde in windows 32-bit?

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#128]
Dear Lu,
I want to install deepxde package on my other laptop with windows 32-bit? Does my system support deepxde? because I tried for numerous times but i couldn't install it.

**Comment by lululxvi** [comment]
I don't test on 32-bit machine. If you could successfully install the requires packages, especially TensorFlow, then it should be good. But I guess it may be hard to make TensorFlow working on 32-bit system.

**Comment by katayooneshkofti** [comment]
thank you @lululxvi , I could install tensorflow. I will test if I could install deepxde, too. I will close the issue.
