### ISSUE TITLE
About the training data, T_f, T_b and T_i for inverse problem

### ISSUE THREAD

**Issue by pjss1223** [lululxvi/deepxde#131]
Hello, I hope all is well.
When I work on an Inverse problem, I set up T_f, T_b, and T_i by writing dde.data.PDE(..,num_domain = , num_boundary=, anchors=). I think that the boundary and anchor points for T_b, T_i are automatically included in T_f. So even if I have num_domain = 0, it still gives me a valid loss for T_f data as T_f includes all points in T_b, T_i. 
Is this the right observation or am I misunderstanding anything?
If it is true, Is there any way to separate T_f form T_b and T_i?
Thank you very much.

**Comment by lululxvi** [comment]
Yes, you are right. The boundary and anchor points for T_b, T_i are automatically included in T_f. If you want to separate, then you have to modify the code https://github.com/lululxvi/deepxde/blob/28bb4d8510f5ad9136a42af8dfd5bb57e161e9ff/deepxde/data/pde.py#L88
