### ISSUE TITLE
Not able to solve a 2-d parabolic equation? Getting an error.

### ISSUE THREAD

**Issue by panghalshagun** [lululxvi/deepxde#132]
I am looking to solve the following parabolic PDE using deepxde.

<img width="352" alt="Screenshot 2020-09-29 at 2 04 28 PM" src="https://user-images.githubusercontent.com/55479654/94533584-f3796c80-025c-11eb-9fdd-abe7b657e226.png">
The code is here as follows:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import numpy as np
import deepxde as dde
from deepxde.backend import tf

def main():
          def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_y,dy_t = dy_x[:, 0:1], dy_x[:, 1:2], dy_x[:,2:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_yy = tf.gradients(dy_y, y)[0][:, 1:2]
        return dy_t-y*(dy_xx+dy_yy)-y
        
```
        
    geom = dde.geometry.Rectangle([0, 0],[1,1])
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)
    def func(x):
        return np.exp(x[:,2:])*(1+np.exp(x[:,0:1])*np.sin(x[:,1:2]))
    
    bc = dde.DirichletBC(geom, func, lambda _, on_boundary: on_boundary)
    ic = dde.IC(
        geomtime, lambda x: 1+np(exp(x[:,0:1])*np.sin(x[:,1:2])), lambda _, on_initial: on_initial
    )
    data=dde.data.TimePDE(
        geomtime, pde, [bc,ic], num_domain=1000, num_boundary=200, num_test=160
    )
    net = dde.maps.FNN([3] + [20]+ [1], "tanh", "Glorot normal")
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3)
    model.train(epochs=15000)
    model.compile("L-BFGS-B")
    #losshistory, train_state = model.train()
    model.train()
```
if __name__ == "__main__":
    main()
```

I am getting the following error:

ValueError: operands could not be broadcast together with shapes (3,) (2,)

**Comment by lululxvi** [comment]
`dy_yy = tf.gradients(dy_y, x)[0][:, 1:2]`

**Comment by panghalshagun** [comment]
Still getting the same error
