### ISSUE TITLE
How to implement Neumann BC: u_x(0,t) = u_x(L,t)?

### ISSUE THREAD

**Issue by EigenvectorOfFate** [lululxvi/deepxde#1352]
Hi @lululxvi,
I read through all the issues on boundary conditions, but still couldn't solve how to define u_x(0,t) = u_x(L,t) using OperatorBC.
Could you please give me a example?

For example, how to modify this code to satisfy u_x(0,t) = u_x(L,t)
def func(x, u, _):
   du_x = dde.grad.jacobian(u, x, i=0, j=0)
   return du_x

def boundary_r(x, on_boundary):
    return on_boundary and dde.utils.isclose(x[0], L)

def boundary_l(x, on_boundary):
   return on_boundary and dde.utils.isclose(x[0], 0)

Thank you in advance!

**Comment by lululxvi** [comment]
Use `PeriodicBC` with `derivative_order=1` https://deepxde.readthedocs.io/en/latest/modules/deepxde.icbc.html#deepxde.icbc.boundary_conditions.PeriodicBC

**Comment by EigenvectorOfFate** [comment]
Thank you very much!

It is worked with the following code.

def on_boundary(x, domain):
    return domain and (np.isclose(x[0], 0) or np.isclose(x[0], L))

bc = dde.icbc.boundary_conditions.PeriodicBC(geom, 0, on_boundary, derivative_order=1)
