### ISSUE TITLE
How do you solve a system of partial differential equations

### ISSUE THREAD

**Issue by ShiGuang72** [lululxvi/deepxde#137]
Hi,lu:
Thanks for sharing your work on deepxde, I have a question to consult you.If I want to solve a system of partial differential equations, such as a two-dimensional NS equation. The solution is a vector, how do I design a neural network? And how to ideal the pressure?

**Comment by lululxvi** [comment]
Check FAQ for some example.

**Comment by ShuGuang72** [comment]
Thank you for your answer

**Comment by ShuGuang72** [comment]
Hi，lu 
And how can I find the FAQ

**Comment by lululxvi** [comment]
It is at  deepxde.readthedocs.io
