### ISSUE TITLE
deeponet

### ISSUE THREAD

**Issue by EzequielS2** [lululxvi/deepxde#1380]
Hi @lululxvi  how to implement deeponet in code:

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

import math as m
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

from deepxde.callbacks import EarlyStopping

def main():

    k = float(0.0078) #sorption uptake rate, 1/s
    D_0 = float(2e-7) #Diffusion coefficient through pores, m^2/s
    alpha = float(100.0) # dimensioneless ratio q_sat/c_sat
    L_0 = float(2000.0e-6) #length, m / thickness of paper
    epsilon = float(0.5) #porosity
    num_time = 1000 #time given for the diffusion, s    

    gamma = num_time * D_0 / (alpha*L_0**2)
    
   
    time = 1 #dim.less time 

    L = 1 #dim.less length - l/L_0

    def pde(x, y):
        c, q = y[:, 0:1], y[:, 1:2] #have to be >= 0. These are dim.less concentrations
        
        #real concentrations are c*c_sat and q*q_sat [mol/m^3]
        
        dc_t = dde.grad.jacobian(y, x, i=0, j=1)
        dc_xx = dde.grad.hessian(y, x, component=0, i=0, j=0)
        dq_t = dde.grad.jacobian(y, x, i=1, j=1)

        eq_a = (1/alpha)*dc_t - gamma * dc_xx + ((1-epsilon)/epsilon) * dq_t 
        eq_b = dq_t - num_time * k * (1 - q) / (1 + tf.exp(-60.0*c))
        return [eq_a, eq_b]

    
    def fun_init(x):
        return np.exp(-5 * x[:, 0:1])+np.exp(-5 *(1 - x[:, 0:1]))

    def boundary_left(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_right(x, on_boundary):
        return on_boundary and np.isclose(x[0], L)
    

    geom = dde.geometry.Interval(0, L)
    timedomain = dde.geometry.TimeDomain(0, time)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc_a_left = dde.DirichletBC(
        geomtime, lambda x: 1, boundary_left, component=0
    )
    
    
    bc_a_right = dde.DirichletBC(
        geomtime, lambda x: 1, boundary_right, component=0
    )
    

    bc_b_left = dde.DirichletBC(
        geomtime, lambda x: 1, boundary_left, component=1
    )
    
    bc_b_right = dde.DirichletBC(
        geomtime, lambda x: 1, boundary_right, component=1
    )
 

    ic1 = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial, component=0)
    ic2 = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial, component=1)

 

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a_left, bc_a_right, bc_b_left, bc_b_right, ic1, ic2],
        num_domain=10000,
        num_boundary=1000,
        num_initial=1000,
        num_test=2000,

    )
    
      
 
    def modify_output(X, y):
        x, t = X[:, 0:1], X[:, 1:2]
        c = y[:, 0:1]
        c_new = x*(1.-x)*c + 1.
        q = y[:, 1:2]
        q_new = x*(1.-x)*q + 1.
        return tf.concat([c_new, q_new], axis=1)

**Comment by lululxvi** [comment]
https://deepxde.readthedocs.io/en/latest/demos/operator.html
