### ISSUE TITLE
'requiremets.txt' needs an update.

### ISSUE THREAD

**Issue by KeunwooPark** [lululxvi/deepxde#139]
When I install requirements.txt. tensor flow shows the following error.

```shell
ERROR: tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
```

I guess the version of Numpy should be indicated.
This version of requirements.txt works fine.
```
matplotlib
numpy<1.19.0
salib
scikit-learn
scipy
tensorflow>=1.14.0
```

**Comment by lululxvi** [comment]
Ah, thanks. I haven't tried TensorFlow 2.3.1 yet. It is really annoying that TensorFlow doesn't support the new version of numpy.
