### ISSUE TITLE
How to implement a state-variable-dependent coefficient in PDE

### ISSUE THREAD

**Issue by XyM6u9** [lululxvi/deepxde#1415]
Such as Richards equation:

    dHdx =  dde.grad.jacobian(y, x, i=0, j=0)
    d2kx = dde.grad.jacobian(K*dHdx, x, i=0, j=0)
    
    dHdy =  dde.grad.jacobian(y, x, i=0, j=1)
    d2ky = dde.grad.jacobian(K*dHdy, x, i=0, j=1)
          
    return d2kx + d2ky
where K=k(H) (k is a specific formula depending on H)

**Comment by schrodingersket** [comment]
If `k(H)` has an analytic form, what you have should work. For instance, if `k(H) = H * H` (as a simple example), you might have:

```
def pde(x, y):
    H = y[:, 0:1]  # Assuming H is the first output. If it's the second, this would be H = y[:, 1:2]

    # Hydraulic conductivity function in terms of H
    #
    K = H * H

    dHdx =  dde.grad.jacobian(y, x, i=0, j=0)
    d2kx = dde.grad.jacobian(K * dHdx, x, i=0, j=0)

    dHdy =  dde.grad.jacobian(y, x, i=0, j=1)
    d2ky = dde.grad.jacobian(K * dHdy, x, i=0, j=1)
      
    return d2kx + d2ky
```

**Comment by XyM6u9** [comment]
> If `k(H)` has an analytic form, what you have should work. For instance, if `k(H) = H * H` (as a simple example), you might have:
> 
> ```
> def pde(x, y):
>     H = y[:, 0:1]  # Assuming H is the first output. If it's the second, this would be H = y[:, 1:2]
> 
>     # Hydraulic conductivity function in terms of H
>     #
>     K = H * H
> 
>     dHdx =  dde.grad.jacobian(y, x, i=0, j=0)
>     d2kx = dde.grad.jacobian(K * dHdx, x, i=0, j=0)
> 
>     dHdy =  dde.grad.jacobian(y, x, i=0, j=1)
>     d2ky = dde.grad.jacobian(K * dHdy, x, i=0, j=1)
>       
>     return d2kx + d2ky
> ```

Thanks a lot. It works. 
Do you know how applied piecewise and state-variable-dependent coefficient in PDE by any chance?
See #1416

**Comment by schrodingersket** [comment]
In the first two lines of your code in the referenced discussion, I notice you have:

```
def pde(x, y):    
    uw = (y-x[:, 1:2])*1000*9.8
```

...which means that you're subtracting the second input vector from the entire output `y` vector. Does changing it to the below make any difference?

```
def pde(x, y):
    H = y[:, 0:1]
    uw = (H - x[:, 1:2]) * 1000 * 9.8
```

**Comment by XyM6u9** [comment]
> In the first two lines of your code in the referenced discussion, I notice you have:
> 
> ```
> def pde(x, y):    
>     uw = (y-x[:, 1:2])*1000*9.8
> ```
> 
> ...which means that you're subtracting the second input vector from the entire output `y` vector. Does changing it to the below make any difference?
> 
> ```
> def pde(x, y):
>     H = y[:, 0:1]
>     uw = (H - x[:, 1:2]) * 1000 * 9.8
> ```

No difference, because y only contains one variable.

**Comment by schrodingersket** [comment]
My apologies; I didn't quite look closely enough at your conditional evaluation. I suggest looking into using [tf.where](https://www.tensorflow.org/api_docs/python/tf/where) instead of [tf.cond](https://www.tensorflow.org/api_docs/python/tf/cond). I've had success doing something like the following:

```
...
def pde(x, y):    
    uw = (y[:, 0:1] - x[:, 1:2]) * 1000 * 9.8
    kr = (1 - tf.abs(-k_a * uw) ** (sr_n * sr_m) / ((1 + tf.abs(-k_a * uw) ** sr_n) ** sr_m)) ** 2 / (1 + tf.abs(-k_a * uw) ** sr_n) ** (sr_m / 2)

    # Desired piecewise condition defined on uw
    #
    condition = tf.less(uw, 0)
    K = tf.where(condition, ks * kr, ks * tf.ones_like(uw))  # ...assuming ks is a scalar that has already been defined elsewhere
...
```

**Comment by XyM6u9** [comment]
> 

Thank!!! It works.
