### ISSUE TITLE
Where are datasets of "antiderivative aligned" and "antiderivative unaligned" examples?

### ISSUE THREAD

**Issue by lijialin03** [lululxvi/deepxde#1422]
### Discussed in https://github.com/lululxvi/deepxde/discussions/1421

<div type='discussions-op-text'>

<sup>Originally posted by **lijialin03** August  7, 2023</sup>
Hi, when I run antiderivative_aligned.py example and antiderivative_unaligned.py example, the following dataset cannot be found,
antiderivative_aligned_train.npz
antiderivative_aligned_test.npz
antiderivative_unaligned_train.npz
antiderivative_unaligned_test.npz
Now that they are neither in dataset folder nor in operator folder, where can I find them?
</div>

**Comment by voloddia** [comment]
For those who are still looking for these datasets and a note for myself: 
https://yaleedu-my.sharepoint.com/:f:/g/personal/lu_lu_yale_edu/EnTn0aLimaRJuNKDOc0lfHkB2MXK8n8vAO1oV5cWVdJo3w?e=OLp80r
