### ISSUE TITLE
How to add value to the loss function?

### ISSUE THREAD

**Issue by Rodfood** [lululxvi/deepxde#143]
Hi.Lu
First of all. DeepXDE is really great!
I have a question to solve, if I want to add some values to the loss function, how I can do it. For example ,  add a regularization item to the loss function.

**Comment by lululxvi** [comment]
Regularization can be added when you define network: https://deepxde.readthedocs.io/en/latest/modules/deepxde.maps.html#deepxde.maps.fnn.FNN. e.g., `regularization=['l2', 1e-5]`

**Comment by Penguin-math** [comment]
Hi, Lulu
If I want to add some constraints to the loss function such as the u>0,how I can do it

**Comment by lululxvi** [comment]
What is `u`? If `u` is the network output, then you can use `net.apply_output_transform(f)` to do it. For example, `f = lambda x,y: tf.exp(y)` by using the exponential of the network output as the PDE solution, which is always positive.
