### ISSUE TITLE
Sciann converges, but deepxde doesn't

### ISSUE THREAD

**Issue by tyagi-ankit** [lululxvi/deepxde#1442]
Hi, thanks for this excellent library. It's very convenient, and I want to use it more often. 

I'm trying to reproduce a simple elasticity problem solved in https://arxiv.org/abs/2003.02751

The corresponding  code is given here  https://github.com/sciann/sciann-applications/blob/master/SciANN-Elasticity/Elasticity-Forward.ipynb and it uses the sciann library. I have run this code: it takes hardly anytime to converge to the exact solution, as shown in the notebook.

I tried to reproduce the results using the deepxde:  see https://drive.google.com/file/d/1w23-ddXPbMMtbMugVRmN6w9wg_qpm9ZK/view?usp=drive_link It never converges. I have gone through it multiple times, but I don't know why it doesn't give me the right results.

Could you please help in finding the issue here?

Thanks.

**Comment by lululxvi** [comment]
You may explain more details on "never converges".

**Comment by tyagi-ankit** [comment]
Thank you so much for the reply.

You can see in the sciann notebook that it takes only 100 epochs for the solution to converge to the right solution. See the prediction plots at the end of that notebook. They look exactly same as the exact solution, which I confirmed by plotting them separately.

In deepxde notebook, which I created, I ran it for as many as 5000 epochs, it still doesn't come close to the right solution profile.
You can see displacement, stress, and strain prediction and exact solution plots in that notebook.

Both the notebooks are linked in my original issue post.

Please let me know for any further details or clarification.

**Comment by ww382** [comment]
I had the following code and ran it for 20000 epochs. I was able to get good results. 

```
import deepxde as dde
from deepxde.backend import torch
import numpy as np

lmbd = 1.0
mu = 0.5
Q = 4.0

pi = torch.pi

def pde(x, f):
    """
    INPUTS:
        x: x[:,0] is the x-coordinate
           x[:,1] is the y-coordinate
        f: Network output
           f[:,0] is ux
           f[:,1] is uy
           f[:,2] is S_xx
           f[:,3] is S_yy
           f[:,4] is S_xy
    OUTPUTS:
        The pde in standard form
        
    """
    
    E_xx = dde.grad.jacobian(f, x, i=0, j=0)
    E_yy = dde.grad.jacobian(f, x, i=1, j=1)
    E_xy = 0.5*(dde.grad.jacobian(f, x, i=0, j=1)+dde.grad.jacobian(f, x, i=1, j=0))
  
    S_xx = E_xx*(2*mu+lmbd)+E_yy*lmbd
    S_yy = E_yy*(2*mu+lmbd)+E_xx*lmbd
    S_xy = E_xy*2*mu
    
    Sxx_x = dde.grad.jacobian(f, x, i=2, j=0)
    Syy_y = dde.grad.jacobian(f, x, i=3, j=1)
    Sxy_x = dde.grad.jacobian(f, x, i=4, j=0)
    Sxy_y = dde.grad.jacobian(f, x, i=4, j=1)
    
    xx = x[:, 0:1]
    yy = x[:, 1:2]
    
    Fx = - lmbd*(4*pi**2*torch.cos(2*pi*xx)*torch.sin(pi*yy) - Q*yy**3*pi*torch.cos(pi*xx)) \
         - mu*(pi**2*torch.cos(2*pi*xx)*torch.sin(pi*yy) - Q*yy**3*pi*torch.cos(pi*xx))\
         - 8*mu*pi**2*torch.cos(2*pi*xx)*torch.sin(pi*yy)

    Fy = lmbd*(3*Q*yy**2*torch.sin(pi*xx) - 2*pi**2*torch.cos(pi*yy)*torch.sin(2*pi*xx))\
         - mu*(2*pi**2*torch.cos(pi*yy)*torch.sin(2*pi*xx) + (Q*yy**4*pi**2*torch.sin(pi*xx))/4)\
         + 6*Q*mu*yy**2*torch.sin(pi*xx)

    momentum_x = ( Sxx_x + Sxy_y - Fx)
    momentum_y = ( Sxy_x + Syy_y - Fy)
    
    stress_x = (S_xx-f[:,2:3])
    stress_y = (S_yy-f[:,3:4])
    stress_xy = (S_xy-f[:,4:5])
    
    return [momentum_x, momentum_y, stress_x, stress_y, stress_xy]

def ux_func(x):
    return np.cos(2*pi*x[:, 0:1])*np.sin(pi*x[:,1:2])

def uy_func(x):
    return np.sin(pi*x[:, 0:1])*Q*x[:,1:2]**4/4

def Sxx_func(x):
    E_xx = np.diff(ux_func(x[:,0:1]))/np.diff(x[:,0:1])
    E_yy = np.diff(uy_func(x[:,0:1]))/np.diff(x[:,1:2])
    return E_xx*(2*mu+lmbd)+E_yy*lmbd

def Syy_func(x):
    E_xx = np.diff(ux_func(x[:,0:1]))/np.diff(x[:,0:1])
    E_yy = np.diff(uy_func(x[:,0:1]))/np.diff(x[:,1:2])
    return E_yy*(2*mu+lmbd)+E_xx*lmbd

def Sxy_func(x):
    E_xy = 0.5*(np.diff(ux_func(x[:,0:1]))/np.diff(x[:,1:2])+np.diff(uy_func(x[:,0:1]))/np.diff(x[:,0:1]))
    return E_xy*2*mu

# Exact solutions
def func(x):
    """
    ux = np.cos(2*pi*x[:, 0:1])*np.sin(pi*x[:,1:2])
    uy = np.sin(pi*x[:, 0:1])*Q*x[:,1:2]**4/4
    """
    return np.hstack((ux_func(x), uy_func(x), Sxx_func(x), Syy_func(x), Sxy_func(x)))

geom = dde.geometry.Rectangle([0, 0], [1, 1])

data = dde.data.PDE(
    geom,
    pde,
    [],
    num_domain=500,
    num_boundary=500,
    solution=func,
    num_test=500,
)

def output_transform(x, y):
    
    ux, uy = y[:, 0:1], y[:, 1:2]
    sxx, syy, sxy = y[:, 2:3], y[:, 3:4], y[:, 4:5]
    
    # enforce displacement boundary conditions
    ux = (1 - x[:, 1:2]) * x[:, 1:2] * ux
    uy = (1 - x[:, 0:1]) * x[:, 0:1] * x[:, 1:2] * uy
    
    # enforce stress boundary conditions
    sxx = (1 - x[:, 0:1]) * x[:, 0:1] * sxx
    syy = (1 - x[:, 1:2]) * syy + (2*mu+lmbd)*Q*torch.sin(pi*x[:, 0:1])
    
    return torch.concat([ux, uy, sxx, syy, sxy], axis=1)

net = dde.maps.FNN([2] + 10 * [45] + [5], "tanh", "Glorot normal")
net.apply_output_transform(output_transform)

model = dde.Model(data, net)
model.compile("adam", lr=0.001)
losshistory, train_state = model.train(epochs=20000)

X = geom.random_points(10000)
output = model.predict(X)

ux_pred = output[:, 0]
uy_pred = output[:, 1]
Sxx_pred = output[:, 2]
Syy_pred = output[:, 3]
Sxy_pred = output[:, 4]

ux_exact = ux_func(X).reshape(-1)
uy_exact = uy_func(X).reshape(-1)

f = model.predict(X, operator=pde)

l2_difference_ux = dde.metrics.l2_relative_error(ux_exact, ux_pred)
l2_difference_uy = dde.metrics.l2_relative_error(uy_exact, uy_pred)

residual = np.mean(np.absolute(f))

print("Mean residual:", residual)
print("L2 relative error in ux:", l2_difference_ux)
print("L2 relative error in uy:", l2_difference_uy)
```
![Screenshot 2023-09-12 at 10 37 55 AM](https://github.com/lululxvi/deepxde/assets/13965012/59145fb1-8533-4e9a-bf42-d77f730eb2ae)

![Screenshot 2023-09-12 at 11 43 50 AM](https://github.com/lululxvi/deepxde/assets/13965012/d2345f5b-aa8b-41db-b7cc-d9a307ac602e)

Sciann uses batches in their analysis; maybe that's why it took fewer epochs for their solution to converge.

**Comment by tyagi-ankit** [comment]
Thanks for the reply.

If batch_size is the only issue, we can always provide it in model.train.

I went through your code. The only differences that I see in yours and my code are

1. Your network has 10 hidden layers each having 45 neurons. Mine has just 4 hidden layers with 40 neurons each, same as the sciann version.
2.  You strictly impose boundary conditions, while I make them part of dde.data.PDE.
3. You use single network, I use parallel networks dde.nn.PFNN, similar to sciann.
4.  You use torch, I use tensorflow.

Other than these, I don't see any major difference. I ran my code for 20000 epochs. It still doesn't converge to the right solution.

I tried to run your code. It gave me a value error:

ValueError: Cannot feed value of shape (1000, 2) for Tensor Placeholder_3:0, which has shape (None, 5)

But this maybe torch vs tf issue --- I had to convert your torch statements to tf statements.

I still don't see what's wrong with my code. Why doesn't it converge to the right solution.

**Comment by ww382** [comment]
I changed the stress boundary condition in your code to 
```
bc_top_syy = dde.icbc.DirichletBC(geom, Syy_bound, boundary_top, component=3)
```
where ```Syy_bound``` is defined as 
```
def Syy_bound(x):
    return (2*mu+la)*Q*sin(pi*x[:,0:1])
```
I was able to get good results with 5000 epochs. 
 
![Screenshot 2023-09-13 at 10 27 41 AM](https://github.com/lululxvi/deepxde/assets/13965012/9dd79997-6f7c-4353-b42a-e85501b57a8b)

**Comment by tyagi-ankit** [comment]
Thanks. It definitely works.

So, effectively the only change is: replace x[0] by x[:, 0:1] in the lambda function of bc_top_syy boundary condition.

While this works perfectly, I wonder what's the fundamental difference between them from the library point of view?

Thanks again.

**Comment by lululxvi** [comment]
@ww382 Feel free to add this example to https://deepxde.readthedocs.io/en/latest/demos/pinn_forward.html
