### ISSUE TITLE
Getting the exact data to test and train

### ISSUE THREAD

**Issue by engsbk** [lululxvi/deepxde#145]
Hello,

In the code Burger.py, I can see that the network is being trained and tested using data from Burgers.npz (x, t, usol). How was this file obtained? If I wanted to train a PINN for another physical equation how can I create a similar file with training/testing data?

I thought of having a separate script to create these values of x, t and their output in the physical equation, but if there is measured data available, this makes it easier to train using those data?

**Comment by lululxvi** [comment]
It is obtained from standard numerical solver. This is just for verifying the network solution. You can ignore them.

**Comment by engsbk** [comment]
Thanks for your reply, Lu! Can you share the name of the solver you used?
Or do you mean I can use something like Matlab, have random numbers in a certain range or boundary fed to the equation, and collect the results?

I appreciate your reply

**Comment by lululxvi** [comment]
It is just finite difference with a very fine mesh. You don't need it to solve the pde.

**Comment by engsbk** [comment]
Great. thanks for the reply!
Did you choose x to be uniformly distributed random values between -1 and 1 and then applied the Finite Difference method to those values with time-stepping?

**Comment by lululxvi** [comment]
Yes, uniform fine mesh with small enough time step. Just standard finite difference, nothing fancy. I have no experience with the the code you mentioned, but there are many online code for this. Burgers is a standard textbook example.
