### ISSUE TITLE
OperatorBC boundary of coupling equation

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#147]
Hi, I recently wanted to use Deepxde to solve coupled partial differential equations with an initial condition like this:
![image](https://user-images.githubusercontent.com/52651366/97109789-37eb1180-1710-11eb-9844-07c365901024.png)
I know that I should use the OperatorBC for the definition. I have been able to run the Wave equation successfully, but I got a large loss value  when running the coupling equation. I wonder what went wrong.
![image](https://user-images.githubusercontent.com/52651366/97109919-18a0b400-1711-11eb-9145-d6f60762ccb3.png)
![image](https://user-images.githubusercontent.com/52651366/97110022-ca3fe500-1711-11eb-952f-8c137db024ea.png)

**Comment by lululxvi** [comment]
`dRA_y` and `dIA_y` are the same except the f and g. Which line is `dRA/dT`, and which is `dIA/dT`? In the code, both are `dy_t`.
