### ISSUE TITLE
How to Tune the Parameters?

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#150]
Dear @lululxvi 
Firstly, I am grateful for your commitment and the answers to my questions. 
I would like to know is there any rule of thumb for setting the values of num_domain, num_bcs, num_inits, and num_tests especially when we do not have the true solution? 
in addition, is it possible for you to check the specific part of my code for initial and boundary conditions whether it embeds any mistakes or not? (this is about the elasticity problem with two inputs as distance and time along with two outputs for displacement and temperature). I am sorry to bother you but I hesitate for using lambda in my BC and IC definitions. 
The boundary and Initial Conditions are as follows: ![BCs and ICS](https://user-images.githubusercontent.com/68455679/97275182-da0f1480-184a-11eb-81cc-74347235725c.png)
and here is my code in part: 
`def boundary_rin (x, on_boundary):
        return on_boundary and np.isclose(x[0], 1.)  #rmin=1
    
    def boundary_rout (x, on_boundary):
        return on_boundary and np.isclose(x[0], 1.5)  #rmax=1.5  
    
    def boundary_for_initial(x, _ ):
         return np.isclose(x[1],0)
          
    def func(x):
        return np.zeros((len(x),1), dtype=np.float32)
   
    def H(x):
        return np.heaviside(x[:,1:],1)   
    
    def boundary(_, on_initial):
        return on_initial
        
    bc1= dde.DirichletBC(geomtime,func,boundary_rin, component=0)
    bc2= dde.DirichletBC(geomtime,func,boundary_rout,component=0)
    bc3=dde.DirichletBC(geomtime,H,boundary_rin,component=1)
    bc4=dde.DirichletBC(geomtime,func,boundary_rout,component=1)
    ####Considering Neumann Boundary Conditions for initial conditions with derivatives###
    bc5=dde.NeumannBC(geomtime, func, boundary_for_initial, component=0)
    bc6=dde.NeumannBC(geomtime, func, boundary_for_initial, component=1)

    #Initial Conditions
    ic1= dde.IC(geomtime, func, boundary, component=0)
    ic2= dde.IC(geomtime, func, boundary, component=1)`

**Comment by lululxvi** [comment]
You can select `num_domain`, `num_bcs`, `num_inits` by assuming mesh size in the finite difference method. Of course, they can be more sparse. Or you can start from small size to large number, until the solusion conoverges, just like what people do in finite difference.

You code looks good.

**Comment by katayooneshkofti** [comment]
@lululxvi Thank you so much. 
I close this issue.
