### ISSUE TITLE
DeepONet examples

### ISSUE THREAD

**Issue by tituskx** [lululxvi/deepxde#151]
Hi!

In your [paper](https://arxiv.org/pdf/1910.03193.pdf) on learning nonlinear operators you mention that the code of all examples can be found in https://github.com/lululxvi/deepxde. I could be mistaken but I can't find those examples; am I missing something or will they be uploaded in the future?

Thanks for the great work!

**Comment by lululxvi** [comment]
The code will be uploaded soon after our paper is accepted.

**Comment by newalexander** [comment]
Hello @lululxvi ! I see that you have now added classes that implement DeepONets (e.g., https://deepxde.readthedocs.io/en/latest/modules/deepxde.nn.tensorflow.html#module-deepxde.nn.tensorflow.deeponet), which is great. 

Do you have any example scripts showing how to train a DeepONet for a sample dataset? Some things are not fully clear from the code itself. For example, the relevant data class (https://github.com/lululxvi/deepxde/blob/master/deepxde/data/triple.py) doesn't specify what `X_train` should be a tuple of.

**Comment by lululxvi** [comment]
Please the code of DeepONet at
- https://github.com/lululxvi/deeponet
- https://github.com/lu-group/deeponet-fno
