### ISSUE TITLE
Define BC inside the geometry

### ISSUE THREAD

**Issue by PieterGimbel** [lululxvi/deepxde#156]
How would one define a boundary condition inside the `Interval` geometry?

I would assume the following (based on 'normal' boundary conditions):
```
def boundary_c(x, inside):
    return inside and np.isclose(x[0], 2)

geom = dde.geomtery.Interval(0,5)
bc = dde.DiricheletBC(geom, lambda x: 0, boundary_c)
```
which is not working for me (returning `'nan'` for this BC during training and failing on resulting `'NoneType'` for `best_y`).

**Comment by lululxvi** [comment]
You can just define the function as
```
def boundary_c(x, _):
    return np.isclose(x[0], 2)
```

**Comment by Gregouare** [comment]
Hello everyone,
Just a question regarding a similar topic. If I am to set 'boundary' conditions inside my domain, and then add the given points in the sampling , does it matter how I sample them time-wisely (i.e. should I use the same time samples for these points as for all the other points in the training set ?) ? 

Thanks a lot for your help
