### ISSUE TITLE
Complex Geometry

### ISSUE THREAD

**Issue by Clement465** [lululxvi/deepxde#161]
Hi @lululxvi, 

Is it possible to define complex geometries using DeepXDE? Could I for example, read in a set of points that represent the surface of an airfoil instead of using the geometry module?

Thank you for amazing work writing this library.

Best regards,
Clement

**Comment by lululxvi** [comment]
Currently DeepXDE cannot use a set of points to build the geometry.
1. One way to define complex geometry is by using CSG.
1. You can also define your geometry class by inheriting from the base class `Geometry`
1. The geometry is mainly used to generate the training points. You can just define a "dummy" geometry like Cuboid, but not use it at all. Specifically, you set `num_domain=0`, `num_boundary`, and construct all the points manually and pass them by `anchors` in https://deepxde.readthedocs.io/en/latest/modules/deepxde.data.html#deepxde.data.pde.PDE

**Comment by Clement465** [comment]
Would it be possible to impose boundary conditions using the third method?

**Comment by lululxvi** [comment]
Yes.

**Comment by Clement465** [comment]
Thank you!

**Comment by AbhishekP324** [comment]
@lululxvi 

I have convergent nozzle as shown in the figure attached. All the co-ordinates are in CSV file which I read in the code to create the geometry. It is complex geometry which I can't create using CSG feature.

How can I use this geometry to run PINN model using DeepXde?

![image](https://github.com/lululxvi/deepxde/assets/123780491/f7c9cd62-00d4-46fb-ba04-9c12c1536e56)

**Comment by lululxvi** [comment]
You can use `PointCloud` https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#deepxde.geometry.pointcloud.PointCloud

**Comment by ruchitkini** [comment]
> Currently DeepXDE cannot use a set of points to build the geometry.
> 
> 1. One way to define complex geometry is by using CSG.
> 2. You can also define your geometry class by inheriting from the base class `Geometry`
> 3. The geometry is mainly used to generate the training points. You can just define a "dummy" geometry like Cuboid, but not use it at all. Specifically, you set `num_domain=0`, `num_boundary`, and construct all the points manually and pass them by `anchors` in https://deepxde.readthedocs.io/en/latest/modules/deepxde.data.html#deepxde.data.pde.PDE

How to define dummy cuboid geometry here?
When I use, ` geom = dde.geometry.Cuboid( ) ` gives me an error and asks me to enter the xmin and xmax values.
If I give the xmin and xmax values and set the data as
```
geom = dde.geometry.Cuboid([-1, -2, -1], [13, 2, 11])
bc = dde.icbc.DirichletBC(geom, lambda x: 0, boundary)
data = dde.data.PDE(geom, pde, bc, num_domain=0, num_boundary=0, num_test=3000, anchors = coords)
```
the codes don't run properly
```
Training model...

Step      Train loss              Test loss               Test metric
0         [9.69e-01, nan]         [9.81e-01, nan]         [ ]

Best model at step 0:
  train loss: inf
  test loss: inf
  test metric: 

'train' took 0.308201 s
```
Is my code correct?

**Comment by SudharsunG** [comment]
i have used PointCloud to define the boundary and pointsetBC to define the boundary conditions. But while training, My deepxde code is not considering the boundary loss. How do I rectify this issue?
