### ISSUE TITLE
about the burger's equation result

### ISSUE THREAD

**Issue by yonghcui** [lululxvi/deepxde#162]
hello, doctor lulu, i have run the example Burgers.py and i got the results figure 1 and 2, i wonder if it right or not? and i have a question that how do you get the figure like figure 3, just run the code and it will be output? Thank you !
![1](https://user-images.githubusercontent.com/74175204/99207036-e5c17b80-27f7-11eb-864d-54eba29ccf9f.png)
![2](https://user-images.githubusercontent.com/74175204/99207043-e9ed9900-27f7-11eb-82d6-f6c4d60a7f82.png)
![3](https://user-images.githubusercontent.com/74175204/99207049-ee19b680-27f7-11eb-9975-3104742a6470.PNG)

**Comment by lululxvi** [comment]
The results look good. The code will not output Fig. C. You can plot it based on the saved training points file `train.dat` and the messages in the screen.
