### ISSUE TITLE
A large number of nan values appear at runtime

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#164]
Recently, I want to use the DeepXDE framework to solve the equation coupling problem. The equation form is as follows. 
![image](https://user-images.githubusercontent.com/52651366/100219715-4c117100-2f51-11eb-8c34-6a9238960a5c.png)

I want to construct the initial conditions and boundary conditions through analytical solutions. After verification, the analytical solution forms are correct. However, a large number of nan values appear when using PINN calculations. And there is the following warning, I don’t know what I did wrong, can you give me some suggestions？
![image](https://user-images.githubusercontent.com/52651366/100219765-5cc1e700-2f51-11eb-8405-557723aa03b0.png)

**Comment by lululxvi** [comment]
There should be something wrong with your test dataset. Maybe they are too sparse.

**Comment by 979736316** [comment]
> There should be something wrong with your test dataset. Maybe they are too sparse.

Do you mean that I have too few training points when solving the forward problem?

**Comment by lululxvi** [comment]
The `nan` is from testing loss. There might be something wrong with your test dataset. You may just set `num_test=None`.
