### ISSUE TITLE
ZCS support for PINNs

### ISSUE THREAD

**Issue by pescap** [lululxvi/deepxde#1645]
Hi @kuangdai, thank you for adding ZCS support for DeepONets. I am very interested in using this method for PINNs with high-order derivatives. 

Is ZCS directly adaptable to PINNs, or shall we add a custom [ PDE ](https://github.com/lululxvi/deepxde/blob/85920299331bd7c0bad01f3d2abba442a77c89c6/deepxde/data/pde.py#L10) class?

Finally, we could also incorporate ZCS to any of the [operator examples](https://github.com/lululxvi/deepxde/tree/master/examples/operator).

Thank you for your help!

**Comment by pescap** [comment]
Hi, thank you for your quick reply.

I am considering trying ZCS for PINNs involving high-order derivatives. My main case is outlined in the following link:

https://github.com/pescap/TensorPINNs/blob/main/Poisson/tensoruq.py

In this case, one has:

```
 \partial_{x_1} \cdots \partial_{x_k} \Sigma(x_1, \cdots, x_k) = C(x_1,\cdots,x_k)
```
I was recursively applying `dde.grad.hessian` -> Exponential with `k`.

Another interesting case, as mentioned in your work, is gradient-enhanced PINNs, for example:


https://github.com/lu-group/gpinn/blob/09dd5903c326389f041341ed8cfe4984b24278cd/src/poisson_1d.py#L52

**Comment by kuangdai** [comment]
Thanks. 

The scripts you gave above are not using DeepONets. Please note that ZCS is not designed for PINNs but for operators (such as DeepONet).

Please make sure your script uses `deepxde.data.PDEOperatorCartesianProd` for `data`, and `dde.nn.DeepONetCartesianProd` for `net`. For example, https://github.com/lululxvi/deepxde/blob/master/examples/operator/diff_rec_aligned_pideeponet.py.

Once you have one such script ready, I can change a few line for ZCS support to speed it up.

With ZCS, high-dimensional and high-order derivates are made much easier, e.g,:

```python
grad_zcs = dde.zcs.LazyGrad(x, y)
grad_zcs.compute((1, 1, 1, 1))
```
will compute  $\partial{x_1}\partial{x_2}\partial{x_3}\partial{x_4}$.

```python
grad_zcs.compute((2, 2, 2, 2))
```
will compute  $\partial^2{x_1}\partial^2{x_2}\partial^2{x_3}\partial^2{x_4}$.
