### ISSUE TITLE
How do i read data from an excel file and use it to calculate the parameters for a system of ordinary differential equation?

### ISSUE THREAD

**Issue by panghalshagun** [lululxvi/deepxde#167]
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf
import pandas as pd

def gen_traindata():
    df = pd.read_excel (r'cases.xlsx') #place "r" before the path string to address special character, such as '\'. Don't forget to put the file name at the end of the path + '.xlsx'
    t=df.iloc[:, 0:1].values
    y=df.iloc[:,1:].values
    return t,y
def main():
    C1 = tf.Variable(1.0)
    C2 = tf.Variable(1.0)
    def Lorenz_system(x, y):
        """Lorenz system.
        dy1/dx = 10 * (y2 - y1)
        dy2/dx = y1 * (28 - y3) - y2
        dy3/dx = y1 * y2 - 8/3 * y3
        """
        y1, y2, y3 = y[:, 0:1], y[:, 1:2], y[:, 2:]
        dy1_x = tf.gradients(y1, x)[0]
        dy2_x = tf.gradients(y2, x)[0]
        dy3_x = tf.gradients(y3, x)[0]
        return [
            dy1_x +C1 * (y1*y2),
            dy2_x -C1 * (y1*y2)+C2*y2,
            dy3_x - C2*y2
        ]

    def boundary(_, on_initial):
        return on_initial

    geom = dde.geometry.TimeDomain(0, 2)
    ic1 = dde.IC(geom, lambda X: 0.488, boundary, component=0)
    ic2 = dde.IC(geom, lambda X: 0.0488, boundary, component=1)
    ic3 = dde.IC(geom, lambda X: 0, boundary, component=2)

    # Get the train data
    observe_t, ob_y = gen_traindata()
    ptset = dde.bc.PointSet(observe_t)
    inside = lambda x, _: ptset.inside(x)
    observe_y0 = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 0:1]), inside, component=0
    )
    observe_y1 = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 1:2]), inside, component=1
    )
    observe_y2 = dde.DirichletBC(
        geom, ptset.values_to_func(ob_y[:, 2:3]), inside, component=2
    )

    data = dde.data.PDE(
        geom,
        Lorenz_system,
        [ic1, ic2, ic3, observe_y0, observe_y1, observe_y2],
        num_domain=400,
        num_boundary=2,
        anchors=observe_t,
    )

    net = dde.maps.FNN([1] + [20]+ [3], "tanh", "Glorot uniform")
    model = dde.Model(data, net)
    model.compile("adam", lr=0.001)
    variable = dde.callbacks.VariableValue(
        [C1, C2], period=600, filename="variables.dat"
    )
    losshistory, train_state = model.train(epochs=60000, callbacks=[variable])
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()
`

I am getting the following error.
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by lululxvi** [comment]
Your problem is from readling excel file, and not related to DeepXDE. I have no experience on reading excel file in Python.
