### ISSUE TITLE
Different PDEs for different points

### ISSUE THREAD

**Issue by bakhtiyar-k** [lululxvi/deepxde#1695]
Hello,

If I have two sets of collocation points (red and blue), how can I specify two different sets of PDEs for them and run the network training?
![image](https://github.com/lululxvi/deepxde/assets/81955278/c0cf5eb4-b40b-469d-97ea-ef4df791b572)

**Comment by praksharma** [comment]
I think domain decomposition is not supported by DeepXDE. You can try NVIDIA Modulus as they have a comprehensive library to handle such cases.

**Comment by lululxvi** [comment]
You can use `if`/`where` condition to specific the location in your PDE definition.

**Comment by bakhtiyar-k** [comment]
`tf.where(condition, pde_set_1, pde_set_2)`?

**Comment by lululxvi** [comment]
> `tf.where(condition, pde_set_1, pde_set_2)`?

Yes.
