### ISSUE TITLE
about the 1D Poission equation

### ISSUE THREAD

**Issue by yonghcui** [lululxvi/deepxde#171]
Hey, lulu, i have run the code"Poisson_Dirichlet_1d" and obtained the following figure, but i dont know the exact meaning of data in the figure. i know the train refer to the training data, but what's the true and prediction refer to? i read the source code of the saveplot, and i think the true data maybe fefer to the test data, but i dont know the meaining of prediction data, and i dont konw the figure if has a show about reference data(exact data). Thank you!
![Figure_2](https://user-images.githubusercontent.com/74175204/101135988-9a0c3000-3647-11eb-9805-66703665f997.png)
![3](https://user-images.githubusercontent.com/74175204/101136009-a0021100-3647-11eb-9014-d82ebac2e123.PNG)

**Comment by lululxvi** [comment]
"True" is the exact solution. "Prediction" is the network solution.
