### ISSUE TITLE
Ut_x

### ISSUE THREAD

**Issue by engsbk** [lululxvi/deepxde#172]
I understood how to do higher order derivatives with respect to t or x , but how to get Ut_x?

**Comment by lululxvi** [comment]
`dde.grad.hessian(y, x, i=0, j=1)`

**Comment by engsbk** [comment]
Thanks for your reply Lu!
So I can write it in this way:

`dy_xt =  dde.grad.hessian(y, x, i=0, j=1)`

correct?

**Comment by lululxvi** [comment]
Correct. You need to install TensorFlow >= 2.2.0

**Comment by engsbk** [comment]
What do the indices i and j stand for in the call of the function? I tried to read the definition of the function but I understood that they are indices of the Hessian matrix.
Can I consider i as a derivative with respect to x and j is a derivative with respect to y? For example:
```
dy_tt = dde.grad.hessian(y, x, i=1, j=1)
dy_xx = dde.grad.hessian(y, x, i=0, j=0)
```

**Comment by lululxvi** [comment]
Yes, it is Hessian matrix H: H[i][j] = d^2y/dx_idx_j. Your code is correct.
