### ISSUE TITLE
DeepM&Mnet for hypersonics

### ISSUE THREAD

**Issue by lkampoli** [lululxvi/deepxde#173]
Hello,
I recently read the amazing work in the DeepM&Mnet for hypersonics paper. It is written that there are three examples in deepxde where it has been implemented, nevertheless I cannot find them. May you help me, please?

Kind regards,
Lorenzo Campoli

**Comment by lululxvi** [comment]
I haven't uploaded the code yet.

**Comment by GeorgeVassilakis** [comment]
Dear @lululxvi,

I hope all is well. I am trying to implement a DeepM&MNet system for a set of 3 coupled differential equations (2PDEs and 1 ODE). I understand the concepts quite well, but I'm having trouble implementing our problem in code. I am working with Prof. Juner Zhu and Dr. Wei Li at Northeastern for solid-state battery modeling. 

My main question is: has this DeepM&MNet code been uploaded anywhere yet? It is present in the `read.ME`, but is not apparently present in any of the `deepxde` repository. Even some kind of notebook or general framework would be extremely helpful for our use case.  I appreciate your time and help!

Best,

George Vassilakis
