### ISSUE TITLE
Is there a demo/code/model available for Fourier-MIONet?

### ISSUE THREAD

**Issue by dezenn** [lululxvi/deepxde#1758]
I would like to train a neural operator for the case where I have multiple input functions, an input vector of scalar values and multiple output functions.  I tried to implement this using the DeepONet model but I can only use two input functions and I run into errors when I set num_output>1 because I do not know which data shape the model expects.

I came across the Fourier-MIONet paper and this seems to be well suited for my case so I wondered if there is any code available, i.e. a way to implement this fairly easy with this library. Thanks in advance.

Best regards
Dean

**Comment by lululxvi** [comment]
https://github.com/lu-group/fourier-mionet-gcs
