### ISSUE TITLE
Finding the gradient of outputs with respect to the inputs during prediction

### ISSUE THREAD

**Issue by Clement465** [lululxvi/deepxde#177]
Hi @lululxvi, 

Is there a way to find the gradient of outputs with respect to the inputs using automatic differentiation during prediction?

I've seen some solutions online suggesting I use tf.GradientTape() [https://stackoverflow.com/questions/59145221/how-to-compute-gradient-of-output-wrt-input-in-tensorflow-2-0] but all of them are using model() instead of model.predict() for prediction.

with tf.GradientTape() as tape:
    preds = model(inp)

However, when I try this with my code,

with tf.GradientTape() as tape:
    outputs = model(inputs)

I get the error "TypeError: 'Model' object is not callable"

Is there any way to get around this?

Thank you!

**Comment by lululxvi** [comment]
```python
def dydx(x, y):
    return dde.grad.jacobian(y, x, i=0, j=0)
dy_dx = model.predict(X, operator=dydx)
```
Here, `X` is the locations where you need the derivative.

**Comment by Clement465** [comment]
It works well now. Thank you!
