### ISSUE TITLE
inverse problem

### ISSUE THREAD

**Issue by Xilun1995** [lululxvi/deepxde#178]
Hello Lulu,
  I want to know that is there any possibility we can set variable as a function based on location and time as below 
![image](https://user-images.githubusercontent.com/75771241/101722507-5e72cb00-3a78-11eb-9acc-07c6d2392d73.png)

**Comment by Xilun1995** [comment]
I am trying to solve c(r)

**Comment by lululxvi** [comment]
Yes, you can. See "Q: Define an inverse problem to solve unknown parameters/fields in the PDEs or initial/boundary conditions." at FAQ.

**Comment by Xilun1995** [comment]
Thanks for your reply. But I still have a followup question. Since C(r) is a function in terms of r only, but the p is a function in terms of r and t. How can I define c (y[:, 1:2]) as a function only in terms of r in the code.

**Comment by lululxvi** [comment]
It is doable, but slightly tricky. You can use `apply_output_transform` to modify the network output, see "Q: By default, initial/boundary conditions are enforced in DeepXDE as soft constraints. How can I enforce them as hard constraints?" for how to use it. Specifically, in `apply_output_transform`, you manually construct a network whose input is only r, and then use this to replace the original network output as C. See "https://deepxde.readthedocs.io/en/latest/_modules/deepxde/maps/fnn.html#FNN" on how to construct a network.

**Comment by Xilun1995** [comment]
Hello lulu,
  I add the constrains to this problem as below and I attached my code. Since I did not get the correct results, could you please tell me if I am right ? ( I used Cartesian coordinate(x and y) instead of the cylindrical coordinate shown in equation). Thanks in advance. 

![image](https://user-images.githubusercontent.com/75771241/104789214-5b978400-5762-11eb-9a36-5b3e5d19cccd.png)
![image](https://user-images.githubusercontent.com/75771241/104789227-6225fb80-5762-11eb-955e-9576fcfb1eb9.png) ![image](https://user-images.githubusercontent.com/75771241/104789244-710cae00-5762-11eb-9efa-2080513a55ae.png)


geom = dde.geometry.Rectangle([-domain_size, -domain_size], [domain_size, domain_size])
timedomain = dde.geometry.TimeDomain(0, time_size)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)


def init_func(x, y):
    dy_x = tf.gradients(y, x)[0]
    dy_t = dy_x[:, 2:3]
    return dy_t


def boundary_initial(x, on_initial):
    return  on_initial


bc = dde.NeumannBC(geomtime,lambda x:  0, lambda _, on_boundary: on_boundary)
ic = dde.IC(
    geomtime,  lambda x: 0, lambda _, on_initial: on_initial
)
ic2 = dde.OperatorBC(geomtime, lambda x, y, _: init_func(x,y), boundary_initial)

**Comment by lululxvi** [comment]
The BC and IC look good.

**Comment by Xilun1995** [comment]
> It is doable, but slightly tricky. You can use `apply_output_transform` to modify the network output, see "Q: By default, initial/boundary conditions are enforced in DeepXDE as soft constraints. How can I enforce them as hard constraints?" for how to use it. Specifically, in `apply_output_transform`, you manually construct a network whose input is only r, and then use this to replace the original network output as C. See "https://deepxde.readthedocs.io/en/latest/_modules/deepxde/maps/fnn.html#FNN" on how to construct a network.

I am wondering if I can set C ( sound of speed ) as a matrix( containing 256*256 tf.variable s). Is there any way to do that ? I really appreciate that.

**Comment by Xilun1995** [comment]
> It is doable, but slightly tricky. You can use `apply_output_transform` to modify the network output, see "Q: By default, initial/boundary conditions are enforced in DeepXDE as soft constraints. How can I enforce them as hard constraints?" for how to use it. Specifically, in `apply_output_transform`, you manually construct a network whose input is only r, and then use this to replace the original network output as C. See "https://deepxde.readthedocs.io/en/latest/_modules/deepxde/maps/fnn.html#FNN" on how to construct a network.

Also, I already know how to add hard constraint to my problem. It is really smart trick. My hard constraint is c(x0,y0,t1) = c(x0,y0,t2). c is always the same, but I did not find a good solution for this constraint, could you please give me some hint?

**Comment by lululxvi** [comment]
- Not sure why you want to use C as a matrix, which is not easy to implement. Function is recommended.
- I mean you construct a new network in `apply_output_transform` as
```python
def apply_output_transform(inputs, outputs):
    p = outputs[:, 0:1]
    x = inputs[:, 0:1]
    C = FNN(x)
    return tf.concat([p, C], axis=1)
```
In `C = FNN(x)`, construct a network using `tf.layers.dense`.

**Comment by Xilun1995** [comment]
Thanks. I just follow your suggestion. But the result is really bad not even close. Is there any errors in my apply_output_transform. I attached my code. 
net.apply_output_transform(
    lambda x, y : tf.concat(
        [y[:, 0:1] ,
         tf.layers.dense(tf.layers.dense(tf.layers.dense(tf.layers.dense(tf.layers.dense(x[:,0:2], 10, tf.nn.tanh), 10, tf.nn.tanh), 30, tf.nn.tanh), 30, tf.nn.tanh), 1, tf.nn.tanh)
         ], axis = 1
        )   )

**Comment by lululxvi** [comment]
Should the last layer use activation?

**Comment by Xilun1995** [comment]
THANKS!!
One more question: I run the tests several times but Every time I got the different results and one of them is correct. Is there any way to improve that. Also, for the 2d wave equation with time, do you think my number of training points and size of NN is correct or not? 

 num_domain= 12000, num_boundary=1000, num_initial= 2000

[3] + [40] * 7 + [1]

**Comment by lululxvi** [comment]
- You may tune hyperparameters to have more stable results.
- The points may not be enough, but I am not sure. Use hard constraints for IC and BC, if you can.

**Comment by Xilun1995** [comment]
Hello Lulu,
  when I used 6000 training points, the networks works. However,  when I increase the number of training points to 60000, I get 
the following errors. Can you help me to debug?
![image](https://user-images.githubusercontent.com/75771241/111886232-fbf86780-89a2-11eb-9c60-dcdbf9e535dd.png)

**Comment by lululxvi** [comment]
It is out of memory.

**Comment by AlirezaPa** [comment]
Thank you @lululxvi for your library. It is very helpful for our research. I am writing a simple inverse code for 1D-wave equation. First, I modified my code, which I provide below, based on the discussion #114 . Currently, C in my code is a function of x and t, but as we know C is just function of x, and my issue is the same as @Xilun1995 here. I read all above discussions and API, but I still do not know how to write "apply_output_transform" and "tf.layers.dense". Would you please take a look to my code and give me some advises that how to modify my code based on C(x)? I appreciate for your time. 

##### Inverse Wave equation with Dirichlet Boundary Conditions ######
import deepxde as dde
import numpy as np

A = 1
Lright= 1
Lleft = -1
Ldomain = Lright - Lleft
Ttotal = 1

def pde(x, y):
    u, C = y[:, 0:1], y[:, 1:2]
    du_tt = dde.grad.hessian(u, x, i=1, j=1)
    du_x = dde.grad.jacobian(u, x, j=0)
    du_xx = dde.grad.jacobian((C ** 2)*du_x, x, j=0)    
    return du_tt - du_xx

def func(x):
    return np.sin(np.pi * A * x[:, 0:1]) * np.cos(np.pi * A * 1 * x[:, 1:])

def boundary_r(x, on_boundary):
    return on_boundary and np.isclose(x[0], Lright)

def boundary_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], Lleft)


geom = dde.geometry.Interval(Lleft, Lright)
timedomain = dde.geometry.TimeDomain(0, Ttotal)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)


bc_1 = dde.DirichletBC(geomtime, lambda x: 0, boundary_r, component=0)
bc_2 = dde.DirichletBC(geomtime, lambda x: 0, boundary_l, component=0)
ic_1 = dde.IC(geomtime, lambda x: np.sin(np.pi * A * x[:, 0:1]), lambda _, on_initial: on_initial, component=0)
ic_2 = dde.OperatorBC(geomtime, lambda x, u, _: dde.grad.jacobian(u, x, i=0, j=1), lambda x, _: np.isclose(x[1], 0))

observe_x = np.vstack((np.full((300), 0.75), np.linspace(-1, 1, num=300))).T
observe_u = dde.icbc.PointSetBC(observe_x, func(observe_x), component=0)

data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_1, bc_2, ic_1, ic_2, observe_u],
        num_domain=1000,
        num_boundary=300,
        num_initial=300,
        anchors=observe_x,
        num_test=10000,
        )

net = dde.nn.PFNN([2] + [50, 50] * 3 + [2], "tanh", "Glorot normal")
model = dde.Model(data, net)

model.compile("adam", lr=0.0001, loss_weights=[0.1, 10, 10, 10, 10, 10])
losshistory, train_state = model.train(epochs=10000)
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

**Comment by lululxvi** [comment]
>     * I mean you construct a new network in `apply_output_transform` as
> 
> 
> ```python
> def apply_output_transform(inputs, outputs):
>     p = outputs[:, 0:1]
>     x = inputs[:, 0:1]
>     C = FNN(x)
>     return tf.concat([p, C], axis=1)
> ```
> 
> In `C = FNN(x)`, construct a network using `tf.layers.dense`.

This is the answer. You can also find examples at FAQ "Q: A standard network doesn’t work for me, and I want to implement a network with a special structure/property."

**Comment by hannanmustajab** [comment]
@AlirezaPa Hey, I am also solving the same problem. How did you manage to implement this in the end ? Can you please share your code snippet for that ? Also, did you use tf backend only ? 

I also have spatially varying velocity model.
