### ISSUE TITLE
`deepxde.geometry.geometry_nd.Hypercube.boundary_normal` behavior for points on the corner

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#181]
Hi Lu,

I found `deepxde.geometry.geometry_nd.Hypercube.boundary_normal` may cause unexpected behavior when computing points on the corner, because in such case it is tricky to determine which BC the points are belong to, see test below

```python
import deepxde as dde
import numpy as np

x = np.random.rand(10, 2)
x = np.vstack([x, x + 1])
x[:2, 0] = 0
x[3:5, 0] = 1
x[6:7, 1] = 1
x[8:10, :] = 0

geom = dde.geometry.Hypercube((0, 0), (1, 1))

print(x)

f = geom.boundary_normal
y = np.array([f(_x) for _x in x])
print(f.__name__)
print(y)
```
which gives
```
[[0.         0.8392068 ]
 [0.         0.1550776 ]
 [0.42785962 0.03713413]
 [1.         0.01687495]
 [1.         0.05793537]
 [0.09182855 0.3079    ]
 [0.40073334 1.        ]
 [0.22510905 0.8932111 ]
 [0.         0.        ]
 [0.         0.        ]
 [1.05708783 1.8392068 ]
 [1.16254464 1.1550776 ]
 [1.42785962 1.03713413]
 [1.20258336 1.01687495]
 [1.3642525  1.05793537]
 [1.09182855 1.3079    ]
 [1.40073334 1.01355714]
 [1.22510905 1.8932111 ]
 [1.52774904 1.55642904]
 [1.28386605 1.07148174]]
boundary_normal
[[-1.  0.]
 [-1.  0.]
 [ 0.  0.]
 [ 1.  0.]
 [ 1.  0.]
 [ 0.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [-1.  0.]
 [-1.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
```
Your can see that when input is `[0.         0.        ]`, the output is `[-1.  0.]`, the problem here is that `[0.         0.        ]` also belonging to the BC defined by `x[1] == 0`, and the norm on that BC is actually `[0.  -1]`, what do you think?

**Comment by lululxvi** [comment]
Yes, you are right. `Triangle` has the same issue.

One solution is to ask the user not to include the corner points when defining `on_boundary()`, but this doesn't seem to be a good solution.

**Comment by smao-astro** [comment]
Yes, maybe another solution is that `boundary_normal` use the information `deepxde.boundary_conditions.BC.on_boundary` to figure out which boundary users are caring about, what do you think?

**Comment by lululxvi** [comment]
Not sure yet how to do this. For example, consider a rectangle, and we have Neumann BC on all 4 sides. Then `on_boundary` is true for all boundary points.

**Comment by smao-astro** [comment]
> on_boundary is true for all boundary points.
`deepxde.geometry.geometry_2d.Rectangle.on_boundary` is True for all boundary points. But usually user will define different boundary condition for different boundary, and thus `deepxde.boundary_conditions.BC.on_boundary` does not necessarily True on all boundaries. What I suggested above is that we use that information to determine which boundary the users are caring about and then calculate the norm related to that boundary. For example, in https://github.com/lululxvi/deepxde/blob/a894a8c73fbce5d378a9b9b8b78a84008ea6714c/deepxde/boundary_conditions.py#L33-L36
maybe we can do something like `self.geom.boundary_normal(xi, self.on_boundary)` and use `self.on_boundary` (user defined) to figure out the norm.

I also do not know how to implement it, this is just a general idea.

**Comment by smao-astro** [comment]
> One solution is to ask the user not to include the corner points when defining on_boundary(),

How about remove `x_corner` in `deepxde.geometry.geometry_2d.Rectangle.random_boundary_points`?

**Comment by lululxvi** [comment]
`Rectangle.uniform_boundary_points` and `Rectangle.uniform_points` also contain the corners. This issue is tricky...

**Comment by lululxvi** [comment]
This issue has been fixed. DeepXDE will not generate boundary points at the corners.
