### ISSUE TITLE
2D wave equation

### ISSUE THREAD

**Issue by engsbk** [lululxvi/deepxde#184]
Hello Lu,

I'm trying to implement the 2D wave equation through time (x,y,t) in DeepXDE, but I came across these doubts:
- Do I need to define separate ICs and BCs for each dimension of x, y, and t?
- I defined a rectangle "geom" with the low left corner and right top corner using the min and max x and y values as such: for x range [-1,1], y range[0,2] then the rectangle domain has these parameters [-1,0] and [1,2]. Is this correct?
- I need to get slices at t=0.25, 0.5, 0.75 s of the output plot to make sure that the result of the exact and predicted solution align. So I tried slicing like in PINN but I have problem in this line: 
` Y_pred = griddata(X_star, y_pred.flatten(), (xx, tt), method='cubic')`
This line was in the 1D burger example, and it was used for interpolating the predicted solution I suppose, however, I'm not sure how to transform this line to process x,y,t instead of only x,t.

These are the graphs I got:
<img width="502" alt="Screen Shot 2020-12-23 at 6 48 10 PM" src="https://user-images.githubusercontent.com/25299510/103044677-6be78500-454f-11eb-9214-d7d69088d31c.png">

<img width="1169" alt="Screen Shot 2020-12-23 at 6 47 16 PM" src="https://user-images.githubusercontent.com/25299510/103044632-4c505c80-454f-11eb-8bf9-fa8cb701e1e2.png">

Please advise.
Many thanks in advance.

**Comment by lululxvi** [comment]
The geometry, IC and BC look good. Check https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html for the interpolation.

I notice that the training points are too few.

**Comment by engsbk** [comment]
How do I know what is the appropriate number of training points?

**Comment by engsbk** [comment]
I managed to fix my code by making the following changes:

DeepXDE part:
```

def pde(x, u):
    c0 = 1
    
    #Using old DeepXDE gradients
    #du_x = tf.gradients(u, x)[0]
    #du_x = du_x[:, 0:1]
    #du_y = du_x[:, 1:2]
    #du_t = du_x[:, 2:3]
    #du_xx = tf.gradients(du_x, x)[0][:, 0:1] 
    #du_yy = tf.gradients(du_y, x)[0][:, 1:2]
    #du_tt = tf.gradients(du_t, x)[0][:, 2:3]
    #return  du_tt - (c0 ** 2) * (du_xx + du_yy)
    
    #Using new DeepXDE Jacobians and Hessians
    du_xx = dde.grad.hessian(u, x, i=0, j=0)
    du_yy = dde.grad.hessian(u, x, i=1, j=1) 
    du_tt = dde.grad.hessian(u, x, i=2, j=2)
    return   du_tt - (c0 ** 2) * (du_xx + du_yy)

def func(x):
    p = 2
    q = 1
    return (np.sin (p * np.pi * x[:,0:1])) * (np.sin(q * np.pi * x[:,1:2]))

geom = dde.geometry.Rectangle([-1,-1],[1,1])
timedomain = dde.geometry.TimeDomain(0, 0.99)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

bc = dde.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: on_boundary)
#bc = dde.DirichletBC(geomtime, func, lambda _, on_boundary: on_boundary)
ic = dde.IC(
     geomtime, func, lambda _, on_initial: on_initial
)

data = dde.data.TimePDE(
    geomtime, pde, [bc, ic], 
    num_domain=2540, 
    num_boundary=80, 
    num_initial=160
)

net = dde.maps.FNN([3] + [20] * 3 + [1], "tanh", "Glorot normal")
model = dde.Model(data, net)

model.compile("adam", lr=1e-3)
model.train(epochs=15000)
model.compile("L-BFGS-B")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

X, u_true = gen_testdata()
u_pred = model.predict(X)
f = model.predict(X, operator=pde)
print("Mean residual:", np.mean(np.absolute(f)))
print("L2 relative error:", dde.metrics.l2_relative_error(u_true, u_pred))
np.savetxt("test.dat", np.hstack((X, u_true, u_pred)))
```

Then plotting in this way:

```
########imports for plotting #############################
import matplotlib.pyplot as plt
from scipy.interpolate import griddata
#############################################
data = np.load("dataset/2DwaveSOL.npz")
t, x, y, exact = data["t_input"], data["x_input"], data["y_input"], data["u_output"]
xx, yy, tt = np.meshgrid(x,y,t)
X_star = np.hstack((xx.flatten()[:,None], yy.flatten()[:,None]))
Y_star = np.hstack((yy.flatten()[:,None], tt.flatten()[:,None]))
U_predx = griddata(X_star, u_pred.flatten(), (xx, yy), method='cubic')
U_predy = griddata(Y_star, u_pred.flatten(), (xx, yy), method='cubic')
#############################################


fig = plt.figure(figsize=plt.figaspect(0.2))

#################################
#Space slices for x
#################################
ax = fig.add_subplot(2, 4, 1)
ax.plot(x,exact[25,25,:], 'b-', linewidth = 2, label = 'Exact')
ax.plot(x,U_predx[25,:,25], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$x$')
ax.set_ylabel('$u(t,x,y)$')
ax.set_title('$t = 0.25$', fontsize = 10)
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])

ax = fig.add_subplot(2, 4, 2)
ax.plot(x,exact[50,50,:], 'b-', linewidth = 2, label = 'Exact')
ax.plot(x,U_predx[50,:,50], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$x$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])
ax.set_title('$t = 0.50$', fontsize = 10)

ax = fig.add_subplot(2, 4, 3)
ax.plot(x,exact[75,75,:], 'b-', linewidth = 2, label = 'Exact')
ax.plot(x,U_predx[75,:,75], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$x$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])
ax.set_title('$t = 0.75$', fontsize = 10)

ax = fig.add_subplot(2, 4, 4)
ax.plot(x,exact[99,99,:], 'b-', linewidth = 2, label = 'Exact')
ax.plot(x,U_predx[99,:,99], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$x$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])
ax.set_title('$t = 1$', fontsize = 10)



#######################################
#Space slices for y
#######################################
ax = fig.add_subplot(2, 4, 5)
ax.plot(y,exact[25,:,25], 'b-', linewidth = 2, label = 'Exact')
ax.plot(y,U_predx[:,25,25], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$y$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])

ax = fig.add_subplot(2, 4, 6)
ax.plot(y,exact[50,:,50], 'b-', linewidth = 2, label = 'Exact')
ax.plot(y,U_predx[:,50,50], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$y$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])
ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.35), ncol=5, frameon=False)

ax = fig.add_subplot(2, 4, 7)
ax.plot(y,exact[75,:,75], 'b-', linewidth = 2, label = 'Exact')
ax.plot(y,U_predx[:,75,75], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$y$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])

ax = fig.add_subplot(2, 4, 8)
ax.plot(y,exact[99,:,99], 'b-', linewidth = 2, label = 'Exact')
ax.plot(y,U_predx[:,99,99], 'r--', linewidth = 2, label = 'Prediction')
ax.set_xlabel('$y$')
ax.set_ylabel('$u(t,x,y)$')
#ax.axis('square')
ax.set_xlim([-1.1,1.1])
ax.set_ylim([-2.2,2.2])

print("exact",exact.shape)
print("U_predx",U_predx.shape)
print("U_predy",U_predy.shape)

plt.show()
```
3D plots in this way:


```
data = np.load("dataset/2DwaveSOL.npz")
t, x, y, exact = data["t_input"], data["x_input"], data["y_input"], data["u_output"]
#xx, yy, tt = np.meshgrid(y,x,t)
xm, ym = np.meshgrid(x,y)
#X_star = np.hstack((xx.flatten()[:,None], yy.flatten()[:,None], tt.flatten()[:,None]))
X_star = np.hstack((xx.flatten()[:,None], yy.flatten()[:,None]))
print("X_star", X_star.shape)
U_predx = griddata(X_star, u_pred.flatten(), (xx, yy), method='cubic')
#xx, yy, tt = np.meshgrid(x, y, t, indexing='ij')



print("ym",ym.shape)
print("xm",xm.shape)
print("exact",exact.shape)
print("U_predx",U_predx.shape)


fig = plt.figure(figsize=plt.figaspect(0.2) )

ax = fig.add_subplot(1, 4, 1, projection='3d')
ax.plot_surface(xm,ym,exact[25,:,:], cmap=mpl.cm.copper, label = 'Exact')
ax.plot_wireframe(xm,ym,U_predx[:,:,25], rstride=15, cstride=15 ,label = 'Prediction')
ax.view_init(45, 25)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('u(t,x,y)');
ax.set_xlim(-1.01, 1.01)
ax.set_ylim(-1.01, 1.01)
ax.set_zlim(-2.01, 2.01)

ax = fig.add_subplot(1, 4, 2, projection='3d')
ax.plot_surface(xm,ym,exact[50,:,:], cmap=mpl.cm.copper, label = 'Exact')
ax.plot_wireframe(xm,ym,U_predx[:,:,50], rstride=15, cstride=15 ,label = 'Prediction')
ax.view_init(45, 25)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('u(t,x,y)');
ax.set_xlim(-1.01, 1.01)
ax.set_ylim(-1.01, 1.01)
ax.set_zlim(-2.01, 2.01)

ax = fig.add_subplot(1, 4, 3, projection='3d')
ax.plot_surface(xm,ym,exact[75,:,:], cmap=mpl.cm.copper, label = 'Exact')
ax.plot_wireframe(xm,ym,U_predx[:,:,75], rstride=15, cstride=15 ,label = 'Prediction')
ax.view_init(45, 25)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('u(t,x,y)');
ax.set_xlim(-1.01, 1.01)
ax.set_ylim(-1.01, 1.01)
ax.set_zlim(-2.01, 2.01)


ax = fig.add_subplot(1, 4, 4, projection='3d')
ax.plot_surface(xm,ym,exact[99,:,:], cmap=mpl.cm.copper, label = 'Exact')
ax.plot_wireframe(xm,ym,U_predx[:,:,99], rstride=15, cstride=15 ,label = 'Prediction')
ax.view_init(45, 25)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('u(t,x,y)');
ax.set_xlim(-1.01, 1.01)
ax.set_ylim(-1.01, 1.01)
ax.set_zlim(-2.01, 2.01)

plt.show()

```


I got better results, but as you can see they are a bit noisy...

<img width="1043" alt="Screen Shot 2020-12-24 at 1 43 43 AM" src="https://user-images.githubusercontent.com/25299510/103071012-cc4ae680-4590-11eb-8ac2-f46ccd1f4c23.png">
<img width="1060" alt="Screen Shot 2020-12-24 at 1 45 34 AM" src="https://user-images.githubusercontent.com/25299510/103071031-d53bb800-4590-11eb-832d-b49a47972325.png">

**Comment by lululxvi** [comment]
This is the same question as what mesh size I should use in finite difference. Just assume the error convergence is first order or second order.

**Comment by lululxvi** [comment]
By using more points, the accuracy would be better. Welcome to add this code into the DeepXDE examples, if you are interested, after the accuracy is improved.

**Comment by engsbk** [comment]
> This is the same question as what mesh size I should use in finite difference. Just assume the error convergence is first order or second order.

So, to increase the training points, I should increase `num_domain`?

**Comment by engsbk** [comment]
Also, I have a question about these prediction lines:
```
u_pred = model.predict(X)
f = model.predict(X, operator=pde)
```

They both produce a prediction time as such:
```
Predicting...
'predict' took 0.313968 s

Predicting...
'predict' took 3.943197 s
```

Which one is the prediction time of the model?

**Comment by engsbk** [comment]
> By using more points, the accuracy would be better. Welcome to add this code into the DeepXDE examples, if you are interested, after the accuracy is improved.

I'd be more than happy to add it to DeepXDE examples after tweaking the accuracy and the code to its final shape.

**Comment by lululxvi** [comment]
- You need to increase `num_domain`, `num_boundary`, and `num_initial`
- The network is easier to train for some value of c and hard to train for some value of c. When c is large, I guess it is harder to train. Of course, it is still possible to train, but it may need extra tuning. See FAQ "Q: failed to train".
- The prediction time is 0.3s.

**Comment by engsbk** [comment]
Thank you for your reply!
How can I write an initial condition that corresponds to these initial conditions on MATLAB:

```
f = 10
v = 500;        % Wave velocity
c = v*(dt/dx);  % CFL condition
U = zeros(T,Nx);  % U(x,t) = U(space,time)
s1 = floor(T/f);  
%-------------------------------------------------------------------------%
% Initial condition
U((1:s1),1) = sin(2*pi*f.*t(1:s1))
U((1:s1),2) = sin(2*pi*f.*t(1:s1))
%-------------------------------------------------------------------------%

```
?
what I'm basically trying to do is to compose the initial condition using time values.

**Comment by engsbk** [comment]
> * The prediction time is 0.3s.

So, what does the other prediction time depict?

**Comment by lululxvi** [comment]
- Check the time-dependent PDE examples 
- This is the time for predicting the PDE residual

**Comment by engsbk** [comment]
> * This is the time for predicting the PDE residual
There are also 2 training times that show in the output when I run the code, the first one normally printed after step: 15000 of training, and the other training time prints after all steps. what is the difference between them?

Also, I sometimes get a message during training:
```
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 0.008661
  Number of iterations: 5610
  Number of functions evaluations: 6053
```

Does it mean my training has gone wrong since the optimizer has terminated?

**Comment by lululxvi** [comment]
- The first time is the time of the training for 15000 steps, and the second time is the training time for the steps from 15000 to end.
- The message is from the second training of L-BFGS. Nothing is wrong.

**Comment by mariusmerkle** [comment]
@engsbk Could you please share your parameter settings or your code? I simulate the heat equation in 2D, so T(x, y, t), and face problems with the accuracy, see thread #188.

**Comment by engsbk** [comment]
> @engsbk Could you please share your parameter settings or your code? I simulate the heat equation in 2D, so T(x, y, t), and face problems with the accuracy, see the last comment in thread #188.

I'm still changing the code and modifying it. I will add it to the examples of DeepXDE once I get it done accurately. Is there a specific parameter setting I can help you with? where do you feel that you are stuck?

**Comment by mariusmerkle** [comment]
The problem is that I don't find any hyperparameter configuration that brings the loss down. I tried many of them, see my thread and didn't have success. That's why I would be interested in your code.

**Comment by aminetazarine** [comment]
@engsbk  can you please  show me your python code how to get slices at t=0.25, 0.5, 0.75 s .

**Comment by engsbk** [comment]
@aminetazarine sure.
I use this code now. It seems clearer to me this way. Hope it helps.

```

################################################################
########################PLOT RESULTS############################
################################################################

x1 = x
t1 = t
xx1, tt1 = np.meshgrid(x1, t1)
X1 = np.vstack((np.ravel(xx1), np.ravel(tt1))).T
u_pred1SC = modelSC.predict(X1)

X_star1 = np.hstack((xx1.flatten()[:,None], tt1.flatten()[:,None]))
U_pred1SC = griddata(X_star1, u_pred1SC.flatten(), (xx1, tt1), method='cubic')

snaps_num = 5      # without first and last

snaps = [0]        #first slice

for k in range(1,snaps_num):
    snaps += [int(k*(len(t1)/snaps_num))]

snaps += [int(len(t1)-1)] #last slice

print("snapshots at:", snaps)

for snap in snaps:
    exa = plt.plot(x1,exact[snap-1,:],'r-', label = 'FDTD')
    pred = plt.plot(x1,U_pred1SC[snap,:],'b--', label = 'PINN')
    plt.title('$t = %1.3f s$ '%(t[snap]), fontsize = 15)
    plt.legend(prop={'size':12})
    plt.show()
    
```

**Comment by hannanmustajab** [comment]
@engsbk Can you please share the code for this ? Also, in your experiments, did you use a constant velocity model or a variable velocity model ?

**Comment by engsbk** [comment]
@hannanmustajab Our lab is working on creating a repository that will be published soon. I used a constant velocity. Let me know if you have any other questions, or if I can help with your problem.

**Comment by hannanmustajab** [comment]
> @hannanmustajab Our lab is working on creating a repository that will be published soon. I used a constant velocity. Let me know if you have any other questions, or if I can help with your problem.

Hey @engsbk , thank you for the quick response. I have a few questions. It would be really helpful if you could help me with those, and provide some code snippets. 

- Did you use an initial condition, or a source term? For example a ricker wavelet source. 
- Did you use absorbing boundary conditions or reflective ? 
- If you used absorbing, then how exactly did you setup those conditions in deepXDE. If I understand correctly, they will look like` ut - c*ux = 0 at x=0 `and so on. 

Looking forward for your response. 
Best,
Hannan

**Comment by engsbk** [comment]
> * Did you use an initial condition, or a source term? For example a ricker wavelet source.
I used a source term. The initial condition applies on the instance of time when t = 0 only. So, if you're looking to create a pulse at t=0, you can indeed use the initial condition. However, if you're looking to have a source active through the other time instances, you can:
* Use it as a boundary condition
* Create a source term within the main PDE.

> * Did you use absorbing boundary conditions or reflective ?
I used an absorbing boundary condition. I used a dirichelet boundary condition and set it to zero.

> * If you used absorbing, then how exactly did you setup those conditions in deepXDE. If I understand correctly, they will look like`ut - c*ux = 0 at x=0`and so on.
The boundary function I used looks like this for the 2D case:
```
def boundary_x_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], -domain)
def boundary_x_r(x, on_boundary):
    return on_boundary and np.isclose(x[0], domain)
def boundary_y_b(x, on_boundary):
    return on_boundary and np.isclose(x[1], -domain)
def boundary_y_u(x, on_boundary):
    return on_boundary and np.isclose(x[1], domain)
```
Defining the left, right, upper, and lower boundaries.

Hope this helps!
Shaikhah

**Comment by hannanmustajab** [comment]
@engsbk Hey, thanks for your detailed explanation. Part about the B.C became clear now. 
Do you have any example or reference that I could use for the source term ? I was thinking of using a Ricker wavelet source. Another confusion was, how do you place the source at the centre of the domain? Let us say at (x/2,y/2). 
Sorry if the questions are very obvious, I am new to deepXDE, so I am having trouble understanding the geometry API. From what I have seen so far, it's very powerful but a bit complex. 

Lastly, is it possible to plot this geometry and points at boundary ? 

I saw you had the same questions as me, when I was going through other threads here. So I'll just ask them here :) 

Thanks for your help. 
Regards
Hannan
