### ISSUE TITLE
Clarification on how to specigy loss weights

### ISSUE THREAD

**Issue by isaingit** [lululxvi/deepxde#1868]
Dear developers,

I am trying to solve an inverse problem using DeepXDE and I have doubts about how to specify the loss_weights argument in the compile method. It is not clear to me in which order should I provide the list so that the proper weight multiplies the right loss term.

Could anyone help on that, please?

**Comment by tsarikahin** [comment]
It is in the order of pde and BCs. If your pde has 2 components and you have 5 BCs, then you have to define 7 weights in the same order of your pde output and the same order of how you give your bcs into dde.data.PDE object

**Comment by isaingit** [comment]
Thanks Tarik for such a clear answer!
