### ISSUE TITLE
How to use the uniform sampling strategy in DeepXDE?

### ISSUE THREAD

**Issue by EigenvectorOfFate** [lululxvi/deepxde#1882]
Hello everyone, 

I wonder how to use the uniform sampling strategy in DeepXDE?
I attempted to use the following code to get the uniform points to train the model. However, with the _uniform_points_ function will return a numpy array other than <deepxde.geometry.timedomain.GeometryXTime>.

```
num_domain = 10080
geom = dde.geometry.Interval(0, 2*math.pi)
timedomain = dde.geometry.TimeDomain(0, 4)
geomtime = dde.geometry.GeometryXTime(geom, timedomain).uniform_points(num_domain)
```

**Comment by EigenvectorOfFate** [comment]
`data = dde.data.TimePDE(geomtime, pde, [bc, ic], num_domain=num_domain, num_boundary=1000, num_initial=1000)`

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

**Comment by vl-dud** [comment]
Use `train_distribution`:
```
num_domain = 10080
geom = dde.geometry.Interval(0, 2*math.pi)
timedomain = dde.geometry.TimeDomain(0, 4)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)
data = dde.data.TimePDE(
	geomtime, 
	pde, 
	[bc, ic], 
	train_distribution="uniform", 
	num_domain=num_domain, 
	num_boundary=1000, 
	num_initial=1000
)
```

**Comment by EigenvectorOfFate** [comment]
I see. Thank you so much!
