### ISSUE TITLE
adding function-based parameter in pde

### ISSUE THREAD

**Issue by Xilun1995** [lululxvi/deepxde#191]
![image](https://user-images.githubusercontent.com/75771241/103310970-01b76000-49e7-11eb-93e3-7a21a309f60b.png)
Hello Lulu,
  Thanks for your help in advance. I am trying to solve this forward problem but the c(r) is a function instead of a constant. Is there any easy way to add this or any function to implement this ?

**Comment by lululxvi** [comment]
If c(r) has the analytical expression, you can use tensorflow functions to express it.

**Comment by Xilun1995** [comment]
Thanks for your reply. How about if it is piece wise function as  C= 1.47 when x<0  1.57 when c>1.47 
![image](https://user-images.githubusercontent.com/75771241/103353840-e21c4800-4a77-11eb-8266-a53ca28062aa.png)

But there are errors and I am not sure why.
![image](https://user-images.githubusercontent.com/75771241/103353938-2871a700-4a78-11eb-88ed-30e36b7738ac.png)

**Comment by lululxvi** [comment]
See https://github.com/lululxvi/deepxde/issues/185

**Comment by lululxvi** [comment]
Not sure what the issue is. Is the network trained well?

**Comment by Xilun1995** [comment]
> Not sure what the issue is. Is the network trained well?

The network is trained well. 

I just increase the training data and the image is much better now. I found out when it comes to the inhomogeneity, the training points must be large enough to cover all the resolution in the model to show the details. And the number  training points should be as large as the number used in FDM( let is say 100*100*100 for x,y,t). But in this situation, the PINN don't have any advantange in "curse of dimensionality".

**Comment by lululxvi** [comment]
You can use mini-batch, which is being implemented now https://github.com/lululxvi/deepxde/pull/225

**Comment by lshil00** [comment]
Hi, have you solved this problem?
