### ISSUE TITLE
I am trying to impose the dirichlet boundary conditions for a 2-dimensional PDE as hard constraints but i am getting an error.

### ISSUE THREAD

**Issue by panghalshagun** [lululxvi/deepxde#192]
Here is my code:

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    
    def gen_testdata():
        P=20
        a1=P/2+np.sqrt(P**2/4+np.pi**2)
        a2=P/2-np.sqrt(P**2/4+np.pi**2)
        x=np.linspace(0,1,50)
        y=np.linspace(0,1,50)
        xx, yy = np.meshgrid(x, y)
        y=np.sin(yy*np.pi)*(np.exp(a1+a2*xx)-np.exp(a2+a1*xx))/(np.exp(a1)-np.exp(a2))
        X = np.vstack((np.ravel(xx), np.ravel(yy))).T
        return X,y
    
    
    def pde(x, y):
        P=20
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_y = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        dy_yy=tf.gradients(dy_y, x)[0][:, 1:]
        return dy_xx+dy_yy-P*dy_x

    def func(x):
        P=20
        a1=P/2+np.sqrt(P**2/4+np.pi**2)
        a2=P/2-np.sqrt(P**2/4+np.pi**2)
        return np.sin(x[:,1:]*np.pi)*(np.exp(a1+a2*x[:,0:1])-np.exp(a2+a1*x[:,0:1]))/(np.exp(a1)-np.exp(a2))
    geom = dde.geometry.Rectangle([0, 0],[1,1])
    
    def boundary(_, on_boundary):
        return on_boundary
    bc = dde.DirichletBC(geom, func, lambda _, on_boundary: on_boundary)

    net = dde.maps.FNN([2] + [30]+ [1], "tanh", "Glorot normal")
    net.apply_output_transform(
        lambda x, y : 
            x[:,1:2]*(1-x[:,1:2])*(1-x[:,0:1])*np.sin(np.pi*x[:,0:1])*y
        )
    data = dde.data.PDE(geom, pde,bc, num_domain=500,num_boundary=0, num_test=50)
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3)
    model.train(epochs=15000)
    model.compile("L-BFGS-B")
    model.train()
    X, y_true = gen_testdata()
    y_true.shape=(2500,1)
    y_pred = model.predict(X)
    f = model.predict(X, operator=pde)
    print("L2 relative error:", dde.metrics.l2_relative_error(y_true, y_pred))
    print("Mean abs percent error:", dde.metrics.mean_absolute_percentage_error(y_true, y_pred))
    print("Max absolute percentage error:", dde.metrics.max_absolute_percentage_error(y_true, y_pred))
    np.savetxt("h3n200.txt", np.hstack((X,y_true,y_pred,y_true-y_pred)))

if __name__ == "__main__":
    main()
`

**Comment by panghalshagun** [comment]
I am getting the following error:

TypeError: loop of ufunc does not support argument 0 of type Tensor which has no callable sin method

**Comment by lululxvi** [comment]
Use `tf.sin` in `net.apply_output_transform`
