### ISSUE TITLE
Having inputs to the model that are not location coordinates

### ISSUE THREAD

**Issue by Clement465** [lululxvi/deepxde#193]
Hi @lululxvi ,

For a 2D problem, is it possible to add inputs to the model that are not x or y coordinates?

For example, for potential flow over a rotating cylinder with varying circulation, the inputs would be x, y and Gamma (circulation) and the output would be phi. Is it possible to use a 2D domain with the user specifying the values of Gamma to be used for training?

Thank you.

**Comment by lululxvi** [comment]
You can, but Gamma is just a parameter in the PDE, is it right?

**Comment by Clement465** [comment]
No, in this case the PDE is just Laplace's equation. However, Gamma affects the Neumann boundary conditions. 

May I ask how I can have 3 inputs without having a 3d domain? 

Thank you.

**Comment by lululxvi** [comment]
Do you want to get a parametric solution u(x,y,gamma) on gamma? If so, you can just assume gamma is the 3rd dimension. (In PINN, we do not care whether the input is in physical space or the parametric space. The network is just a surrogate of the solution).

Back to your question, just use `net = dde.maps.FNN([3] + ... + [1], ...)`, then the network has 3 input neurons.

**Comment by Clement465** [comment]
The problem I'm facing in this case is that there is no cylinder geometry for 3D in DeepXDE. 

Is it possible to use net = dde.maps.FNN([3] + ... + [1], ...) but with 2D geometry?

**Comment by lululxvi** [comment]
No, you cannot. Because 2D geometry only samples points in 2D. You might implement a 3D cylinder, which is not hard to do. Otherwise, just use any geometry, and when you define the PDE, set `num_domain=0`, ` num_boundary=0` etc, so that we won't use the geometry at all. You sample all the points by yourself, and pass them using the `anchors=...`.

**Comment by Clement465** [comment]
Okay, thank you!
