### ISSUE TITLE
one-dimensional schrodinger equation

### ISSUE THREAD

**Issue by huazhixixi** [lululxvi/deepxde#194]
Hi, i am trying to solve the nonlinear schrodinger equation, as below. 
![image](https://user-images.githubusercontent.com/59355161/103441008-b078cc00-4c85-11eb-8371-a103b49f2bd9.png)

My goal is to obtain the complex envelope **a(z,t)**  (from **0 ~ T**) for any z (0 ~ L). The BC condition at z=0 and z=L is:

![image](https://user-images.githubusercontent.com/59355161/103441269-b40d5280-4c87-11eb-8171-d18e947ce565.png)

There is no initial condition.  As you can see, this is a complex PDE, therefore I have to decompose it into two PDE's, one represent its real part and another is the image part. And I am confusing about how to accomplish it in deepXDE. The doc does not give such an example. Besides, is it ok without IC. My previous numerical method is the split step fourier method. For this method, only the BC of z=0 is enough to get a(z,t) for any z in (0 ~ L). Thanks very much.

**Comment by lululxvi** [comment]
- It is OK without IC in DeepXDE, but is the problem well-defined without IC?
- You need to derive the real and imaginary parts of PDE manually. You also need two outputs, one for Re[a] and one for Im[a].

**Comment by AiceQueen** [comment]
Hello, I'm intersted in this issue. Have you got it? 
I have one problem. Could you please tell me a(0, t) is regarded as IC or BC? Simply, u(t) can be assumed as the Gaussian envelope, but it is at z=0. I guess TimePDE in DeepXDE sets t=0 and many examples are the same situation. So, it can be IC or BC?
Looking forward to your reply.
