### ISSUE TITLE
System of partial IDEs in deepxde

### ISSUE THREAD

**Issue by Sakshi21299** [lululxvi/deepxde#198]
I am trying to solve a system of partial integro-differential equations in deepxde. I tried changing the train_next_batch() function in the ide code but I am getting some shape errors. 

My PDE has two x components and one y component.  So my network has 2 input nodes and one output node. Can you please help me with this error? Is there an example available for solving partial integro-differential equations? 

]: runfile('C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde/Cry_breakage.py', wdir='C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde')
Using TensorFlow 2 backend.

WARNING:tensorflow:From C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
(20,)
Warning: 10 points required, but 12 points sampled.
(14, 2)
(280, 2)
Compiling model...
Building feed-forward neural network...
WARNING:tensorflow:From C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\deepxde\maps\fnn.py:82: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer_v1) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
'build' took 0.139297 s

'compile' took 0.764581 s

Initializing variables...
Training model...

Traceback (most recent call last):

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1365, in _do_call
    return fn(*args)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)

InvalidArgumentError: Incompatible shapes: [15,1] vs. [295,1]
	 [[{{node cond/sub_5}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-fc6da57e541d>", line 1, in <module>
    runfile('C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde/Cry_breakage.py', wdir='C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde')

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde/Cry_breakage.py", line 112, in <module>
    main()

  File "C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde/Cry_breakage.py", line 103, in main
    losshistory, train_state = model.train(epochs=50000)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\deepxde\model.py", line 151, in train
    self._test(uncertainty)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\deepxde\model.py", line 262, in _test
    False, False, 0, self.train_state.X_train, self.train_state.y_train

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 958, in run
    run_metadata_ptr)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _do_run
    run_metadata)

  File "C:\Users\SAKSHI\.conda\envs\env2\lib\site-packages\tensorflow\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: Incompatible shapes: [15,1] vs. [295,1]
	 [[node cond/sub_5 (defined at C:/Users/SAKSHI/Desktop/Kishalay/deepxde-master/Test_deepxde/Cry_breakage.py:44) ]]

**Comment by lululxvi** [comment]
Unfortunately, I don't have any partial IDEs example, and the code has to be modified. It is hard to tell from the error message. Could you explain how do you modify the code exactly?

**Comment by Sakshi21299** [comment]
Thankyou for replying!

Because my PDE has a 2-D input, on running the ide code I was getting an error in the self.train_x = np.vstack((x_bc, self.train_x_all, x_quad)). This was due to dimension mismatch between the quadrature locations which was 1-D  and the x_bc and self.train_x_all which were 2-D. 
In order to get rid of that error, I concatenated x_quad with itself as follows: x_quad_all = np.concatenate((x_quad,x_quad), axis = 1) So now the dimensions matched. I also did the same in the test function. 

Then in the get_it_matrix function, I changed the size of int_mat from: int_mat = np.zeros((num_bc + num_f, X.size), dtype=config.real(np)) to int_mat = np.zeros((num_bc + num_f, X.shape[0]), dtype=config.real(np))
This is because my X.size would be a sum of the zeroth component and the first component of X while we want int_mat to take into account only the size of the zeroth component of X. 

I have done these changes to solve a PDE with two inputs and one output and which has an integral term in it. 
I have checked the shapes of my int_mat and the resulting matrix from tf.matmul(int_mat,y). The shapes look similar to the VolteraIDE example. 

Can you also please explain what exactly is the network learning in the integral part? Is it learning int_mat?

**Comment by Sakshi21299** [comment]
Hi, my previous error got fixed when I did the following change in my ide function. (lhs1 + y)**[: tf.size(rhs)]** - rhs. Earlier I hadn't taken the [: tf.size(rhs)] into account. But now I am getting a new error which says 
InvalidArgumentError: Retval[1] does not have value. 
Can you tell me how can this be resolved?

**Comment by lululxvi** [comment]
What is Retval? 

It might be helpful for you to look at the `FPDE` code, which is quite similar to IDE in terms of implementation. The `FPDE` supports 1D, 2D and 3D.

**Comment by Sakshi21299** [comment]
Dear Lulu, 
I tried figuring out the origin of the error but I am unable to handle it. The fde implementation looks similar to the changes I have made in the IDE code. I am attaching my main code and the modified ide function with this issue.  The error is occurring while training the network.

`def main():
    def ide(x, y, int_mat):
        u, v = y[:,0:1], y[:,1:2]
        L, t = x[:, 0:1], x[:, 1:2]
        du_x = dde.grad.jacobian(y, x, i=0, j=0)
        dv_t = dde.grad.jacobian(y, x, i=1, j=1)
        du_t = dde.grad.jacobian(y, x, i=0, j=1)

        int1 = tf.matmul(int_mat[0], u)
        int2 = tf.matmul(int_mat[1],v)
        int1 = tf.reshape(int1,[-1])
        int2 = tf.reshape(int2,[-1])

        `eq_a` = (dv_t + du_x)[: tf.size(int1)] - int1
        eq_b = du_t[: tf.size(int2)] - int2

        return [eq_a, eq_b]

    def func_sol(x):
        return x

    def bc_r(x,on_boundary):
        return on_boundary and np.isclose(x[0], 1)
   
    def ic_l(x, on_initial):
        return on_initial and np.isclose(x[1], 0)

    
    def fun_bc (x):
        return 0
    
    def fun_init(x):
        return 0
    
    
    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)
    
    bc1 = dde.DirichletBC(geomtime, fun_bc, bc_r , component = 0)
    ic1 = dde.IC(geomtime, fun_init, ic_l, component=0)
  

    quad_deg = 8
    data = dde.data.IDE(
        geomtime,
        ide,
        [bc1,ic1],
        quad_deg,
        num_domain=50,
        num_boundary=10,
        solution = func_sol,
        train_distribution="uniform",
    )

    net = dde.maps.FNN([2] + [2] * 1 + [2], "tanh", "Glorot uniform")
    
    
    model = dde.Model(data, net)
    model.compile("adam", loss = "mse", lr=0.001)
    losshistory, train_state = model.train(epochs=50000)
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
   

if __name__ == "__main__":
    main()
`
This is my modified IDE code.  Since the output is 2D, for the integration terms for each quadrature point, I have kept the second coordinate constant. I am still getting the same error which says RetVal[1] doesn't have a value.  Please help me with this. 
`
class IDE(PDE):
    """IDE solver.

    The current version only supports 1D problems with the integral int_0^x K(x, t) y(t) dt.

    Args:
        kernel: (x, t) --> R.
    """

    def __init__(
        self,
        geometry,
        ide,
        bcs,
        quad_deg,
        kernel1=None,
        kernel2 = None,
        num_domain=0,
        num_boundary=0,
        train_distribution="sobol",
        anchors=None,
        solution=None,
        num_test=None,
    ):
        self.kernel1 = kernel1 or one_function(1)
        self.kernel2 = kernel2 or one_function(1)
        self.quad_deg = quad_deg
        self.quad_x, self.quad_w = np.polynomial.legendre.leggauss(quad_deg)
        
        #self.quad_x2, self.quad_w2 = np.polynomial.legendre.leggauss(quad_deg)
        #self.quad_x = np.transpose(np.vstack((self.quad_x1,self.quad_x2)))
        #self.quad_w = np.transpose(np.vstack((self.quad_w1, self.quad_w2)))
        #print(self.quad_x1.shape)
        #print(self.quad_x2.shape)
        
        print(self.quad_x.shape)
        
       

        super(IDE, self).__init__(
            geometry,
            ide,
            bcs,
            num_domain=num_domain,
            num_boundary=num_boundary,
            train_distribution=train_distribution,
            anchors=anchors,
            solution=solution,
            num_test=num_test,
        )

    def losses(self, targets, outputs, loss, model):
        def losses_train():
            bcs_start = np.cumsum([0] + self.num_bcs)
            int_mat = self.get_int_matrix(True)
            f = self.pde(model.net.inputs, outputs, int_mat)
            if not isinstance(f, (list, tuple)):
                f = [f]
            f = [fi[bcs_start[-1] :] for fi in f]
            losses = [
                loss(tf.zeros(tf.shape(fi), dtype=config.real(tf)), fi) for fi in f
            ]

            for i, bc in enumerate(self.bcs):
                beg, end = bcs_start[i], bcs_start[i + 1]
                error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)
                losses.append(
                    loss(tf.zeros(tf.shape(error), dtype=config.real(tf)), error)
                )
            return losses

        def losses_test():
            int_mat = self.get_int_matrix(False)
            f = self.pde(model.net.inputs, outputs, int_mat)
            if not isinstance(f, (list, tuple)):
                f = [f]
            return [
                loss(tf.zeros(tf.shape(fi), dtype=config.real(tf)), fi) for fi in f
            ] + [tf.constant(0, dtype=config.real(tf)) for _ in self.bcs]

        return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)

    @run_if_all_none("train_x", "train_y")
    def train_next_batch(self, batch_size=None):
        self.train_x_all = self.train_points()
        x_bc = self.bc_points()
        x_quad = (self.quad_points(self.train_x_all,val=0)).reshape(-1)
        
        t_x_quad = self.train_x_all[:,1] 
        t_list = []
        for ti in t_x_quad:
            t_list = t_list + [ti]*self.quad_deg
        t_list = np.array(t_list)
        x_quad_all = np.vstack((x_quad,t_list)).T
        
        self.train_x = np.vstack((x_bc, self.train_x_all, x_quad_all))
        self.train_y = self.soln(self.train_x) if self.soln else None
        return self.train_x, self.train_y

    @run_if_all_none("test_x", "test_y")
    def test(self):
        if self.num_test is None:
            self.test_x = self.train_x_all
        else:
            self.test_x = self.test_points()
        x_quad = (self.quad_points(self.test_x, val = 0)).reshape(-1)
        t_x_quad = self.test_x[:,1]
        t_list = []
        for ti in t_x_quad:
            t_list = t_list + [ti]*self.quad_deg
        t_list = np.array(t_list)
        #t_quad = self.quad_points(self.train_x_all)
        x_quad_all = np.vstack((x_quad,t_list)).T
        
        
        self.test_x = np.vstack((self.test_x, x_quad_all))
        self.test_y = self.soln(self.test_x) if self.soln else None
        print('test_x', self.test_x.shape)
        return self.test_x, self.test_y

    def quad_points(self, X,val):
        def get_quad_points(x,val):
            if val == 0: 
                ans = (self.quad_x +1) * x / 2
            else: 
                ans = (self.quad_x +1) * x / 2

            #print(((self.quad_x +1) * x / 2).shape)
            return ans
        #print(list((map(lambda xi: get_quad_points(xi[0]), X))))
        #print(np.hstack(list(map(lambda xi: get_quad_points(xi[0]), X)))[:, None])
        return np.hstack(list(map(lambda xi: get_quad_points(xi[0],val), X)))[:, None]

    def get_int_matrix(self, training):
        def get_quad_weights(x):
            return self.quad_w * x / 2

        if training:
            num_bc = sum(self.num_bcs)
            X = self.train_x
            
        else:
            num_bc = 0
            X = self.test_x
        if training or self.num_test is None:
            num_f = len(self.train_x_all)
            
        else:
            num_f = self.num_test

        int_mat_x = np.zeros((num_bc + num_f, X.shape[0]), dtype=config.real(np))
        int_mat_t = np.zeros((num_bc + num_f, X.shape[0]), dtype=config.real(np))
        print(int_mat_x.shape)
        for i in range(num_f):
            x = X[i + num_bc, 0]

            beg = num_f + num_bc + self.quad_deg * i
            end = beg + self.quad_deg
            K_x = np.ravel(self.kernel1(np.full((self.quad_deg, 1), x), X[beg:end,0]))
            K_t = np.ravel(self.kernel2(np.full((self.quad_deg, 1), x), X[beg:end,1]))
            print(int_mat_x[i + num_bc, beg:end].shape)
            print(get_quad_weights(x).shape)
            print(K_x.shape)
            int_mat_x[i + num_bc, beg:end] = get_quad_weights(x) * K_x
            int_mat_t[i + num_bc, beg:end] = get_quad_weights(x) * K_t
            
            
        return [int_mat_x, int_mat_t]
`
 I am still getting the same error which says RetVal[1] doesn't have a value.  Please help me with this.

**Comment by lululxvi** [comment]
`RetVal` is not in your code. Which line of your code induces this error?

**Comment by Sakshi21299** [comment]
The issue is induced in the Model class in deepxde in the _test function. 
`self.train_state.loss_test, self.train_state.y_pred_test = self.sess.run(
                [self.losses, self.net.outputs],
                feed_dict=self.net.feed_dict(
                    False, False, 1, self.train_state.X_test, self.train_state.y_test
                ),
            )
            `
This line is throwing an error. RetVal[1] isn't defined by me and is not defined in deepxde to the best of my knowledge. I think the error is thrown by tensor flow. Any idea why this could be happening? 
self.train_state.X_test  = [0.         1.        ]
 [1.         1.        ]
 [0.33333334 1.        ]
 [0.66666669 1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.21132487 1.        ]
 [0.78867513 1.        ]
 [0.07044162 1.        ]
 [0.26289172 1.        ]
 [0.14088325 1.        ]
 [0.52578344 1.        ]]

self.losses Tensor("packed:0", shape=(4,), dtype=float32)
self.net.outputs Tensor("dense_4/BiasAdd:0", shape=(?, 2), dtype=float32)

I have printed the inputs to self.sess.run() above. 
My input training points to the network after stacking the domain points with the quadrature locations are as follows: 
Train X: 
[[1.         1.        ]
 [0.         1.        ]
 [1.         1.        ]
 [0.33333334 1.        ]
 [0.66666669 1.        ]
 [0.         1.        ]
 [0.         1.        ]
 [0.21132487 1.        ]
 [0.78867513 1.        ]
 [0.07044162 1.        ]
 [0.26289172 1.        ]
 [0.14088325 1.        ]
 [0.52578344 1.        ]]

Can you please help me regarding how I can fix this error?

**Comment by Sakshi21299** [comment]
Hi Lulu, I was able to narrow down the problem to gradient computation. When I use tf.gradients instead of dde.grad.jacobian in my code I no longer get that error. But I still haven't figured out why dde.grad.jacobian doesn't work. Technically both the methods use tf.gradients inside them to compute the gradients. So it is unclear to me what is causing the error.

**Comment by lululxvi** [comment]
Yes, it is strange. Not sure why.
