### ISSUE TITLE
Example with DeepONet

### ISSUE THREAD

**Issue by tliu1023** [lululxvi/deepxde#199]
Hi Lu,

Thanks for your effort and your repo! I'm wondering in the example folder, which example is implemented with DeepONet? Thank you!

**Comment by lululxvi** [comment]
We will upload the code of DeepONet very soon.

**Comment by frobnitzem** [comment]
The class is there, but there doesn't seem to be an example using [OpNN](https://deepxde.readthedocs.io/en/latest/modules/deepxde.maps.html?highlight=operator#deepxde.maps.OpNN) yet.  It's a little hard to figure out from the documentation alone.

**Comment by dpdclub** [comment]
finally. have been expecting for a long time.

LinLin

**Comment by kopanicakova** [comment]
Hi Lu, 

I just downloaded the library and I would like to check out the DeepONet example. 
Did you guys manage to make it available yet? If so, could you please point me to the file? 

Many thanks for sharing your repo with us.

best regards, 
alena

**Comment by lululxvi** [comment]
It is here https://github.com/lululxvi/deeponet

**Comment by kopanicakova** [comment]
many thanks!

**Comment by xueqi1234** [comment]
Hello, lulu,

I encountered this error in deeponet: AttributeError: module 'deepxde.nn.pytorch' has no attribute 'OpNN'. How should I resolve this issue? Which version of deepxde and paddlepaddle should I install? Thank you！

**Comment by lululxvi** [comment]
`OpNN` is a very old API. Update your code to the new API.
