### ISSUE TITLE
 >> unexpected keyword argument 'metrics' << when tensorflow-gpu is installed

### ISSUE THREAD

**Issue by mxbuschi** [lululxvi/deepxde#2]
**Problem:**
After installing tensorflow-gpu in my conda environment, a functional code failed with the following error:

`File ".../deepxde/boundary_conditions.py", line 33, in normal_derivative
    return tf.reduce_sum(dydx * n, axis=1, keepdims=True)
TypeError: reduce_sum() got an unexpected keyword argument 'keepdims'`

**Working fix:**
Changing `keepdims` to `keep_dims`  in the `boundary_conditions.py`-file seems to fix this issue.

**Comment by lululxvi** [comment]
Hi mxbuschi,

What is your TensorFlow version? `keep_dims` is deprecated,  see https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum
