### ISSUE TITLE
Wave Equation with Single Point Source

### ISSUE THREAD

**Issue by engsbk** [lululxvi/deepxde#200]
Hello @lululxvi ,
Thanks for answering our questions!
I created an example for 1D wave equation in time. How is dx and dt determined for the FNN? Is it the same that I use in my exact solution or are they different?

---------------
I'm asking this question to figure out how to tune the training output to the right scale. The training loss seems really small but the results are off. 

Training loss looks like:

```
Compiling model...
Building feed-forward neural network...
'build' took 0.078368 s

'compile' took 0.945946 s

Initializing variables...
Training model...

Step      Train loss                        Test loss                         Test metric
0         [1.07e-03, 2.83e-03, 3.19e-03]    [1.07e-03, 0.00e+00, 0.00e+00]    []  
1000      [6.68e-08, 1.79e-08, 2.68e-09]    [6.68e-08, 0.00e+00, 0.00e+00]    []  
2000      [9.85e-09, 3.38e-09, 7.31e-10]    [9.85e-09, 0.00e+00, 0.00e+00]    []  
3000      [4.11e-09, 1.10e-09, 3.30e-10]    [4.11e-09, 0.00e+00, 0.00e+00]    []  
4000      [2.20e-09, 5.40e-10, 1.79e-10]    [2.20e-09, 0.00e+00, 0.00e+00]    []  
5000      [1.21e-08, 7.32e-09, 9.51e-09]    [1.21e-08, 0.00e+00, 0.00e+00]    []  
6000      [5.72e-10, 2.77e-10, 1.26e-10]    [5.72e-10, 0.00e+00, 0.00e+00]    []  
7000      [1.24e-10, 9.51e-11, 6.20e-11]    [1.24e-10, 0.00e+00, 0.00e+00]    []  
8000      [2.26e-11, 2.39e-11, 1.84e-11]    [2.26e-11, 0.00e+00, 0.00e+00]    []  
9000      [1.72e-10, 1.79e-11, 6.37e-12]    [1.72e-10, 0.00e+00, 0.00e+00]    []  
10000     [5.91e-09, 1.75e-09, 5.74e-10]    [5.91e-09, 0.00e+00, 0.00e+00]    []  
11000     [3.69e-09, 2.41e-10, 6.04e-11]    [3.69e-09, 0.00e+00, 0.00e+00]    []  
12000     [2.57e-09, 2.73e-11, 5.86e-12]    [2.57e-09, 0.00e+00, 0.00e+00]    []  
13000     [1.60e-09, 2.82e-11, 4.26e-12]    [1.60e-09, 0.00e+00, 0.00e+00]    []  
14000     [9.18e-10, 3.40e-11, 7.18e-12]    [9.18e-10, 0.00e+00, 0.00e+00]    []  
15000     [4.74e-10, 2.36e-11, 5.83e-12]    [4.74e-10, 0.00e+00, 0.00e+00]    []  

Best model at step 8000:
  train loss: 6.49e-11
  test loss: 2.26e-11
  test metric: []

'train' took 3117.899176 s

Compiling model...
'compile' took 0.601153 s

Training model...

Step      Train loss                        Test loss                         Test metric
15000     [4.74e-10, 2.36e-11, 5.83e-12]    [4.74e-10, 0.00e+00, 0.00e+00]    []  
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: 0.000000
  Number of iterations: 0
  Number of functions evaluations: 1
15001     [4.74e-10, 2.36e-11, 5.83e-12]    [4.74e-10, 0.00e+00, 0.00e+00]    []  

Best model at step 8000:
  train loss: 6.49e-11
  test loss: 2.26e-11
  test metric: []

'train' took 1.475585 s
```

<img width="622" alt="Screen Shot 2021-01-08 at 6 03 53 PM" src="https://user-images.githubusercontent.com/25299510/104073514-e107bb00-51db-11eb-8141-2aa76beadfcb.png">

**Comment by lululxvi** [comment]
I don't understand what you mean by dx and dt. There is no dx and dt in the algorithm. There is only `num_domain`, `num_initial` and `num_boundary`

**Comment by engsbk** [comment]
dt and dx as in the delta between points in the Finite difference I used to create an exact solution. 
I created an exact solution using 100 points of x and 100 of t.
dx = 1 and dt =0.01.
Does this mean I can choose 100 domain points for the same purpose?

**Comment by lululxvi** [comment]
In DeepXDE, by default, the points are sampled randomly according to `num_domain` etc, not in a grid. So there is no dx and dt. There is no need for the exact solution for training.

**Comment by engsbk** [comment]
I ran DeepXDE for wave equation with IC in space:

```
ic = dde.IC(
    geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
)

```

it works fine with good results:
<img width="987" alt="Screen Shot 2021-01-21 at 10 23 26 AM" src="https://user-images.githubusercontent.com/25299510/105371544-b6056a00-5bd2-11eb-9356-980e559a26b5.png">

<img width="1002" alt="Screen Shot 2021-01-21 at 10 23 51 AM" src="https://user-images.githubusercontent.com/25299510/105371611-c584b300-5bd2-11eb-89a9-77b031f463a5.png">


but it does not show good results when I'm setting IC to be in terms of time:
```

def func(x):
    f_exact = 10
    return np.sin(2*np.pi*f_exact*x[:,1:])


ic = dde.IC(
     geomtime, func, lambda _, on_initial: on_initial
)
```

<img width="983" alt="Screen Shot 2021-01-21 at 10 27 18 AM" src="https://user-images.githubusercontent.com/25299510/105372083-40e66480-5bd3-11eb-903b-aac4d43fe1f6.png">


<img width="1002" alt="Screen Shot 2021-01-21 at 10 27 44 AM" src="https://user-images.githubusercontent.com/25299510/105372164-5065ad80-5bd3-11eb-8d53-e7595d0a2dca.png">
<img width="993" alt="Screen Shot 2021-01-21 at 10 28 05 AM" src="https://user-images.githubusercontent.com/25299510/105372218-5d829c80-5bd3-11eb-818b-0cb2cf43f713.png">



This is my code:

```
def pde(x, u):
    c0 = 0.1
#Using new DeepXDE Jacobians and Hessians
    du_xx = dde.grad.hessian(u, x, i=0, j=0)
    du_tt = dde.grad.hessian(u, x, i=1, j=1)
    return   du_tt - (c0 ** 2) * (du_xx)
   

#function for IC
def func(x):
    f_exact = 10
    return np.sin(2*np.pi*f_exact*x[:,1:])
   
geom = dde.geometry.Interval(-1,1)
timedomain = dde.geometry.TimeDomain(0,1)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

bc = dde.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: on_boundary)
ic = dde.IC(
     geomtime, func, lambda _, on_initial: on_initial
)


#variable folds is for testing multiple numbers of training points
folds = 2
data = dde.data.TimePDE(
    geomtime, pde, [bc, ic], 
    num_domain=int(folds*2500), 
    num_boundary=int(folds*1), 
    num_initial=int(folds*1),
    solution=func,
    num_test=int(folds*2500)
)


net = dde.maps.FNN([2] + [40] * 3 + [1], "tanh", "Glorot normal")
#net.apply_feature_transform(lambda x: x * np.array([100,100]))
#net.apply_output_transform(lambda x, u: u * 1000)

model = dde.Model(data, net)

model.compile("adam", lr=1e-3)
model.train(epochs=15000)
model.compile("L-BFGS-B")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

#There are 3 columns in train loss: 
#the first column is PDE loss, the second column is left BC loss, and the third column is right BC loss.

X, u_true = gen_testdata()
u_pred = model.predict(X)
f = model.predict(X, operator=pde)
print("Mean residual:", np.mean(np.absolute(f)))
print("L2 relative error:", dde.metrics.l2_relative_error(u_true, u_pred))
np.savetxt("test.dat", np.hstack((X, u_true, u_pred)))
```

I tried scaling and choosing different numbers of training points. I tried multiple values for c (sound speed) but with no luck.
Please advise. What do you think is the problem?

**Comment by engsbk** [comment]
Thanks for your responses, Lu!
I have a couple of questions to help me understand DeepXDE with source functions:

- I'm trying to implement a single point source, how can I specify the location of the time-function source in the geometry domain since we don't have a grid in DeepXDE? I thought about using a Delta function(to support having an exciting source at one single point)...

- Also I have another question about the units of geometry, the Interval (-1,1), is it in centimeters or meters for instance? How can I implement an interval of 2cm or 4m? Do I have to use the features transform for that?

**Comment by lululxvi** [comment]
- Do you mean you have a point source in the PDE? If so, you can use other functions to approximate the delta function, e.g., a Gaussian. see https://en.wikipedia.org/wiki/Dirac_delta_function
- There is no physical unit. Everything is purely "mathematical".

**Comment by engsbk** [comment]
Thank you for the suggestion, @lululxvi .
I have tried using Dirac Delta function. There's an error that shows when I use it in the source term:
```
def pde(x, u):
    c = 0.01
    frequency = 10
    print("shape",x[:,1:2].shape)
    source = signal.unit_impulse(x[:,1:2].shape,'mid') * tf.sin(-2*np.pi*frequency*x[:,1:2])
    #impulse*sin^(-2*pi*f*t)

    du_xx = dde.grad.hessian(u, x, i=0, j=0)
    du_tt = dde.grad.hessian(u, x, i=1, j=1)
    
    return   du_tt - (c ** 2)*(du_xx) - source
   
```

The error is:

`TypeError: __index__ returned non-int (type NoneType)
`

I used the term: `signal.unit_impulse(x[:,1:2].shape,'mid')` because I wanted to create a impulse function with a signal 1 in the middle of zeros array. I used the term: `x[:,1:2].shape`, because I think every time the code runs it selects a different number of points, so I tried to fix it with `.shape` so I would create the right size of impulse function for multiplication.

I also tried printing the shape of `x[:,1:2]` before using it for shaping the impulse function, and it showed `(?,1)`. 
How can I choose the right shape for source term multiplication in `pde( x,u)` ?
or
How does the shape of x[:,1:2] gets decided in `pde(x,u)`?

**Comment by lululxvi** [comment]
Not quite understand your code. `x` is a tf tensor.
