### ISSUE TITLE
Adaptive Activation Function

### ISSUE THREAD

**Issue by mariusmerkle** [lululxvi/deepxde#203]
Hi,

I want to experiment with adaptive activation functions (https://www.sciencedirect.com/science/article/pii/S0021999119308411?casa_token=Kazj2y9fKdoAAAAA:eaQAQWv3Nyj_RrkTgCOlQ7zeACTY6JwcUzCBa70HXef2CYBgopN8dPgZwy2OlDNdW9pKyVzY558) but get an error in the following line of code:

`net = dde.maps.FNN([1] + hidden_layers*[hidden_units] + [1], dde.maps.activations.layer_wise_locally_adaptive("LAAF-10 tanh"), "Glorot normal")`

It should be an easy fix, but I can't find any reference code example. @lululxvi

**Comment by lululxvi** [comment]
See the example at https://deepxde.readthedocs.io/en/latest/modules/deepxde.maps.html#deepxde.maps.activations.layer_wise_locally_adaptive
