### ISSUE TITLE
About the design of PDE functions

### ISSUE THREAD

**Issue by Poker-Pan** [lululxvi/deepxde#205]
Dear author, thank you very much for sharing.
        Now I run into a problem with this library that I can't solve.
        I want to design the term f at the right end of the equation as a piecewise function, but when I write it in the pde function, I cannot achieve it.
        I would like to ask you how to achieve this.
        Such as:  
                      when x>1, f=x;
                      when x<=1, f = x**2.

Thank you for your help!

**Comment by lululxvi** [comment]
see https://github.com/lululxvi/deepxde/issues/185
