### ISSUE TITLE
Adding a list of pdes

### ISSUE THREAD

**Issue by Clement465** [lululxvi/deepxde#209]
Hi @lululxvi ,

I have been encountering the following error when trying to use a list of pdes instead of one pde. In the docs it says that a global PDE or a list of PDEs can be used. What am I doing wrong here?

Traceback (most recent call last):
  File "flowoverairfoil-ns.py", line 224, in <module>
    main()
  File "flowoverairfoil-ns.py", line 99, in main
    model.compile("adam", lr=0.001)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\model.py", line 85, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\data\pde.py", line 81, in losses
    if self.pde is not None and get_num_args(self.pde) == 2:
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\deepxde\utils.py", line 169, in get_num_args
    sig = inspect.signature(func)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\inspect.py", line 3093, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\inspect.py", line 2842, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\inspect.py", line 2216, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: [<function main.<locals>.pde1 at 0x00000198C3C07C10>, <function main.<locals>.pde2 at 0x00000198C50B13A0>, <function main.<locals>.pde3 at 0x00000198C50B1430>] is not a callable object

```python
    pdes = [pde1, pde2, pde3]

    data = dde.data.PDE(geom, pdes, bcs, num_domain=600,num_boundary=250, num_test=200)
```

Thank you.

**Comment by Clement465** [comment]
Hi Lu Lu, 

I managed to find the answer in #179,

I modified the pde function to return 3 losses instead of using three separate pde functions.

```Python
    def pde(inputs, outputs, _):
        ...
        ...
        ...
        return [loss1, loss2, loss3]
    ...
    ...
    data = dde.data.PDE(geom, pde, bcs, num_domain=1000,num_boundary=300, num_test=400)
```

Thank you.

**Comment by lululxvi** [comment]
Looks good. But you should use
```python
def pde(inputs, outputs):
    ...
```

**Comment by Clement465** [comment]
Hi Lu Lu,

Is there any reason to use "def pde(inputs, outputs):" instead of "def pde(inputs, outputs, _):" other than grammar?

Thank you.

**Comment by lululxvi** [comment]
`pde(inputs, outputs, _)` is used for special cases

**Comment by Clement465** [comment]
Ok, thank you Lu Lu!

**Comment by chaibaoqiang** [comment]
I use the model :
def pde(inputs, outputs):
    ...
and the way like:
 pdes = [pde1, pde2, pde3]
 data = dde.data.PDE(geom, pdes, bcs, num_domain=600,num_boundary=250, num_test=200)

my output like @Clement465 you，e.g:
TypeError: [<function main..pde1 at 0x00000198C3C07C10>, <function main..pde2 at 0x00000198C50B13A0>, <function main..pde3 at 0x00000198C50B1430>] is not a callable object

@Clement465 @lululxvi how did you solve this problem? waiting for your reply! thanks!

**Comment by lululxvi** [comment]
See https://github.com/lululxvi/deepxde/blob/master/examples/ode_system.py for a list of PDEs

**Comment by chaibaoqiang** [comment]
@lululxvi 
hi,lulu, thanks for your reply, I try my best to solve the problem, but it does not succeed, my problems as follows:
![8D2977F0B64D3D68281977A341A84A6A](https://user-images.githubusercontent.com/44567442/121275147-9ca15800-c8fe-11eb-8544-b7d5d1776c14.png)

 my code is :

import deepxde as dde
from deepxde.backend import tf
import numpy as np

T = 1
L = 1
geom = dde.geometry.Interval(0, L)
timedomain = dde.geometry.TimeDomain(0, T)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

def pde(x,y):
    y1,y2 = y[:,0:1],y[:,1:]
    
    dy1 = tf.gradients(y1, x)[0]
    dy2 = tf.gradients(y2, x)[0]
    
    y1_x,y1_t =dy1[:,0:1],dy1[:,1:2]
    y2_x,y2_t =dy2[:,0:1],dy2[:,1:2]
    
    y1_xx = tf.gradients(y1_x,x)[0][:,0:1]
    y1_tt = tf.gradients(y1_x,x)[0][:,1:2]
    
    y2_xx = tf.gradients(y2_x,x)[0][:,0:1]
    y2_tt = tf.gradients(y2_x,x)[0][:,1:2]
    
    y1_xxxx = tf.hessians(y1_xx,x)[0][:,0:1]
    
    y2_xxxx = tf.hessians(y2_xx,x)[0][:,0:1]
    
    y1_xxtt = tf.hessians(y1_xx,x)[0][:,1:2]
    
    y2_xxtt = tf.hessians(y1_xx,x)[0][:,1:2]
    
    return [y1_tt - y1_xxtt + y1_xxxx - y1_xx + y2_xx, 
             y2_tt - y2_xxtt + y1_xx + y2_xxxx - y2_xx - y2]

######以下为在边界条件中使用OperatorBC 重复定义了各个分量
def y1(x,y):
    return y[:,0:1]
def y2(x,y):
    return y[:,1:2]
def dy1(x,y):
    return tf.gradients(y1, x)[0]
def dy2(x,y):
    return tf.gradients(y2, x)[0]
def y1_x(x,y):
    return dy1[:,0:1]
def y1_t(x,y):
    return dy1[:,1:2]
def y2_x(x,y):
    return dy2[:,0:1]
def y2_t(x,y):
    return dy2[:,1:2]
def y1_xx(x,y):
    return tf.gradients(y1_x,x)[0][:,0:1]
def y2_xx(x,y):
    return tf.gradients(y2_x,x)[0][:,0:1]
####################################################

def boundary_l(x, on_boundary):
    return on_boundary and np.isclose(x[0],0)

bc1 = dde.DirichletBC(geom, lambda x : 0 , boundary_l)
bc2 = dde.NeumannBC(geom, lambda x : 0 , boundary_l )
bc3 = dde.OperatorBC(geom, lambda x,y,_:y1_xx(x,y),boundary_l)
bc4 = dde.OperatorBC(geom, lambda x,y,_:y2_xx(x,y),boundary_l)

data = dde.data.TimePDE(geomtime, pde,[bc1,bc2],num_domain=2540, num_boundary=80, num_initial=160)

net = dde.maps.FNN([2] + [20] * 3 + [2], "tanh", "Glorot normal")

model = dde.Model(data, net)
model.compile("adam", lr=1e-3)

losshistory, train_state = model.train(epochs = 5000)

###########################################
Q：
1. when i use [ bc1 , bc3, bc4] (This boundary condition should be used according to the problem), the error is：
 
![Q1](https://user-images.githubusercontent.com/44567442/121275590-a8d9e500-c8ff-11eb-8b68-d3f69759649b.jpg)

2.  at first  for test my pde , i use the[bc1, bc2], the error is:
![Q2](https://user-images.githubusercontent.com/44567442/121275787-ffdfba00-c8ff-11eb-88e8-18bd64690189.jpg)

after the  first step , the code can not run ,and  the error is :
![Q3](https://user-images.githubusercontent.com/44567442/121275882-2b62a480-c900-11eb-93e5-ea78cbb33cee.jpg)

i use the code on different computer the result is same, can you help me, thanks!
waiting for your reply, best wishes!

**Comment by chaibaoqiang** [comment]
@lululxvi  I think the problem may be lie in the boundary conditions.(geom has been replaced with geomtime, but the problem remains the same). Please help me to solve it. 

Waiting for your reply, best wishes!

**Comment by lululxvi** [comment]
The code of BC doesn't satisfy Python grammar. See the following example:
```
def dy1_dx(x,y):
    return dde.grad.jacobian(y, x, i=0, j=0)
```
Also, use `dde.grad.jacobian` and `dde.grad.hessian` instead of tf, see https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.gradients.hessian and https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.gradients.jacobian

**Comment by FZUcipher** [comment]
@chaibaoqiang 请问你的案例成功实现了吗？
