### ISSUE TITLE
2D Poisson equation with variable coefficient

### ISSUE THREAD

**Issue by tangqi** [lululxvi/deepxde#21]
Hi, I am interested in solving some practical problems with your solver. As a first test, I would like to solve -div(coeff*grad y) = 1, where coeff=1+x1+x2. (a similar 1D case works fine.) The computational domain is [0,1]^2. 

Here is the simple code:
```python
def main():
    def pde(x, y):
        x1=x[:,0]
        x2=x[:,1]
        coeff=1+x1+x2
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_y = dy_x[:, 0:1], dy_x[:, 1:]
        dy_xx = tf.gradients(coeff*dy_x, x)[0][:, 0:1]
        dy_yy = tf.gradients(coeff*dy_y, x)[0][:, 1:]
        return -dy_xx-dy_yy-1

    def boundary(x, on_boundary):
        return on_boundary

    def func(x):
        return np.zeros([len(x), 1])

    geom = dde.geometry.Rectangle([0,0],[1,1])
    bc = dde.DirichletBC(geom, func, boundary)

    data = dde.data.PDE(
        geom, 1, pde, bc, num_domain=1200, num_boundary=120, num_test=1500
    )
    net = dde.maps.FNN([2] + [50] * 4 + [1], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=50000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
But the solver converges to the wrong solution. One obvious mistake is the boundary condition is not 0 and also the solution is quite off. I also tried the non conserved version of the problem, it give me an even worse solution. 

The solver has no issue to solve a problem of -dy_xx-dy_yy-dy_x-dy_y=1, which is very close to the problem I failed. Therefore, I do not quite understand why the solver fails so badly for the problem I set up. I am new to tensorflow, so it is likely I may miss something obvious. Any suggestions? 

Thanks!
Qi

**Comment by lululxvi** [comment]
Could you change `x1=x[:,0]` and `x2=x[:,1]` to `x1=x[:, 0:1]` and `x2=x[:, 1:]`, so that `x1` and `x2` are column vectors?

**Comment by tangqi** [comment]
Thanks a lot! That appears to be the bug.

Do you happen to have a 3D case or a time-dependent 2D example by any chance, or have you ever tried it? 

-Qi

**Comment by lululxvi** [comment]
Yes, we have time-dependent 2D example, but the code is not online.

**Comment by tangqi** [comment]
Great! Looking forward to it. Thanks again for the help.

**Comment by tangqi** [comment]
Hi Lu, is there any chance to share a simple 2D time dependent case, like the one in the arxiv paper for us to try? Thanks, -Qi

**Comment by lululxvi** [comment]
I will upload these days. 2D time case should be very similar to 1D case.

**Comment by tangqi** [comment]
Thank you! That would be great!

**Comment by Fayaud** [comment]
Hello Lulu!

Please where can I  find an example of a time dependent 2D domain.

best regards,

**Comment by Fayaud** [comment]
Hello Lulu!

Please is this the right syntax to fix the time-periodicity condition for a PDE problem in 2D in space? 

Spatial_domain = dde.geometry.Rectangle(xmin=[-1, -1], xmax=[1, 1])
Temporal_domain = dde.geometry.TimeDomain(0, 2*np.pi)
Spatio_temporal_domain = dde.geometry.GeometryXTime(Spatial_domain, Temporal_domain)
boundary_condition_u = dde.DirichletBC(Spatio_temporal_domain, u_func, lambda _, on_boundary: on_boundary, component=0)
boundary_condition_v = dde.DirichletBC(Spatio_temporal_domain, v_func, lambda _, on_boundary: on_boundary, component=1)

periodic_condition_u = dde.PeriodicBC(Spatio_temporal_domain, 1, lambda _, on_boundary: on_boundary, component=0)???
periodic_condition_v = dde.PeriodicBC(Spatio_temporal_domain, 1, lambda _, on_boundary: on_boundary, component=1)???

I only want to check the two last line for:  u(x, y, 0) = u(x, y, 2*pi); v(x, y, 0) = v(x, y, 2*pi)

thank you very much!

best,

**Comment by Fayaud** [comment]
Or should I instead use this syntax for the time-periodicity for a problem in 2D in space ?


periodic_condition_u = dde.PeriodicBC(Spatio_temporal_domain, 1, lambda _, on_periodic: on_periodic, component=0)???
periodic_condition_v = dde.PeriodicBC(Spatio_temporal_domain, 1, lambda _, on_periodic: on_periodic, component=1)???

Thank you very much!

best,

**Comment by lululxvi** [comment]
For the periodic in x and y, why "u(x, y, 0) = u(x, y, 2pi); v(x, y, 0) = v(x, y, 2pi)"? Should it be u(-1, y, t) = u(1, y, t); v(x, -1, 0) = v(x, 1, t)?

**Comment by Fayaud** [comment]
Hello Professor!

Thank you for replying. I want to enforce the periodic in time. So, my problem is in 2 dimension in space and the third dimension is the time as: (x, y, t).  I actually want to write:

u(x, y, 0) = u(x, y, 2pi);  v(x, y, 0) = v(x, y, 2pi) for all (x, y).

best regards!

Fayaud!

**Comment by Fayaud** [comment]
For more precision, I am solving the following time-dependent Navier-Stokes equation:

[File.pdf](https://github.com/lululxvi/deepxde/files/7175025/File.pdf)

best,

**Comment by AlirezaPa** [comment]
Hi, I have a similar question about this topic. My PDEs also have a variable g which depends to x[0]. This is the portion of my code that I have problem with that. I tried several times to write a for loop including if statement, but I got errors. I am also new to Tensorflow. I would be glad if you can help me to figure out this problem. 

![image](https://user-images.githubusercontent.com/93855073/149759997-b345a9d3-d32b-442e-bd0e-adad4331cc56.png)

Thank you,
Alireza
