### ISSUE TITLE
Eager Execution for debugging

### ISSUE THREAD

**Issue by Clement465** [lululxvi/deepxde#213]
Hi @lululxvi,

Is there a way to enable eager execution for the purpose for debugging?

tf.compat.v1.enable_eager_execution doesn't seem to be working for me.

Thank you.

**Comment by lululxvi** [comment]
Unfortunately, no. But you can use [OperatorPredictor](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.callbacks.OperatorPredictor) and other callbacks to get the internal status.

**Comment by Clement465** [comment]
Ok, thank you!
