### ISSUE TITLE
DeepXDE for time series data

### ISSUE THREAD

**Issue by kimianoorbakhsh** [lululxvi/deepxde#214]
Hello @lululxvi 
Thanks for this amazing library.
I have been working on my research project, and I tried to use DeepXDE for my dataset. My data is from a 2D diffusion equation (the heat transfer equation), but the data pattern has a time-series pattern. 

Assume that the equation I am working on is: dT_t = D * (dT_xx + dT_yy). where T is a temperature value that I would like to predict.

What I mean from time-series pattern is that for example for a specific pair of value for x and y like (x1,y1), I have 100 different samples in my data like below:

(x1, y1, t = 0) -> Temp1
(x1, y1, t=1) -> Temp2
...
(x1, y1, t = 100) -> Temp100

And then I have the same thing for (x2,y2) and so on. Therefore, the boundary conditions are changing over time.
My question is that does DeepXDE support these kinds of data? Could you please help me with this and give me some suggestions?

**Comment by lululxvi** [comment]
I am not quite sure what is your difficult. "boundary conditions are changing over time" is not a problem at all. We don't have any restriction on the data format, and it can be many time series.

**Comment by engsbk** [comment]
Thanks for your reply @lululxvi !
Can you supply an example on the syntax of using time-dependent functions as BC? 
Is it possible to have the function active at only one point (fixed location) in the BC?

**Comment by lululxvi** [comment]
- If you use `DirichletBC`, then you need to define `func` for this BC. https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.DirichletBC . e.g., diffusion_1d_inverse.py
- Yes, define `on_boundary` to return `True` only for that point.

**Comment by engsbk** [comment]
> * Yes, define `on_boundary` to return `True` only for that point.

Is this syntax correct for point (0,5)?
```python
def boundary_point(x, on_boundary):
    return on_boundary and np.isclose(x[0], 0) and np.isclose(x[1], 5)# POINT SOURCE ON BOUNDARY
```
