### ISSUE TITLE
Test metric

### ISSUE THREAD

**Issue by JuntaoHuang** [lululxvi/deepxde#217]
What is the meaning of "Test metric" in the output of the code?

**Comment by lululxvi** [comment]
It is the value of `metrics` used in `Model.compile()`

**Comment by JuntaoHuang** [comment]
Thanks!

**Comment by ruchitkini** [comment]
> It is the value of `metrics` used in `Model.compile()`

Do you know what metrics can be used. i have code which says, metrics =  [12 relative error]. But this gives me keyerror. What is the solution on this?
