### ISSUE TITLE
Try to generate a coefficient which changes by its corresponding coordinate 

### ISSUE THREAD

**Issue by Enowyz** [lululxvi/deepxde#219]
Hi, Lulu.

I am trying to generate a PDE which has a coefficient c : when x<1, c= 3000; when x>=1 c= 3. I try to use **tf.where**.

The following is my code:
```python
def pde(x, y):  # x is a x,y,t input; y is my value

        dy_x = tf.gradients(y, x)[0] 
        dy_x1 = dy_x[:, 0:1]    
        dy_x2 = dy_x[:, 1:2]  
        dy_t = dy_x[:, 2:3]      
        dy_x1x1 = tf.gradients(dy_x1, x)[0][:, 0:1]  
        dy_x2x2 = tf.gradients(dy_x2, x)[0][:, 1:2]  

        C_result = tf.where(x[:, 0:1] > 1, x[:, 0:1] *0+3000, x[:, 0:1] *0+3)   # when x>1, c= 3000 and maintain a same shape as x
        C = tf.Session().run(C_result)

        return ( 
            dy_t * C - dy_x1x1 - dy_x2x2
        )
```
But I got an error like this:

**InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_63' with dtype float and shape [?,3]**
	 **[[{{node Placeholder_63}}]]**

I think I have arranged my C as the same format as my dx, dy and dt, but there is still a shape of 3 not matching. Could you please tell me how to implement this coefficient C with two different x domains? I have read the issue 185 but still stuck with this shape error for tf.where. Thank you.

**Comment by lululxvi** [comment]
Do not run `C`.

**Comment by Enowyz** [comment]
> Do not run `C`.

You mean I directly use tf_result as the C in my pde?

**Comment by lululxvi** [comment]
Yes
