### ISSUE TITLE
multiple neural networks with different input dimensions

### ISSUE THREAD

**Issue by JuntaoHuang** [lululxvi/deepxde#221]
I am trying to solve a system of PDEs using this package. The unknown variables for the PDEs have different input dimensions. For example, the unknown variables are `u` and `v`, where `u = u(x)` is a function only depending on `x` and `v = v(x,y)` is a function depending on both `x` and `y`.

In all the available examples, it seems that we can only define **_one_** neural network with the uniform input dimension. Is it possible to define several neural networks with different input dimensions? Thanks!

**Comment by lululxvi** [comment]
see #178

**Comment by JuntaoHuang** [comment]
Thanks!
