### ISSUE TITLE
Movies for Multi-Dimensional Problems

### ISSUE THREAD

**Issue by mariusmerkle** [lululxvi/deepxde#223]
Hi @lululxvi,

I have seen that it is possible to generate a movie during training, for example in deepxde/example/Poisson_Dirichlet_1d.py using callbacks. In the DeepXDE, I have seen that it is possible to generate a movie along a **line**.

Is it also possible to generate movies for multi-dimensional equations, e.g. the heat equation? If so, can we generate a movie of surface plots or a line for some fixed value of t or x?

I get the following error: "x and y must have same first dimension, but have shapes (200,) and (100,)"

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    def pde(x, u):
        u_x = dde.grad.jacobian(u, x, i = 0, j = 0)
        u_t = dde.grad.jacobian(u, x, i = 0, j = 1)
        u_xx = dde.grad.hessian(u, x, i = 0, j = 0)
        return u_t - 0.05*u_xx

    def boundary(x, on_boundary):
        return on_boundary

    def func(x):
        return -np.sin(np.pi*x[:, 0:1])*np.exp(-nu_ref*np.pi**2*x[:, 1:2])

    nu_ref = 0.5
    x_min = -1
    x_max = 1
    t_min = 0
    t_max = 1

    spatial_domain = dde.geometry.Interval(x_min, x_max)
    temporal_domain = dde.geometry.TimeDomain(t_min, t_max)
    spatio_temporal_domain = dde.geometry.GeometryXTime(spatial_domain, temporal_domain) 

    boundary_condition = dde.DirichletBC(spatio_temporal_domain, lambda x: 0, lambda _, on_boundary: on_boundary)
    initial_condition = dde.IC(spatio_temporal_domain, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial)
    data = dde.data.TimePDE(spatio_temporal_domain, pde, [boundary_condition, initial_condition], num_domain = 1000, num_boundary = 1000, num_initial = 1000, solution=func, num_test=100)

    layer_size = [2] + [20] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)
    model.compile("adam", lr=0.001, metrics=["l2 relative error"])

    checkpointer = dde.callbacks.ModelCheckpoint(
        "model/model.ckpt", verbose=1, save_better_only=True
    )
    # ImageMagick (https://imagemagick.org/) is required to generate the movie.
    movie = dde.callbacks.MovieDumper(
        "model/movie", [-1, 0], [1, 1], period=10, save_spectrum=True, y_reference=func
    )
    losshistory, train_state = model.train(
        epochs=1000, callbacks=[checkpointer, movie]
    )

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

    # Plot PDE residual
    model.restore("model/model.ckpt-" + str(train_state.best_step), verbose=1)
    x = spatio_temporal_domain.uniform_points(1000, True)
    y = model.predict(x, operator=pde)
    plt.figure()
    plt.plot(x, y)
    plt.xlabel("x")
    plt.ylabel("PDE residual")
    plt.show()

if __name__ == "__main__":
    main()`

**Comment by lululxvi** [comment]
The movie can only be on a line. You can use `model.predict()` to have any prediction you need, and then generate the movie.
