### ISSUE TITLE
Boundary conditions in a hole inside the domain

### ISSUE THREAD

**Issue by EmirChacra** [lululxvi/deepxde#224]
I'm using a 2D rectangular domain with a hole in it

`rect = dde.geometry.geometry_2d.Rectangle(xmin=[0,0],xmax=[12.0,4.0])`
 `cilin= dde.geometry.geometry_2d.Disk(center= [4.0,2.0], radius= 0.4)`
 `geom = rect - cilin`

I've trying to define Dirichlet conditions in the boundary of the hole, but i always get NaN values in the error in those conditions during training. Now i'm defining the boundary this way

`def cilinder_boundary(x, on_boundary):`
`return on_boundary and np.isclose((x[0]- 4.0)**2 + (x[1]-2.0)**2 - 0.16, 0.0)`

but it's not working, do you have some idea of how can i make it work?

**Comment by alokwarey** [comment]
I am having the same issue. Trying to solve a 2D heat conduction problem with a circle inside a square. the BC's seem to be set correctly but the solution is completely off. Not sure what I am doing wrong.

domain = dde.geometry.Rectangle([0,0],[1,1])
circle= dde.geometry.Disk(center= [0.5,0.5], radius= 0.1)

geom = dde.geometry.CSGDifference(domain, circle)

def boundary_x_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], 0)

def boundary_x_r(x, on_boundary):
    return on_boundary and np.isclose(x[0], 1)

def boundary_y_b(x, on_boundary):
    return on_boundary and np.isclose(x[1], 0)

def boundary_y_u(x, on_boundary):
    return on_boundary and np.isclose(x[1], 1)

**OPTION 1**
# def boundary_circle(x, on_boundary):
#      return on_boundary and circle.on_boundary(x[:2])

**OPTION 2**
def boundary_circle(x, on_boundary):
     return on_boundary and np.isclose((x[0]- 0.5)**2 + (x[1]-0.5)**2 - 0.1**2, 0.0)

def func_0(x):
    return np.zeros((len(x),1), dtype=np.float32)

def func_1(x):
    return np.ones((len(x),1), dtype=np.float32)

bc_x_l = dde.DirichletBC(geom, func_0, boundary_x_l)
bc_x_r = dde.DirichletBC(geom, func_0, boundary_x_r)
bc_y_u = dde.DirichletBC(geom, func_0, boundary_y_u)
bc_y_b = dde.DirichletBC(geom, func_0, boundary_y_b)
bc_circle = dde.DirichletBC(geom, func_1, boundary_circle)


![image](https://user-images.githubusercontent.com/69644995/108545383-b8ccab00-72b5-11eb-9da6-14664eac8899.png)

**Comment by lululxvi** [comment]
`cilinder_boundary` seems correct. Maybe the NaN is due to other reason

**Comment by EmirChacra** [comment]
yes! I found another annoying typo that was messing with the boundary. It was changing the radius so it was interpreting a smaller radius.

Thanks!
