### ISSUE TITLE
deepxde.geometry.geometry_nd.Hypersphere

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#226]
https://github.com/lululxvi/deepxde/blob/9d460afafe0cd723cc1c767f233756bef5480628/deepxde/geometry/geometry_nd.py#L110
should be
```return np.amin(self.radius - np.linalg.norm(x - self.center, axis=-1))```?

**Comment by smao-astro** [comment]
And `deepxde.geometry.geometry_2d.Disk` could be subclass of `deepxde.geometry.geometry_nd.Hypersphere`?

**Comment by lululxvi** [comment]
- axis=1 and axis=-1 are the same axis.
- Yes, `Disk` can be subclass of `Hypersphere`

**Comment by smao-astro** [comment]
Thanks.
