### ISSUE TITLE
Layer normalization

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#227]
Hi Lu,

I would like to see whether layer normalization helps to further decrease the loss, however I do not know the *proper* way to implement one, I searched online but there is few discussion of layer norm in fully-connected network, could you implement one, or give me some detailed instruction? for example, should the beta/gamma be a tensor of [1, 1] or [1, N], (N the number of neurons)? Thanks.

**Comment by lululxvi** [comment]
I didn't look into layer norm yet, and not sure what is the best way of doing layer norm for FNN. Actually, it is not clear if PINN needs this.
