### ISSUE TITLE
Retraining model with new data

### ISSUE THREAD

**Issue by Cpc1533** [lululxvi/deepxde#228]
Hello @lululxvi
Your library has been of great help in a my recent research project. I am currently using deepxde for a 2D heat transfer diffusion equation at a range of time steps. 

Using your library, would it be possible to use a previously trained model for a new data set, keeping the previous weights as a starting point? If we can, are there any examples we could reference?

    model=dde.Model(data, net)

Because the model is defined by the data as seen in the code above, can we replace it with another data set while keeping the same model?

**Comment by lululxvi** [comment]
See FAQ: how to save and restore model.

**Comment by Cpc1533** [comment]
Thanks!

**Comment by frankiezoo** [comment]
Hey cpc1533, did you get this application to work? Do you mind posting the code that worked for you? Thanks!
