### ISSUE TITLE
HOWTO: Initial condition as input

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#233]
Hi Lu,

For forward time-dependent pde problem, I are wondering do you have any idea on how to do the follow:
- Solve N initial value problem in one training run, where the initial condition is slightly different while the pde and BC is the same. Once the model trained, given any initial condition, with/without a few additional train, can predict the short-time evolution.
- In addition, the initial condition is likely from some experiment such as is only known on discrete points (but sample can be dense enough).
- OPTIONAL: the system might sensitive to IC, i.e., ideally the IC can be constraint accurately (current popular soft constraint/penalty might cause error increase with time, however hard constraint as far as I know only apply when math expression is known).

**Comment by lululxvi** [comment]
Not sure if PINN is a good method for this. You may consider DeepONet https://arxiv.org/abs/1910.03193. The published version will be online soon.
