### ISSUE TITLE
Question about the reaction_inverse.py 

### ISSUE THREAD

**Issue by Xilun1995** [lululxvi/deepxde#235]
As the code shown, we used the training data to solve the inverse problem. 

**But I am confused what if observe_x1 is different from observe_x2?(anchor should be equal to observe_x1+observe_x2?)    If not, how to define the anchor. Thank in advance.**

observe_y1 = dde.PointSetBC(observe_x1, Ca, component=0)
 observe_y2 = dde.PointSetBC(observe_x2, Cb, component=1)

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic1, ic2, observe_y1, observe_y2],
        num_domain=2000,
        num_boundary=100,
        num_initial=100,
        anchors=????????????????????????????,
        num_test=50000,
    )

**Comment by lululxvi** [comment]
Use the union of observe_x1 and observe_x2.

**Comment by engsbk** [comment]
```python
anchors=geomtime.union((observe_x1, observe_x2, observe_x3))
```
shows an error:
```error
AttributeError: 'GeometryXTime' object has no attribute 'union'
```

How to perform the union for 3 point sets?

Thank you in advance!

**Comment by santoss2020** [comment]
hello,
I want to know how to solve a fractional differential equation in time with derivative of caputo using your framework for example u_t(caputo)-u_xx=f(x).
thanks

**Comment by lululxvi** [comment]
No. But you can implement time derivative similar as the space derivative, see the fPINN paper.

**Comment by wangxiao2019** [comment]
Hello, I'm wondering if this framework can only solve spatial fractional derivatives of the Laplace operator. Also, in your paper titled "fPINNs: Fractional Physics-Informed Neural Networks", where in the framework's code module is the finite difference schemes for fractional derivatives, specifically the following equation, implemented?
Finite difference schemes for fractional derivatives，$\begin{aligned} \frac{\partial^\gamma \tilde{u}(\boldsymbol{x}, t)}{\partial t^\gamma} \approx \mathcal{L}_{\Delta t}^\gamma \tilde{u}(\boldsymbol{x}, t):=\frac{1}{\Gamma(2-\gamma)(\Delta t)^\gamma}\left\{-c_{\lceil\lambda t\rceil-1} \tilde{u}(\boldsymbol{x}, 0)+c_0 \tilde{u}(\boldsymbol{x}, t)\right. & \\ & \left.+\sum_{k=1}^{\lceil\lambda t\rceil-1}\left(c_{\lceil\lambda t\rceil-k}-c_{\lceil\lambda t\rceil-k-1}\right) \tilde{u}(\boldsymbol{x}, k \Delta t)\right\}\end{aligned}$
Where in the code is this part implemented?
