### ISSUE TITLE
Eigen_value_problem

### ISSUE THREAD

**Issue by amultab** [lululxvi/deepxde#237]
If I have an eigenvalue problem for differential operators, How can I predict Eigenvalue and eigenfunction where I have been given ground truth eigen pair.

**Comment by lululxvi** [comment]
It is doable. Someone gave a talk on this some time ago, but I don't remember the details, and cannot find the paper

**Comment by EmirChacra** [comment]
I think this is the one.

https://arxiv.org/abs/2010.05075

**Comment by amultab** [comment]
Thank you , I will check it)))
