### ISSUE TITLE
Error Plot for PINN vs DEEPXDE in Poisson_Lshape

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#238]
Dear Dr. Lu Sir, 
I have gone through the  [Reserach Paper](https://epubs.siam.org/doi/10.1137/19M1274067) 
Where the 4.1 Poisson L-shaped problem domain is solved PINN with SEM method.

Also, error plot has depicted there.

Please comment on the error plot for two different solutions. 
How can we get the error plot?

Thanks

https://github.com/lululxvi/deepxde/blob/master/examples/Poisson_Lshape.py

**Comment by lululxvi** [comment]
You need a separate SEM code.

**Comment by SanjuSoni** [comment]
Thanks for your suggestion.

What is SEM Code?

Any Github sample code would be helpful for me.

**Comment by lululxvi** [comment]
It is spectral element.
