### ISSUE TITLE
Tensorflow 2 support

### ISSUE THREAD

**Issue by deepgradient** [lululxvi/deepxde#24]
Hi,
I sm wondering whether you have any plan to support TF2 for the deepxde?

As you know, there would be no maintenance of TF1 in the near future.

**Comment by lululxvi** [comment]
Yes, I will. Hopefully in the next couple of months.

**Comment by deepgradient** [comment]
Thanks for consideration.

**Comment by lululxvi** [comment]
TF2 is being supported.

**Comment by deepgradient** [comment]
> TF2 is being supported.

Thanks a lot...
