### ISSUE TITLE
Inverse problems with unmeasured (hidden) variables 

### ISSUE THREAD

**Issue by rohitsupekar** [lululxvi/deepxde#242]
Hello, thanks for a great package! 
Does deepxde have the functionality to solve inverse problems involving multiple fields, with data available only for one of them (for example, [hidden fluid mechanics](https://science.sciencemag.org/content/367/6481/1026))?

**Comment by lululxvi** [comment]
Yes, sure. It is very flexible.

**Comment by rohitsupekar** [comment]
@lululxvi Thanks! If possible, could you point me to an example that does this, or something similar?

**Comment by lululxvi** [comment]
- Check Lorenz_inverse.py in the examples. You can just remove `observe_y2`, and the code stills works.
- You can also check examples in this paper https://doi.org/10.1371/journal.pcbi.1007575 with the code there.
