### ISSUE TITLE
Hollow Cylinder 

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#245]
Dear @lululxvi 
if we have a hollow cylinder (one dimensional)-**(an Annulus)** and the derivatives of u (displacement) and T(temperature) with respect to r(radial distance) and t(time), how can we define the geometry? 
I used the following code: 
```
circle1 = dde.geometry.Disk(0, 1.0)
    circle2=dde.geometry.Disk(0, 1.5)
    hollowcylinder=dde.geometry.CSGDifference(circle2, circle1)
    timedomain = dde.geometry.TimeDomain(0,0.5)
    geomtime = dde.geometry.GeometryXTime(hollowcylinder, timedomain)
 
def boundary_rin (x, on_boundary):
        return on_boundary and circle1.on_boundary(x[0])
  
    def boundary_rout (x, on_boundary):
        return on_boundary and circle2.on_boundary(x[0]) 
```
but when I want to define the layer size I have to write layer_size = [3] + [64] * 5 + [2], otherwise it will end in error. but the fact is that there are r and t as inputs. the syntax of the above results in inf values 

thank you

**Comment by lululxvi** [comment]
You can use `Interval` for 1d domain.
