### ISSUE TITLE
Question about auxiliary_var_function with multiple coefficients needed

### ISSUE THREAD

**Issue by Enowyz** [lululxvi/deepxde#246]
Hi, @lululxvi 

In the previous version, deepxde 9.0, I used **pde(x, u, X_np)** with the interpolation function **sol_c(X_np)** and **sol_r(X_np)** to generate my parameters inside my pde function.
```python
def sol_c(x):
    ...
    spline = sp.interpolate.Rbf(S[:, 0], S[:, 1], F, function='thin_plate', smooth=0, episilon=0)
    return spline(x[:, 0:1],x[:, 1:2])

def sol_r(x):
    ...
    spline = sp.interpolate.Rbf(S[:, 0], S[:, 1], F, function='thin_plate', smooth=0, episilon=0)
    return spline(x[:, 0:1],x[:, 1:2])

def pde(x, u, X_np): 
    ...
    cc = sol_c(X_np)
    rhor = sol_r(X_np)  
    ...

```
I currently upgrade to version 10.0 and the previous functions need to be modified by **auxiliary_var_function**.
From what I learned: I need to first define **a function A** as my previous parameter X_np, and pass A into auxiliary_var_function like this:

```python
data = dde.data.TimePDE( 
    ...
    auxiliary_var_function = A
)
```

So, in my case, the function A is going to be treated as **sol_c and sol_r**: (is it correct?)

```python
data = dde.data.TimePDE( 
    ...
    auxiliary_var_function = sol_c, sol_r
)
```

Therefore, what I should write at here? (my x_np should be sol_c and sol_r?):

**def pde(x, u,  ???? )**    
-----------------------------------------------------------------------------------------

If my above understanding is correct, I need to modify my code "auxiliary_var_function =" adding functions similar as my previous X_np's coefficients in the last version deepxde 9.0,  which I don't know how to define them.

Generally speaking, I need to replace my former **sol_c(X_np) and sol_r(X_np)** (multiple coefficients) with new updated **auxiliary_var_function** . But auxiliary_var_function transmits a pre-defined function into my pde function's third input, I don't know how to define it without influence my sol_c(X_np) and sol_r(X_np).

Looking forward to your response. Thanks.

**Comment by smao-astro** [comment]
Hi @Enowyz ,

From my understanding, you can define `auxiliary_var_fn` as a function whose inputs are `x` and outputs are an array  (N * M one column per auxiliary variable) of the auxiliary variables (assume you need M auxiliary variables), and then modify your `pde` function so that the third arguments accept these auxiliary variables.

Assuming your function `sol_c` and `sol_r` both return (N*1) ndarray, you can define `auxiliary_var_function` as

```python
def auxiliary_var_function(x):
    return np.hstack([sol_c(x), sol_r(x)])
```

and
```python
data = dde.data.TimePDE( 
    ...
    auxiliary_var_function = auxiliary_var_function
)
```
and
```python
def pde(x, u, auxiliary_vars): 
    ...
    cc = auxiliary_vars[:, 0:1]
    rhor = auxiliary_vars[:, 1:2]
    ...
```

Hopes this help.

**Comment by engsbk** [comment]
Hello everyone!

I just want to understand this post better.

1- Are you solving the forward or inverse problem?
2- What is the formula of the equation you are trying to solve?
3- If my equation is the 2D wave equation with a time-dependent source term `S`. i.e:
`du_tt - (c ** 2)*(du_xx + du_yy) - S`
How can I write/use the functions: `TimePDE`, `auxiliary_var_function`, `pde`?

This is important for me to understand. I really hope that I'm not using DeepXDE in the wrong way when it comes to source terms.
