### ISSUE TITLE
Question about model.predict

### ISSUE THREAD

**Issue by Hochinghao** [lululxvi/deepxde#248]
can i use another initial point to predict the result from a trained-model?

**Comment by JakobEliasWagner** [comment]
predict generates an output prediction for the input samples you provided. The values you pass into that functions can be anything you like. They can be inside or outside of your  training-set. So as long as you pass the right format you should be fine. You can look up the documentation here [https://deepxde.readthedocs.io/en/latest/modules/deepxde.html?highlight=predict#deepxde.Model.predict](documentation predict (deepxde)) or on the tensorflow page with a bigger description [https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict](documentation predict).

**Comment by Hochinghao** [comment]
> predict generates an output prediction for the input samples you provided. The values you pass into that functions can be anything you like. They can be inside or outside of your training-set. So as long as you pass the right format you should be fine. You can look up the documentation here [documentation predict (deepxde)](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html?highlight=predict#deepxde.Model.predict) or on the tensorflow page with a bigger description [documentation on tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict).

**Comment by Hochinghao** [comment]
> predict generates an output prediction for the input samples you provided. The values you pass into that functions can be anything you like. They can be inside or outside of your training-set. So as long as you pass the right format you should be fine. You can look up the documentation here [documentation predict (deepxde)](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html?highlight=predict#deepxde.Model.predict) or on the tensorflow page with a bigger description [documentation on tensorflow](https://www.tensorflow.org/api_docs/python/tf/keras/Model#predict).

but it seen to just can give different time but can't give another initial point

**Comment by lululxvi** [comment]
What do you mean by "time" and "initial point"?

**Comment by Hochinghao** [comment]
I mean for example i train the model by initial point [8,-2,27] and time
from 0 to 8. And I wanna predict the value use another initial point
[3,-5,9] and time from 0 to 8.

**Comment by lululxvi** [comment]
No, you cannot do that. Different IC means different PDEs.
