### ISSUE TITLE
question about time fractional pde

### ISSUE THREAD

**Issue by songjhaha** [lululxvi/deepxde#256]
Hi, Lulu:
Could deepxde solve the  time fractional pde with time-fractional derivative like:
<a href="https://www.codecogs.com/eqnedit.php?latex=\partial^\gamma_t&space;u(x,t)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\partial^\gamma_t&space;u(x,t)" title="\partial^\gamma_t u(x,t)" /></a>
in the example code I could only find the fractional pde with space-fractional derivative.
Thank you very much!

**Comment by lululxvi** [comment]
No, it is not in DeepXDE yet. Check the paper https://doi.org/10.1137/18M1229845 on how to solve it. It is quite similar to space fractional.

**Comment by songjhaha** [comment]
thank you ! I will try.
