### ISSUE TITLE
A few queries about the capabilities of DeepXDE

### ISSUE THREAD

**Issue by tnnandi** [lululxvi/deepxde#262]
Thanks for the excellent contribution to the scientific community. I'd appreciate it if you can clarify a few questions I have regarding this framework:

1. One of the major advantages of such frameworks over conventional CFD is the ability to do a parameterized study over multiple inputs/physical parameters/geometries with a single run. Has this tool been tried for such a parametric study? If not, is it relatively easy to extend the present framework to add this capability for forward runs?

2. Has the performance of this tool compared with conventional CFD solvers for industrial scale problems (say, with > 10 million training points)? 

3. Can this tool use multiple GPUs (intra- and inter-node) to handle large problems? On the same note, is there any scaling study available that can tell how large a problem can the framework handle efficiently and the corresponding number of GPUs required?

**Comment by lululxvi** [comment]
1. Not really. My research focus is not on this, and thus DeepXDE has not been used for this. But it can be directly used in some parametric study, or can be easily extended.
2. No. I don't work on large scale real engineering problems, but ideally this definitely can be done.
3. This is a software engineering question. DeepXDE uses TensorFlow: if TensorFlow supports, then DeepXDE supports.
