### ISSUE TITLE
deepxde.model.Model._test calculate metrics

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#265]
Hi Lu,

I can not understand how this part of code works:
https://github.com/lululxvi/deepxde/blob/3cd2d5555b05d059594f84c9885a4496e4816e39/deepxde/model.py#L316-L326
Here I am working with a forward PDEs problem with outputs (y1,y2,y3), my `dde.data.TimePDE`'s `soln` is a function that return (N, 3) array, so my `self.net.targets` is Tensor with `(?, 3)` other than a list/tuple, and the execution skip to `else`, and I get a single value of metrics.

I do not know the meaning of the single value, I am expecting to get a (3,) array for the error of the three outputs, could you tell me how to do so?

Thanks.

**Comment by lululxvi** [comment]
By definition, a metric is a value to measure the different between y_true and y_pred, no matter what the shape of y_pred is. You need to implement new metrics to compute the error for each component of y.

**Comment by smao-astro** [comment]
I see, thanks.
