### ISSUE TITLE
Simple RC circuit problem

### ISSUE THREAD

**Issue by tanielfranklin** [lululxvi/deepxde#267]
Hi everybody ,

I decided to start using a very simple problem in order to solve a first order EDO but I don't know where is the mistake.
I can't understand why the following code model.compile line return  
"ValueError: None values not supported."

import deepxde as dde
R=1.0;
C=2.0;
V0=5;
# SEDO
def ode_system(v,t):
    #dv(t)/dt+1/RC*v(t)=0
    dv = dde.grad.jacobian(v,t,i=0);
    return dv+v/R/C;
    
def boundary(_, on_initial):
    return on_initial;
def func(v):
    # y=v(t)
    return v;
    
geom = dde.geometry.TimeDomain(0, 10)
Ic=dde.IC(geom, lambda X: V0, boundary)
data = dde.data.PDE(geom, ode_system, Ic, 15, 2, solution=func, num_test=100)

layer_size = [1] + [40] * 3 + [1];
activation = "tanh";
initializer = "Glorot uniform";
net = dde.maps.FNN(layer_size, activation, initializer);
model = dde.Model(data, net);
#####################################
#optimizer – String. Name of optimizer.
#lr – A Tensor or a floating point value. The learning rate.
model.compile("adam",lr=0.001);
losshistory, train_state = model.train(epochs=10000)
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

**Comment by xy1015874723** [comment]
i think that you should use 
data = dde.data.PDE(geomtime, ode_system, Ic, 15, 2, solution=func, num_test=100)

**Comment by tanielfranklin** [comment]
I add an interval to y and t generating  a geomtime geometry and I also changed the model to TimePDE but the error keeps the same.


import deepxde as dde
import numpy as np

R=1.0;
C=2.0;
V0=5;

def ode_system(y,x):
    #dv/dt+1/RC*v(t)=0
    #x=t
    #y=v
    y1 = y[:,0:1];
    dy1 = dde.grad.jacobian(y,x,i=0);
    return dy1+y1/R/C;
    
def boundary(_, on_initial):
    return on_initial;
def func(x):
    # x=v(t)
    return V0*np.exp(-x/(R*C));

def boundary_v(x, on_boundary):
    return on_boundary and np.isclose(x, 5.1)

geom = dde.geometry.Interval(0, 5) #interval of y   
timedomain = dde.geometry.TimeDomain(0, 10) # interval of t
geomtime = dde.geometry.GeometryXTime(geom,timedomain)

Ic=dde.IC(geomtime, lambda X: V0, boundary)
#data = dde.data.PDE(geom, ode_system, Ic, 15, 2, solution=func, num_test=100)
data = dde.data.TimePDE(geomtime, ode_system, Ic, 15, 2, solution=func, num_test=100)


layer_size = [1] + [40] * 3 + [1];
activation = "tanh";
initializer = "Glorot uniform";
net = dde.maps.FNN(layer_size, activation, initializer);
model = dde.Model(data, net);
#####################################
#optimizer – String. Name of optimizer.
#lr – A Tensor or a floating point value. The learning rate.
model.compile("adam",lr=0.001,metrics=["l2 relative error"]);

**Comment by lululxvi** [comment]
Your problem seems an ODE problem. There are several ODE examples and also FAQ that you can check. BTW, your code format is hard to read.

**Comment by tanielfranklin** [comment]
Thank you Lu. I don't think so it be an EDO problem. It is a first order EDO whose solution is very easy and has only one initial condition (described by the func()). Now I could put  the code correctly. Unfortunately I can't found what is wrong in my code. I checked your ODEs examples deeply to write mine.

`import deepxde as dde
import numpy as np
from deepxde.backend import tf

R=1.0;
C=2.0;
V0=5;
def main():

    def ode_system(y,x):
        y1 = y[:,0:1];
        dy1 = dde.grad.jacobian(y,x,i=0);
        return (dy1+y1/R/C);
        
    def boundary(_, on_initial):
        return on_initial;
    def func(x):
        # x=v(t)
        return V0*np.exp(-x/(R*C));
    
    
    timedomain = dde.geometry.TimeDomain(0, 10) # interval of t
    Ic=dde.IC(timedomain, func, boundary,component=0)
    data = dde.data.PDE(timedomain,
                        ode_system,
                        Ic, 
                        num_domain=15,
                        num_boundary=2,
                        solution=func,
                        num_test=100)

    layer_size = [1] + [40] * 3 + [1];
    activation = "tanh";
    initializer = "Glorot uniform";
    net = dde.maps.FNN(layer_size, activation, initializer);
    model = dde.Model(data, net);
    print('compilando ...')
    model.compile("adam",lr=0.001,metrics=["l2 relative error"]);

if __name__ == "__main__":
    main()
`

**Comment by lululxvi** [comment]
Could you first try the time from 0 to 1?

**Comment by tanielfranklin** [comment]
> Could you first try the time from 0 to 1

Yes, but it didn't change

**Comment by tanielfranklin** [comment]
I found the problem. 
wrong:
def ode_system(y,x):
Correct:
def ode_system(x,y):
