### ISSUE TITLE
How to visualize my results?

### ISSUE THREAD

**Issue by supersuxy** [lululxvi/deepxde#276]
Hi , doctor lu. DeepXDE is really wonderful, and I have used it training my model. Here is my training results.
![image](https://user-images.githubusercontent.com/82855270/115332689-e5744480-a1ca-11eb-8c9e-7bf04ba30399.png)
The result is quite exact, but how can I visualize my results like this one in your paper.
![image](https://user-images.githubusercontent.com/82855270/115332719-fa50d800-a1ca-11eb-9b2a-cf052c875183.png)
I have read the FAQ, but I am still a little confused that how to plot the results all in the domain through a few points.
Could you please answer my question?
Thanks

**Comment by troyrock** [comment]
There is a partial answer in [#17 ](https://github.com/lululxvi/deepxde/issues/17):

The Fig. 7 was plotted in Matlab by importing test.dat. I will try to provide a Python script.

In test.dat, the first column is x coordinate, the second column is y coordinate, the 3rd column is y_true (but here we don't have y_true, and thus is set as 0), the 4th column is y_pred.

Here is a quick and dirty way to implement something like the above for square domains (which yours appears to be):
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp2d

data = np.genfromtxt("test.dat", delimiter=' ')
f = interp2d(data[:,0], data[:,1], data[:,3], kind="linear")
x_coords = np.arange(min(data[:,0]), max(data[:,0]))
y_coords = np.arange(min(data[:,1]), max(data[:,1]))
z_coords = f(x_coords, y_coords)
plt.imshow(z_coords, extent=[min(data[:,0]), max(data[:,0]), min(data[:,1]), max(data[:,2])])
plt.show()
```

**Comment by supersuxy** [comment]
@troyrock That's what I need, and I will try it. Thanks a lot

**Comment by xy1015874723** [comment]
@troyrock 
Hello, I have tried it, and I got the result.
![image](https://user-images.githubusercontent.com/73056004/115960594-ded82b00-a544-11eb-8ba7-ec6930167dab.png)
![image](https://user-images.githubusercontent.com/73056004/115960623-0e873300-a545-11eb-9492-16090404c5cc.png)
It seems strange, could you give me some advice?
Here is my code which contains x,t,y_pred 3 columns.
![image](https://user-images.githubusercontent.com/73056004/115960749-bbfa4680-a545-11eb-97c5-3c6e89ab8ddd.png)
![image](https://user-images.githubusercontent.com/73056004/115960753-c3b9eb00-a545-11eb-9f91-c8eb87bec49d.png)
Thanks

**Comment by troyrock** [comment]
Sorry, I didn't actually try it (shame on me).  Here is working code:

```
import numpy as np
from matplotlib import pyplot

data = np.genfromtxt("test.dat", delimiter=' ')
x = data[:, 0]
y = data[:, 1]
z = data[:, 3]

fig, ax = pyplot.subplots(nrows=1)
ax.tricontour(x, y, z, levels=14, linewidths=0.5, colors='k')
cntr = ax.tricontourf(x, y, z, levels=14, cmap="RdBu_r")

fig.colorbar(cntr, ax=ax)
ax.plot(x, y, 'k.', ms=3)
pyplot.show()

```

**Comment by xy1015874723** [comment]
@troyrock Nice! It works. Thank you for your selfless help.

**Comment by smurf-17** [comment]
@troyrock Sir I tried the above code for plotting my results, Its of flow over a circular cylinder but I am not getting the result
![Screenshot (616)](https://user-images.githubusercontent.com/85953463/125844258-9c7e3c57-06e5-4b87-bd58-14b2d9a7458d.png)
I am getting something like this.

**Comment by Mouhamedsaw** [comment]
Hi dear All,
@troyrock Please I want to learn how to plot the solution in 3D (i.e., x, y, z).

I tried :

` import numpy as np
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D

data = np.genfromtxt("test.dat", delimiter=' ')
x = data[:, 0]
y = data[:, 1]
z = data[:, 3]

X, Y = np.meshgrid(x, t)
Xgrid = np.vstack([X.flatten(),Y.flatten()]).T

# Determine predictions of z(t, x)
y = model.predict(Xgrid)   

# Reshape upred
U = y.reshape(len(x), len(y))

# Surface plot of solution z(t,x)
fig = plt.figure(figsize=(9,6))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X, Y, z, cmap='RdBu_r');        #cmap = 'RdBu_r'       viridis
ax.view_init(35,35)
ax.set_xlabel('$t$')
ax.set_ylabel('$x$')
ax.set_zlabel('Moisture')
ax.set_title('Numerical Solution');
  `

Thank you for your time and your patience.
