### ISSUE TITLE
DeepOnets, Physics informed DeepOnets and Fourier features/networks

### ISSUE THREAD

**Issue by alokwarey** [lululxvi/deepxde#277]
o Any plans to include examples of DeepOnets and physics informed DeepOnets? 
o Some researchers have shown that appropriate coordinate embeddings can help a neural network to efﬁciently learn high-
frequency or multi-scale functions, boundary layers, etc. (Fourier features and Fourier networks). Any plans to include this capability in DeepXDE?

**Comment by schelian** [comment]
I too am interested in trying DeepONet.  I see the files are bionet.py & mfonet.py in a recent commit.  However I'm not sure how to call these modules to implement the examples given in the paper.

Please let us know how to implement the examples :)

@chrisdegrendele

**Comment by lululxvi** [comment]
- The DeepONet examples are at https://github.com/lululxvi/deeponet
- I will implement physics-informed DeepOnets when I have time.
- DeepXDE already supports embedding appropriate coordinate/transformations by using `net.apply_feature_transform()`. Here are some examples you can check
    - https://github.com/lululxvi/deepxde/blob/master/examples/Laplace_disk.py
    - https://github.com/alirezayazdani1/SBINNs

**Comment by alokwarey** [comment]
Thanks! Appreciate it!
