### ISSUE TITLE
TypeError: 'function' object is not scriptable

### ISSUE THREAD

**Issue by troyrock** [lululxvi/deepxde#278]
I am getting "TypeError: 'function' object is not subscriptable" after the model.compile line.  I have included the error first and then my code follows.  Thank you very much for any assistance.

> Using TensorFlow 2 backend.
> 
> WARNING:tensorflow:From /home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Warning: 1500 points required, but 1728 points sampled.
> Compiling model...
> Building feed-forward neural network...
> /home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/keras/legacy_tf_layers/core.py:171: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
>   warnings.warn('`tf.layers.dense` is deprecated and '
> /home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1719: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
>   warnings.warn('`layer.apply` is deprecated and '
> 'build' took 0.041853 s
> 
> 2021-04-21 18:13:54.097581: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-04-21 18:13:54.098368: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
> Traceback (most recent call last):
>   File "poisson3d.py", line 161, in <module>
>     main()
>   File "poisson3d.py", line 151, in main
>     model.compile("adam", lr=0.001)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/deepxde/utils.py", line 52, in wrapper
>     result = f(*args, **kwargs)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/deepxde/model.py", line 87, in compile
>     self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/deepxde/data/pde.py", line 140, in losses
>     return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
>     return target(*args, **kwargs)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 538, in new_func
>     return func(*args, **kwargs)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1230, in cond
>     orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1066, in BuildCondBranch
>     original_result = fn()
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/deepxde/data/pde.py", line 125, in losses_train
>     error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)
>   File "/home/troyrock/anaconda3/envs/deepxde/lib/python3.9/site-packages/deepxde/boundary_conditions.py", line 137, in error
>     return self.func(inputs, outputs, X)[beg:end]
> TypeError: 'function' object is not subscriptable
> 

```
  from __future__ import absolute_import
  from __future__ import division
  from __future__ import print_function
  
  import numpy as np
  import deepxde as dde
  from deepxde.backend import tf
  
  # geometry variables
  ldotx = -45
  ldoty = 0
  ldotr = 50
  
  rect_width = 30
  rect_height = 200
  
  rdotx = 45
  rdoty = 0
  rdotr = 50
  
  bottom_z = -200
  top_z = 200
  left_x = -200
  right_x = 200
  back_y = -200
  front_y = 200
  sheet_z = 200 - 40  # sheet of charge 40 nm from the top
  quantum_top = 200 - 134.3  # z coordinate for the top of the quantum layer
  quantum_bottom = 200 - 156.8  # z coordinate for the bottom of the quantum layer
  lower_left_corner = [left_x, back_y, bottom_z]
  upper_right_corner = [right_x, front_y, top_z]
  
  # material variables
  sigma0 = 0.0036
  epsilon_above = 0.769
  epsilon_quantum = 0.697
  epsilon_below = 0.769
  
  # boundary voltages
  vl = -0.2
  vr = -0.2
  vm = 1

def main():
      def boundary(_, on_boundary):
          return on_boundary
  
      def boundary_t_b(x, on_boundary):
          return on_boundary and np.isclose(abs(x[2]), upper_right_corner[2])
  
      def top_bottom_boundary_condition(x):
          # Top and bottom boundary conditions are Dirchlet
          result = []
          for coords in x:
              if coords[2] == 200:
                  # left circle
                  if (coords[0]-ldotx)**2 + (coords[1] - ldoty)**2 < ldotr**2:
                      # result.append(net.inputs[3])
                      result.append(vl)
  
                  # right circle
                  elif (coords[0]-rdotx)**2 + (coords[1] - rdoty)**2 < rdotr**2:
                      # result.append(net.inputs[4])
                      result.append(vr)
  
                  # middle rectangle
                  elif coords[0] < rect_width/2.0 and coords[1] < rect_height/2.0:
                      # result.append(net.inputs[5])
                      result.append(vm)
  
                  else:
                      result.append(0)  # zero everywhere except on the electrodes.
  
              else:
                  result.append(0)  # zero at the bottom
  
              return np.array(result, ndmin=2).transpose()
  
     def boundary_side(x, on_boundary):
          return on_boundary and not np.isclose(abs(x[2]), upper_right_corner[2])
  
      above_sheet = dde.geometry.Cuboid(xmin=[left_x, back_y, sheet_z],
                                        xmax=upper_right_corner)
      between = dde.geometry.Cuboid(xmin=[left_x, back_y, quantum_top],
                                    xmax=[right_x, front_y, sheet_z])
      quantum = dde.geometry.Cuboid(xmin=[left_x, back_y, quantum_bottom],
                                    xmax=[right_x, front_y, quantum_top])
      below = dde.geometry.Cuboid(xmin=lower_left_corner,
                                  xmax=[right_x, front_y, quantum_bottom])
  
      def boundary_above_sheet(x, on_boundary):
          # above sheet of charge 40 nm down from the top
          return on_boundary and above_sheet.inside(x)
  
      def boundary_between_sheet_and_quantum_layer(x, on_boundary):
          return on_boundary and between.inside(x)
  
      def boundary_in_quantum_layer(x, on_boundary):
          return on_boundary and quantum.inside(x)
  
      def boundary_below_quantum_layer(x, on_boundary):
          return on_boundary and below.inside(x)
  
      def pde_above(x, y):
          dy_xx = dde.grad.hessian(y, x, i=0, j=0)
          dy_yy = dde.grad.hessian(y, x, i=1, j=1)
          dz_zz = dde.grad.hessian(y, x, i=2, j=2)
          return epsilon_above*(dy_xx + dy_yy + dz_zz) - sigma0*x[:, 2:3]
  
      def pde_between(x, y):
          dy_xx = dde.grad.hessian(y, x, i=0, j=0)
          dy_yy = dde.grad.hessian(y, x, i=1, j=1)
          dz_zz = dde.grad.hessian(y, x, i=2, j=2)
          return epsilon_above*(dy_xx + dy_yy + dz_zz) - sigma0*sheet_z
  
      def pde_quantum(x, y):
          dy_xx = dde.grad.hessian(y, x, i=0, j=0)
          dy_yy = dde.grad.hessian(y, x, i=1, j=1)
          dz_zz = dde.grad.hessian(y, x, i=2, j=2)
          return epsilon_quantum*(dy_xx + dy_yy + dz_zz) - sigma0*sheet_z
  
      def pde_below(x, y):
          dy_xx = dde.grad.hessian(y, x, i=0, j=0)
          dy_yy = dde.grad.hessian(y, x, i=1, j=1)
          dz_zz = dde.grad.hessian(y, x, i=2, j=2)
          return epsilon_below*(dy_xx + dy_yy + dz_zz) - sigma0*sheet_z

      geom = dde.geometry.Cuboid(xmin=lower_left_corner, xmax=upper_right_corner)
      bc_top_bottom = dde.DirichletBC(geom, top_bottom_boundary_condition, boundary_t_b)
      bc_side = dde.PeriodicBC(geom, 0, boundary_side)
      condition_above = dde.OperatorBC(geom, lambda x, y, _: pde_above, boundary_above_sheet)
      condition_between = dde.OperatorBC(geom, lambda x, y, _: pde_between, boundary_between_sheet_and_qu  antum_layer)
      condition_quantum = dde.OperatorBC(geom, lambda x, y, _: pde_quantum, boundary_in_quantum_layer)
      condition_below = dde.OperatorBC(geom, lambda x, y, _: pde_below, boundary_below_quantum_layer)
      data = dde.data.PDE(geom,
                          None,
                          [bc_top_bottom,
                           bc_side,
                           condition_above,
                           condition_between,
                           condition_quantum,
                           condition_below],
                          num_domain=1200,
                          num_boundary=120,
                          num_test=1500)
  
      net = dde.maps.FNN([3] + [50] * 4 + [1], "tanh", "Glorot uniform")
      model = dde.Model(data, net)
  
      model.compile("adam", lr=0.001)
      model.train(epochs=50000, model_save_path="project_model")
      model.compile("L-BFGS-B")
      losshistory, train_state = model.train()
      dde.saveplot(losshistory, train_state, issave=True, isplot=True)
      model._print_model()
  
  
  if __name__ == "__main__":
      main()

````

**Comment by lululxvi** [comment]
Which version of DeepXDE are you using? The error could be due to `inside(x)`. Could you first remove all the BCs using `inside` to see whether the error still exists?

**Comment by alecjervis1** [comment]
Hello, I am receiving the same error with use of .inside(x) and was wondering if you had any joy solving this issue or whether you have any suggestions for alternate methods to achieve the same outcome as .inside(x)?

**Comment by lululxvi** [comment]
Because `inside` takes a 2d numpy array, so change
```python
a.inside(x)
```
to
```
a.inside(np.array([x]))[0]
```
