### ISSUE TITLE
Precision in deepxde

### ISSUE THREAD

**Issue by tangqi** [lululxvi/deepxde#28]
There is a config.py set `real=Real(32)`. Is it true the default precision in deepxde is single precision? If I want to switch to double precision to 64 globally, then I will just do `real=Real(64)`?

**Comment by lululxvi** [comment]
Yes, by default, it is single precision. To switch to double precision, call
```
dde.config.real.set_float64()
```

**Comment by tangqi** [comment]
OK, thank. This is good to know

**Comment by tangqi** [comment]
Looks like float64 is not working any more. It complains:
```
  File "/Users/qtang/anaconda3/envs/tf/lib/python3.6/site-packages/deepxde/data/pde.py", line 69, in losses
    return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)
...
in cond
    (val_x.dtype.name, val_y.dtype.name))
ValueError: Outputs of true_fn and false_fn must have the same type: float32, float64
```
I tried to fix but did not succeed.

**Comment by lululxvi** [comment]
I have fixed it. If you are interested, see my commit.

**Comment by tangqi** [comment]
Thanks! Appreciate your quick fix.

**Comment by tangqi** [comment]
Can you do us a favor? Can you increase your deepxde version (0.5.2) to include those fix, so that other users can use it when installing through conda? 

Thanks!

**Comment by lululxvi** [comment]
The new version 0.6.0 is released. Note that the API of `PDE` is changed. Check the examples.

**Comment by tangqi** [comment]
Thanks!

**Comment by lululxvi** [comment]
For DeepXDE > v0.13.0, use [`set_default_float`](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.config.set_default_float)
