### ISSUE TITLE
Generalization of the network

### ISSUE THREAD

**Issue by Mengting009** [lululxvi/deepxde#282]
Hi Lu,

Thank you for sharing the library. 

It seems that a trained network can only be used to predict the results of the same geometry with the same boundary condition and initial condition. Once any of the above-mentioned conditions is changed, the network has to be trained again for new predictions. I am wondering is there a possibility to generalize the approach such that once the network is trained, it can be used for predictions with different initial and boundary conditions? Thank you!

**Comment by lululxvi** [comment]
Yes, PINN is for specific IC/BC. If you want to train a network for different IC/BC, you can use these IC/BC as an extra network input, and train the network for different IC/BC. Another way is to use DeepONet, see https://doi.org/10.1038/s42256-021-00302-5

**Comment by alokwarey** [comment]
@lululxvi: Is there an example on how to setup a problem for different IC/BC using PINNs with deepxde?

**Comment by lululxvi** [comment]
No good examples yet, but see #273
