### ISSUE TITLE
hard boundary 

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#285]
I want to convert the boundary to a hard constraint. My boundary and initial conditions are as follows:
u(0,t)=e^(-2t); left boundary
u(1,t)=e^(-3t); right boundary
u(x,0)=1;
I checked the questions 36, 90, 92, and I set the code:
`net.apply_output_transform(lambda x, y: (tf.exp(-3*x[:, 1:2]) - tf.exp(-2*x[:, 1:2]))*x[:, 0:1] + tf.exp(-2*x[:, 1:2]) + x[:, 0:1]*(x[:, 0:1]-1)*y*x[:, 1:2])`
The following is the result of my calculation. Figure 1 is the soft constraint, and Figure 2 is the calculation result of adding code. This does not seem to change. Why is this?
![image](https://user-images.githubusercontent.com/52651366/117630627-fa326f80-b1ad-11eb-95e1-1b92f4d644d7.png)
![image](https://user-images.githubusercontent.com/52651366/117630665-01597d80-b1ae-11eb-9c81-1642a850c597.png)

**Comment by lululxvi** [comment]
Using hard constraints doesn't mean you will get a perfect answer. It is a possible way to improve the result, not a "silver bullet".

**Comment by 979736316** [comment]
> Using hard constraints doesn't mean you will get a perfect answer. It is a possible way to improve the result, not a "silver bullet".

Thank you for your reply, is my hard constraint conversion correct?

**Comment by lululxvi** [comment]
(tf.exp(-3*x[:, 1:2]) - tf.exp(-2*x[:, 1:2]))*x[:, 0:1] + tf.exp(-2*x[:, 1:2]) + x[:, 0:1]*(x[:, 0:1]-1)*y*x[:, 1:2])
--> (exp(-3t) - exp(-2t)) * x + exp(-2t) + x*(x-1)*t*y
is OK.
