### ISSUE TITLE
Complex partial differential equations

### ISSUE THREAD

**Issue by chaibaoqiang** [lululxvi/deepxde#287]
hi, lulu! I learn your project and study your paper, great job! I have a  complex PDE in my photo , how can I expresstion the ped and BC and IC by deepxde.  
![IMG_4048](https://user-images.githubusercontent.com/44567442/117900624-22c87f80-b2fc-11eb-8f83-3d2a36b07696.JPG)

**Comment by lululxvi** [comment]
Read:
- https://deepxde.readthedocs.io
- https://github.com/lululxvi/deepxde/tree/master/examples
