### ISSUE TITLE
complex bc and ic

### ISSUE THREAD

**Issue by chaibaoqiang** [lululxvi/deepxde#289]
![IMG_4062](https://user-images.githubusercontent.com/44567442/118355631-90e2a000-b5a3-11eb-890e-142ae667b552.jpg)
 i am puzzled by this question can help me, thanks!

**Comment by lululxvi** [comment]
- If you only know u1 and u2 on some locations, use PointSetBC https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.PointSetBC and #264 
- They are Dirichlent and Neumann BCs.

**Comment by chaibaoqiang** [comment]
> * If you only know u1 and u2 on some locations, use PointSetBC https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.PointSetBC and #264
> * They are Dirichlent and Neumann BCs.

@lululxvi Thank you for your reply, it's useful for me. In fact, u1 and u2 are not PointSetBc. In mathematic, they are given abstract functions with no concrete expressions(and do not know any locations). I will continue to study how to deal with this problem. If there are any results, I will share them here for the first time.
