### ISSUE TITLE
Issues with func

### ISSUE THREAD

**Issue by circularsquare** [lululxvi/deepxde#29]
Hi,

I'm having trouble using func() when trying to use DeepXDE for a reverse problem.
I have this line: `data = dde.data.PDE(geom, 3, odes, [ic1, ic2, ic3, observe_y0, observe_y1, observe_y2], func=func, num_domain=400, num_boundary=2, anchors=observe_t)`

And if I leave "func=func" in it, I get this error: 
`return np.linalg.norm(y_true - y_pred) / np.linalg.norm(y_true)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float' `
which occurs upon calling model.train.

However, if I take out the "func=func", because I don't see what it would be used for in this case, I get the error 
`self.test_y = self.train_y[sum(self.num_bcs) :] if self.train_y else None
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
Which occurs on the line that defines `data`.

I see in another issue that func is only used to compute test metric, which I don't think I need. So I'd like to not use it.
Would you be able to help me resolve this?

**Comment by lululxvi** [comment]
Could you provide a simple code to reproduce to error?

**Comment by circularsquare** [comment]
Ah, sorry, I just figured it out, I hadn't removed the `metrics=["l2 relative error"]` from model.train. Thank you for the prompt response though!
