### ISSUE TITLE
Dimensionless: what should we do? 

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#290]
hello @lululxvi, 
when in a paper, they introduce dimensionless variables (for example they divide the "x" by characteristic length and so on ) and then they reach a system of coupled partial differential equations, should we do any extra step like feature or output transform in Deepxde?

**Comment by lululxvi** [comment]
You can directly solve the dimensionless PDEs

**Comment by katayooneshkofti** [comment]
@lululxvi  Thank you, and just one more question. 
when we have u and T as output and r and t as input, then for the following boundary condition, should I use OperatorBC or Robin? 
`du/dr (r=1.0 , t)+ 1/r * (1-C) * u(r=1.0 , t) - T (r=1.0 , t) =0 `

**Comment by lululxvi** [comment]
Robin is OK.

**Comment by katayooneshkofti** [comment]
@lululxvi  Thank you so much
