### ISSUE TITLE
'Tensor' object has no attribute 'ref'

### ISSUE THREAD

**Issue by alecjervis1** [lululxvi/deepxde#291]
Hello, 
When I try and run a file that uses 'dde.grad.hessian' I receive an error saying the following: 'Tensor' object has no attribute 'ref'. I am quite new to all of this and so it is probably quite a straight forward issue but any help would be more than welcome. 
Thanks in advance, 
Alec

**Comment by lululxvi** [comment]
Is your tf version >=2.2?

**Comment by alecjervis1** [comment]
Hello, thank you for your response - this was indeed the solution to the issue. 

I am trying to create a heat transfer model on a square geometry with: a constant temperature on one side and also a tube running through the centre removing heat at a constant rate. I am having further problems that I wondered if you could assist me with please; namely: 

- I am getting very large train losses on my boundary conditions (of positive orders of magnitude)
- If I use just "model.compile("adam"..  " I receive an error saying 'ValueError: No epochs for adam.' - I feel this might be linked to the first issue? 
- The plot often shows the function falling off in the corners of the domain (but often quite drastically in one corner)

![Screenshot 2021-05-25 at 17 28 38](https://user-images.githubusercontent.com/79330532/119534438-d01ca800-bd7e-11eb-843f-33a6be61806f.png)
![Screenshot 2021-05-25 at 17 29 08](https://user-images.githubusercontent.com/79330532/119534443-d1e66b80-bd7e-11eb-9880-59e137204eee.png)
![deepxdeplot](https://user-images.githubusercontent.com/79330532/119534459-d7dc4c80-bd7e-11eb-823d-ff16b8f0574d.png)


Again, thank you in advance for any responses! 

Also if anyone could point me in the direction of any good sources to gain a deeper understanding it would be very helpful!

Thank you, 
Alec

**Comment by lululxvi** [comment]
- Is `boundaryinner` correct? The center of the inner disk is (15, 15), right?
- Is this problem well defined if you only the temperature on one side?
- The scale of the problem is not good. See FAQ "Q: I failed to train the network or get the right solution, e.g., the training loss is large." about scaling

**Comment by DSJ414** [comment]
> 你的 tf 版本是否>=2.2？

我的tensorflow版本是1.15，deepxde版本是0.9.0，也碰到的这样的问题，应该怎么解决呢？
