### ISSUE TITLE
Uncertainty Quantification for Inverse Problems

### ISSUE THREAD

**Issue by azhu529** [lululxvi/deepxde#293]
Hi @lululxvi, thanks again for the package.

Does DeepXDE support uncertainty quantification for inferring parameters in an inverse problem? I know it supports UQ via MC  dropout for the forward problem, but is there a similar approach for inverse parameters?

For example, I am trying to solve some reaction-diffusion equations:
```
def pde(v, u):
    u_t = dde.grad.jacobian(u, v, i=0,j=3)
    u_xx = dde.grad.hessian(u, v, i=0, j=0)
    u_yy = dde.grad.hessian(u, v, i=1, j=1)
    u_zz = dde.grad.hessian(u, v, i=2, j=2)
    
    return [u_t -( D*(u_xx + u_yy + u_zz) + kf*u*(1-u))]
```
where the parameters I want to learn are D and kf. When I solve the inverse problem I get satisfactory results (compared to the known parameters) but I would also like to have some uncertainty bounds. From one of your papers, I saw something to this extent was done with stochastic PDEs, but is there something for non-stochastic PDEs as well?

Thanks!

**Comment by lululxvi** [comment]
Unfortunately not yet

**Comment by azhu529** [comment]
Hi @lululxvi,

I came across a paper on Bayesian PINNs (B-PINNs) [https://arxiv.org/abs/2003.06097] that seems quite helpful for this situation (I noticed G.E. Karniadakis, who I believe was part of the DeepXDE paper, was also part of this paper).

Do you think DeepXDE could be easily modified to implement B-PINNs? The paper only provides pseudo-code, but I think something building off of the existing DeepXDE architecture might be feasible.

Let me know what you think, thank you.

**Comment by lululxvi** [comment]
Yes, it should be doable. Basically you need to replace a standard network with Bayesian network, but I don't have any experience on Bayesian network.

**Comment by haison19952013** [comment]
> Hi @lululxvi,
> 
> I came across a paper on Bayesian PINNs (B-PINNs) [https://arxiv.org/abs/2003.06097] that seems quite helpful for this situation (I noticed G.E. Karniadakis, who I believe was part of the DeepXDE paper, was also part of this paper).
> 
> Do you think DeepXDE could be easily modified to implement B-PINNs? The paper only provides pseudo-code, but I think something building off of the existing DeepXDE architecture might be feasible.
> 
> Let me know what you think, thank you.

Hi @azhu529 , I'm also interested in the problem you describe above. Did you have any progress in implementing the codes you talked about ? Could you share with us?

**Comment by azhu529** [comment]
Hi @haison19952013, I emailed the authors and they said that a library called UQ-SciML would be released pending publication. Not sure about its progress, but they said there would be open-source code with it.

**Comment by haison19952013** [comment]
> Hi @haison19952013, I emailed the authors and they said that a library called UQ-SciML would be released pending publication. Not sure about its progress, but they said there would be open-source code with it.

Hi, thank you for your response. I think prof. George Em Karniadakis has published a brand new paper (https://arxiv.org/pdf/2205.08304.pdf) dealing with all uncertainties about both ANN and physics parameters in PINNs. I'm really looking forward to the UQ-SciML or relavant implementations in deepXDE :)
