### ISSUE TITLE
What geometry will be suitable? 

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#295]
@lululxvi  Thank you for all your previous answers. I have a new question. If I have a hollow cylinder like the picture I attached and the outputs are the functions of (r, z, t). That is (radial, axial, time). what geometry will be suitable? 
Should I use 2 rectangle geometry and then csgdifference?
![Cylinder](https://user-images.githubusercontent.com/68455679/119298737-da518000-bc72-11eb-91b0-011eb74ea721.JPG)
Thank You

**Comment by lululxvi** [comment]
A single rectangle should be good, if you only need the geometry in the right figure.

**Comment by katayooneshkofti** [comment]
Thank You
