### ISSUE TITLE
AttributeError: module 'deepxde' has no attribute 'OperatorBC'

### ISSUE THREAD

**Issue by x9m** [lululxvi/deepxde#3]
Hi Lu,

I'm trying to run your newly added euler_beam.py. somehow, it gave me attribute error regarding to a new BC.  

"AttributeError: module 'deepxde' has no attribute 'OperatorBC'"

then, I explicitly state this BC as "from deepxde.boundary_conditions import OperatorBC" and it didn't work. after that, I changed "OperatorBC" into "DirichletBC" to do a test run and it worked.

is it possible for you to look into this issue and let me know if I did it wrong by any chance?

much appreciated.
Aaron

**Comment by lululxvi** [comment]
Hi, Aaron,

`OperatorBC` is a new class, and not in the version in pip or anaconda. Could you try to clone the updated codes, and then import it explicitly:

```
import sys
sys.path.insert(0, '..')
import deepxde as dde
```

**Comment by x9m** [comment]
Hi Lu,

Thank you for your reply.  I added 2 lines as your suggested. and also, I need to change the path of Spyder as well to get it working.

Cheers,
Aaron
