### ISSUE TITLE
Error running Burgers example and Navier stokes eqn enquiry

### ISSUE THREAD

**Issue by zonexo** [lululxvi/deepxde#30]
Hi, I tried to run the Burgers example but I got the error:

```
  File "D:\wtay\OneDrive\TL\AI_machine_learning\Data\deepxde-master\examples\Burgers.py", line 59, in <module>
    main()

  File "D:\wtay\OneDrive\TL\AI_machine_learning\Data\deepxde-master\examples\Burgers.py", line 39, in main
    geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160

TypeError: __init__() missing 1 required positional argument: 'ic_bcs'
```

Any idea what's wrong?

Btw, have you tried using your code on the Navier Stokes eqn? If so, how does it perform? It should be interesting to find out.

Thanks!

**Comment by lululxvi** [comment]
Install the new version 0.6.0.

For NS, the short answer is yes. But the performance depends on the problem, e.g., Re number. Look at some examples here https://science.sciencemag.org/content/367/6481/1026 .

**Comment by jeffreyrdcs** [comment]
I still get the same "TypeError: __init__() missing 1 required positional argument: 'ic_bcs'"  error with version 0.12.0

**Comment by lululxvi** [comment]
What is the output of
```
dde.__version__
```
