### ISSUE TITLE
flowmaps in ResNet

### ISSUE THREAD

**Issue by s185231** [lululxvi/deepxde#300]
Hello!
We are using DeepXDE for function approximation and solving differential equations. We have currently only been working with FNN but we encounter problems with extrapolation. Therefor we want to try using ResNet instead. We will use a flowmap, but we are not sure how to implement this using the inbuild ResNet in DeepXDE. 

We want to find a flow map 
![image](https://user-images.githubusercontent.com/77012225/120608120-1fcf3380-c451-11eb-9daa-9b4fc9d60cb2.png)

such that
![image](https://user-images.githubusercontent.com/77012225/120781877-c6870300-c529-11eb-831d-c50fccd060cb.png)

Is this already considered when using ResNet, if not how can we implement it?

Kind Regards

**Comment by lululxvi** [comment]
You are not using PINN, right?

The network you considered is a standard function approximation mapping from y_{k-1} to y_k. What you can do is generating a dataset whose input is y_{k-1} and output is y_k. Then you can use [FNN](https://deepxde.readthedocs.io/en/latest/modules/deepxde.maps.html#module-deepxde.maps.fnn) or [ResNet](https://deepxde.readthedocs.io/en/latest/modules/deepxde.maps.html#module-deepxde.maps.resnet) to learn \Phi

**Comment by s185231** [comment]
We are using PINNs, does that limit the applicability?

**Comment by lululxvi** [comment]
Which PINN are you using specifically? In PINN, we usually don't do time stepping.
