### ISSUE TITLE
NPZ FILE and How to modify or change the loss function

### ISSUE THREAD

**Issue by NanaKwesiAsante** [lululxvi/deepxde#302]
How did you save your datasets to npz extensions? Also, how can one change the loss function in your lulu package and also change the weights for the ic or the bc in the loss function?

**Comment by lululxvi** [comment]
- see https://numpy.org/doc/stable/reference/generated/numpy.savez.html
- What type of loss do you want?
- see loss_weights in https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.model.Model.compile

**Comment by NanaKwesiAsante** [comment]
> * see https://numpy.org/doc/stable/reference/generated/numpy.savez.html
> * What type of loss do you want?
> * see loss_weights in https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.model.Model.compile

so the problem I am trying to solve is an interface problem. I am using a least-square functional that incorporates two interface conditions. Below is an example:
![interface](https://user-images.githubusercontent.com/55963133/122071102-14b6c480-cdbc-11eb-8bce-b0dc9bafbe7f.PNG)

1.do you have the least square functional in your package like the way you have the MSE?
2. how can I do this in your lulu package?

**Comment by lululxvi** [comment]
So you want to define some non-standard boundary conditions, right? In DeepXDE, the interface condition is one type of boundary condition with the interface as the boundary. This can be implemented by using [`OperatorBC`](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.OperatorBC). You can check FAQ "Q: More details and examples about boundary conditions." for some examples

**Comment by NanaKwesiAsante** [comment]
> So you want to define some non-standard boundary conditions, right? In DeepXDE, the interface condition is one type of boundary condition with the interface as the boundary. This can be implemented by using [`OperatorBC`](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.OperatorBC). You can check FAQ "Q: More details and examples about boundary conditions." for some examples

So below is the interface problem i am trying to use your package to solve this example i saw in a paper;
![interface](https://user-images.githubusercontent.com/55963133/123650751-7f222880-d7f0-11eb-9eb0-658b68bd8de3.PNG)

and this is example i am trying to solve using your package to repeat the procedure in the paper.
![interface2](https://user-images.githubusercontent.com/55963133/123651223-eb049100-d7f0-11eb-8e6f-1806a1a65dc8.PNG)

below is the code i wrote using your package but when i run it i get errors and wanted you to give me suggestions on how to improve the code to make it work. In the code i was  trying to use two NN for the two domains which i think might be a wrong idea or i am doing something wrong.


#for domain 1 circle
def main():
    def pde1(x, y):
        beta1=1
        dy_xx1 = dde.grad.hessian(y, x, i=0, j=0)
        dy_yy1 = dde.grad.hessian(y, x, i=1, j=1)
        fct=(3*(2*np.power(x,2)+np.power(y,2))/np.sqrt(np.power(x,2)+np.power(y,2)))
        return -(dy_xx1 + dy_yy1 )*beta1+fct

    def boundary(_, on_boundary):
        return on_boundary
    
    #for domain 2 rectangle
    def pde2(x, y):
        beta2=1
        dy_xx2 = dde.grad.hessian(y, x, i=0, j=0)
        dy_yy2 = dde.grad.hessian(y, x, i=1, j=1)
        fct1=(3*(np.power(x,2)+2*np.power(y,2))/np.sqrt(np.power(x,2)+np.power(y,2)))
        return -(dy_xx2 + dy_yy2 )*beta2+fct1

#domain 1 geom1
    def boundary(_, on_boundary):
        return on_boundary
    geom22 = dde.geometry.Rectangle([-1,-1], [1,1])
    #geom2=geom2.random_points(100, random='pseudo')
    #domain 2 geom
    geom1 = dde.geometry.Disk([0,0], 0.5)
    #geom1=geom1.random_points(100, random='pseudo')
    geom2= dde.geometry.CSGDifference(geom22, geom1)
    
    #Gj
    def func1(x,y):
        beta2=1
        beta1=1
        r=np.sqrt(np.power(x,2)+np.power(y,2))
        ro=0.4
        return (beta2*(r**3-ro**3)+beta1(ro**3-r**3))/(beta1*beta2)
    
    
    #normalx
    def nx(x,y):
        r=np.sqrt(np.power(x,2)+np.power(y,2))
        return (-y/r)
    #normaly
    def ny(x,y):
        r=np.sqrt(np.power(x,2)+np.power(y,2))
        return (x/r)
    
    #Gf
    def func2(x,y):
        r=np.sqrt(np.power(x,2)+np.power(y,2))
        return ((3*np.array(x)*r)*np.array([nx,ny]))-((3*np.array(y)*r)*np.array([nx,ny]))
    
    
    # #Gd domain 1
    # def func3d1(x,y):
    #     beta1=1
    #     r=np.sqrt(np.array(x)**2+np.array(y)**2)
    #     return (r**3)/beta1
    
    #Gd domain 2
    def func3d2(x,y):
        beta2=1
        beta1=1
        r=np.sqrt(np.array(x)**2+np.array(y)**2)
        ro=0.4
        return ((r**3)/beta2)+((1/beta1)-(1/beta2))*ro**3
    
     
                          
    bc1n = dde.DirichletBC(geom1, lambda x: func1, boundary)
    bc1nn = dde.NeumannBC(geom1, lambda x: func2, boundary)
    #bc1d = dde.DirichletBC(geom1, lambda x: func3d,boundary)
    

#domain 2
   # bc2n = dde.DirichletBC(geom1, lambda x: func1, boundary)
    #bc2nn = dde.NeumannBC(geom1, lambda x: func2, boundary)
    bc2d = dde.DirichletBC(geom2, lambda x:func3d2, boundary)
    
    #domain 1
    data1 = dde.data.PDE(geom1, pde1, [bc1n,bc1nn], num_domain=50, num_boundary=10, num_test=100)
    net1 = dde.maps.FNN([2] + [64] * 4 + [1], "tanh", "Glorot uniform")
    #model1 = dde.Model(data1, net1)
    
    #domain 2
    data2 = dde.data.PDE(geom2, pde2, bc2d, num_domain=50, num_boundary=10, num_test=100)
    net2 = dde.maps.FNN([2] + [64] * 4 + [1], "tanh", "Glorot uniform")
    #model = dde.Model([data1,data2], [net1,net2])
    
    data3 = dde.data.PDE([geom2,geom1], pde1, [bc1n,bc1nn], num_domain=50, num_boundary=10, num_test=100)
    net1 = dde.maps.FNN([2] + [64] * 4 + [1], "tanh", "Glorot uniform")
    
    model = dde.Model(data2, net2)
    model.compile("adam", lr=0.001)
    model.train(epochs=50)
    losshistory, train_state = model.train()
    
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()

**Comment by lululxvi** [comment]
- You only need to define one geometry, which is the larger rectangle, which already contains the inner disk.
- Use only one network with 2 outputs, like
```python
dde.maps.FNN([2] + [64] * 4 + [2], "tanh", "Glorot uniform")
```
Then the first output is the solution in the inner disk, and the second output is the solution of the outside.
- Define pde as
```python
def pde(x, y):
    # Here y1 = y[:, 0:1], y2 = y[1:2]
    # compute the two residuals for y1 and y2, similar as your code pde1 and pde2
    error1 = ...
    error2 = ...
    # indicate if x is inside the disk
    r2 = tf.sum(tf.square(x), axis=1, keep_dim=True) # r**2 for each x
    is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
    # For x inside, use error1; for x outside, use error2
    return error1 * is_inside, error2 * (1 - is_inside)
```
- Define the outside BC for y2
- For interface BC, for example in the circle, y2 - y1 = sin(x) + cos(y)
```python
def on_circle(x, _):
    r2 = x[0] ** 2 + x[1] **2
    return np.isclose(r2, 0.5**2)

def func(inputs, outputs, X):
    y1 = inputs[:, 0:1]
    y2 = inputs[:, 1:2]
    return y2 - y1 - np.sin(X[:, 0:1]) - np.cos(X[:, 1:2])

bc = dde.bc.OperatorBC(geom, func, on_circle)
```
- Make sure the points on the interface is in the training points
```python
x_circle = ...  # Generate manually some points on the circle; a Numpy array of size N x 2
dde.data.PDE(..., anchors=X)
```

**Comment by NanaKwesiAsante** [comment]
> * You only need to define one geometry, which is the larger rectangle, which already contains the inner disk.
> * Use only one network with 2 outputs, like
> 
> ```python
> dde.maps.FNN([2] + [64] * 4 + [2], "tanh", "Glorot uniform")
> ```
> 
> Then the first output is the solution in the inner disk, and the second output is the solution of the outside.
> 
> * Define pde as
> 
> ```python
> def pde(x, y):
>     # Here y1 = y[:, 0:1], y2 = y[1:2]
>     # compute the two residuals for y1 and y2, similar as your code pde1 and pde2
>     error1 = ...
>     error2 = ...
>     # indicate if x is inside the disk
>     r2 = tf.sum(tf.square(x), axis=1, keep_dim=True) # r**2 for each x
>     is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
>     # For x inside, use error1; for x outside, use error2
>     return error1 * is_inside, error2 * (1 - is_inside)
> ```
> 
> * Define the outside BC for y2
> * For interface BC, for example in the circle, y2 - y1 = sin(x) + cos(y)
> 
> ```python
> def on_circle(x, _):
>     r2 = x[0] ** 2 + x[1] **2
>     return np.isclose(r2, 0.5**2)
> 
> def func(inputs, outputs, X):
>     y1 = inputs[:, 0:1]
>     y2 = inputs[:, 1:2]
>     return y2 - y1 - np.sin(X[:, 0:1]) - np.cos(X[:, 1:2])
> 
> bc = dde.bc.OperatorBC(geom, func, on_circle)
> ```
> 
> * Make sure the points on the interface is in the training points
> 
> ```python
> x_circle = ...  # Generate manually some points on the circle; a Numpy array of size N x 2
> dde.data.PDE(..., anchors=X)
> ```



Thank you soo much.
1. So I did what you suggested and below is the code but it still gives me this error:

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\gradients.py", line 59, in __init__
    raise ValueError("The component of y is missing.")

ValueError: The component of y is missing.

The code:
def main():
    def pde(x, y):
    # Here y1 = y[:, 0:1], y2 = y[1:2]
    # compute the two residuals for y1 and y2, similar as your code pde1 and pde2
        beta1=1
        dy_xx1 = dde.grad.hessian(y, x, i=0, j=0)
        dy_yy1 = dde.grad.hessian(y, x, i=1, j=1)
        fct1=(3*(2*np.power(x[:,0],2)+np.power(x[:,1],2))/np.sqrt(np.power(x[:,0],2)+np.power(x[:,1],2)))
        error1 = -(dy_xx1 + dy_yy1 )*beta1+fct1
        
        beta2=1
        fct2=(3*(np.power(x[:,0],2)+2*np.power(x[:,1],2))/np.sqrt(np.power(x[:,0],2)+np.power(x[:,1],2)))
        error2 = -(dy_xx1 + dy_yy1 )*beta2+fct2
    # indicate if x is inside the disk
        r2 = tf.sum(tf.square(x), axis=1, keep_dim=True) # r**2 for each x
        is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
    # For x inside, use error1; for x outside, use error2
        return error1 * is_inside, error2 * (1 - is_inside)
    
    geom = dde.geometry.Rectangle([-1,-1], [1,1])    
    
    def boundary(x, on_boundary):
        return on_boundary
    #on the boundary rectangle
    def func1(x):
        beta2=1
        beta1=1
        r=np.sqrt(np.array(x[:,0])**2+np.array(x[:,1])**2)
        ro=0.4
        return ((r**3)/beta2)+((1/beta1)-(1/beta2))*ro**3
    
    #on the interface which is the circle
    def on_circle(x, _):
        r2 = x[0] ** 2 + x[1] **2
        return np.isclose(r2, 0.5**2)

    def func(inputs, outputs, X):
        y1 = inputs[:, 0:1]
        y2 = inputs[:, 1:2]
        ro=0.4
        beta2=1
        beta1=1
        r=np.sqrt(np.array(X[:,0])**2+np.array(X[:,1])**2)
        return y2 - y1 - (beta2*(r**3-ro**3)+beta1(ro**3-r**3))/(beta1*beta2)
    
    bcd = dde.DirichletBC(geom, lambda x: func1, boundary)
    bc = dde.bc.OperatorBC(geom, func, on_circle)
    
    # Generate manually some points on the circle; a Numpy array of size N x 2
    N=50
    r=0.5
    theta = np.linspace(0, 2*np.pi, N) 
    ox, oy = r * np.cos(theta), r * np.sin(theta)
    X=np.transpose([ox,oy])
    #dde.data.PDE(..., anchors=X)  
    data = dde.data.PDE(geom, pde, [bcd,bc], num_domain=50, num_boundary=10, num_test=100,anchors=X)
    net=dde.maps.FNN([2] + [64] * 4 + [2], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=50000)
    #model.compile("L-BFGS-B") 
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
  
    
    
if __name__ == "__main__":
    main()    

2. in the pdf above there are two functions on the interface, gj and gf and from the things you suggested , you only did for gj . so my question is ,do I have to use operatorBC to go through the same procedure for gf?

**Comment by lululxvi** [comment]
- You didn't specific `component` in `hessian`, see https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.gradients.hessian
- Yes. I just give you an example.

**Comment by NanaKwesiAsante** [comment]
> * You didn't specific `component` in `hessian`, see https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.gradients.hessian
> * Yes. I just give you an example.

i get this error when I run this code after your suggestions you gave me:

TypeError: Input 'y' of 'Mul' Op has type bool that does not match type float32 of argument 'x'.

Below is the code:
def main():

    def pde(x, y):
        
        dy_xx1 = dde.grad.hessian(y, x,component=0, i=0, j=0)
        dy_yy1 = dde.grad.hessian(y, x, component=0,i=1, j=1)
        dy_xx2 = dde.grad.hessian(y, x,component=1, i=0, j=0)
        dy_yy2 = dde.grad.hessian(y, x, component=1,i=1, j=1)
        
        #u1
        beta1=1
        fct1=(3*(2*x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error1 = -(dy_xx1 + dy_yy1 )*beta1+fct1
        
        #u2
        beta2=1
        fct2=(3*(x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error2 = -(dy_xx2 + dy_yy2 )*beta2+fct2
        
        # indicate if x is inside the disk
        #r2 = tf.sum(tf.square(x), axis=1, keep_dim=True) # r**2 for each x
        r2=tf.math.reduce_sum (tf.square(x), axis=1, keepdims=True)
        #r2=x[:,0:1]**2+x[:,1:2]**2
        is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
    # For x inside, use error1; for x outside, use error2
        return error1 * is_inside, error2 * (1 - is_inside)
          
    geom = dde.geometry.Rectangle([-1,-1], [1,1])    
    
    def boundary(x, on_boundary):
         return on_boundary
    #on the boundary rectangle
    def func1(x):
        beta2=1
        beta1=1
        r=np.sqrt(x[:,0:1]**2+x[:,1:2]**2)
        ro=0.4
        return ((r**3)/beta2)+((1/beta1)-(1/beta2))*ro**3
    
   # the 1st function on the interface which is the circle
    def on_circle(x, _):
        r2 = x[0] ** 2 + x[1] **2
        return np.isclose(r2, 0.5**2)

    def func2(inputs, outputs, X):
        y1 = inputs[:, 0:1]
        y2 = inputs[:, 1:2]
        ro=0.4
        beta2=1 
        beta1=1
        r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
        return y2 - y1 - (beta2*(r**3-ro**3)+beta1*(ro**3-r**3))/(beta1*beta2)
    
    
    
     #normals
      #normalx
    def nx(x):
         #r=np.sqrt(np.power(x[:,0],2)+np.power(x[:,1],2))
         r=np.sqrt(x[:,0:1]**2+x[:,1:2]**2)
         return (-x[:,1:2]/r)
     #normaly
    def ny(x):
        # r=np.sqrt(np.power(x[:,0],2)+np.power(x[:,1],2))
        r=np.sqrt(x[:,0:1]**2+x[:,1:2]**2)
        return (x[:,0:1]/r)
    
    
   # # the 2nd function on the interface which is the circle(flux)
   #  def func3(x, y, X):
   #      #y1 = y[:, 0:1]
   #      #y2 = y[:, 1:2]
   #      #ro=0.4
   #      du1 = dde.grad.jacobian(y, x, i=0,j=1)
   #      du2=dde.grad.jacobian(y, x, i=0,j=1)
   #      beta2=1 
   #      beta1=1
   #      r=np.sqrt(np.array(X[:,0])**2+np.array(X[:,1])**2)
   #      return ((beta1*du1*np.array([nx,ny]))-(beta2*du2*np.array([nx,ny])))-(((beta1*3*np.array(x[:,0])*r)*np.array([nx,ny]))-((beta2*3*np.array(x[:,1])*r)*np.array([nx,ny])))
    bc1 = dde.DirichletBC(geom,  func1, boundary,component=0)
    bc2 = dde.bc.OperatorBC(geom, func2, on_circle)
    #bc3 = dde.bc.OperatorBC(geom, func3, on_circle)
    
    # Generate manually some points on the circle; a Numpy array of size N x 2
    N=50
    r=0.5
    theta = np.linspace(0, 2*np.pi, N) 
    ox, oy = r * np.cos(theta), r * np.sin(theta)
    X=np.transpose([ox,oy])
    #dde.data.PDE(..., anchors=X)  
    data = dde.data.PDE(geom, pde, [bc1,bc2], num_domain=50, num_boundary=10, num_test=100,anchors=X)
    net=dde.maps.FNN([2] + [64] * 4 + [2], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=50000)
    #model.compile("L-BFGS-B") 
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
  
    
    
if __name__ == "__main__":
    main()

**Comment by NanaKwesiAsante** [comment]
When i comment this part of the code out
 '' # r2=tf.math.reduce_sum (tf.square(x), axis=1, keepdims=True)''
''#is_inside = tf.math.less(r2, 0.5**2) ''
 '' #return error1 * is_inside, error2 * (1 - is_inside)''.

 the code runs fine but if i don't it gives me the above error I stated earlier. below is the commented part of the code in the pde function which runs fine but gives me nan in the output errors. How can I rectify this error giving me when I uncomment that side of the error

def pde(x, y):
        
        dy_xx1 = dde.grad.hessian(y, x,component=0, i=0, j=0)
        dy_yy1 = dde.grad.hessian(y, x, component=0,i=1, j=1)
        dy_xx2 = dde.grad.hessian(y, x,component=1, i=0, j=0)
        dy_yy2 = dde.grad.hessian(y, x, component=1,i=1, j=1)
        
        #u1
        beta1=1
        fct1=(3*(2*x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error1 = -(dy_xx1 + dy_yy1 )*beta1+fct1
        
        #u2
        beta2=1
        fct2=(3*(x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error2 = -(dy_xx2 + dy_yy2 )*beta2+fct2
        
        # indicate if x is inside the disk
        #r2 = tf.sum(tf.square(x), axis=1, keep_dim=True) # r**2 for each x
       # r2=tf.math.reduce_sum (tf.square(x), axis=1, keepdims=True)
        #r2=x[:,0:1]**2+x[:,1:2]**2
        #is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
    # For x inside, use error1; for x outside, use error2
        #return error1 * is_inside, error2 * (1 - is_inside)
        return error1 , error2 

output, when the whole code is run with those lines commented out
Step      Train loss                                  Test loss                                   Test metric
0         [nan, nan, 4.00e+00, 2.50e-01]              [1.71e+01, 7.34e+00, 0.00e+00, 0.00e+00]    []  
1000      [nan, nan, nan, 2.50e-01]                   [nan, nan, 0.00e+00, 0.00e+00]              []  
2000      [nan, nan, nan, 2.50e-01]                   [nan, nan, 0.00e+00, 0.00e+00]              []  
3000      [nan, nan, nan, 2.50e-01]                   [nan, nan, 0.00e+00, 0.00e+00]              []  
4000      [nan, nan, nan, 2.50e-01]                   [nan, nan, 0.00e+00, 0.00e+00]              []  
5000      [nan, nan, nan, 2.50e-01]

**Comment by lululxvi** [comment]
Use `tf.cast` to covert r2 from bool to float32

**Comment by NanaKwesiAsante** [comment]
Hello Dr. LuLu, first of all, I would like to thank you for the help you have been giving me, I really appreciate it. I have several questions to ask about the example I shared with you that I am using your package to solve.

 Below is a suggestion you gave me when I asked for your help about how to use the operator bc.:
def on_circle(x, _):
    r2 = x[0] ** 2 + x[1] **2
    return np.isclose(r2, 0.5**2)

def func(inputs, outputs, X):
    y1 = inputs[:, 0:1]
    y2 = inputs[:, 1:2]
    return y2 - y1 - np.sin(X[:, 0:1]) - np.cos(X[:, 1:2])

bc = dde.bc.OperatorBC(geom, func, on_circle)

1.My first question is about the inputs in the func function, was it a mistake you typed  y1 = inputs[:, 0:1]
    y2 = inputs[:, 1:2] instead of  y1 = outputs[:, 0:1]
    y2 = outputs[:, 1:2]?
Also do we need to include inputs(x) as an argument for func because we need just X as the input(x) on the interface?so meaning can func just be
def func(outputs(or y), X):
    y1 = outputs[:, 0:1]
    y2 = outputs[:, 1:2]
    return y2 - y1 - np.sin(X[:, 0:1]) - np.cos(X[:, 1:2])?

2.Also this is the code I have come up with so far, but when I run it, it gives me lots of nan as the error. Can you brush through real quick for me and let me know the places I made mistakes and also give me suggestions on how to make it work?


def main():

    def pde(x, y):
        
        dy_xx1 = dde.grad.hessian(y, x,component=0, i=0, j=0)
        dy_yy1 = dde.grad.hessian(y, x, component=0,i=1, j=1)
        dy_xx2 = dde.grad.hessian(y, x,component=1, i=0, j=0)
        dy_yy2 = dde.grad.hessian(y, x, component=1,i=1, j=1)
        
        #u1
        beta1=1
        fct1=(3*(2*x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error1 = -(dy_xx1 + dy_yy1 )*beta1+fct1
        
        #u2
        beta2=1
        fct2=(3*(x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        error2 = -(dy_xx2 + dy_yy2 )*beta2+fct2
        
        
        r2=tf.math.reduce_sum (tf.square(x), axis=1, keepdims=True)
        
        
        is_inside = tf.math.less(r2, 0.5**2)  # True --> inside, False --> outside
        
       
        return error1 * tf.cast(is_inside, dtype = tf.float32), error2 * (1 - tf.cast(is_inside, dtype = tf.float32))
         
    geom = dde.geometry.Rectangle([-1,-1], [1,1])    
    
    
    def boundary(x, on_boundary):
         return on_boundary
    #on the boundary rectangle
    def func1(x):
        beta2=1
        beta1=1
        r=np.sqrt(x[:,0:1]**2+x[:,1:2]**2)
        ro=0.4
        return ((r**3)/beta2)+((1/beta1)-(1/beta2))*ro**3
    
   # the 1st function on the interface which is the circle
    def on_circle(x, _):
        r2 = x[0] ** 2 + x[1] **2
        return np.isclose(r2, 0.5**2)

    def func2(x, y, X):
        y1 = x[:, 0:1]
        y2 = x[:, 1:2]
        ro=0.4
        beta2=1 
        beta1=1
        r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
        return y2 - y1 - (beta2*(r**3-ro**3)+beta1*(ro**3-r**3))/(beta1*beta2)
    
    
    
    
    # the 2nd function on the interface which is the circle(flux)
    def func3(x, y, X):
         r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
         #normal for x
         nx=X[:,0:1]/r
         #normal for y
         ny=X[:,1:2]/r
         du1x = dde.grad.jacobian(y, x, i=0,j=0)
         du1y= dde.grad.jacobian(y, x, i=0,j=1)
         du1=[du1x,du1y]
         du2x=dde.grad.jacobian(y, x, i=1,j=0)
         du2y=dde.grad.jacobian(y, x, i=1,j=1)
         du2=[du2x,du2y]
         beta2=1 
         beta1=1
         n1=np.transpose([nx,ny])
         #normal u2
         n2=-n1
        
         return ((beta1*du1*n1)-(beta2*du2*n2))-(((beta1*3*X[:,0:1]*r)*n1)-((beta2*3*X[:,1:2]*r)*n2))
    bc1 = dde.DirichletBC(geom,  func1, boundary,component=0)
    bc2 = dde.bc.OperatorBC(geom, func2, on_circle)
    bc3 = dde.bc.OperatorBC(geom, func3, on_circle)
    
    # Generate manually some points on the circle; a Numpy array of size N x 2
    N=50
    r=0.5
    theta = np.linspace(0, 2*np.pi, N) 
    ox, oy = r * np.cos(theta), r * np.sin(theta)
    X=np.transpose([ox,oy])
    #dde.data.PDE(..., anchors=X)  
    data = dde.data.PDE(geom, pde, [bc1,bc2,bc3], num_domain=50, num_boundary=10, num_test=100,anchors=X)
    net=dde.maps.FNN([2] + [64] * 4 + [2], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=50000)
    #model.compile("L-BFGS-B") 
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
  
    
    
if __name__ == "__main__":
    main()    



3.how can I see the outputs of certain functions in the code if I am debugging. For example, if func3 in my above code how can I see the return outputs when debugging. This will help me know how some assignments are stored and arranged for me to do the multiplication and division better and efficiently

**Comment by lululxvi** [comment]
1. Not quite understand your question. `inputs` are network inputs, `outputs` are network outputs. You need to have all the arguments, which is the design of the API.
2. I didn't find an obvious error. You may start from a simple problem with simpler geometry and boundary conditions to test
3. All the arguments are 2d tf/np array. You can use `model.predict(X, operator=func3)` to get the outputs, see https://github.com/lululxvi/deepxde/blob/master/examples/Burgers.py

**Comment by NanaKwesiAsante** [comment]
1. Below is a suggestion you gave me when I asked for your help about how to use the operator bc.:
def on_circle(x, _):
r2 = x[0] ** 2 + x[1] 2
return np.isclose(r2, 0.52)

def func(inputs, outputs, X):
y1 = inputs[:, 0:1]
y2 = inputs[:, 1:2]
return y2 - y1 - np.sin(X[:, 0:1]) - np.cos(X[:, 1:2])
To make my question clear y1 and y2 are the solutions(i.e u1 and u2) of the pde right? If YES then why do we have y1 =inputs[:,0:1] in your suggestion? i was thinking it should be y1=outputs[:,0:1] and same for y2. If NO can you give me a little explanation on why we using inputs for y1 and y2.

**Comment by lululxvi** [comment]
You are right. It is a mistake in my code.

**Comment by NanaKwesiAsante** [comment]
Hi Dr LuLu , so i rewrote the code for the interface again but this time it gives me this error below.
1.Am i doing something wrong in code considering the interface problem.
2. i used anchor to give points to the func3 but it still says it need arguments X and outputs.

runfile('C:/Users/Nana Kwesi/Desktop/DeepLearning/interface/internew.py', wdir='C:/Users/Nana Kwesi/Desktop/DeepLearning/interface')
Compiling model...
Building feed-forward neural network...
'build' took 3.577945 s

Traceback (most recent call last):

  File "C:\Users\Nana Kwesi\Desktop\DeepLearning\interface\internew.py", line 120, in <module>
    main()

  File "C:\Users\Nana Kwesi\Desktop\DeepLearning\interface\internew.py", line 109, in main
    model.compile("adam", lr=0.001)

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\utils.py", line 52, in wrapper
    result = f(*args, **kwargs)

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\model.py", line 87, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\data\pde.py", line 135, in losses
    return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)

  File "C:\anaconda\envs\tf\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)

  File "C:\anaconda\envs\tf\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\anaconda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1230, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)

  File "C:\anaconda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1066, in BuildCondBranch
    original_result = fn()

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\data\pde.py", line 120, in losses_train
    error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)

  File "C:\anaconda\envs\tf\lib\site-packages\deepxde\boundary_conditions.py", line 53, in error
    values = self.func(X[beg:end])

TypeError: func3() missing 2 required positional arguments: 'outputs' and 'X'


THIS IS THE NEW CODE BELOW


def main():
    r0 = 0.5
    rg=0.4
    B1=1
    B2=1
    innerdisk = dde.geometry.Disk([0, 0], rg)
    geom = dde.geometry.Rectangle([-1,-1], [1,1]) 
    def pde(x, y):
        
        u1, u2 = y[:, 0:1], y[:, 1:2]
        
        #radius of circles of points inside
        i0 = tf.reduce_sum(x**2, axis=1, keepdims=True) < r0**2
        inside = tf.cast(i0, tf.float32)
        outside=1-inside
        
        f1=(3*(2*x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        f2=(3*(x[:,0:1]**2+x[:,1:2]**2)/tf.sqrt(x[:,0:1]**2+x[:,1:2]**2))
        
        #u1
        du1_x = tf.gradients(u1, x)[0][:,0:1]
        du1_y = tf.gradients(u1, x)[0][:,1:]
        du1_xx = tf.gradients(du1_x, x)[0][:, 0:1]
        du1_yy = tf.gradients(du1_y, x)[0][:, 1:]
        Laplacian_u1 = -(du1_xx + du1_yy )*B1+f1
        
        #u2
        du2_x = tf.gradients(u2, x)[0][:,0:1]
        du2_y = tf.gradients(u2, x)[0][:,1:]
        du2_xx = tf.gradients(du2_x, x)[0][:, 0:1]
        du2_yy = tf.gradients(du2_y, x)[0][:, 1:]
        Laplacian_u2 = -(du2_xx + du2_yy)*B2+f2
        
        f1=Laplacian_u1*inside
        f2=Laplacian_u2*outside
        return f1, f2
    
    # circle boundary
    def boundary(x, _):
        return innerdisk.on_boundary(x)
    
    #on the interface circle
    def func1(inputs, outputs, X):
        u1, u2 = outputs[:, 0:1], outputs[:, 1:2]
        r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
        gj=(B2*(r**3-rg**3)+B1*(rg**3-r**3))/(B1*B2)
        return (u1 - u2)-gj
    
     #on the interface but for the flux
    def func2(inputs, outputs, X):
        u1, u2 = outputs[:, 0:1], outputs[:, 1:2]
        r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
        du1dx = tf.gradients(u1, inputs)[0]
        du2dx = tf.gradients(u2, inputs)[0]
        n = np.array(list(map(innerdisk.boundary_normal, X)))
        gf=(((B1*3*X[:,0:1]*r)*n)-((B2*3*X[:,1:2]*r)*n))
        f1 = tf.reduce_sum(du1dx * n * B1, axis=1, keepdims=True)
        f2 = tf.reduce_sum(du2dx * n * B2, axis=1, keepdims=True)
        return  (f1 - f2)-gf
    
    #rectangle boundary
    def boundary2(x, _):
        return geom.on_boundary(x)
    
    #on the rectangle
    def func3(inputs, outputs, X):
        u2 = outputs[:, 1:2]
        r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
        gd=((r**3)/B2)+((1/B1)-(1/B2))*rg**3
        return u2-gd
    
    
    # #rectangle boundary
    # def boundary2(x, on_boundary):
    #     return on_boundary
    
    # #on the rectangle
    # def func3(X):
    #     #u2 = outputs[:, 1:2]
    #     r=np.sqrt(X[:,0:1]**2+X[:,1:2]**2)
    #     gd=((r**3)/B2)+((1/B1)-(1/B2))*rg**3
    #     return gd
    
    bc1 = dde.OperatorBC(geom, func1, boundary)
    bc2 = dde.OperatorBC(geom, func2, boundary)
    bc3 = dde.DirichletBC(geom,func3, boundary2,component=1)
    
    data = dde.data.PDE(geom,pde, [bc1, bc2, bc3], num_domain=0,num_boundary=0, anchors=np.vstack((innerdisk.random_boundary_points(100),geom.random_boundary_points(100))))
    net = dde.maps.FNN([2] + [128] * 8 + [2], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=50000)
    #model.compile("L-BFGS-B") 
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
     
    
    
    
    
if __name__ == "__main__":
    main()
