### ISSUE TITLE
2D Darcy equation

### ISSUE THREAD

**Issue by NischalKMapakshi** [lululxvi/deepxde#304]
Hello Lu,

I'm trying to implement a 2D darcy equation that has the following (referenced from your Beltrami_flow.py):
    # Defining PDE(loss function)
    def pde(x,u):
        u1, u2, p = u[:,0:1], u[:,1:2], u[:,2:3]
        du1_x = dde.grad.jacobian(u, x, i=0, j=0)
        du1_y = dde.grad.jacobian(u, x, i=0, j=1)
        du2_x = dde.grad.jacobian(u, x, i=1, j=0)
        du2_y = dde.grad.jacobian(u, x, i=1, j=1)
        dp_x = dde.grad.jacobian(u, x, i=2, j=0)
        dp_y = dde.grad.jacobian(u, x, i=2, j=1)
        
        lf = tf.sqrt(tf.square(alpha*u1+dp_x)+tf.square(alpha*u2+dp_y)+tf.square(du1_x + du2_y))
        return lf
I'm getting:
ValueError: j=1 is not valid.

I'm solving it on a rectangular domain.
Please advise.
Thank you

**Comment by XyM6u9** [comment]
Did you solve it? I got the same error.
