### ISSUE TITLE
Different behavior of L-BFGS-B on CPU and GPU

### ISSUE THREAD

**Issue by mrzw731** [lululxvi/deepxde#308]
Hi Lu,
First, I want to thank you and your team for developing this amazing package!
As I was testing the tutorial code on the burgers equation, I noticed that the behavior of BFGS is extremely different when GPU or CPU is used during training.
When trained with a CPU, it takes about 3000 iterations to terminate, and the loss is significantly reduced. However, when GPU is deployed, it terminates in about 10 iterations, and the loss is not meaningfully reduced. I have tested this multiple times with different initialization, and the issues seems to be persistent...
Best,
Wei

**Comment by lululxvi** [comment]
It could be due to the precision of CPU and GPU. What is your GPU model? Also, could you try using float64, see https://github.com/lululxvi/deepxde/issues/28?

**Comment by mrzw731** [comment]
Thank you very much Lu. The issue has been fixed after changing the precision to float64.
