### ISSUE TITLE
[Question] Integro-differential equations

### ISSUE THREAD

**Issue by kookma** [lululxvi/deepxde#311]
Is it possible to solve integro differential equations with deepxde?

In transport of facilitated membrane! a component react and diffuse through a membrane! The model results in a set of integro differential equations as described below [1]

![image](https://user-images.githubusercontent.com/830394/122346008-bfb2b400-cf5d-11eb-930c-d6a9e418d7f5.png)
![img_337_Idle](https://user-images.githubusercontent.com/830394/122346231-fab4e780-cf5d-11eb-96b9-41cac3bea8be.png)
![img_338_msedge](https://user-images.githubusercontent.com/830394/122346257-00aac880-cf5e-11eb-865e-f1ede489afc9.png)

Is it possible to implement this in deepxde?

Ref:
[1] https://www.sciencedirect.com/science/article/abs/pii/S0011916409007723?via%3Dihub

**Comment by lululxvi** [comment]
So basically you try to constrain the C_L and C_ML such that \int (C_L + C_ML) = a constant, right?

**Comment by kookma** [comment]
Yes, that's true!

**Comment by lululxvi** [comment]
This is doable. Actually, I have a similar question in https://arxiv.org/abs/2102.04626 . The code will be uploaded to https://github.com/lululxvi/hpinn soon

**Comment by kookma** [comment]
Much appreciated!
