### ISSUE TITLE
use of lambda function

### ISSUE THREAD

**Issue by ian204** [lululxvi/deepxde#315]
Hello Lu,
I am trying to understand the proper use of lambda function used when defining, for example, BCs. I have read your DeepXDE guide but in certain instances the use of lambda is still obscure to me. For example, in the code Beltrami_flow.py you use it as follows. 

Thank you for any comment.
Ian.

**boundary_condition_u = dde.DirichletBC(
        spatio_temporal_domain, u_func, lambda _, on_boundary: on_boundary, component=0
)**
- first, what is the difference of this code with the following code (without lambda)
 **boundary_condition_u = dde.DirichletBC(
        spatio_temporal_domain, u_func, on_boundary, component=0
)**
It seems to me they are equivalent, and if so, why one uses the lambda function?

- second, what really the function lambda does in this case, and what is the logic behind it? it takes the strange parameter _ and on_boundary and returns on_boundary; does **lambda _, on boundary: on_boundary** is equivalent to "run the on_boundary function, with one parameter equal to on_boundary and the other, represented by _, being whatever value the systems has stored for it"?

**Comment by lululxvi** [comment]
You don't have to use `lambda` if you don't understand this Python grammer well. See https://deepxde.readthedocs.io/en/latest/demos/poisson.1d.dirichlet.html for how to implement the function to check the boundary location.
