### ISSUE TITLE
Errors while running "fractional_Poisson_2d_inverse.py" in examples.

### ISSUE THREAD

**Issue by Song921012** [lululxvi/deepxde#318]
While runing "fractional_Poisson_2d_inverse.py" in examples, I found an inconsistency between "fpde.py" and "pde.py". In "fpde.py", code shows train_distribution="sobol". However in "pde.py", it use "Sobol"  (Capital).  Maybe "Sobol" is right. I am not sure.

**Comment by lululxvi** [comment]
Thanks. You are right. I have fixed it.
