### ISSUE TITLE
What's the principle to set the number of residual points of BC, IC and equation appropriately?

### ISSUE THREAD

**Issue by WANGFYPHYS** [lululxvi/deepxde#319]
Hi, Lu Lu! Thank you for your excellent DeepXDE library. Here I have a question.

What's the principle to set the number of residual points of BC, IC and equation appropriately?
Or in other words, what’s the appropriate number relationship between the three items for a certain question to get the best NN more quikly?

I have read your DeepXDE paper(Lu L, Meng X, Mao Z, et al. DeepXDE: A deep learning library for solving differential equations[J]. SIAM Review, 2021, 63(1): 208-228.). It should be an open question. Could I hear some your experience?

By the way, in my question, the boundary is a rectangle: q [-16 fm, 48 fm] * v [-0.02 c, 0.03 c]. The time domain is t [0, 900 fm/c]. Here fm, c, fm/c are the units of length, speed and time respectively.

Thank you very much!

**Comment by lululxvi** [comment]
It depends on the specific problem and the smoothness of the solution. You can assume you are using finite different, then compute the number of points inside and on the boundary, and then tune the numbers based on the error.

**Comment by WANGFYPHYS** [comment]
Hi! @lululxvi

Thanks for your reply! After lots of attempt, here I have another question to bother you.

In the expression of BC and IC, whether I can use a function f(y) to write the conditions instead of f(x)? Should I make some changes with the DeepXDE code? How to achieve it?

The solution of my PDE is w(q, v, t). Because its large range(from ~10^(-30) to ~10^2), I need to make a transformation w(q, v, t) = e^u(q, v , t). The original BC & IC are w(q’, v’, t) = 0 & w(q, v, t = 0) = f(q, v). Now, the new BC & IC are changed correspondingly. It is not appropriate to give u(q’, v’, t) a specific value (like -20 or -30) simply after a detailed analysis with my problem. So, I still want to use the original expression to write the new BC & IC e^u(q’, v’, t) = 0 & e^u(q, v, t = 0) = f(q, v). Here u(q, v, t) is the solution I need to solve (then, I can get w(q, v, t)), and cannot be written as a function of (q, v, t) explicitly. Then, the question is appeared.

Thank you for your help again!

**Comment by WANGFYPHYS** [comment]
@lululxvi :

Recently, I have changed the “boundary_conditions.py” code in DeepXDE library. It seemed worked.

With the “class DirichletBC(BC)” module, I changed `return outputs[beg:end, self.component : self.component + 1] – values`
to `return np.exp( outputs[beg:end, self.component : self.component + 1] ) – values`. With this change, the BC loss could reach a very high accuracy.

Whether it is right? Need your double check. :)

In the same way, I change “initial_condition.py”. an error occurs:

_NotImplementedError: Cannot convert a symbolic Tensor (cond/strided_slice_2:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported_

Then, I change “np.exp” to “tf.exp” and it works. But the IC loss accuracy cannot reach beyond 10^(-6). “dde.config.real.set_float64()” is in my code and my tensorflow version is 2.5.0.

How can I solve this problem? Bother you again…

**Comment by WANGFYPHYS** [comment]
@lululxvi :

Recently, I have changed the “boundary_conditions.py” code in DeepXDE library. It seemed worked.

With the “class DirichletBC(BC)” module, I changed `return outputs[beg:end, self.component : self.component + 1] – values`
to `return np.exp( outputs[beg:end, self.component : self.component + 1] ) – values`. With this change, the BC loss could reach a very high accuracy.

Whether it is right? Need your double check. :)

In the same way, I change “initial_condition.py”. an error occurs:

_NotImplementedError: Cannot convert a symbolic Tensor (cond/strided_slice_2:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported_

Then, I change “np.exp” to “tf.exp” and it works. But the IC loss accuracy cannot reach beyond 10^(-6). “dde.config.real.set_float64()” is in my code and my tensorflow version is 2.5.0.

How can I solve this problem? Bother you again…

**Comment by lululxvi** [comment]
Should it be `tf.exp` instead of `np.exp` also in BC? Otherwise it looks good.

Do you also try L-BFGS? But usually the optimization is really hard to reach 1e-6... You can also use hard constraints for IC/BC

**Comment by WANGFYPHYS** [comment]
Thank you @lululxvi 

I have changed `np.exp` to `tf.exp` in BC and IC. It seems that optimizers in tensorflow don’t support `float64`, just only `float32`. I’m a newcomer to use tensorflow and not sure of this. 

As for _L-BFGS-B_, it is an excellent optimizer. This optimizer seems coming from `scipy`. Sometimes, it get an error: 

```
lbfgsb.py:439: RuntimeWarning: divide by zero encountered in true_divide
  self.rho = 1 / np.einsum('ij,ij->i', sk, yk)
```

Maybe I should change the value of `gtol` or `eps` in _train.py_ to avoid this problem.

Thanks! Good rest!

**Comment by lululxvi** [comment]
- See FAQ on how to use float64 in DeepXDE.
- You can ignore the warning in most times, unless you find there is something wrong in the results.

**Comment by WANGFYPHYS** [comment]
- Yeah, I have posted that ` dde.config.real.set_float64()` was in my code. I mean it seems that some modules in tensorflow don’t support float64 data type.

- Ok, I will try to ignore the waring if there is nothing wrong in the results.

Thank you.
