### ISSUE TITLE
MFNN predictions

### ISSUE THREAD

**Issue by ClausTrost** [lululxvi/deepxde#324]
Hi Lu,

I use a MFNN to predict data, I know that I have to transform the new test data using the scaler_x inside the original training data and I know how to handle the input. I usually do it similar to the code below:

```
X_test_scaled=data.scaler_x.transform(X_test)

def predict(model, features, x):
    results=[]
    for element in x:
        results.append(model.predict(element.reshape(1, len(features))))
    return results

prediction=predict(model, features, X_test_scaled)
```

Predict now always leads to two predictions [prediction_1, prediction_2] where prediction_2 is the endoutput of the MFNN in my point of view. And prediction_1 is the output from the Low fidelity Neural Network, right?

I just want to check if I'm right, because I haven't found it in the docs, yet.

Thank you very much.

Cheers,
Claus

**Comment by lululxvi** [comment]
Yes, you are right. You can also check the examples at https://github.com/lululxvi/deep-learning-for-indentation
