### ISSUE TITLE
Method to construct a structural frame in Deepxde

### ISSUE THREAD

**Issue by haha1250** [lululxvi/deepxde#327]
Hi Lu Lu,

I am looking for a method to construct a structural frame as in the picture below. I am thinking of using CSGUnion to connect two Interval geometry, however, I do not know how to set the square angle of the frame. Could you please suggest a possible way to construct it?
![download](https://user-images.githubusercontent.com/85663269/124432561-f54bff80-dd9b-11eb-8d3b-9042ff5843da.png)

Thanks

**Comment by lululxvi** [comment]
You can use `Polygon` https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#deepxde.geometry.geometry_2d.Polygon
