### ISSUE TITLE
loading the exact values in inverse problems

### ISSUE THREAD

**Issue by 78MFChemeng** [lululxvi/deepxde#330]
Dear Dr.LuLu
Hello
Let me first appreciate you to sharing of PINN codes but a questions:
In inverse  problems like reaction-inverse, you have loaded the concentration distribution data and you have used them in the input of PointSetBC as the exact values, but how we can have the exact values before solving problems for the first time?

**Comment by lululxvi** [comment]
This is the measurement you have to infer the unknown hyperparameters. This is how the inverse problems are defined.
