### ISSUE TITLE
Moving Domain

### ISSUE THREAD

**Issue by smurf-17** [lululxvi/deepxde#332]
Hello Dr.Lu
Thanks for your great library. I am new to learning so sorry about the basic question. I am trying to solve a question of multiphase flow and require a moving domain so is it possible to have a moving domain over a stationary domain.

**Comment by lululxvi** [comment]
You can define a large domain, and then control all the training points by yourself.

**Comment by smurf-17** [comment]
Thankyou Dr Lu, It will be very helpful if you could share an example.

**Comment by lululxvi** [comment]
Unfortunately I don't have an example of this.
