### ISSUE TITLE
Boundary problem

### ISSUE THREAD

**Issue by ErfanTabatabaee** [lululxvi/deepxde#333]
Hi Dr. lu 
I face up with something weird
first I want run very simple problem
dy/dx = 2x

here is my code

```
import numpy as np
import deepxde as dde 

def ode(x, y):

	dy_dx = dde.grad.jacobian(y, x)

	return dy_dx - 2*x

def boundary_l(x, on_boundary):
	print("x=  ", x, "on_boundary=  ", on_boundary, "     type=   ", type(on_boundary and np.isclose(x,0)))
	return on_boundary and np.isclose(x,0)

geom = dde.geometry.Interval(0, 5)
bc = dde.DirichletBC(geom, lambda x: 0, boundary_l)

data = dde.data.PDE(geom, ode, bc, num_domain=50, num_boundary = 2, num_test = 80)
net = dde.maps.FNN([1]+ [3] + [1], "tanh", "Glorot uniform")

model = dde.Model(data, net)
model.compile("adam", lr = 0.001)

losshistory, train_state = model.train(epochs = 10000)
dde.saveplot(losshistory, train_state, isplot = True, show_plot = True)
```

and This give me error

>  return X[self.on_boundary(X, self.geom.on_boundary(X))]
> IndexError: arrays used as indices must be of integer (or boolean) type

when I print self.on_boundary(X, self.geom.on_boundary(X)) I get this 

[array([ True]) array([False]) False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False]

as you see the type of 0 and 1 index of matrix is different.
and in my boundary_l(above code) i print something look what gave me

_x=   [0.] on_boundary=   True      type=    <class 'numpy.ndarray'>
x=   [5.] on_boundary=   True      type=    <class 'numpy.ndarray'>
x=   [2.5] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.75] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.25] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.9375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.4375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.6875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.1875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.5625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.0625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.8125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.3125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.46875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.96875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.21875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.71875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.34375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.84375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.59375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.09375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.78125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.28125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.53125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.03125] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.40625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.90625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.65625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.15625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.234375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.734375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.984375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.484375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.109375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.609375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.359375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.859375] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.171875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.671875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.921875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.421875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [1.796875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.296875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [3.046875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.546875] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [0.390625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [2.890625] on_boundary=   False      type=    <class 'numpy.bool_'>
x=   [4.140625] on_boundary=   False      type=    <class 'numpy.bool_'>_

when on_boundary is True the return type is numpy.ndarray but in other situation is numpy.bool
I can fix it by changing return in boundary_l
`return np.isclose(x, 0)`
But it's not good because some of my num_domain goes to my boundary...

What can I do? is there any mistakes in my code?

**Comment by lululxvi** [comment]
Use
```python
return on_boundary and np.isclose(x[0], 0)
```
Here, `x` is always a d-dim array.
