### ISSUE TITLE
couple the boundary conditions at different nodes 

### ISSUE THREAD

**Issue by bondwbe** [lululxvi/deepxde#335]
Hello Lu and others,

I want to know if it is possible to couple the boundary conditions at different nodes in deepxde similar to that in FEM. something similar to the constraint equations described here: https://abaqus-docs.mit.edu/2017/English/SIMACAEGSARefMap/simagsa-t-definingconstraintequations.htm 

thank you.

**Comment by lululxvi** [comment]
I am not sure what you are trying to do, but PINN is mesh-free, and doesn't really have nodes and the basis.
