### ISSUE TITLE
DeepXde for inverse problems 

### ISSUE THREAD

**Issue by domxp** [lululxvi/deepxde#34]
I'm amazed by your work and as part of a project on PINNs, I would like to test the resolution of inverse problems with DeepXDE. But I'm lost, how do I use DeepXDE for inverse problems where we have to identify functions depending on x, not real parameters? I saw that it was possible thanks to your article "Physics-informed neural networks for inverse problems in nano-optics and metamaterials". 
Would it be possible to have an example like in the article with the corresponding code?

 Thank you for your reply !

**Comment by lululxvi** [comment]
There are documents, slides, and video in the README page, and some examples provided. You can read them first, and let me know if you have any questions.
