### ISSUE TITLE
Application in PDEs with Parameters having probability distributions

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#341]
Dear @lululxvi, 
is  Deepxde capable of solving system of coupled pdes with parameters having probability distribution?

**Comment by lululxvi** [comment]
system of coupled pdes --> Yes

I am not sure what you mean exactly "parameters having probability distribution". Do you mean SPDE?

**Comment by katayooneshkofti** [comment]
@lululxvi  Yes Exactly. I mean PDEs with stochastic parameters.

**Comment by lululxvi** [comment]
You can check [this paper](https://doi.org/10.1016/j.jcp.2019.07.048) for SPDE, but the algorithm is not in DeepXDE, although it can be implemented in DeepXDE.

**Comment by katayooneshkofti** [comment]
Thank you so much. is it possible for you to send over the source code of this paper? 
I have sent several emails to the corresponding author but unfortunately, I didn't get any answer.

**Comment by lululxvi** [comment]
Unfortunately I don't have the final code.

**Comment by katayooneshkofti** [comment]
@lululxvi, Can we utilize PI-GAN for the parametric uncertainty in PDEs (parameters with probability distributions? I mean the algorithm proposed by paper : Physics-Informed Generative Adversarial Networks for Stochastic Differential Equations



Read More: https://epubs.siam.org/doi/abs/10.1137/18M1225409?journalCode=sjoce3

**Comment by lululxvi** [comment]
It is not in DeepXDE yet.

**Comment by katayooneshkofti** [comment]
@lululxvi 
I know the overall model of PI_GAN and how to code it, is Deepxde capable of containing such a structure in addition to FNN? I want to be sure that I am putting my efforts in the right direction.

**Comment by lululxvi** [comment]
Yes, it is doable. You need to modify the network and the training procedure.
