### ISSUE TITLE
Different activation functions for each output of FNN

### ISSUE THREAD

**Issue by manojkt1991** [lululxvi/deepxde#346]
Dear Dr. @lululxvi,

Generally, I have seen something like this in the examples:
layer_size = [3] + [20] * 8 + [2]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

Here, a single activation function "tanh" can be assigned for all layers/nodes. Is it possible to have two different activation functions for the two outputs and have "tanh" for all the other layers. If not in the maps.FNN syntax, can this be achieved relatively easily with apply_output_transform?

Thanks,
Manoj,

**Comment by lululxvi** [comment]
You have to modify the code of FNN https://github.com/lululxvi/deepxde/blob/07773fda1f5cf2c84e0087b56007a87a5132d257/deepxde/maps/tensorflow_compat_v1/fnn.py#L67 , which is also easy to do.
