### ISSUE TITLE
how do you get the ground truth of the fem solutions?

### ISSUE THREAD

**Issue by zhaoguangyuan123** [lululxvi/deepxde#351]
Great work. I am relatively new to this area while I am pariticularly interested in the "Physics-informed neural networks for inverse problems in nano-optics and metamaterials" 
I am curious how you get the ground truth fem solutions.

Do you have any recommendations for open-source resources that I can refer to? 
Appreciate it
Guangyuan

**Comment by lululxvi** [comment]
You can use FEniCS.

**Comment by zhaoguangyuan123** [comment]
Thank you. 
I will check it out.
