### ISSUE TITLE
Time and space dependent boundary conditions

### ISSUE THREAD

**Issue by Patco96** [lululxvi/deepxde#352]
Hi! I am using deepxde with the navier stokes equations but I have not been able to set the boundary conditions properly.

I am considering 40 observation points and 100 measurements for each. Up to now, I have been setting the boundary conditions as a list of PointSetBC for each component (2 components). This leads to a really long list of boundary conditions.

Is there a better way to implement this?

**Comment by lululxvi** [comment]
I don't quite understand your question. Each variable has a BC, and thus the number BCs is equal to the number of variables. A PointSetBC can have a set of points, not a single point.

**Comment by Patco96** [comment]
Thank you! Even though you didn't understand the question, you answer was enough to do it 😄 

When trying to use PintSetBC I was passing both variables together and thought only one set of points could be passed at a time. Knowing that the number of BCs is equal to the number of variables was the key.

Thanks again!
