### ISSUE TITLE
error value at boundary

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#36]
while solving simple ODE example [ dy/dx = 0,  y(0) =0, domain =[0,1]   ]

the solution has a nice agreement with the exact solution but the error value for boundary condition is not equal to zero (approx error at that point is 0.00001).

I think, boundary value are well known for Diff eq, and the error should be equal to zero at that boundary point.

![ode_error](https://user-images.githubusercontent.com/61820415/81037860-c8fbd100-8ec1-11ea-9df0-6f52f5603c11.png)

**Comment by smao-astro** [comment]
Hi @SanjuSoni , maybe you are interested in this paper https://arxiv.org/abs/1904.06619.

**Comment by SanjuSoni** [comment]
Thanks, I'll ask further in case of not getting my answer from this research paper.

**Comment by lululxvi** [comment]
@SanjuSoni Thanks for providing the paper.

The idea is actually simple, see the second paragraph on Page 6 in the DeepXDE paper (https://arxiv.org/abs/1907.04502).

@SanjuSoni For your problem, by default DeepXDE uses a soft constraint for the IC. If you want a hard constraint, i.e., `y(0) = 0`, you can multiply the network output `N(x)` by `x`, i.e., the final network `N'(x)` is `N'(x) = x N(x)`. Obviously, `N'(0) = 0`. In DeepXDE, use the following code:
```python
net.outputs_modify(lambda x, y: x * y)
```

Here is an another example for the diffusion equation to satisfy both IC and BC exactly:
https://github.com/lululxvi/deepxde/blob/master/examples/diffusion_1d_exactBC.py

**Comment by SanjuSoni** [comment]
Now, I am getting the exact boundary condition satisfying at boundaries (for dy/dx = 0 , y(0) = 0 )


But, for second-order linear differential equation, I have got exact boundary values at one end only.

I have used differential equation: d2y/dx2 -1 = 0 , y(0) = 0, y(1) = 1,

for that I have written:    **net.outputs_modify(lambda x, y:  x* y)**    

because it would satisfy for both condition at 0 and 1.

but result That I got is as: 

![second order](https://user-images.githubusercontent.com/61820415/81049422-cc9c5180-8edb-11ea-9955-9aa9554a72f4.png)



I think at x = 1, the output value should have error 0.000.

**Comment by lululxvi** [comment]
Could you try
```
net.outputs_modify(lambda x, y: x + x * (1 - x) * y)
```

**Comment by SanjuSoni** [comment]
Thannks, It give me an idea to implement.

![Second_Order_Error](https://user-images.githubusercontent.com/61820415/81138378-7da7f800-8f7f-11ea-9c6c-af9cbe7706b8.png)

**Comment by ryabs07** [comment]
> Could you try
> 
> ```
> net.outputs_modify(lambda x, y: x + x * (1 - x) * y)
> ```

I am a little bit confused by this application of hard BC. Although the output transform function satisfies the required conditions when x = 0 or x = 1, wouldnt it also change the outcome for rest of the values of x?

**Comment by lululxvi** [comment]
See https://doi.org/10.1137/21M1397908
