### ISSUE TITLE
Directly import array ranther than func to Class IC

### ISSUE THREAD

**Issue by YouCantRedo** [lululxvi/deepxde#362]
Dear @lululxvi 
I want to ask a question about defining the initial question.
I have read your answer for issue #75, in this case, it seems ok to import an N by 1 array to replace the 'func' for Class IC. If I understand it correctly, you first generate an 'X' that satisfies 'on initial' condition and then substitute it to 'func' to get the result array. So I wonder if it is ok to directly import the result array when defining the initial condition because in many cases there is no 'func' that can represent the initial condition.

`u_initial = np.load("u1.npy")
u_initial = u_initial.flatten()[:, None]`
` ic = dde.IC(geomtime, lambda x: u_initial, lambda _, on_initial: on_initial, component=0)`

In fact, I have tried it and it runs ok, but I did not find how you achieve this in your code, so I don't know if my result is correct, so I want to confirm with you.

**Comment by lululxvi** [comment]
You can directly use `PointsetBC` https://deepxde.readthedocs.io/en/latest/modules/deepxde.icbcs.html#deepxde.icbcs.boundary_conditions.PointSetBC

**Comment by YouCantRedo** [comment]
@lululxvi Thank you very much for your answer! 
(Maybe you can check issue #284 and comment on that issue)
