### ISSUE TITLE
Ways to specify known function in the loss function and customised boundary locations?

### ISSUE THREAD

**Issue by YingHH1** [lululxvi/deepxde#365]
Hi Lulu,

I hope you are well.

There are 2 questions that I would like to ask you for advice:

The first question is regarding when one of the governing equations is of the form dx/da*dy/db-dy/da*dx/db=A(a,b), where x=x(a,b,t), y=y(a,b,t) and A(a,b) is a known time-invariant quantity and it can be determined at t=0 by the initial values x(a,b,0) and y(a,b,0). The spatial/time domain is [a,b,t] in [[0 1], [0 1], [0 1]]. The quantity A(a,b) is present in all governing equations. My question is how do I put this in the residual loss function without also solving for A(a,b) since it is already known?

The second question that I have is to do with the boundary conditions. Rather than setting all four boundaries for both x and y, I only wish to set x(0,b,t)=0, x(1,b,t)=1, y(0,b,t)=0 and dx/dt(0,b,t)=0, dx/dt(1,b,t)=0, dy/dt(0,b,t)=0. Could you tell me a way to implement the above boundary conditions in DeepXDE?

Many thanks,

Ying

**Comment by lululxvi** [comment]
- If you have the analytical form of A(a,b), then just use it when defining the PDE residual
- Use `on_boundary`. See https://deepxde.readthedocs.io/en/latest/demos/poisson.1d.dirichlet.html and lots of examples in FAQ

**Comment by YingHH1** [comment]
Thanks for the help. 

So for a rectangular domain with boundary conditions x(a=0,b,t)=0, x(a=L,b,t)=L, y(a,b=0,t)=0, I have written these boundary conditions as:
def boundary_a0(a, _):
    return np.isclose(a[0], 0)

def boundary_aL(a, _):
    return np.isclose(a[0], L)

def boundary_b0(a, _):
    return np.isclose(a[1], 0)

boundary_condition_a0 = dde.DirichletBC(spatio_temporal_domain, x_func_tf, boundary_a0, component=0)
boundary_condition_aL = dde.DirichletBC(spatio_temporal_domain, x_func_tf, boundary_aL, component=0)
boundary_condition_b0 = dde.DirichletBC(spatio_temporal_domain, y_func_tf, boundary_b0, component=1)

where x_func_tf, y_func_tf return the exact linear solutions which satisfy the above boundary conditions

Could you let me know if this is the correct way to impose the boundary conditions?

**Comment by lululxvi** [comment]
Your code is correct. But `x_func_tf` is a numpy function, not tf. The same for x_func_tf and y_func_tf.
