### ISSUE TITLE
Poor performance 2D heat equation

### ISSUE THREAD

**Issue by andrea-sacchetti** [lululxvi/deepxde#366]
Hi

I am trying to solve the following PDE:

![image](https://user-images.githubusercontent.com/10077202/132007690-2769cc2d-104b-45c7-8e1e-13290964247d.png)

where 
![image](https://user-images.githubusercontent.com/10077202/132007806-49a6da4e-0846-4e50-a0df-1b6809b741e6.png)

This has the following analytical solution: 
![image](https://user-images.githubusercontent.com/10077202/132007862-b78ec956-1de3-4cda-972a-564b97adbdad.png)
which I use to define Dirichlet boundary-conditions on all boundaries of the domain. The domain is a L-shape, i.e. a square of side _b_ with the top right quadrant excluded and it has a circular hole of diameter _a_ centred at _x_ = _b_/4, _y_ = _b_/2 so that the region around the singularity is not part of the domain.
![image](https://user-images.githubusercontent.com/10077202/132007624-e455afdb-4b1c-4120-b48f-408b5571387f.png)

The issue I am having is that the quality of the result is very poor as train loss is way too large and test loss is abysmal: 

```
'compile' took 0.603443 s

Initializing variables...
Training model...

Step      Train loss                        Test loss                         Test metric
0         [1.94e+02, 2.32e-01, 6.67e-01]    [8.92e+01, 2.32e-01, 6.67e-01]    []  
1000      [4.85e-01, 9.66e-01, 3.98e-01]    [4.43e-01, 9.66e-01, 3.98e-01]    []  
2000      [3.12e-01, 8.38e-01, 3.70e-01]    [2.97e-01, 8.38e-01, 3.70e-01]    []  
3000      [2.68e-01, 7.52e-01, 3.30e-01]    [2.65e-01, 7.52e-01, 3.30e-01]    []  
4000      [2.29e-01, 7.09e-01, 2.98e-01]    [2.28e-01, 7.09e-01, 2.98e-01]    []  
5000      [2.11e-01, 6.83e-01, 2.86e-01]    [2.04e-01, 6.83e-01, 2.86e-01]    []  
6000      [1.96e-01, 6.68e-01, 2.79e-01]    [1.89e-01, 6.68e-01, 2.79e-01]    []  
7000      [1.79e-01, 6.63e-01, 2.74e-01]    [1.77e-01, 6.63e-01, 2.74e-01]    []  
8000      [1.68e-01, 6.58e-01, 2.71e-01]    [1.65e-01, 6.58e-01, 2.71e-01]    []  
9000      [1.61e-01, 6.54e-01, 2.69e-01]    [1.59e-01, 6.54e-01, 2.69e-01]    []  
10000     [1.56e-01, 6.49e-01, 2.66e-01]    [1.53e-01, 6.49e-01, 2.66e-01]    []  

Best model at step 10000:
  train loss: 1.07e+00
  test loss: 1.07e+00
  test metric: []

'train' took 118.465970 s

Compiling model...
'compile' took 1.181491 s

Training model...

Step      Train loss                        Test loss                         Test metric
10000     [1.56e-01, 6.49e-01, 2.66e-01]    [1.53e-01, 6.49e-01, 2.66e-01]    []  
11000     [1.37e-01, 5.99e-01, 2.21e-01]                                          
12000     [1.17e-01, 5.55e-01, 1.97e-01]                                          
13000     [1.04e-01, 5.36e-01, 1.84e-01]                                          
14000     [1.05e-01, 5.07e-01, 1.68e-01]                                          
15000     [1.07e-01, 4.79e-01, 1.61e-01]                                          
16000     [1.18e-01, 4.46e-01, 1.45e-01]                                          
17000     [1.63e-01, 3.81e-01, 1.14e-01]                                          
18000     [2.14e-01, 2.11e-01, 6.40e-02]                                          
19000     [1.87e-01, 7.24e-02, 2.14e-02]                                          
20000     [1.24e-01, 1.99e-02, 6.37e-03]                                          
21000     [7.09e-02, 8.89e-03, 4.26e-03]                                          
22000     [4.56e-02, 3.70e-03, 1.40e-03]                                          
23000     [3.10e-02, 1.27e-03, 1.08e-03]                                          
INFO:tensorflow:Optimization terminated with:
  Message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  Objective function value: 0.021997
  Number of iterations: 13111
  Number of functions evaluations: 13984
23984     [2.00e-02, 1.30e-03, 6.50e-04]    [4.13e-02, 1.30e-03, 6.50e-04]    []  

Best model at step 23984:
  train loss: 2.20e-02
  test loss: 4.32e-02
  test metric: []

'train' took 345.266056 s
```

![image](https://user-images.githubusercontent.com/10077202/132374621-4607ed70-dab4-4a17-9019-7936940639ec.png)
![image](https://user-images.githubusercontent.com/10077202/132374637-0486d0a1-dac8-43db-bfc0-dd6dd769ad5d.png)
![image](https://user-images.githubusercontent.com/10077202/132374650-d4442b21-7e45-4aa7-994a-a8751cc61b25.png)

I indeed verified that the obtained solution deviates significantly from the exact one and that it does a poor job at satisfied the condition imposed by the PDE on the domain:

![image](https://user-images.githubusercontent.com/10077202/132374696-e042464b-f8b5-49a2-a4dc-3a7406235ab9.png)
![image](https://user-images.githubusercontent.com/10077202/132374714-c97e89b4-5451-45aa-b829-9ef2ff51912c.png)
![image](https://user-images.githubusercontent.com/10077202/132374733-20001a4e-5d12-4e17-a6f7-54db2f539831.png)
![image](https://user-images.githubusercontent.com/10077202/132374748-97217661-4170-4fdd-bc82-cfa01c2c653b.png)

Despite my numerous attempts at playing with the hyperparameters or finding some mathematical mistake I wasn't able to make any progress for quite some time. Therefore, I decided to refer to the community in the hope somebody can help. 

Here is my code for reference:

```
import deepxde as dde

b = 1.0
a = 0.25
c1 = 0.1

def exact_sol(r):
    x = r[:, 0:1]
    y = r[:, 1:]
    return c1 / ((x - b/4)**2 + (y - b/2)**2)**0.5


def pde(r, T):
    dT_xx = dde.grad.hessian(T, r, i=0, j=0)
    dT_yy = dde.grad.hessian(T, r, i=1, j=1)
    x = r[:, 0:1]
    y = r[:, 1:]
    return dT_xx + dT_yy - c1 / ((x - b/4)**2 + (y - b/2)**2)**1.5


def ext_boundary(r, on_boundary):
    x, y = r
    return on_boundary and ((x - b/4)**2 + (y - b/2)**2) > (a / 2)**2


def int_boundary(r, on_boundary):
    x, y = r
    return on_boundary and (((x - b/4)**2 + (y - b/2)**2) == (a / 2)**2)


geom = dde.geometry.Polygon([[0, 0], [b, 0], [b, b/2], [b/2, b/2], [b/2, b], [0, b]]) - dde.geometry.Disk([b/4, b/2], a / 2)

ext_bc = dde.DirichletBC(geom, exact_sol, ext_boundary)
int_bc = dde.DirichletBC(geom, exact_sol, int_boundary)

data = dde.data.PDE(geom, pde, [ext_bc, int_bc], num_domain=1200, num_boundary=120, num_test=1500, solution=exact_sol)
net = dde.maps.FNN([2] + [50] * 2 + [1], "tanh", "Glorot uniform")
model = dde.Model(data, net)

model.compile("adam", lr=0.001)
model.train(epochs=10000)
model.compile("L-BFGS-B")

losshistory, train_state = model.train(epochs = 50000)

dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```

**Comment by andrea-sacchetti** [comment]
Never mind. I think I figured it out with a few tweaks (don't ask me how I got there because I honestly don't know). Here is the "winning" code for those interested:
```
import deepxde as dde

b = 1.0
a = 0.25
c1 = 0.1

def exact_sol(r):
    x = r[:, 0:1]
    y = r[:, 1:]
    return c1 / ((x - b/4)**2 + (y - b/2)**2)**0.5


def pde(r, T):
    dT_xx = dde.grad.hessian(T, r, i=0, j=0)
    dT_yy = dde.grad.hessian(T, r, i=1, j=1)
    x = r[:, 0:1]
    y = r[:, 1:]
    return dT_xx + dT_yy - c1 / ((x - b/4)**2 + (y - b/2)**2)**1.5


def ext_boundary(r, on_boundary):
    x, y = r
    return on_boundary and ((x - b/4)**2 + (y - b/2)**2) > (a / 2)**2


def int_boundary(r, on_boundary):
    x, y = r
    return on_boundary and np.isclose(((x - b/4)**2 + (y - b/2)**2), (a / 2)**2)


geom = dde.geometry.Polygon([[0, 0], [b, 0], [b, b/2], [b/2, b/2], [b/2, b], [0, b]]) - dde.geometry.Disk([b/4, b/2], a / 2)

ext_bc = dde.DirichletBC(geom, exact_sol, ext_boundary)
int_bc = dde.DirichletBC(geom, exact_sol, int_boundary)

data = dde.data.PDE(geom, pde, [ext_bc, int_bc], num_domain=1200, num_boundary=120, num_test=1500, solution=exact_sol)

net = dde.maps.FNN([2] + [10] * 4 + [1], "tanh", "Glorot uniform")
model = dde.Model(data, net)

model.compile("adam", lr=0.001)
model.train(epochs=10000, batch_size = 32)

model.compile("L-BFGS-B")
dde.optimizers.set_LBFGS_options(
    maxcor=50,
    ftol=1e-20,
    maxiter=1e5,
)
losshistory, train_state = model.train(epochs = 50000, batch_size = 32)

dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```

And here are the results:
```
Warning: CSGDifference.uniform_points not implemented. Use random_points instead.
Compiling model...
Building feed-forward neural network...
'build' took 0.090602 s

'compile' took 1.051511 s

Initializing variables...
Training model...

Step      Train loss                        Test loss                         Test metric
0         [2.01e+02, 3.35e-01, 7.96e-01]    [7.41e+01, 3.35e-01, 7.96e-01]    []  
1000      [8.78e-01, 9.52e-01, 3.94e-01]    [7.09e-01, 9.52e-01, 3.94e-01]    []  
2000      [2.98e-01, 1.05e+00, 3.83e-01]    [2.38e-01, 1.05e+00, 3.83e-01]    []  
3000      [2.28e-01, 1.00e+00, 3.80e-01]    [1.94e-01, 1.00e+00, 3.80e-01]    []  
4000      [1.89e-01, 9.44e-01, 3.65e-01]    [1.64e-01, 9.44e-01, 3.65e-01]    []  
5000      [1.71e-01, 8.90e-01, 3.50e-01]    [1.45e-01, 8.90e-01, 3.50e-01]    []  
6000      [1.79e-01, 8.37e-01, 3.37e-01]    [1.64e-01, 8.37e-01, 3.37e-01]    []  
7000      [1.81e-01, 7.96e-01, 3.26e-01]    [1.67e-01, 7.96e-01, 3.26e-01]    []  
8000      [1.74e-01, 7.70e-01, 3.19e-01]    [1.64e-01, 7.70e-01, 3.19e-01]    []  
9000      [1.68e-01, 7.51e-01, 3.13e-01]    [1.62e-01, 7.51e-01, 3.13e-01]    []  
10000     [1.65e-01, 7.28e-01, 3.05e-01]    [1.61e-01, 7.28e-01, 3.05e-01]    []  

Best model at step 10000:
  train loss: 1.20e+00
  test loss: 1.19e+00
  test metric: []

'train' took 104.322579 s

Compiling model...
'compile' took 1.940588 s

Training model...

Step      Train loss                        Test loss                         Test metric
10000     [1.65e-01, 7.28e-01, 3.05e-01]    [1.61e-01, 7.28e-01, 3.05e-01]    []  
11000     [6.49e-02, 5.62e-02, 2.05e-02]                                          
12000     [8.73e-03, 2.39e-03, 1.12e-03]                                          
13000     [4.50e-03, 5.01e-04, 6.76e-04]                                          
14000     [2.74e-03, 2.52e-04, 3.42e-04]                                          
15000     [1.74e-03, 1.89e-04, 1.91e-04]                                          
INFO:tensorflow:Optimization terminated with:
  Message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  Objective function value: 0.001681
  Number of iterations: 5212
  Number of functions evaluations: 5504
15504     [1.35e-03, 1.51e-04, 1.85e-04]    [2.76e-03, 1.51e-04, 1.85e-04]    []  

Best model at step 15504:
  train loss: 1.68e-03
  test loss: 3.10e-03
  test metric: []

'train' took 286.336498 s
```
![image](https://user-images.githubusercontent.com/10077202/132453522-a8cd4e50-4fc0-44e5-ac6f-dff11fbff03e.png)
![image](https://user-images.githubusercontent.com/10077202/132453550-438f3428-96a3-4698-a01e-27e160b107ae.png)
![image](https://user-images.githubusercontent.com/10077202/132453565-99a55e23-dc83-498a-aa72-333dea557bf4.png)

Performance looks indeed good now:
![image](https://user-images.githubusercontent.com/10077202/132453605-af401c9d-88ac-4f24-bb88-82ffffdf7ac6.png)
![image](https://user-images.githubusercontent.com/10077202/132453666-828d0d10-fa22-4021-81f2-c6f99b2b8845.png)
![image](https://user-images.githubusercontent.com/10077202/132453676-90e7fe52-6a6b-4472-996d-93366c24fd76.png)
![image](https://user-images.githubusercontent.com/10077202/132453700-2b641f21-7c31-4438-8aa4-068312d53f71.png)

It would be cool if we managed as a small community to develop some sort of "guidelines" and "best practices" to avoid this kind of issues.

**Comment by TianjieZhang1993** [comment]
> Never mind. I think I figured it out with a few tweaks (don't ask me how I got there because I honestly don't know). Here is the "winning" code for those interested:
> 
> ```
> import deepxde as dde
> 
> b = 1.0
> a = 0.25
> c1 = 0.1
> 
> def exact_sol(r):
>     x = r[:, 0:1]
>     y = r[:, 1:]
>     return c1 / ((x - b/4)**2 + (y - b/2)**2)**0.5
> 
> 
> def pde(r, T):
>     dT_xx = dde.grad.hessian(T, r, i=0, j=0)
>     dT_yy = dde.grad.hessian(T, r, i=1, j=1)
>     x = r[:, 0:1]
>     y = r[:, 1:]
>     return dT_xx + dT_yy - c1 / ((x - b/4)**2 + (y - b/2)**2)**1.5
> 
> 
> def ext_boundary(r, on_boundary):
>     x, y = r
>     return on_boundary and ((x - b/4)**2 + (y - b/2)**2) > (a / 2)**2
> 
> 
> def int_boundary(r, on_boundary):
>     x, y = r
>     return on_boundary and np.isclose(((x - b/4)**2 + (y - b/2)**2), (a / 2)**2)
> 
> 
> geom = dde.geometry.Polygon([[0, 0], [b, 0], [b, b/2], [b/2, b/2], [b/2, b], [0, b]]) - dde.geometry.Disk([b/4, b/2], a / 2)
> 
> ext_bc = dde.DirichletBC(geom, exact_sol, ext_boundary)
> int_bc = dde.DirichletBC(geom, exact_sol, int_boundary)
> 
> data = dde.data.PDE(geom, pde, [ext_bc, int_bc], num_domain=1200, num_boundary=120, num_test=1500, solution=exact_sol)
> 
> net = dde.maps.FNN([2] + [10] * 4 + [1], "tanh", "Glorot uniform")
> model = dde.Model(data, net)
> 
> model.compile("adam", lr=0.001)
> model.train(epochs=10000, batch_size = 32)
> 
> model.compile("L-BFGS-B")
> dde.optimizers.set_LBFGS_options(
>     maxcor=50,
>     ftol=1e-20,
>     maxiter=1e5,
> )
> losshistory, train_state = model.train(epochs = 50000, batch_size = 32)
> 
> dde.saveplot(losshistory, train_state, issave=True, isplot=True)
> ```
> 
> And here are the results:
> 
> ```
> Warning: CSGDifference.uniform_points not implemented. Use random_points instead.
> Compiling model...
> Building feed-forward neural network...
> 'build' took 0.090602 s
> 
> 'compile' took 1.051511 s
> 
> Initializing variables...
> Training model...
> 
> Step      Train loss                        Test loss                         Test metric
> 0         [2.01e+02, 3.35e-01, 7.96e-01]    [7.41e+01, 3.35e-01, 7.96e-01]    []  
> 1000      [8.78e-01, 9.52e-01, 3.94e-01]    [7.09e-01, 9.52e-01, 3.94e-01]    []  
> 2000      [2.98e-01, 1.05e+00, 3.83e-01]    [2.38e-01, 1.05e+00, 3.83e-01]    []  
> 3000      [2.28e-01, 1.00e+00, 3.80e-01]    [1.94e-01, 1.00e+00, 3.80e-01]    []  
> 4000      [1.89e-01, 9.44e-01, 3.65e-01]    [1.64e-01, 9.44e-01, 3.65e-01]    []  
> 5000      [1.71e-01, 8.90e-01, 3.50e-01]    [1.45e-01, 8.90e-01, 3.50e-01]    []  
> 6000      [1.79e-01, 8.37e-01, 3.37e-01]    [1.64e-01, 8.37e-01, 3.37e-01]    []  
> 7000      [1.81e-01, 7.96e-01, 3.26e-01]    [1.67e-01, 7.96e-01, 3.26e-01]    []  
> 8000      [1.74e-01, 7.70e-01, 3.19e-01]    [1.64e-01, 7.70e-01, 3.19e-01]    []  
> 9000      [1.68e-01, 7.51e-01, 3.13e-01]    [1.62e-01, 7.51e-01, 3.13e-01]    []  
> 10000     [1.65e-01, 7.28e-01, 3.05e-01]    [1.61e-01, 7.28e-01, 3.05e-01]    []  
> 
> Best model at step 10000:
>   train loss: 1.20e+00
>   test loss: 1.19e+00
>   test metric: []
> 
> 'train' took 104.322579 s
> 
> Compiling model...
> 'compile' took 1.940588 s
> 
> Training model...
> 
> Step      Train loss                        Test loss                         Test metric
> 10000     [1.65e-01, 7.28e-01, 3.05e-01]    [1.61e-01, 7.28e-01, 3.05e-01]    []  
> 11000     [6.49e-02, 5.62e-02, 2.05e-02]                                          
> 12000     [8.73e-03, 2.39e-03, 1.12e-03]                                          
> 13000     [4.50e-03, 5.01e-04, 6.76e-04]                                          
> 14000     [2.74e-03, 2.52e-04, 3.42e-04]                                          
> 15000     [1.74e-03, 1.89e-04, 1.91e-04]                                          
> INFO:tensorflow:Optimization terminated with:
>   Message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
>   Objective function value: 0.001681
>   Number of iterations: 5212
>   Number of functions evaluations: 5504
> 15504     [1.35e-03, 1.51e-04, 1.85e-04]    [2.76e-03, 1.51e-04, 1.85e-04]    []  
> 
> Best model at step 15504:
>   train loss: 1.68e-03
>   test loss: 3.10e-03
>   test metric: []
> 
> 'train' took 286.336498 s
> ```
> 
> ![image](https://user-images.githubusercontent.com/10077202/132453522-a8cd4e50-4fc0-44e5-ac6f-dff11fbff03e.png) ![image](https://user-images.githubusercontent.com/10077202/132453550-438f3428-96a3-4698-a01e-27e160b107ae.png) ![image](https://user-images.githubusercontent.com/10077202/132453565-99a55e23-dc83-498a-aa72-333dea557bf4.png)
> 
> Performance looks indeed good now: ![image](https://user-images.githubusercontent.com/10077202/132453605-af401c9d-88ac-4f24-bb88-82ffffdf7ac6.png) ![image](https://user-images.githubusercontent.com/10077202/132453666-828d0d10-fa22-4021-81f2-c6f99b2b8845.png) ![image](https://user-images.githubusercontent.com/10077202/132453676-90e7fe52-6a6b-4472-996d-93366c24fd76.png) ![image](https://user-images.githubusercontent.com/10077202/132453700-2b641f21-7c31-4438-8aa4-068312d53f71.png)
> 
> It would be cool if we managed as a small community to develop some sort of "guidelines" and "best practices" to avoid this kind of issues.

Hi andrea,
Can I see your code of imshowing the image,  especially how to dig a hole in the image ? Yours looks amazing.

**Comment by andrea-sacchetti** [comment]
Hi

Sorry for the late reply. I just used a colour map on a grid of points (101x101) where I excluded the ones not belonging to the domain.

**Comment by 123new-net** [comment]
@andrea-sacchetti Hi! 
I also want to ask you to share your drawing code. Because I also constructed a rectangle with a circle subtracted from the middle, but when I predicted the result later and drew it, the result would still be a complete rectangle. I'd like to take a page from your playbook.
Thanks！

**Comment by andrea-sacchetti** [comment]
I used this function to generate the points:
```
def grid_points(x_coord, y_coord, geom) :
    xx, yy = np.meshgrid(x_coord, y_coord)
    all_points = np.vstack((xx.flatten(), yy.flatten())).T
    selector = geom.inside(all_points)
    return all_points[selector]
```
then I made a color-map plot which you can do like this (matplotlib)
```
f = plt.figure()
f.suptitle("Exact")
p = plt.scatter(*(my_points.T), marker = 'o', c = exct)
plt.colorbar(p)
plt.gca().set_aspect(1)
plt.show()
```
or like this (plotly):
```
fig = make_subplots(
    rows = 4, cols = 1, 
    subplot_titles=("Exact", "Solution", "Deviation", "Loss-PDE"),
    vertical_spacing=0.02,
    )
fig.update_layout(width = 550, height = 1600,)
fig.add_trace(plotly.graph_objects.Scatter(
    x = (my_points.T)[0], 
    y = (my_points.T)[1], 
    marker = {"color": exct,
        "symbol": "square", "size": 16, "colorbar": {"title": "level", "len": 0.15, "y": 0.875}},
    mode = "markers", showlegend = False,),
    row = 1, col = 1, 
    )
# Iterate over the other subplots as required
```
I hope this helps. Sorry for the late reply ;-)
