### ISSUE TITLE
i value not recognized

### ISSUE THREAD

**Issue by alieakins** [lululxvi/deepxde#367]
Hello, 

I am a novice at coding and ANNs, with about a year of experience. I am trying to solve a system of ODEs with the DeepXDE library, but have arrived at a problem which I am not sure how to solve. I have the following ode system set up for the library:
![image](https://user-images.githubusercontent.com/87545241/132073778-422f5d03-f8fa-4cbb-abfc-d91f0f3e0921.png)

but later on when I try to compile the model I get the error that i=3 is not valid. 
![image](https://user-images.githubusercontent.com/87545241/132073826-4e1103a6-601a-475e-aab8-68eb86c6a98a.png)

Why would only one of the ODEs be invalid?

**Comment by lululxvi** [comment]
What is your network size?
