### ISSUE TITLE
Few notices about installation instructions

### ISSUE THREAD

**Issue by engenegr** [lululxvi/deepxde#37]
Thank you very much for your work. I'm not ML specialist and I just tried your library for self-education. I met some issues running standard examples.

1. The first problem was that there is no explicit requirement for Python version. I'd like to understand if I have correct version before approaching to installations of any libraries.

2. I found that TensorFlow > v2 isn't working. It produces such error:

```
AttributeError: module 'tensorflow_core.python.keras.api._v2.keras.losses' has no attribute 'softmax_cross_entropy'
```

With TensorFlow == 1.15.2 I was able to proceed. Hint: it is good to have versions in your requirements.txt.

3. This problem could be related to Python version.
```
Traceback (most recent call last):
  File "ode_system.py", line 8, in <module>
    from deepxde.backend import tf
ModuleNotFoundError: No module named 'deepxde.backend'
```
Actually I don't know why you obfuscate TensorFlow module via your deepxde.backend module. So I got an example working via:

```
import tensorflow as tf
```

**Comment by lululxvi** [comment]
1. Python 3.6 or 3.7 is good.
2. If you install the version v0.6.1 through `conda` or `pip`, then it only supports Tensorflow 1, and you need to modify the `import` as your point 3.
3. If you clone the updated version in GitHub directly, then Tensorflow 1 and 2 can be used, and there is no need to modify the `import`.
