### ISSUE TITLE
How to change value of "t" in each iteration in DE system

### ISSUE THREAD

**Issue by richieakka** [lululxvi/deepxde#370]
Dear LuLu,

We need to solve the problem of the following type 
return [
        d_r_over_d_t - ((1+np.cos((np.pi * t )/12)) - 0.72*r),
        d_p_over_d_t - k1*r + k2*p,
        d_z_over_d_t - k2*p
    ]

Here, we need to vary the values of t along with solving equations for r,p,z.
If we use t = np.linspace(0, 48, 2000) in my pde_system, it seems to be reading the same value of t over every iteration. We need your help on how to resolve it and passing the values of t while calling "data = dde.data.PDE(geom, pde_system, [ic1, ic2, ic3], 4000, 2, num_test=100)"

Thanks
Hoping for your early response.

**Comment by richieakka** [comment]
Dear LuLu,

Kindly help us resolve our query. Thanking you in advance.

**Comment by richieakka** [comment]
Kindly guide how we can resolve it.

**Comment by lululxvi** [comment]
Do you want to use different t for different iterations? You can use the callback `PDEresample`, check diffusion_1d_resample.py in the example.
