### ISSUE TITLE
Handling division by zero when implementing the Laplace-Beltrami Operator

### ISSUE THREAD

**Issue by zhang-liu-official** [lululxvi/deepxde#373]
Hi Dr. Lu,

Thanks for this amazing contribution. 

I would like to use DeepXDE to solve Poisson equation on the 2-sphere, <img src="https://render.githubusercontent.com/render/math?math=\Delta u = f(\theta, \phi)">. 

The domain is on the surface of the 2-sphere (and not in the sphere). My current approach is to use reparameterization and sample points representing <img src="https://render.githubusercontent.com/render/math?math=(\theta, \phi)"> from the rectangular domain using the rectangle geometry module. Thus, I have the following boundary conditions:
- Dirichlet BC to make the solution unique: <img src="https://render.githubusercontent.com/render/math?math=u(0,0) = f(0, 0)">.
- Periodic BC to make the phi direction periodic: <img src="https://render.githubusercontent.com/render/math?math=u(0,\phi) = u(2 \pi,\phi )">.
- Periodic BC to make the theta direction periodic: <img src="https://render.githubusercontent.com/render/math?math=u(\theta,0) = u(\theta, \pi )">.

(Do you think this is the correct way of defining the pde in this case?)

```python
"""Backend supported: tensorflow.compat.v1"""
import deepxde as dde
from numpy.core.numeric import isclose
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import random
from deepxde.backend import tf

## useful reference: https://en.wikipedia.org/wiki/Laplace_operator#Coordinate_expressions
## Laplacian-beltrami operator in spherical coordinates for 2-sphere:
##                   https://en.wikipedia.org/wiki/Laplace%E2%80%93Beltrami_operator#Examples

# note thta u (the solution) is the y here!
def pde(x, y):
    ## adapted from Laplacian on disk example
    # (X1, X2, X3) = (x,y,z) = (sin(phi)cos(theta), sin(phi)sin(theta), cos(phi))
    theta, phi = x[:,0], x[:,1]
    theta = tf.reshape(theta, [-1,1])
    phi = tf.reshape(phi, [-1,1])

    dy_thetatheta = dde.grad.hessian(y, x, i=0, j=0)
    dy_phi = dde.grad.jacobian(y, x,i=0,j=1)
    dy_phiphi = dde.grad.hessian(y,x, i=1, j=1)

    lhs = dy_phiphi + tf.cos(phi)/tf.sin(phi) * dy_phi + tf.sin(phi) **(-2) * dy_thetatheta
    rhs = 3 * tf.cos(theta) ** 2 - 1
    return lhs - rhs         

def boundary0(x,_):
    ## theta phi
    theta, phi = x[0], x[1]
    return np.isclose(theta, 0) and np.isclose(phi, 0)

def boundary1(x,_):
    ## theta phi
    theta, phi = x[0], x[1]

    return (np.isclose(theta, 0) or np.isclose(theta, 2 * np.pi))

def boundary2(x,_):
    ## theta phi
    theta, phi = x[0], x[1]

    return (np.isclose(phi, 0) or np.isclose(phi, np.pi))

    return np.isclose(phi, np.pi)

def main():
    # theta in [0, 2pi] phi in [0, pi]
    geom = dde.geometry.Rectangle(xmin=[0, 0], xmax=[2 * np.pi, np.pi])

    bc0 = dde.DirichletBC(geom,lambda x: -1/3,boundary0,)
    bc1 = dde.PeriodicBC(geom, 1, boundary1,)
    bc2 = dde.PeriodicBC(geom, 0, boundary2,)

    data = dde.data.PDE(
        geom, pde, [bc0, bc1, bc2], num_domain=600, num_boundary=200, num_test = 1000)

    net = dde.maps.FNN([2] + [700] + [1], "tanh", "Glorot uniform")

    model = dde.Model(data, net)
    model.compile("adam", lr=0.001)
    
    losshistory, train_state = model.train(epochs=15000)
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

    X = geom.uniform_points(1000)
    y_pred = model.predict(X, operator = pde)
    y_pred = y_pred.reshape((y_pred.shape[0],1))
    np.savetxt("test.dat", np.hstack((X, y_pred)))

if __name__ == "__main__":
    main()
```

The training results: 

>Initializing variables...
Training model...
Step      Train loss                                  Test loss                                   Test metric
0         [nan, 1.11e-01, 9.75e-06, 1.01e-03]         [1.31e+00, 1.11e-01, 9.75e-06, 1.01e-03]    []  
1000      [nan, nan, nan, nan]                        [nan, nan, nan, nan]                        []  
2000      [nan, nan, nan, nan]                        [nan, nan, nan, nan]                        []  
3000      [nan, nan, nan, nan]                        [nan, nan, nan, nan]                        []  

I have verified that this is due to the division by zero when sin(phi) = 0, since this error disappeared when I delete the sin(phi) term from the expression for the spherical Laplacian-Beltrami operator. I am not aware how this can be avoided. Could you give some suggestions on this? What is the best practice when encountering division by zero in automatic differentiation? 

I also tried to change the Laplacian-Beltrami operator from spherical coordinates to cartesian coordinates in the pde definition:

```python 
def pde(x, y):
    ## adapted from Laplacian on disk example
    # (X1, X2, X3) = (x,y,z) = (sin(phi)cos(theta), sin(phi)sin(theta), cos(phi))
    theta, phi = x[:,0], x[:,1]
    theta = tf.reshape(theta, [-1,1])
    phi = tf.reshape(phi, [-1,1])

    X = tf.concat([tf.multiply(tf.sin(phi), tf.cos(theta)), tf.multiply(tf.sin(phi), tf.sin(theta)), tf.cos(phi)], axis = -1)
    dy_xx = dde.grad.hessian(y, X, i=0, j=0)
    dy_yy = dde.grad.hessian(y, X, i=1, j=1)
    dy_zz = dde.grad.hessian(y, X, i=2, j=2)
    lhs = dy_xx + dy_yy + dy_zz

    rhs = 3 * tf.cos(theta) ** 2 - 1
    return lhs - rhs     
```

However, this then gave this error message:

> Traceback (most recent call last):
  File "c:\Users\ifisa\Documents\venv\deepxde\Poisson_S2_reparameterization.py", line 103, in <module>
    main()
  File "c:\Users\ifisa\Documents\venv\deepxde\Poisson_S2_reparameterization.py", line 87, in main
    model.compile("adam", lr=0.001)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\utils\internal.py", line 53, in wrapper
    result = f(*args, **kwargs)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\model.py", line 105, in compile
    self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\model.py", line 125, in _compile_tensorflow_compat_v1
    losses = self.data.losses(self.net.targets, self.net.outputs, loss_fn, self)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\data\pde.py", line 133, in losses
    f = self.pde(model.net.inputs, outputs)
  File "c:\Users\ifisa\Documents\venv\deepxde\Poisson_S2_reparameterization.py", line 26, in pde
    dy_xx = xde.grad.hessian(y, X, i=0, j=0)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\gradients.py", line 234, in hessian
    return hessian._Hessians(ys, xs, component=component, i=i, j=j, grad_y=grad_y)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\gradients.py", line 201, in __call__
    self.Hs[key] = Hessian(y, xs, component=component, grad_y=grad_y)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\gradients.py", line 177, in __init__
    self.H = Jacobian(grad_y, xs)
  File "c:\Users\ifisa\Documents\venv\deepxde\xde\gradients.py", line 25, in __init__
    self.dim_y = ys.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

Could you give me some suggestions? Thanks!

**Comment by zhang-liu-official** [comment]
As a follow-up to this question, I've noticed that the hypersphere module is currently sampling domain points from inside the sphere and boundary points from on the surface of the sphere. Which parts of the code should we modify if we want to instead sample domain points from the on the surface of the sphere and periodic BC?

**Comment by lululxvi** [comment]
Your codes seems correct. You can multiply the PDE by sin(phi) to avoid 0.

For the second error, it could be that the gradient cannot be computed wrt intermediate varialbe X. maybe you can try to expand the du/d(sin(phi) * cos(theta)) manually in terms of du/d phi and du/d theta, so that you don't need the variable X.

You can change here:
https://github.com/lululxvi/deepxde/blob/e3186e7dead57184641ca9681600b06e2fb0e6a1/deepxde/geometry/geometry_nd.py#L134
for the point sampling.
