### ISSUE TITLE
PDEs in higher dimensions

### ISSUE THREAD

**Issue by fperiago** [lululxvi/deepxde#374]
Dear Lu, dear users,
I'm interested in solving a PDE (e.g. Poisson equation) on a rectangle of R^N, with N larger than 3.
Is it possible with deepxed? If Yes, how should I introduce the geometry or the training points in the interior and boundary domains?
Is there any example available?
Thanks a lot in advance and congratulations to Lu for this wonderful library. It makes life easier.
Best,
Francisco

**Comment by lululxvi** [comment]
You can use Hypercube https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#deepxde.geometry.geometry_nd.Hypercube
