### ISSUE TITLE
Data sampling in 2D and 3D domains

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#375]
Dear Prof Dr. Lu
How could we sample data in the case of 2D geometry and 3D domain ( Cube, sphere, Cube with hole, etc )?

Which algorithm helps in DeepXDE for these purposes?

Thanks in advance?

**Comment by lululxvi** [comment]
Check `dde.geometry` module https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#deepxde.geometry.geometry.Geometry.random_points

**Comment by SanjuSoni** [comment]
Sorry for Late reply Sir.

May I know the alogorithm or path used for dde.geometry module.

**Comment by lululxvi** [comment]
What do you mean? You can find the source code in the link above.

**Comment by SanjuSoni** [comment]
Thanks Prof.
