### ISSUE TITLE
Complex Domain Problem

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#38]
Hello Lu,

- do you have any example which includes the arbitrary domain used for PDE?

- how to implement the different boundary conditions in a unit circle.
like upper half-circle include Neumann and lower half-circle include Dirichlet boundary condition.

I got one import module :   **from deepxde.backend import tf**
does it support Tensorflow 2?

**Comment by lululxvi** [comment]
- Check Fig 6 in the [paper](https://arxiv.org/abs/1907.04502) for the define of arbitrary domain. For example, you can define a geometry composed from more than one sub-domains, e.g.,
```
geom1 = dde.geometry.Rectangle(...)
geom2 = dde.geometry.Disk(...)
geom = geom1 | geom2
```
- To define different BC on different parts, check the examples of Poisson_Neumann_1d.py. So, to define different BC in a circle:
```
def boundary_top(x, on_boundary):
    """On the boundary of disk and y > 0"""
    return on_boundary and x[1] > 0

def boundary_bottom(x, on_boundary):
    """On the boundary of disk and y < 0"""
    return on_boundary and x[1] < 0

geom = dde.geometry.Disk([0, 0], 1)
bc_top = dde.NeumannBC(geom, ..., boundary_top)
bc_bottom = dde.DirichletBC(geom, ..., boundary_bottom)
```
- Yes, it supports Tensorflow 2. Check the Installation on README page, and #37

**Comment by SanjuSoni** [comment]
Thanks Lu, Now I got it.

**Comment by SanjuSoni** [comment]
I am using  tensorflow 1.15 gpu version 
and while compiling I got Module error mentioned below

ModuleNotFoundError: No module named 'deepxde.backend'


Then I reinstall deepxde using  comand  **pip install deepxde**.

Using simple Import module is working like:
 import tensorflow as tf


How to fix it with this module error:

**Comment by lululxvi** [comment]
The current DeepXDE in `conda` and `pip` is not consistent with the examples. Sorry for this. You can replace `from deepxde.backend import tf` with `import tensorflow as tf`.

**Comment by SanjuSoni** [comment]
Yes, after replacing it with import tensorflow as tf  , it works properly.

Thanks

**Comment by LiHua1213** [comment]
Hello Lu,
I read this page carefully, but i still have a question: if i have a domain as the following codes show, how can i define the initial conditions/boundary conditions of every surface in the domian? Thank you!
spatial_domain1 = dde.geometry.Cuboid(xmin=[0, 0, 0], xmax=[2, 2, 2])
spatial_domain2 = dde.geometry.Cuboid(xmin=[0.5, 0.5, 0], xmax=[1.5, 1.5, 1])
spatial_domain = spatial_domain1 - spatial_domain2
temporal_domain = dde.geometry.TimeDomain(0, 1)
spatio_temporal_domain = dde.geometry.GeometryXTime(spatial_domain, temporal_domain)

**Comment by lululxvi** [comment]
The way to define IC/BC for complex geometry is exactly the same as a standard geometry. See demos https://deepxde.readthedocs.io/en/latest/demos/forward.html, FAQ "Q: More details and examples about initial conditions", FAQ "Q: More details and examples about boundary conditions"

**Comment by LiHua1213** [comment]
Dear lu :
Thanks for your help!&nbsp;
when i have the boundary conditions (including @)as follows, an error is roperted :ValueError: Rectangle: Method boundary_normal do not accept points on the vertexes.
when i have the boundary conditions (without @)above, the code run correctly.&nbsp;So if i want to run correctly with the boundary conditions (including @)above, how can revise the boundary conditions? Thanks
def pde(x, u):
u_vel, v_vel, p = u[:, 0:1], u[:, 1:2], u[:, 2:].............
spatial_domain = dde.geometry.Rectangle(xmin=[-0.5, -0.5], xmax=[1, 1.5])
timedomain = dde.geometry.TimeDomain(0, 1)
geomtime = dde.geometry.GeometryXTime(spatial_domain, timedomain)

def boundary_outflow(x, on_boundary):
return on_boundary and np.isclose(x[0], 1)
def boundary_inlet(x, on_boundary):
return on_boundary and np.isclose(x[0], -0.5)
def boundary_b(x, on_boundary):
return on_boundary and np.isclose(x[1], -0.5)
def boundary_t(x, on_boundary):
return on_boundary and np.isclose(x[1], 1.5)
boundary_condition_in0 = dde.DirichletBC(
geomtime, lambda x: np.ones((len(x), 1)) * 8, boundary_inlet, component=0
)
boundary_condition_in1 = dde.DirichletBC(
geomtime, lambda x: np.zeros((len(x), 1)) , boundary_inlet, component=1
)
boundary_condition_bot0 = dde.DirichletBC(
geomtime, lambda x: np.zeros((len(x), 1)), boundary_b, component=0
)
boundary_condition_bot1 = dde.DirichletBC(
geomtime, lambda x: np.zeros((len(x), 1)), boundary_b, component=1
)
boundary_condition_top1 = dde.DirichletBC(
geomtime, lambda x: np.zeros((len(x), 1)), boundary_t, component=2
)

@boundary_condition_top0 = dde.NeumannBC(
@geomtime, lambda x: np.zeros((len(x), 1)), boundary_t, component=1
@)
@boundary_condition_top2 = dde.NeumannBC(
@geomtime, lambda x: np.zeros((len(x), 1)), boundary_t, component=0
@)
boundary_condition_out2 = dde.DirichletBC(
geomtime, lambda x: np.zeros((len(x), 1)), boundary_outflow, component=2
)
@boundary_condition_out0 = dde.NeumannBC(
@geomtime, lambda x: np.zeros((len(x), 1)), boundary_outflow, component=0
@)
@boundary_condition_out1 = dde.NeumannBC(
@geomtime, lambda x: np.zeros((len(x), 1)), boundary_outflow, component=1
@)







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lululxvi/deepxde"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lululxvi/deepxde] Complex Domain Problem (#38)





 
The way to define IC/BC for complex geometry is exactly the same as a standard geometry. See demos https://deepxde.readthedocs.io/en/latest/demos/forward.html, FAQ "Q: More details and examples about initial conditions", FAQ "Q: More details and examples about boundary conditions"
