### ISSUE TITLE
Restriction to tf.Variable in inverse problem

### ISSUE THREAD

**Issue by tanielfranklin** [lululxvi/deepxde#380]
Hi Lu,
How can we define a restriction in a tf.Variable of a PDE inverse problem training?
In my model a non negative parameter is becoming negative and the training can't make it positive back.

The model is trained very well with good prediction on direct problem with the parameter fixed on its real value. But in inverse problem this parameter become negative even starting it close the real value.

Additionally, I noticed after L-FBGS optimization and followed by adam the parameter  becomes negative.

Thanks

**Comment by lululxvi** [comment]
You can look at https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007575 and its code for an example.
