### ISSUE TITLE
Some problems about solving PDEs using DeepXDE

### ISSUE THREAD

**Issue by wanghao-stack** [lululxvi/deepxde#381]
Hi Lu,

I've been studying how to use this lib to solve PDEs recently.
I wonder if this lib can solve PDEs in the complex field?
And how can  I use this lib to solve PDEs without boundary conditions such as solving wave equation in a infinite plate?

Thank you very much!

**Comment by lululxvi** [comment]
What do you mean by "complex field"? complex number? You can write the real and imag parts explicitly, see https://arxiv.org/abs/2102.04626

It is OK to solve without BC.
