### ISSUE TITLE
dde.model.predict for tensor when building graphs

### ISSUE THREAD

**Issue by YingHH1** [lululxvi/deepxde#382]
Hi Lulu,

I am trying to use prediction from a trained model when I define my PDEs, so naturally it will be building graph (tf1 backend) via tensors rather than numpy arrays. When I was trying to run it, an error stating tensor object has no attribute ‘astype’. 

So before I go any further in that route, I was wondering if you know whether dde.model.predict can be used in this way (for constructing tf graphs)？

Many thanks,

Ying

**Comment by lululxvi** [comment]
I didn't quite follow your question. Could you provide more details?

**Comment by YingHH1** [comment]
Basically I have a model u(x,y,t) which has been trained for say t1 between 0 and 0.5 (i.e. t1=[0, 0.5]). Now for the t2 = [0.5, 1] I want to minimise the residual:

# model = a trained deepxde model

def pde(x, u):
       # x[:,0:3] is x, y, t
       'compute gradients and define equations'
       x_new=copy.copy(x) # these two lines won't work here since x will be a tf placeholder object with shape [None,3] at this stage
       x_new[:, 2:3]=0.5 # but basically I want to fix t to be 0.5 throughout
       u1=model.predict(x_new) # won't work either even if the above lines work since x_new will not be a numpy array
       residual=some function of u and u1
       return residual

Note that the option of feeding model.predict(x_new) to initial condition does not work in this case, because it is used when defining the pde residual, i.e. the residual is a function of model.predict(x_new).

I hope this is helpful in making my question more clear, but Let me know if this still doesn't make sense.

Cheers!

**Comment by lululxvi** [comment]
- If you need to fix t=0.5, then you can only sample points with t=0.5
- If you need to compute the output of a trained network, it is totally doable to use `model.predict` to define the PDE, but this makes things complicated. Another simpler way is first saving lots of points of the trained network, and then use auxiliary variables, see example https://github.com/lululxvi/deepxde/blob/master/examples/Lorenz_inverse_forced_Colab.ipynb
