### ISSUE TITLE
Question about why there is no on_boundary function in geometry_2d.Rectangle.

### ISSUE THREAD

**Issue by YouCantRedo** [lululxvi/deepxde#383]
Dear @lululxvi  @AneleNcube
I am now trying to implement a 3D problem using deepxde.
And I used the  **2D + timedomain** approach to form my 3D geometry. 
`    geom = dde.geometry.Rectangle([0, 0], [4, 4])                 
    timedomain = dde.geometry.TimeDomain(0, 50)                  
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)`

My boundary conditions and initial conditions are as follows.
![image](https://user-images.githubusercontent.com/77193332/134767354-fe83df40-2209-45df-bf6b-eacd206b2d89.png)

However, the model prediction results are not good, so I checked my code and found there is no **on_boundary** function in class **geometry_2d.Rectangle** but this function exists in the Disk and Polygen class. [https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#module-deepxde.geometry.geometry_2d](url)
So I guess maybe this is the reason why my results are bad? (because the deepxde cannot tell where is my boundary).

I would like to know your suggestion and opinion about this issue. Thanks a lot!

**Comment by lululxvi** [comment]
`Rectangle` has `on_boundary` from `Hypercube`. It should be other reasons.
