### ISSUE TITLE
Questions about how to define the boundary conditions of the differential form

### ISSUE THREAD

**Issue by juice-drinker** [lululxvi/deepxde#386]
Dear Mr. Lulu
Hello 
I tried to use deepxde to solve differential equations, but encountered some difficulties in defining BC. The BC of this problem is described in a differential form. I cannot define the BC of this problem based on the existing examples. The specific boundary conditions are as follows:
![image](https://user-images.githubusercontent.com/81470970/135298029-8511d923-d94d-400b-acb3-4369871d4033.png)
If you can help me, I would be very grateful.

**Comment by lululxvi** [comment]
It seems to me that they are just Neumann BC.

**Comment by juice-drinker** [comment]
Yes, with your help, I went to browse the relevant introduction and examples of Neumann BC, and now I have successfully solved the differential equation.
Thank you, Professor Lu.
