### ISSUE TITLE
DeepXDE Backend switch automatically from pytorch to tensorflow_combat_v1

### ISSUE THREAD

**Issue by kochlisGit** [lululxvi/deepxde#391]
I am trying to implement some of the examples in the documentation with pytorch as backend. I have followed the instructions from the documentation:

- Set **pytorch** as backend
- Import pytorch module
- Even tried to modify the config file to using pytorch.

Then, i tried to create a FNN using `deepxde.nn.pytorch`, but i ran into the error:

`module 'deepxde.nn.tensorflow_compat_v1' has no attribute 'pytorch'`

Here is my code:

`%env DDEBACKEND="pytorch"
!export DDEBACKEND="pytorch"

from deepxde.backend import pytorch
import deepxde as dde
import torch
import numpy as np

dde.backend.set_default_backend("pytorch")`
which returns:

`env: DDEBACKEND="pytorch"
Setting the default backend to "pytorch". You can change it in the ~/.deepxde/config.json file or export the DDEBACKEND environment variable. Valid options are: tensorflow.compat.v1, tensorflow, pytorch (all lowercase)`

Then i tried to use **deepxde.nn.pytorch module** as:

`net = dde.nn.pytorch.fnn.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")`

which returns:

`deepxde.nn.tensorflow_compat_v1' has no attribute 'pytorch`

Is there anthing missing from the documentation? 
Thanks

**Comment by lululxvi** [comment]
You can try to run any example in https://github.com/lululxvi/deepxde/tree/master/examples
```
$ DDEBACKEND=pytorch python xxx.py 
```
