### ISSUE TITLE
Dear Lulu, Please I have a question in the Beltrami_flow.py code. This is a Navier Stokes problem in 3D with initial conditions on u, v and w. Please how can we replace the initial conditions with the periodic conditions in time on u, v and w. Thank you so much. 

### ISSUE THREAD

**Issue by Fayaud** [lululxvi/deepxde#415]

**Comment by Fayaud** [comment]
Dear @lululxvi , here is one example where I try to include the periodic condition.

domain = dde.geometry.Cuboid(xmin=[-1, -1, 0], xmax=[1, 1, 1])

def space_boundary(x, on_boundary):    # defines \partial\Omega\times (0,T)        
    return on_boundary and (np.isclose(x[0]**2-1, 0) or np.isclose(x[1]**2-1, 0))

def top_bottom_z(x, on_boundary):
    
    return on_boundary and np.isclose(x[2], 0)                    #???
boundary_condition_u = dde.DirichletBC(domain, u_func, space_boundary, component=0)
boundary_condition_v = dde.DirichletBC(domain, v_func, space_boundary, component=1)
periodic_condition_u = dde.PeriodicBC(domain, 2, top_bottom_z, component=0)
periodic_condition_v = dde.PeriodicBC(domain, 2, top_bottom_z, component=1)
data = dde.data.pde.PDE(domain, 
                        pde, 
                        [boundary_condition_u, boundary_condition_v, periodic_condition_u, periodic_condition_v],            
                        num_domain=500, 
                        num_boundary=300, 
                        num_test=200)
net = dde.maps.FNN([3] + 4* [50] + [3], "tanh", "Glorot normal")

model = dde.Model(data, net)

model.compile("adam", lr=1e-4)
model.train(epochs=40000)
model.compile("L-BFGS-B")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

This give me the following results:
Accuracy at t =  0 :
Mean residual: 0.081857584
L2 relative error in u: 0.3144374954213204
L2 relative error in v: 0.8383435095078381

Accuracy at t =  1 :
Mean residual: 0.1379331
L2 relative error in u: 0.7591696355716555
L2 relative error in v: 0.42157396837305283

I am not satisfy with that results because, just as the Beltrami_flow code, when I replace the periodic conditions with the initial conditions I get this result which is better:

Accuracy at t =  0 :
Mean residual: 0.00074068067
L2 relative error in u: 0.00021278928194283798
L2 relative error in v: 0.00041738021125487315

Accuracy at t = 1 :
Mean residual: 0.0017348104
L2 relative error in u: 0.005380774017995635
L2 relative error in v: 0.0025077725171020206

I think there is a mistake on my code especially where I enforce the periodic condition. Please can you help??? Thank you very  much.

**Comment by lululxvi** [comment]
PBC looks good. Your training points are too few.

**Comment by Fayaud** [comment]
Dear Lulu!

I added the number of training points

domain = dde.geometry.Cuboid(xmin=[-1, -1, 0], xmax=[1, 1, 1])

def space_boundary(x, on_boundary):    # defines \partial\Omega\times (0,T)        
    return on_boundary and (np.isclose(x[0]**2-1, 0) or np.isclose(x[1]**2-1, 0))

def top_bottom_z(x, on_boundary):
    
    return on_boundary and np.isclose(x[2], 0)                              #or  np.isclose(x[2], 1 )

boundary_condition_u = dde.DirichletBC(domain, u_func, space_boundary, component=0)
boundary_condition_v = dde.DirichletBC(domain, v_func, space_boundary, component=1)

periodic_condition_u = dde.PeriodicBC(domain, 2, top_bottom_z, component=0)
periodic_condition_v = dde.PeriodicBC(domain, 2, top_bottom_z, component=1)


data = dde.data.pde.PDE(domain, 
                        pde, 
                        [boundary_condition_u,
                         boundary_condition_v, 
                         periodic_condition_u, 
                         periodic_condition_v
                        ],            
                        num_domain=50000, 
                        num_boundary=5000,
                        num_test=30000)

Here is the results

Accuracy at t =  0 :
Mean residual: 0.0614769
L2 relative error in u: 0.3566727976617164
L2 relative error in v: 1.0571396553066983


Accuracy at t =  1 :
Mean residual: 0.04759127
L2 relative error in u: 0.46288452241195
L2 relative error in v: 0.26086082714075365

I am still not satisfy because the code with initial condition is much more better than this. Also I do not understand the gap between the error in u and the error in v at t= 0?

**Comment by lululxvi** [comment]
You may also include the first-order derivative in PBC, see the docs for dde.PeriodicBC.

**Comment by Fayaud** [comment]
Yes Professor but I do not have the periodicity of the derivative u_{t} in
my problem. Here is what I consider please (we may change 2\pi to 1).

[image: image.png]

I do not have the periodicity of the first order derivative. I am only
trying to enforce the last equation in the loss function.  I am making a
mistake? Otherwise, how can I do it manually?

best,

**Comment by Fayaud** [comment]
Sorry this is what I consider:

[File (1).pdf](https://github.com/lululxvi/deepxde/files/7653509/File.1.pdf)

**Comment by lululxvi** [comment]
OK. Then there is no need to use first order derivative. The code looks good.

**Comment by Fayaud** [comment]
Dear @lululxvi, 

I was trying to run the Schrodinger equation you wrote using deepxde but I got this error while enforcing the periodic condition.

# Boundary and Initial conditions

# Periodic Boundary conditions
bc_u_0 = dde.icbc.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=0
)
bc_u_1 = dde.icbc.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=0
)
bc_v_0 = dde.icbc.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=1
)
bc_v_1 = dde.icbc.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=1
)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-b87cc1f3ae51> in <module>
      2 
      3 # Periodic Boundary conditions
----> 4 bc_u_0 = dde.icbc.PeriodicBC(
      5     geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=0, component=0
      6 )

AttributeError: module 'deepxde' has no attribute 'icbc'.

How can I fix this error please?

**Comment by Fayaud** [comment]
Please, @lululxvi  do you have an example where you solve a 2D and time dependent periodic pde?

**Comment by forxltk** [comment]
You need to upgrade your DeepXDE, or use `dde.PeriodicBC` instead of `dde.icbc`.

**Comment by Fayaud** [comment]
Thank you so much @forxltk  and @lululxvi . 

My real concern is on this problem,  the way I enforce the periodic condition looks fine to me but I am getting an error.  It is in 2D in space and the time should be the third component.

ρ∂u ∂t + ρ(u.∇)u − µ∆u + ∇p = ρ.g in Ω
div(u) = 0 in Ω
u(t, .) = u(t + T, .) in Ω

geom = dde.geometry.Rectangle(xmin = [-1, -1], xmax = [1, 1])
timedomain = dde.geometry.TimeDomain(0, 2*np.pi)
domain = dde.geometry.GeometryXTime(geom, timedomain)


def periodic_boundary(x, domain):       
    return domain and (np.isclose(x[2], 0) or np.isclose(x[2], 2*np.pi))


boundary_condition_u = dde.DirichletBC(domain, u_func, lambda _, on_boundary: on_boundary, component=0)
boundary_condition_v = dde.DirichletBC(domain, v_func, lambda _, on_boundary: on_boundary, component=1)



periodic_condition_u = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=0)

periodic_condition_v = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=1)

periodic_condition_p = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=2)

I am getting this error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-9b8af29be8a1> in <module>
----> 1 data = dde.data.pde.PDE(domain, 
      2                         pde,
      3                         [boundary_condition_u,
      4                          boundary_condition_v,
      5                        

~/deepxde/lib/python3.8/site-packages/deepxde/data/pde.py in __init__(self, geometry, pde, bcs, num_domain, num_boundary, train_distribution, anchors, exclusions, solution, num_test, auxiliary_var_function)
    120         self.train_aux_vars, self.test_aux_vars = None, None
    121 
--> 122         self.train_next_batch()
    123         self.test()
    124 

~/deepxde/lib/python3.8/site-packages/deepxde/utils/internal.py in wrapper(self, *args, **kwargs)
     35             x = [getattr(self, a) for a in attr]
     36             if all(i is None for i in x):
---> 37                 return func(self, *args, **kwargs)
     38             return x if len(x) > 1 else x[0]
     39 

~/deepxde/lib/python3.8/site-packages/deepxde/data/pde.py in train_next_batch(self, batch_size)
    159     def train_next_batch(self, batch_size=None):
    160         self.train_x_all = self.train_points()
--> 161         self.train_x = self.bc_points()
    162         if self.pde is not None:
    163             self.train_x = np.vstack((self.train_x, self.train_x_all))

~/deepxde/lib/python3.8/site-packages/deepxde/utils/internal.py in wrapper(self, *args, **kwargs)
     35             x = [getattr(self, a) for a in attr]
     36             if all(i is None for i in x):
---> 37                 return func(self, *args, **kwargs)
     38             return x if len(x) > 1 else x[0]
     39 

~/deepxde/lib/python3.8/site-packages/deepxde/data/pde.py in bc_points(self)
    233     @run_if_all_none("train_x_bc")
    234     def bc_points(self):
--> 235         x_bcs = [bc.collocation_points(self.train_x_all) for bc in self.bcs]
    236         self.num_bcs = list(map(len, x_bcs))
    237         self.train_x_bc = (

~/deepxde/lib/python3.8/site-packages/deepxde/data/pde.py in <listcomp>(.0)
    233     @run_if_all_none("train_x_bc")
    234     def bc_points(self):
--> 235         x_bcs = [bc.collocation_points(self.train_x_all) for bc in self.bcs]
    236         self.num_bcs = list(map(len, x_bcs))
    237         self.train_x_bc = (

~/deepxde/lib/python3.8/site-packages/deepxde/icbcs/boundary_conditions.py in collocation_points(self, X)
    116     def collocation_points(self, X):
    117         X1 = self.filter(X)
--> 118         X2 = self.geom.periodic_point(X1, self.component_x)
    119         return np.vstack((X1, X2))
    120 

~/deepxde/lib/python3.8/site-packages/deepxde/geometry/timedomain.py in periodic_point(self, x, component)
    137 
    138     def periodic_point(self, x, component):
--> 139         xp = self.geometry.periodic_point(x[:, :-1], component)
    140         return np.hstack([xp, x[:, -1:]])

~/deepxde/lib/python3.8/site-packages/deepxde/geometry/geometry_nd.py in periodic_point(self, x, component)
     95     def periodic_point(self, x, component):
     96         y = np.copy(x)
---> 97         _on_xmin = np.isclose(y[:, component], self.xmin[component])
     98         _on_xmax = np.isclose(y[:, component], self.xmax[component])
     99         y[:, component][_on_xmin] = self.xmax[component]

IndexError: index 2 is out of bounds for axis 1 with size 2

The program do not understand my third component but my periodic condition is on the third component. The Schrodinger equation was for me to understand what is going on. If you can help fixing this error I will  appreciate it.

Thank you so much!

Fayaud!

**Comment by forxltk** [comment]
I haven't solve a periodicBC problem yet. But your code for the periodic bc is different to the Schrodinger example. 

And for the index error, I think the size of NN is not right. Please use `<>` to upload all your code.

**Comment by Fayaud** [comment]
Dear @forxltk ,

Here is the entire code.

`import deepxde as dde
import numpy as np
from deepxde.backend import tf
import matplotlib.pyplot as plt


Re = 1
a = 4
b = 2

def pde(x, u):      # x=(x,y,t),  u=(u,v,p)
        u_vel, v_vel, p = u[:, 0:1], u[:, 1:2], u[:, 2:3]

        u_vel_x = dde.grad.jacobian(u, x, i=0, j=0)
        u_vel_y = dde.grad.jacobian(u, x, i=0, j=1)
        u_vel_t = dde.grad.jacobian(u, x, i=0, j=2)
        u_vel_xx = dde.grad.hessian(u, x, component=0, i=0, j=0)
        u_vel_yy = dde.grad.hessian(u, x, component=0, i=1, j=1)

        v_vel_x = dde.grad.jacobian(u, x, i=1, j=0)
        v_vel_y = dde.grad.jacobian(u, x, i=1, j=1)
        v_vel_t = dde.grad.jacobian(u, x, i=1, j=2)
        v_vel_xx = dde.grad.hessian(u, x, component=1, i=0, j=0)
        v_vel_yy = dde.grad.hessian(u, x, component=1, i=1, j=1)

        p_x = dde.grad.jacobian(u, x, i=2, j=0)
        p_y = dde.grad.jacobian(u, x, i=2, j=1)

        momentum_x = (
            u_vel_t
            + (u_vel * u_vel_x + v_vel * u_vel_y)
            + p_x
            - 1 / Re * (u_vel_xx + u_vel_yy) 
        )
        momentum_y = (
            v_vel_t
            + (u_vel * v_vel_x + v_vel * v_vel_y)
            + p_y
            - 1 / Re * (v_vel_xx + v_vel_yy)
        )
        continuity = u_vel_x + v_vel_y

        return [momentum_x, momentum_y, continuity]



def u_func(x):
    return (np.sin(a*x[:,2:3])*x[:,0:1] + (np.cos(a*x[:,2:3]) + b)*x[:,1:2])

def v_func(x):
    return ( (np.cos(a*x[:,2:3]) - b)*x[:,0:1] - np.sin(a*x[:,2:3])*x[:,1:2] )

def p_func(x):
    return ( (b**2 - 1)*(x[:,0:1]**2 + x[:,1:2]**2)/2.0 
                + a*np.sin(a*x[:,2:3])*x[:,0:1]*x[:,1:2]
                - a*(x[:,0:1]**2 - x[:,1:2]**2)*np.cos(a*x[:,2:3])/2.0 )

geom = dde.geometry.Rectangle(xmin = [-1, -1], xmax = [1, 1])
timedomain = dde.geometry.TimeDomain(0, 2*np.pi)
domain = dde.geometry.GeometryXTime(geom, timedomain)


def periodic_boundary(x, domain):       
    return domain and (np.isclose(x[2], 0) or np.isclose(x[2], 2*np.pi))


boundary_condition_u = dde.DirichletBC(domain, u_func, lambda _, on_boundary: on_boundary, component=0)
boundary_condition_v = dde.DirichletBC(domain, v_func, lambda _, on_boundary: on_boundary, component=1)

periodic_condition_u = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=0)

periodic_condition_v = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=1)

periodic_condition_p = dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=2)


data = dde.data.pde.PDE(domain, 
                        pde, 
                        [boundary_condition_u,
                         boundary_condition_v, 
                         #pressure_data_p, 
                         periodic_condition_u,
                         periodic_condition_v,
                         periodic_condition_p,
                        ],
                        num_domain=192, 
                        num_boundary=152, 
                        #num_test=1000
                       )

net = dde.maps.FNN([3] + 4 * [20] + [3], "tanh", "Glorot normal")

model = dde.Model(data, net)

model.compile("adam", lr=1e-4, loss_weights=[1, 1, 1, 1, 1, 1, 1, 1])

model.train(epochs=30000, display_every=1000)

dde.optimizers.config.set_LBFGS_options(
    maxcor=50,
    ftol=1.0 * np.finfo(float).eps,
    gtol=1e-08,
    maxiter=50000,
    maxfun=50000,
    maxls=50,
)

model.compile("L-BFGS", loss_weights=[1, 1, 1, 1, 1, 1, 1, 1])             #L-BFGS-B


losshistory, train_state = model.train()


dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
`

best regards!

Fayaud!

**Comment by forxltk** [comment]
There are two problems in `dde.PeriodicBC(domain, 2, periodic_boundary, derivative_order=0, component=0)`.
1. I think the index error is due to the second parameter `component_x`. It should be 0 `x` or 1 `t`. 
2. Your definition of `periodic_boundary` seems not correct. I think you should use the same one as the Schrodinger example.

**Comment by Fayaud** [comment]
Okay thank you so much for your quick reply.

For Schrodinger they used dde.PeriodicBC(
    geomtime, 0, lambda _, on_boundary: on_boundary, derivative_order=1, component=0.
)

The periodicity is on the space for the Schrodinger equation and I guess this is while we have 0 as second argument of dde.PeriodicBC. For me, the periodicity is on the time. May be this is why you said I should put 1 instead of 2. But I have a question. In my case, the space is in 2 dimensions, what if I want to apply the periodicity on the second variable in space which is y? Because X= (x, y, t), and this is why I initially put 2. This question is to understand better.

I thought that x is 0, y is 1, and t is 2.

 Please can you come again?

Thank you so much @forxltk .

**Comment by forxltk** [comment]
OK, the periodic bc on time doesn’t appear to be implemented in `PeriodicBC`. Maybe you have to modify the source code which requires some effort.

**Comment by lululxvi** [comment]
The source code is on Github...

Yes, use the `CSG` operation. Check DeepXDE paper.

**Comment by Fayaud** [comment]
Yes, Thank you so much @lululxvi ,

I have checked the deepxde paper, I saw how to do union and intersection of domains such as disk, spheres, hypercube, polygon etc... that will be useful to me. But I did not see the cylinder.  Please can you give a hint on how to design the cylinder? Just an example, let say cylinder with high= 3 and base the disk D(0, 1).This will really help me. Thank you so much...

**Comment by lululxvi** [comment]
DeepXDE currently doesn't have a cylinder. You need to implement it by yourself.

**Comment by Fayaud** [comment]
Thank you so much @lululxvi ,

How can I implement it? can you help?

best regards!

Fayaud!

**Comment by lululxvi** [comment]
Read the source code of other geometries and implement it in a similar way.
