### ISSUE TITLE
Add a "Cite this repository" dropdown option in the repository

### ISSUE THREAD

**Issue by Saransh-cpp** [lululxvi/deepxde#423]
GitHub now provides a feature to add a "Cite this repository" option using a `CITATION.cff` file. It looks something like this (in the about section) -
![image](https://user-images.githubusercontent.com/74055102/141760733-389c5a45-279e-427a-85da-10dc2bae6984.png)

I'd like to take this up if everyone want it to be added in.

**Comment by lululxvi** [comment]
Great suggestion. Please submit a pull request.
