### ISSUE TITLE
When we have different data points for each output 

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#426]
My questions don't seem to finish. If we have two outputs and there are a few points available in the domain but the inputs for each output are different, is it possible to use this code? 
`   observe_y = dde.PointSetBC(observe_x, points , component = 1)
    observe_y_1 = dde.PointSetBC(observe_x_1, points_1 , component = 0)
    total_observations = np.vstack((observe_x , observe_x_1))`
points and points_1 are the labels and thus for anchors can we use total_observations?

**Comment by lululxvi** [comment]
yes, it is good.
