### ISSUE TITLE
Additional hard-constraints with a condition 

### ISSUE THREAD

**Issue by tsarikahin** [lululxvi/deepxde#431]
Dear Lulu,

thanks for this unique tool, DeepXDE!

I would like to add hard constraints meanwhile keeping the soft constraints. Below you can see the physical problem. 
![beam_hard](https://user-images.githubusercontent.com/51532356/142463648-6c71c808-e251-47d5-af29-6f0485727535.png)

my PDE is: $d^4/dw^4 +q = 0$ 

How PDE is defined? 
```python
def pde(x, y):
    dy_xx = ddy(x, y)
    dy_xxxx = dde.grad.hessian(dy_xx, x)
    return dy_xxxx + p(x)
```
BCs
```python
bc1 = dde.DirichletBC(geom, lambda _: 0, boundary_l)
bc2 = dde.OperatorBC(geom, lambda x, y, _: ddy(x, y), boundary_l)
bc3 = dde.DirichletBC(geom, lambda _: 0, boundary_r)
bc4 = dde.OperatorBC(geom, lambda x, y, _: ddy(x, y), boundary_r)

data = dde.data.PDE(
    geom,
    pde,
    [bc1, bc2, bc3, bc4],
    num_domain=20,
    num_boundary=2,
    solution=func,
    num_test=100,
)
```
Additional-hard constraints
```python
net.apply_output_transform(
    # Backend tensorflow.compat.v1 or tensorflow
    lambda _,y: (tf.experimental.numpy.heaviside(y+0.4,1))*y + (1-(tf.experimental.numpy.heaviside(y+0.4,1)))*(-0.4)
    # Backend pytorch
    # lambda x, y: x[:, 1:2] * (1 - x[:, 0:1] ** 2) * y + torch.sin(np.pi * x[:, 0:1])
)
```

Here is the point. I would like to apply the hard constraints only on the points that lie below -0.4. But for the rest, there will be no constraints since those points will not meet the additional boundary. To achieve that, I used the Heaviside function. Here we can see that Heaviside is working as expected:

![heaviside](https://user-images.githubusercontent.com/51532356/142465263-16eb2bbe-44bf-4fd4-b69b-f669092bb94a.png)

**If** the predicted result is smaller than -0.4, it will stay as it is, **if not**, it will be equal to -0.4 and constant. But the obtained results are not as expected. What could be the reason for that? Or what I have done is senseless? Thanks in advance!
![res](https://user-images.githubusercontent.com/51532356/142466434-186650dc-9a94-4f05-9d5c-724b622df389.png)

Note: please just ignore the true solution. I kept it to see the solution without hard constraints.

**Comment by lululxvi** [comment]
The issue could be `tf.experimental.numpy`. Do not use `numpy`.

**Comment by tsarikahin** [comment]
Thanks for your reply @lululxvi .

**Comment by HumbertHumbert7** [comment]
I am having the same problem, could you tell us how did you solve this problem?
