### ISSUE TITLE
Running the L-shape Poisson example took 8 hours.

### ISSUE THREAD

**Issue by kai-lan** [lululxvi/deepxde#432]
Hi,

I tried running the L shape Poisson example from the Docs, and I did not make any changes to it. I let my computer run overnight and it turned out to be 510 mins or so. 

I have an Apple M1 machine, and the backend is PyTorch. Is this normal?

Kai

**Comment by lululxvi** [comment]
It should not take so much. It could be due to M1 version of PyTorch, which I have no idea.

**Comment by kai-lan** [comment]
Indeed, i tried it again just now. And it only took about half an hour. So I think the problem is that I left it overnight, probably network connection impacted the execution for Jupyter...
