### ISSUE TITLE
Normalized solution to evolution PDE

### ISSUE THREAD

**Issue by ELorinDeLaG** [lululxvi/deepxde#434]
Dear Lulu,

I have a quick question on using DeepXDE with a normalization constraint. 

Is there a simple way to impose that the solution to a scalar evolution PDE has *at any time* a L2-norm equal to 1.

Thank you !

**Comment by lululxvi** [comment]
https://github.com/lululxvi/deepxde/issues/174

**Comment by lqq53** [comment]
I have the same problem. Have you solved it？how to normalize the input and output?
