### ISSUE TITLE
tfp.optimizer.lbfgs_minimize TypeError: minimize() got an unexpected keyword argument 'previous_optimizer_results'

### ISSUE THREAD

**Issue by JetsonPaul** [lululxvi/deepxde#439]
Hi, I tested a few examples from your DeepXDE library. When I use TensorFlow backend and examples with model.compile("L-BFGS") I get the error written in the title. When I change to Adam optimizer the examples work fine. You have any ideas how to fix it? 

Best regards Paul

**Comment by lululxvi** [comment]
What is your tfp version?

**Comment by JetsonPaul** [comment]
I use Conda environment to prevent version issues. Installed is tensorflow-probability-0.7

**Comment by lululxvi** [comment]
0.7 might be too old. Could you try new versions?

**Comment by JetsonPaul** [comment]
Hi, 
Thanks a lot for your quick response. Was a good idea to check the versions. Don't know why conda installed such a old version of tensor-probability. I have now upgraded both TensorFlow and TensorFlow-probability with pip install. I'm now on TensorFlow 2.7.0 (MacOS) and TensorFlow-probability 1.15.0. 

And if an Apple user with M1 reads this. Don't install TensorFlow Metal. The training then will run on GPU but it's way slower. Don't know why. 

Thanks again. Paul
