### ISSUE TITLE
dde.callbacks.MovieDumper not working

### ISSUE THREAD

**Issue by pescap** [lululxvi/deepxde#446]
Hi! 
I was trying to run the [Poisson_Dirichlet_1d](https://github.com/lululxvi/deepxde/blob/master/examples/Poisson_Dirichlet_1d.py) code with the MovieDumper callback --I installed Imagemagick previously. 
```
movie = dde.callbacks.MovieDumper("model/movie", [-1], [1], period=100, save_spectrum=True, y_reference=func)
losshistory, train_state = model.train(epochs=10000, callbacks=[movie])
```

Still, I get the following error: 

```
Output: 
/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1165                 'Cannot feed value of shape %r for Tensor %r, '
   1166                 'which has shape %r' %
-> 1167                 (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
   1168           if not self.graph.is_feedable(subfeed_t):
   1169             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape () for Tensor 'Placeholder_2:0', which has shape '(None, 1)'
```
I tried to run the code on different machines and got the same error. Any idea of what I am doing wrong? 
Thanks you for your help,
Paul

**Comment by tsarikahin** [comment]
Same problem here!

**Comment by lululxvi** [comment]
Bug fixed.

**Comment by NouamaneTazi** [comment]
I got the error `CalledProcessError: Command '['convert', '-size', '720x360', '-depth', '8', '-delay', '3.3333333333333335', '-loop', '0', 'rgba:-', 'model/movie_y.gif']' returned non-zero exit status 1.`

**Comment by lululxvi** [comment]
Try this: https://stackoverflow.com/questions/57422195/how-can-fix-calledprocesserror-in-ffmpeg

**Comment by pescap** [comment]
Tested. Thank you @lululxvi
