### ISSUE TITLE
How can I use DEEPXDE to solve an ODE that includes the unknow function derivative at boundaries in side the equation?

### ISSUE THREAD

**Issue by ali-fallah-66** [lululxvi/deepxde#451]
Dear Lu 
thanks for your efforts. I want to solve an ODE that includes the unknow function derivative at boundaries in side the equation. For examples: 
y(x) unknow function, 0<x<1 , ODE Eq.:  D4y + (Dy(1)-Dy(0))*D2y + y=1, y(0)=0 ,D2y(0)=0, y(1)=0 ,D2y(1)=0, Dny=d^n y/dx^n

I'm wondering if you help me with this issue. 
Best wishes

**Comment by lululxvi** [comment]
Not fully understand what is your questin. Maybe you can check https://deepxde.readthedocs.io/en/latest/demos/eulerbeam.html

**Comment by ali-fallah-66** [comment]
Thanks for your response. Let me explain in more detail. Consider following equation : 
D4y/Dx + { Dy/Dx(1)-Dy/Dx(0) } *y=1 , 0<x<1
Dy/Dx(1) is derivate of y at x=1 and Dy/Dx(0) is derivative of y at x=0. I don't know how add Dy/Dx(1) and Dy/Dx(0) in ODE definition.

**Comment by lululxvi** [comment]
Interesting problem. There may be a few ways to do it. 
1. Iterative method. First guess dy/dx(1) - dy/dx(0), solve it, then have a updated dy/dx(1) - dy/dx(0);
2. Formate it as an inverse problem setting. Assume a = dy/dx(1), b = dy/dx(0), then solve a and b together with the ODE.

**Comment by ali-fallah-66** [comment]
@lululxvi Thanks for your kind help. I will try them, and let you know the result. 
Best wishes
