### ISSUE TITLE
TypeError: x and y must have the same dtype, got tf.float32 != tf.float64

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#46]
I noticed that it will trigger an error if doing arithmetic with TensorFlow tensor, to reproduce
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf


def main():
    def pde(x, y):
        dy_x = tf.gradients(y, x)[0]
        dy_xx = tf.gradients(dy_x, x)[0]
        return dy_xx - 2

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], -1)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    def func(x):
        return (x + 1) ** 2

    geom = dde.geometry.Interval(-1, 1)
    bc_l = dde.DirichletBC(geom, func, boundary_l)
    bc_r = dde.RobinBC(geom, lambda X, y: tf.math.truediv(y, X), boundary_r)
    data = dde.data.PDE(geom, pde, [bc_l, bc_r], 16, 2, solution=func, num_test=100)

    layer_size = [1] + [50] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)
    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=10000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
```
the modification is on line 28
```python
    bc_r = dde.RobinBC(geom, lambda X, y: tf.math.truediv(y, X), boundary_r)
```
the trackback

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
>     yield g
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1977, in cond
>     orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1814, in BuildCondBranch
>     original_result = fn()
>   File "/Users/kyika/Documents/project/pinn/deepxde/deepxde/data/pde.py", line 74, in losses_train
>     error = bc.error(self.train_x, model.net.inputs, outputs, beg, end)
>   File "/Users/kyika/Documents/project/pinn/deepxde/deepxde/boundary_conditions.py", line 110, in error
>     X[beg:end], outputs[beg:end]
>   File "/Users/kyika/Documents/project/pinn/deepxde/examples/Poisson_Robin_1d.py", line 28, in <lambda>
>     bc_r = dde.RobinBC(geom, lambda X, y: tf.math.truediv(y, X), boundary_r)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
>     return target(*args, **kwargs)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1051, in truediv
>     return _truediv_python3(x, y, name)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 982, in _truediv_python3
>     (x_dtype, y_dtype))
> TypeError: x and y must have the same dtype, got tf.float32 != tf.float64

this probably because the default dtype for NumPy is `float64` while TensorFlow is `float32`, the discrepancy probably introduced from call `train_next_batch` in `deepxde/data/pde.py` which generate data using NumPy.

Please have a look at it.

Shunyuan

**Comment by lululxvi** [comment]
Yes, it is the problem of `float32` and `float64`. I have fixed the bug.

The most simple solution is using `y / X` instead of `tf.math.truediv(y, X)`.

**Comment by smao-astro** [comment]
I see, Thank you.
