### ISSUE TITLE
How many network model when solve the system of eqs?

### ISSUE THREAD

**Issue by Runfa-Zhang** [lululxvi/deepxde#463]
like [Schrodinger example](https://github.com/lululxvi/deepxde/blob/master/examples/Schrodinger.ipynb) as follows Fig,
![](https://user-images.githubusercontent.com/45444680/147384943-b56bf6d3-20cf-4a13-9250-b1faf07de462.png)
how many network model when solve this system of eqs?
one network model to 2 output $u$ and $v$ as follows Fig?（please wait for loading fig）
![](https://user-images.githubusercontent.com/45444680/147385053-2bf62aaa-f1cd-461f-91d5-93b83309ca8a.png)
or 2 network model to $u$ and $v$ respectively as follows Fig?（please wait for loading fig）
![](https://user-images.githubusercontent.com/45444680/147385074-e661a622-1f8b-45a2-b8ab-29edcda7d117.png)

**Comment by lululxvi** [comment]
Both work, and DeepXDE supports both. You can pick the one you like. For the code of Schrodinger example, it uses the first network.

**Comment by Runfa-Zhang** [comment]
> Both work, and DeepXDE supports both. You can pick the one you like. For the code of Schrodinger example, it uses the first network.

# Many thanks for your help！
