### ISSUE TITLE
How to setting GPU when using jupyter notebook？

### ISSUE THREAD

**Issue by Runfa-Zhang** [lululxvi/deepxde#464]
How to setting GPU in IDE and systme of eqs？
1 [IDE](https://github.com/lululxvi/deepxde/blob/master/examples/ide.py)
2 [systme of eqs](https://github.com/lululxvi/deepxde/blob/master/examples/Schrodinger.ipynb)

**Comment by lululxvi** [comment]
I am not sure exactly what you mean by "setting GPU".

**Comment by Runfa-Zhang** [comment]
> I am not sure exactly what you mean by "setting GPU".

# How to use GPU in deepxde？

**Comment by lululxvi** [comment]
If there is GPU, and Tensorflow/Pytorch are installed correctly for GPU, then DeepXDE will automatically use it by default.

**Comment by Runfa-Zhang** [comment]
> If there is GPU, and Tensorflow/Pytorch are installed correctly for GPU, then DeepXDE will automatically use it by default.

# Many thanks for your help!

**Comment by pooo04** [comment]
> If there is GPU, and Tensorflow/Pytorch are installed correctly for GPU, then DeepXDE will automatically use it by default.

When I use PyCharm to calculate PDEs, I use deepxde for the calculations and torch as the backend. The background shows that the GPU usage is low. How can I determine that GPU acceleration is being used for the calculations? I have already written the following in my code:`if torch.cuda.is_available():
    torch.set_default_device("cuda")`
