### ISSUE TITLE
How to use 2 network model to solve a system with 2 PDEs?

### ISSUE THREAD

**Issue by Runfa-Zhang** [lululxvi/deepxde#466]
like [Schrodinger example](https://github.com/lululxvi/deepxde/blob/master/examples/Schrodinger.ipynb) as follows Fig,
![](https://user-images.githubusercontent.com/45444680/147384943-b56bf6d3-20cf-4a13-9250-b1faf07de462.png)
one network model with 2 output $u$ and $v$ have been used as follows Fig,
![](https://user-images.githubusercontent.com/45444680/147385053-2bf62aaa-f1cd-461f-91d5-93b83309ca8a.png)
```
# 1 Network architecture
net = dde.maps.FNN([2] + [100] * 4 + [2], "tanh", "Glorot normal")
model = dde.Model(data, net)
```
# How to use 2 network model as follows Fig?
![](https://user-images.githubusercontent.com/45444680/147385074-e661a622-1f8b-45a2-b8ab-29edcda7d117.png)

I try to: 
```
# 2 Network architecture
net = [
dde.maps.FNN([2] + [100] * 4 + [1], "tanh", "Glorot normal"),
dde.maps.FNN([2] + [100] * 4 + [1], "tanh", "Glorot normal")
]
model = dde.Model(data, net)
```
but not work.

**Comment by lululxvi** [comment]
Use `PFNN`, see https://github.com/lululxvi/deepxde/blob/master/examples/elliptic_inverse_field.py
