### ISSUE TITLE
<About saving the trained model and loading the model weights in the current DeepXDE version>

### ISSUE THREAD

**Issue by zyz-rise** [lululxvi/deepxde#468]
Dear Dr. Lu，
Thanks for the provision of DeepXDE library , which greatly facilitates the use of PINN to solve differential equations！
The way to save and load the model was mentioned in the previous F&Q, and I tried to copy the code to run it, but I still get the following error：

**train and save model**
```
model = dde.Model(data, net)
model.compile("adam", lr=0.001)
checkpointer = dde.callbacks.ModelCheckpoint("./model/trained_model", verbose=1, save_better_only=True, period=30000)
loss_history, train_state = model.train(epochs=30000, callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=True, isplot=True)  
```
Then the meta, index, data files with the file name as "trained_model-30000.ckpt.meta“ were generated.

**load model**
```
## Way I ##
model_new = dde.Model(data, net)
model_new.compile("adam", lr=0.001)
losshistory, train_state = model_new.train(epochs=30000, model_restore_path="./model/trained_model-30000.ckpt", callbacks = [checkpointer])
## Way II ##
model_new = dde.Model(data, net)
model_new.compile("adam", lr=0.001)
model_new.restore(save_path = "./model/trained_model-30000.ckpt")
```
Loading a model using either of these two ways will report errors：
```
NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
Key beta1_power_6 not found in checkpoint
	 [[node save_7/RestoreV2 (defined at C:\Users\Dell\anaconda3\envs\deepxde\lib\site-packages\deepxde\model.py:124) ]]
2021-12-31 14:27:49.852856: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-31 14:30:27.185691: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power_1 not found in checkpoint
2021-12-31 14:33:43.124910: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power_1 not found in checkpoint
2021-12-31 14:39:59.341468: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power_1 not found in checkpoint
2021-12-31 14:43:04.350841: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key beta1_power_6 not found in checkpoint
```

I have checked all the issues in F&Q about the restore model, but none of them seem to make my code work. So I'm wondering if this is a problem with the current version of deepXDE that has been updated or is there something wrong with the code? Can you provide some suggestions?

**Comment by lululxvi** [comment]
It is strange.  Are they in two files?

**Comment by zyz-rise** [comment]
The files in the three formats of meta, index, and data are all saved in one folder named "./model". I think there should be no problem with saving. It's a bit difficult to reload the model.

**Comment by lululxvi** [comment]
I mean your code. How do you organize your code? You may try the save and restore at https://deepxde.readthedocs.io/en/latest/demos/poisson.1d.dirichlet.html

**Comment by zyz-rise** [comment]
Thanks for your advice. 
At present, I can use `model.restore(...) `or `model.train(model_restore_path="...")` to load the model immediately after training the model. But if I run `model = dde.Model(data, net)` before restoring the model, error will be reported. I also refer to the final solution in issue #103, but still report error, it is very strange.
Here is the code I used：
```
# train and save model
checkpointer = dde.callbacks.ModelCheckpoint("./model/trained_model.ckpt", verbose=1, save_better_only=True, period=30000)
loss_history, train_state = model.train(epochs=30000, callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=False, isplot=True)  
```
The above is no problem. As long as I add `model = dde.Model(data, net) `below, then there will be an error.
```
# restore model
model = dde.Model(data, net) # I think this line of code initializes the trained network again
model.compile("adam", lr=0.001)
checkpointer = dde.callbacks.ModelCheckpoint("./model/trained_model.ckpt", verbose=1, save_better_only=True, period=30000)
loss_history, train_state = model.train(epochs=30000, model_restore_path = "./model/trained_model.ckpt-30000", callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=False, isplot=True)   
```
I just want to get the weight of model A that has been trained well, and then use the weight of model A as the initial weight of model B. Is this possible? Is there any other way? Please give me some advice~~

**Comment by zyz-rise** [comment]
Here is the complete code I used：
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import deepxde as dde
from deepxde.backend import tf
import matplotlib.pyplot as plt
 
def ode_system(t, x):
    """
    ODE system.
    """
    epsilon=0.05
    x1, x2, x3 = x[:, 0:1], x[:, 1:2], x[:, 2:3]
    dx1_t = dde.grad.jacobian(x, t, i=0)
    dx2_t = dde.grad.jacobian(x, t, i=1)   
    dx3_t = dde.grad.jacobian(x, t, i=2)
    return [dx1_t - x2/epsilon - x1 - 2 * x3, dx2_t + x1/epsilon - x2, dx3_t - (x1**2 + x2**2)/1]

def boundary(_, on_initial):
    return on_initial

"Training dataset"
geom = dde.geometry.TimeDomain(0.0, 1.0)
ic1 = dde.IC(geom, lambda x: 1, boundary, component=0)
ic2 = dde.IC(geom, lambda x: 0, boundary, component=1)
ic3 = dde.IC(geom, lambda x: 0, boundary, component=2)
num_data = 101
data = dde.data.PDE(geom, ode_system, [ic1, ic2, ic3], num_data, 2)

"Neural network layer structure, activation function and initialization settings"
layer_size = [1] + [40] * 5 + [3]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

"Build model and compile"
model = dde.Model(data, net)
model.compile("adam", lr=0.001)

"Train model，save model"
checkpointer = dde.callbacks.ModelCheckpoint("./model/trained_model.ckpt", 
                                             verbose=1, save_better_only= False, 
                                             period=10000)
loss_history, train_state = model.train(epochs=30000, callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=Ture, isplot=True)       

"Restore model"
# model = dde.Model(data, net)  # The main problem!!!
model.compile("adam", lr=0.001)
model.restore("./model/trained_model.ckpt-30000", verbose=1)
# Optional: Restore the model before training.
# loss_history, train_state = model.train(epochs=10000, 
                                        model_restore_path = "./model/trained_model.ckpt-30000", 
                                        callbacks=[checkpointer])
```

**Comment by lululxvi** [comment]
See https://github.com/lululxvi/deepxde/issues/54#issuecomment-983257824

**Comment by AlirezaPa** [comment]
Thank you @lululxvi for your library. It is very helpful for our research. And thank you @zyz-rise to share your issue here. My issue seems very simple, and I checked all the comments in the FAQ but could not figure out this problem. The trained model was successfully saved but cannot be restored. For your convenience, I present here Dr. Lu Poisson_Dirichlet_1d. py to see the error that I face. Thank you for your time.

The error says: The passed save_path is not a valid checkpoint: /content/gdrive/MyDrive/codes/model.ckpt-8000

Below is the code:

def pde(x, y):
dy_xx = dde.grad.hessian(y, x)
return -dy_xx - np.pi ** 2 * tf.sin(np.pi * x)

def boundary(x, on_boundary):
return on_boundary

def func(x):
return np.sin(np.pi * x)

geom = dde.geometry.Interval(-1, 1)
bc = dde.DirichletBC(geom, func, boundary)
data = dde.data.PDE(geom, pde, bc, 16, 2, solution=func, num_test=100)

layer_size = [1] + [50] * 3 + [1]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.maps.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=0.001, metrics=["l2 relative error"])

checkpointer = dde.callbacks.ModelCheckpoint("/content/gdrive/MyDrive/codes/model.ckpt", verbose=1, save_better_only=True )

losshistory, train_state = model.train(epochs=10000, callbacks=[checkpointer])

dde.saveplot(losshistory, train_state, issave=True, isplot=True)

model.restore("/content/gdrive/MyDrive/codes/model.ckpt-" + str(train_state.best_step), verbose=1)

![image](https://user-images.githubusercontent.com/93855073/150734802-6c0e1e4b-e75e-4c73-97cb-92d98107abb1.png)

**Comment by zyz-rise** [comment]
Maybe you can try this：
```
checkpointer = dde.callbacks.ModelCheckpoint("./codes/model", verbose=1, save_better_only= True)
loss_history, train_state = model.train(epochs=10000, callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=False, isplot=True)
model.restore("./codes/model-"+ str(train_state.best_step) + ".ckpt", verbose=1)
```
I tried running your code with it and it worked.

**Comment by AlirezaPa** [comment]
Thank you very much @zyz-rise . It works. I will modify my original code. Thank you.

**Comment by engsbk** [comment]
Hello @zyz-rise, @AlirezaPa @lululxvi and thank you for the useful discussion here. 
I saved my model using this code:

```
d = 2 #dimensions
level = 3  #dataset level
nx_train = 10 * 2 ** (level - 1)
data = dde.data.TimePDE(
    geomtime, pde, 
    [], 
    num_domain = nx_train**d, 
    num_boundary = 2 * d * nx_train, 
    num_initial = nx_train**d,
    train_distribution="uniform",
    anchors = observe_x
) 
n = 5
activation = "sin" 
net = dde.maps.FNN([2] + [100] * 6 + [1], activation, "Glorot normal")
net.apply_output_transform(output_transform)
modelx = dde.Model(data, net)
modelx.compile("adam", lr=5e-4)
checkpointer = dde.callbacks.ModelCheckpoint(
     "modelx/model.ckpt", verbose=1, save_better_only=True
)

loss_history, train_state = modelx.train(epochs=20000, callbacks=[checkpointer])
dde.saveplot(loss_history, train_state, issave=True, isplot=True) 
```
![1](https://user-images.githubusercontent.com/25299510/171675067-29d54086-b505-4b58-9969-75b5fec6c644.png)
![2](https://user-images.githubusercontent.com/25299510/171675071-cd0139ab-e336-4fa0-9906-b41a266b85e6.png)
![3](https://user-images.githubusercontent.com/25299510/171675075-6a8c4f1e-0c43-414f-be0b-073e69ff9ce3.png)
![4](https://user-images.githubusercontent.com/25299510/171675077-94f7012a-024e-4a68-ae13-2d0dead45074.png)
![5](https://user-images.githubusercontent.com/25299510/171675078-d2515bba-b2f1-4acd-9c74-f8d6f199726c.png)
![6](https://user-images.githubusercontent.com/25299510/171675079-d3468669-6ef1-4d55-aef2-571bfa448611.png)

However when I attempt to restore it using this code in a different file:
```

d = 2 #dimensions
level = 3  #dataset level
nx_train = 10 * 2 ** (level - 1)
data = dde.data.TimePDE(
    geomtime, pde, 
    [], 
    num_domain = nx_train**d, 
    num_boundary = 2 * d * nx_train, 
    num_initial = nx_train**d,
    train_distribution="uniform",
    anchors = observe_x
) 
n = 5
activation = "sin" 
net = dde.maps.FNN([2] + [100] * 6 + [1], activation, "Glorot normal")
net.apply_output_transform(output_transform)
modely = dde.Model(data, net)
modely.compile("adam", lr=5e-4)
modely.restore("./modelx/model.ckpt-14000.ckpt", verbose=1)
```
The prediction results are different:
![11](https://user-images.githubusercontent.com/25299510/171675507-332767cf-3743-4fde-ab39-66697abca1e5.png)
![22](https://user-images.githubusercontent.com/25299510/171675511-bbfbde74-3376-4c41-a8e5-96a6d2fd62bf.png)
![33](https://user-images.githubusercontent.com/25299510/171675515-cde80d74-038d-4728-8ede-edd92fe14bfd.png)
![44](https://user-images.githubusercontent.com/25299510/171675518-8f543d6a-46b5-4792-873c-924d651e46aa.png)
![55](https://user-images.githubusercontent.com/25299510/171675523-dc7b8f42-a9e4-4dfe-959a-ccc1b781eb8f.png)
![66](https://user-images.githubusercontent.com/25299510/171675527-17f03901-f2aa-426e-ae88-9ab567c0db9a.png)


What do you think is the problem? I'm looking forward for your suggestions on how to fix this.

**Comment by zyz-rise** [comment]
@engsbk Maybe you can try the restore twice or three times at the same time

**Comment by engsbk** [comment]
@zyz-rise That is unexpected, but I actually restored twice and it worked. calling restore once did not restore the parameters.
Thank you for the suggestion!

**Comment by zyz-rise** [comment]
Emmm...this is very strange. Sometimes only restore once is not successful, maybe need restore twice or three times.  Dr. Lu, @lululxvi do you know what's the reason? is it a bug here?

**Comment by AlirezaPa** [comment]
Hello @lululxvi  @zyz-rise  @engsbk . I also have a problem regarding saving the data. The following is some portion of "Lorenz system" code of Dr. Lu that I just copied and pasted from the code.

#callbacks for storing results
variable = dde.callbacks.VariableValue([C1, C2, C3], period=1000, filename="variables.dat")
model.train(epochs=10000, callbacks=[variable])

Code works well, and I can see the variables on the screen during the iterations , but in the output it just shows number of iterations and shows "nan" for the variables.

![image](https://user-images.githubusercontent.com/93855073/172029281-6e54bd7b-94a4-4f9e-b886-ee31554a57f6.png)

Does anybody know how to fix this issue? Thanks

**Comment by lululxvi** [comment]
> Emmm...this is very strange. Sometimes only restore once is not successful, maybe need restore twice or three times. Dr. Lu, @lululxvi do you know what's the reason? is it a bug here?

@zyz-rise @engsbk This is strange. I never had this problem. Do you have a very simple complete demo code to reproduce this?

**Comment by lululxvi** [comment]
@AlirezaPa I have never seen this issue. Actually if you specific `filename="variables.dat"`, then you shouldn't seen the variables in the screen.

**Comment by AlirezaPa** [comment]
> @AlirezaPa I have never seen this issue. Actually if you specific `filename="variables.dat"`, then you shouldn't seen the variables in the screen.

Dr. @lululxvi , I see the variables in the screen by the following command

#callbacks for storing results
variable = dde.callbacks.VariableValue([C1, C2, C3], period=1000)
model.train(epochs=10000, callbacks=[variable])

But, with the command in my previous comment, I got "nan" values in my output file.

**Comment by engsbk** [comment]
I'm using VScode, and I had the same issue.

**Comment by tsarikahin** [comment]
@engsbk @zyz-rise @lululxvi If you store the model using JupyterNotebook and restore it using another JupyterNotebook or python file, does not recognize the weights. And @engsbk it seems like you are using JupyterNotebook. I had the same problem. So do not store the weights using JupyterNotebook but a python file. It solved my problem.

**Comment by lululxvi** [comment]
@tsarikahin Good point. I don't use JupyterNotebook. Not sure why JupyterNotebook "destroys" the saving process.
