### ISSUE TITLE
obtain boundary normal

### ISSUE THREAD

**Issue by bondwbe** [lululxvi/deepxde#469]
hello Lu,

I want to use boundary normal vector in the operatorBC. Is there a way to do so? e.g. could the boundary_normal function be used in operatorBC? I will appreciate any example that you may have.

thank you.

**Comment by lululxvi** [comment]
Yes, you can, see NeumannBC example.

**Comment by bondwbe** [comment]
hi Lu,

thanks for the response. But it is not clear to me what specifically from NeumannBC will get me the boundary normal vector. The NeumannBC code is given below, but it is not clear to me which part is calculating boundary normal vector. The only function calcuating normal_derivative is self.normal_derivative(X, inputs, outputs, beg, end) but it's taking many argument in addition to X (=x,y), which is what should be needed to compute boundary normal vector.

class NeumannBC(BC):
    """Neumann boundary conditions: dy/dn(x) = func(x)."""

    def __init__(self, geom, func, on_boundary, component=0):
        super(NeumannBC, self).__init__(geom, on_boundary, component)
        self.func = npfunc_range_autocache(utils.return_tensor(func))

   def error(self, X, inputs, outputs, beg, end):
        values = self.func(X, beg, end)
        return self.normal_derivative(X, inputs, outputs, beg, end) - values

**Comment by lululxvi** [comment]
Check the code of `normal_derivative()`

**Comment by bondwbe** [comment]
thank you for response but i am not able to figure it out.  e.g. when i used n = geom.normal_derivative(x) in the operatorBC definition i got error AttributeError: 'Rectangle' object has no attribute 'normal_derivative'
i will appreciate any additional guidance.

**Comment by lululxvi** [comment]
Check https://github.com/lululxvi/deepxde/blob/dd1900a70a149b97b84ba94b6c8e9ae5bab68cdb/deepxde/icbcs/boundary_conditions.py#L54

**Comment by bondwbe** [comment]
Dr. Lu, I tried various things in the past few days but was not successful to get the boundary normal in the boundary condition function definition. for time being I am calculating the boundary normal manually and it's working. i may revisit this issue later. Thank you for your inputs.
