### ISSUE TITLE
some constrain issue about DeepONet

### ISSUE THREAD

**Issue by xuliang5115** [lululxvi/deepxde#472]
---
Dear Pro.Lu:
&emsp;&emsp;I try to solve long-range propagation problem of Helmholtz equation, it's a multi-scale problem, generally consider a three-dimensional Cartesian coordinate system (x,y,z) and x-axis is direction of propagation.
&emsp;&emsp;I use FNN and MsFFN solve a little benchmark problem (Green's function), but i think DeepONet is more useful in this project due to BC/IC often changed.  
&emsp;&emsp;In practice condition, we consider different frequencies (IC) and range depended boundary (BC), i tried PINN method solve this and i found if i continue use PINN i should train a model per freq and per boundary.   

---
So, i try to make it clear what model i need and what i should add: 
**1. Fourier feature layers in x-axis, y-axis and z-axis**
 &emsp;&emsp; It seems i should change this, because i should set "sigma_x" "sigma_y" "sigma_z", in my propagation issue these axis has differenet fourier feature because different BC. I think code change may little, i can do this but not clear is this necessary?
Model like MsFFN is just a alternative solver, if I have simulate data i don't need change fourier feature, am i right?  

**2. DeepONet**
  &emsp;&emsp;DeepONet use API named triple, triple data should from solver.So that mean we can't add physics information in DeepONet, but we know pure data-drived method hard to learn physics from data and insure the evaluate long-range result still keep low error and hard to train.Sifan Wang's PI-DeepONet added PDE constrain to model, but in Deepxde we can't add a constrain, i want to know do you have a plan add it.  

---
Anyway, Thank you a lot.
Wishing You a Healthy and Happy New Year.

**Comment by lululxvi** [comment]
- Yes, you can modify the code of Fourier feature layer.
- Yes, using DeepONet could be a better option than PINN for your project. You can do purely data-driven if you have a relatively large dataset. You can also add PDE loss, but you need to modify the DeepXDE code (basically adding another loss term). I plan to add the support of PI-DeepONet.
