### ISSUE TITLE
Rescaling problem of heat transfer with an external source

### ISSUE THREAD

**Issue by lshil00** [lululxvi/deepxde#476]
Dear Lulu,
I am dealing with a 2D Steady-State heat transfer problem with a laser source. As expected, the losses of PDEs and BCs differ greatly from each other due to the laser source Q, and it is really hard to train. So I try to rescale the problem following the FAQs, but how can I rescale the temperature(T) correctly without changing the original equations?
Great thanks!
![image](https://user-images.githubusercontent.com/47272107/148361174-3cfc0031-6053-426a-85c1-13c67d55cd94.png)

**Comment by lululxvi** [comment]
change of variable T'=kT.
