### ISSUE TITLE
Add judgment conditions related to time variables in ordinary differential equations

### ISSUE THREAD

**Issue by MotorZ** [lululxvi/deepxde#478]
Dear lulu，

First, I really appreciate your dedicated work.
I have questions regarding DeepXDE solve ODEs like:
![image](https://user-images.githubusercontent.com/44264730/148675620-88fd841b-ed67-4cf1-9da8-ce7b32c2430e.png)
I made some simplifications to the equations for easier reading.
in which a，b, c ,p, q, r are constant
C(t) depends on B(t)
Because the judgment condition about B(t) needs to be added to the equation.
I have no idea how to apply C(t) as a function. 
I have read many FAQ but got no answer like my qusetion.
Could you please tell me if deepxde can handle this or any example to reference，Thanks！
I really thankful for your precious time！

**Comment by lululxvi** [comment]
Use ` tf.cond`

**Comment by MotorZ** [comment]
Thank you so much！(´▽`)ﾉ
