### ISSUE TITLE
How to use deepxde to reconstruct the flow field.

### ISSUE THREAD

**Issue by sylva0** [lululxvi/deepxde#479]
Dear Lulu,

After reading your article, I was greatly inspired. Now I have created a new dataset about two-dimensional cavity mixed convection according to the format of "burgers.npz". I want to use deepxde to train the network by inputting my dataset and reconstruct the flow field, but I don't know which problem to refer to.

Thank you very much if you can answer my questions

**Comment by lululxvi** [comment]
You can check any inverse problem.

**Comment by sylva0** [comment]
Thank you for your reply. Now I have written the following code and my training dataset is composed of 1000 points randomly selected from the output result of fluent. The input variables are x, y and the output variables are u, v and p which are in the form of (1,1000). I have no idea how to deal with the errors.

**Comment by sylva0** [comment]
![DELL9205 2022_1_17 13_25_53](https://user-images.githubusercontent.com/94151886/149712949-9c594afc-40bf-4c0d-91b7-f0d0c07bb2c5.png)
![DELL9205 2022_1_17 13_26_26](https://user-images.githubusercontent.com/94151886/149712959-1d8b516a-2699-431e-8965-9a49201c5799.png)

**Comment by lululxvi** [comment]
Could you first figure out which line induces the error?

**Comment by sylva0** [comment]
I'm so sorry, here are the specific error
![DELL9205 2022_1_17 13_25_53](https://user-images.githubusercontent.com/94151886/149858209-15156939-6874-49ab-983c-f7c74b15e152.png)
![DELL9205 2022_1_17 13_26_26](https://user-images.githubusercontent.com/94151886/149858217-302efc09-a82b-498f-9190-811edbf1c7c8.png)

**Comment by lululxvi** [comment]
I mean if you can remove some lines until the code works, and then figure out which line is critical.
