### ISSUE TITLE
Is there a way to save the plots as .svg or .eps ?

### ISSUE THREAD

**Issue by tareqath** [lululxvi/deepxde#48]
Hello again Lu, sorry for the noobish question but I can only save them as .png.

I use 
```
from google.colab import files
files.download( "train.dat" ) 
```

And it gives me the .dat file, but did you program anything to do eps and svg ? Or what files are they in ? Or I should just use matlab or python3 to plot the .dat files I have ? Thanks !

**Comment by lululxvi** [comment]
`DeepXDE` doesn't have many built-in plotting functions. The results for training and testing is saved in `train.dat` and `test.dat`, and you can plot the results using any tools you like. Check the question "What is the expected output of DeepXDE?" at the [FAQ](https://deepxde.readthedocs.io/en/latest/user/questions_answers.html) for more information.

**Comment by tareqath** [comment]
Cheers man
