### ISSUE TITLE
Boundary Condition that seems troublesome

### ISSUE THREAD

**Issue by katayooneshkofti** [lululxvi/deepxde#481]
Dear Lu, 
I Have a set of boundary and initial conditions, all of them are zero, except one Dirichlet boundary condition which is of 10^3 order. This boundary condition seems not to be trained and when I consider all the weight_losses zero except this one, the train_loss doesn't change through the iterations. 
when I consider it as hard BC, it affects another BC train_loss and makes it extremely larger. I rescaled the output to 10^3 * y but it didn't work well. 
Now, I don't know what other solution can help me to figure out this problem. 
I would be grateful if you give me another useful suggestion.

**Comment by katayooneshkofti** [comment]
To update: I did Something else, I rescaled the output to the order of 10^3 by y* 10^3 and then considered just the weights of the first PDE and first BC equal to one. now it seems that the NN learns because both are decreasing in every iteration. 
Now, what does it mean? why when I rescale the problem and consider the whole BCs and ICs,  it doesn't train properly?

**Comment by lululxvi** [comment]
I cannot tell what happened in your case from the information you provided.

**Comment by katayooneshkofti** [comment]
sorry for being vague. I have 2 outputs as P, U . I have 2 inputs as x , t. 
there are 2 PDEs and the BCs and ICs are as follows: 
**1-** p(x=0 , t) =p0H(t) (p0 is 10^3) and H(t) is Heaviside step function 
**2-** du_x (x=0 , t) = 10^-3 * p (Robin BC)
**3-** p(x=1 , t)=0
**4-** u(x=1 , t) = 0 
**5-** the initial conditions and their derivatives are also zero. 
the train loss for the first bc is of O(10^9)-Considering it as a hard BC doesn't help to the convergence of the problem.

**Comment by lululxvi** [comment]
It seems the issue is not from the BC. It is due to something eles.
