### ISSUE TITLE
Error with dde.geometry.Rectangle in single precision - TF2.0

### ISSUE THREAD

**Issue by pescap** [lululxvi/deepxde#483]
Hi Lu Lu, 
When I run the Poisson Lshape [script](https://github.com/lululxvi/deepxde/blob/master/examples/Poisson_Lshape.py) with `float32` precision and `tensorflow` backend for a 2D unit rectangle:

```
"""Backend supported: tensorflow.compat.v1, tensorflow, pytorch"""
import deepxde as dde


def pde(x, y):
    dy_xx = dde.grad.hessian(y, x, i=0, j=0)
    dy_yy = dde.grad.hessian(y, x, i=1, j=1)
    print(x.dtype, 'x dtype')
    return -dy_xx - dy_yy - 1


def boundary(_, on_boundary):
    return on_boundary

dde.config.set_default_float('float32')
#geom = dde.geometry.Polygon([[0, 0], [1, 0], [1, -1], [-1, -1], [-1, 1], [0, 1]])
geom = dde.geometry.Rectangle([0, 0], [1, 1])
bc = dde.DirichletBC(geom, lambda x: 0, boundary)

data = dde.data.PDE(geom, pde, bc, num_domain=1200, num_boundary=120, num_test=1500)
net = dde.maps.FNN([2] + [50] * 4 + [1], "tanh", "Glorot uniform")
model = dde.Model(data, net)

model.compile("adam", lr=0.001)
model.train(epochs=50000)
model.compile("L-BFGS")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```
I get the following error:

 TypeError: Cannot convert a list containing a tensor of dtype <dtype: 'float32'> to <dtype: 'float64'> (Tensor is: <tf.Tensor 'Mean_1:0' shape=() dtype=float32>)

According to my observatons, the second call to ``pde`` is with ``x`` being a float64. 
Best wishes,
Paul

**Comment by lululxvi** [comment]
The L shape Poisson should work in tensorflow backend. What is your DeepXDE version?

**Comment by pescap** [comment]
I'm very sorry, I forgot I was using '0.13.6'. Everything is fine with '0.14.1'!
