### ISSUE TITLE
`NeumannBC` with temporal coordinates?

### ISSUE THREAD

**Issue by Saransh-cpp** [lululxvi/deepxde#485]
Greetings,

The `wave_1D.py` example says -
```py
# do not use dde.NeumannBC here, since `normal_derivative` does not work with temporal coordinate
```

Is this still an issue or has this been fixed in `DeepXDE`?

Thank you!

**Comment by lululxvi** [comment]
It is not an issue. It is designed as this. `NeumannBC` is for boundary condition for space, not time.

**Comment by Saransh-cpp** [comment]
Oh, I see. Thank you!

**Comment by Saransh-cpp** [comment]
@lululxvi can I use `NeumannBC` when defining ICs with derivatives? For instance `At t = 0 -> du(x, t) / dt = 0`, or should I use `OperatorBC` here too?

**Comment by lululxvi** [comment]
Use `OperatorBC`. `NeumannBC` only computes the gradient with respect to space coordinate.
