### ISSUE TITLE
Training a PDE based on only datapoints

### ISSUE THREAD

**Issue by cevheck** [lululxvi/deepxde#487]
Dear all,

Is there a possibility to fit an equation with measurement data. 
For example in this tutorial (https://deepxde.readthedocs.io/en/latest/demos/diffusion.1d.inverse.html), I would like to replace the data object with a version that does not need a formulation of the real underlying function (right now it is using solution=func to train the model). Instead I would like to provide the PDE with some input-output data pairs and learn the equation and value for C that way.

Thanks in advance
Cedric

**Comment by Little7776** [comment]
> Dear all,
> 
> Is there a possibility to fit an equation with measurement data. For example in this tutorial (https://deepxde.readthedocs.io/en/latest/demos/pinn_inverse/diffusion.1d.inverse.html), I would like to replace the data object with a version that does not need a formulation of the real underlying function (right now it is using solution=func to train the model). Instead I would like to provide the PDE with some input-output data pairs and learn the equation and value for C that way.
> 
> Thanks in advance Cedric

Hello, I am also trying to train the network through the measurement data set recently. May I ask you for specific implementation methods?

**Comment by lululxvi** [comment]
See https://deepxde.readthedocs.io/en/latest/demos/function.html

**Comment by DuterLAOHU** [comment]
Dear Lulu,

Thanks for your contribution! it works a lot, but I have some similar problems. 
I am trying to solve inverse problems to obtain unknown parameters in ODEs. Now I have got the ODEs with exogenous input and measurement data. **The difference is that the exogenous input data for the model comes as part of the measured data**. For example, My ODEs will contain the product of exogenous inputs and state variables. May I use the existing APIs to solve for the unknown parameters in it? How can I define dde.data.PDE object?

Best wishes for U!
hu

**Comment by lululxvi** [comment]
> Now I have got the ODEs with exogenous input and measurement data. **The difference is that the exogenous input data for the model comes as part of the measured data**. For example, My ODEs will contain the product of exogenous inputs and state variables. May I use the existing APIs to solve for the unknown parameters in it? How can I define dde.data.PDE object?

I don't understand your question.

**Comment by zyb00** [comment]
Dear Lulu, I have a similar problem. I'm trying to solve the forward problem with deepxde. There are only some discrete points as initial and boundary conditions, and there are no initial and boundary equations, can I use PointSetBC to solve them?

**Comment by zhengxinshuo99** [comment]
> Dear Lulu, I have a similar problem. I'm trying to solve the forward problem with deepxde. There are only some discrete points as initial and boundary conditions, and there are no initial and boundary equations, can I use PointSetBC to solve them.
Yes, see
https://deepxde.readthedocs.io/en/latest/modules/deepxde.icbc.html#deepxde.icbc.boundary_conditions.PointSetBC

**Comment by reactingflow** [comment]
Hello, everyone, @lululxvi @cevheck @Little7776 @DuterLAOHU @zyb00 

I'm currently learning how to utilize Deepxde to address practical chemical engineering problems. As mentioned in a similar issue by cevheck @cevheck , when dealing with a tubular chemical reactor, we might only know part of the governing equations along with some inlet and outlet information. These inlet and outlet data are typically obtained under various operating conditions and are presented in pairs (e.g., inlet molar concentration and corresponding outlet molar concentration).

My question revolves around whether there is a relationship between the number of equations and additional supplementary data. For instance, does having fewer equations mean needing more varied types of data? Is it feasible to model a one-dimensional plug flow reactor (PFR) by supplementing missing equations with extra inlet and outlet information? 

Following some readings and tests, I conducted a test case. However, the results from training show discrepancies between the trained solution and the real solution.

```
import deepxde as dde
import numpy as np
# from scipy.integrate import odeint
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# constants
L = 1
G = 4684 
rhoB = 1300
Mm = 29.48
yA0 = 0.00924 
yO2 = 0.208
Cp = 1.047
U = 345.686
P = 101.325
dt = 0.0254
TJ = 580 
# T0 = 700
H1 = -1.285e+6
H3 = -4.564e+6
E1 = 1.1304e5 
E2 = 1.315e5 
E3 = 1.197e5
R = 8.314 

Ac = np.pi * (dt/2)**2 
Ft = G*Ac/Mm 
us = 3600 
rhog = G/us
Ct = Ft/(Ac*us)
FA0 = yA0*Ft
CA0 = FA0/(Ac*us)

def equations(z, y):
    CA, CB, CC = y
    yA = CA/Ct
    yB = CB/Ct
    yC = CC/Ct
    rA, rB, rC = rates(yA, yB, yC)
    
    dCAdz = rhoB*rA/us
    dCBdz = rhoB*rB/us
    dCCdz = rhoB*rC/us
    
    return [dCAdz, dCBdz, dCCdz]

def rates(yA, yB, yC):
    T = 620.0
    k1 = np.exp(-E1/(R*T) + 19.837)
    k2 = np.exp(-E2/(R*T) + 20.86)
    k3 = np.exp(-E3/(R*T) + 18.97)
    
    rA = -(k1+k3)*yA*yO2
    rB = k1*yA*yO2 - k2*yB*yO2
    rC = k2*yB*yO2 + k3*yA*yO2
    
    return rA, rB, rC

# inlet boundary condition list
y0_list = [[CA0*0.9, 0, 0], 
           [CA0*0.8, 0, 0], 
           [CA0*0.7, 0, 0], 
           [CA0*0.6, 0, 0], 
           [CA0*0.5, 0, 0], 
           [CA0*0.4, 0, 0]] 

xvals = np.linspace(0, L, 100)
solutions = []

for y0 in y0_list:
    solution = solve_ivp(equations, [0, L], y0, method='RK45', t_eval=xvals)
    solutions.append(solution)

def gen_traindata(xvals, solutions):
    end_indices = [0, len(xvals) - 1]
    ob_x = np.array([[xvals[i]] for i in end_indices])
    
    ob_y1 = np.array([solutions[j].y[0, i] for j in range(len(solutions)) for i in end_indices])
    ob_y2 = np.array([solutions[j].y[1, i] for j in range(len(solutions)) for i in end_indices])
    ob_y3 = np.array([solutions[j].y[2, i] for j in range(len(solutions)) for i in end_indices])
    
    return ob_x, ob_y1, ob_y2, ob_y3


# generate training data
ob_x, ob_y1, ob_y2, ob_y3 = gen_traindata(xvals, solutions)

observe_y1 = dde.icbc.PointSetBC(ob_x, ob_y1, component=0)
observe_y2 = dde.icbc.PointSetBC(ob_x, ob_y2, component=1)
observe_y3 = dde.icbc.PointSetBC(ob_x, ob_y3, component=2)

def pde_system(x, y):
    CA, CB, CC= y[:, 0:1], y[:, 1:2], y[:, 2:3]
    const = y[:, 3:] # extra unknown variable
    dy1_x = dde.grad.jacobian(y, x, i=0)
    dy2_x = dde.grad.jacobian(y, x, i=1)
    dy3_x = dde.grad.jacobian(y, x, i=2)
    yA = CA / Ct
    yB = CB / Ct
    yC = CC / Ct
    rA, rB, rC = rates(yA, yB, yC)
    eq1 = dy1_x - const * rhoB * rA / us
    eq2 = dy2_x - const * rhoB * rB / us
    eq3 = dy3_x - const * rhoB * rC / us
    return [eq1, eq2, eq3]

def boundary(x, _):
    return dde.utils.isclose(x[0], 0)

geom = dde.geometry.Interval(0, L)
bc1 = dde.icbc.DirichletBC(geom, lambda x: CA0, boundary, component=0)
bc2 = dde.icbc.DirichletBC(geom, lambda x: 0, boundary, component=1)
bc3 = dde.icbc.DirichletBC(geom, lambda x: 0, boundary, component=2)

data = dde.data.PDE(
    geom, 
    pde_system, 
    [bc1, bc2, bc3, observe_y1, observe_y2, observe_y3], 
    num_domain=100, 
    num_boundary=2,
    train_distribution="uniform",
    # anchors=ob_x,
)

layer_size = [1] + [50] * 3 + [4]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.nn.FNN(layer_size, activation, initializer)

model = dde.Model(data, net)
model.compile("adam", lr=0.001)
losshistory, train_state = model.train(iterations=20000)

dde.saveplot(losshistory, train_state, issave=True, isplot=False)

# postprocess
data = np.loadtxt('loss.dat', comments='#')

step = data[:, 0]
loss_train = data[:, 1]
loss_test = data[:, 2]

plt.figure(figsize=(10, 6))

plt.semilogy(step, loss_train, label='Training Loss')
plt.semilogy(step, loss_test, label='Testing Loss', linestyle='--')
plt.title('Loss over Training Steps')
plt.xlabel('Step')
plt.ylabel('Loss')
plt.legend()

plt.grid(True, which="both", ls="--")

plt.show()

data = np.loadtxt('test.dat', comments='#')

x = data[:, 0]
y1_pred = data[:, 1]
y2_pred = data[:, 2]
y3_pred = data[:, 3]

plt.figure(figsize=(10, 6))

plt.plot(x, y1_pred, label='y1_pred', marker='x', linestyle='', color='red')
plt.plot(x, y2_pred, label='y2_pred', marker='+', linestyle='', color='red')
plt.plot(x, y3_pred, label='y3_pred', marker='x', linestyle='', color='red')

plt.xlabel('X')
plt.ylabel('Y')
plt.legend()

plt.grid(True)

plt.show()
```

![Image](https://github.com/user-attachments/assets/5aa33102-a39f-4f35-829a-bbd24268250a)

![Image](https://github.com/user-attachments/assets/f31a265c-516d-4356-8a4c-97a03e62b85a)

![Image](https://github.com/user-attachments/assets/a98ca10c-0a83-4d2c-9c4e-a4d8d754226f)

Could anyone provide any advice or suggestions on this matter? Your guidance would be greatly appreciated.

Thank you very much!

Best regards,

**Comment by Mouhamedsaw** [comment]
> See https://deepxde.readthedocs.io/en/latest/demos/function.html

Hi everyone,

Dear Lu Lu,

I am trying to approach data measurements from Navier-Stockes equations (cylinder_nektar_wake.mat) with a neural network. 


I used the same approach as suggested above but I got the following error:


TypeError                                 Traceback (most recent call last)

[<ipython-input-9-85f03c8e4ca0>](https://localhost:8080/#) in <cell line: 0>()
     16 
     17 # Training datasets and Loss
---> 18 data = dde.data.DataSet(
     19     [observe_u, observe_v],
     20     anchors=ob_xyt,

TypeError: DataSet.__init__() got an unexpected keyword argument 'anchors'.


Following is the minimal code to reproduce the error above.

` 

!pip install deepxde


import deepxde as dde
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

from google.colab import files
uploaded = files.upload()
import os
os.listdir('/content/')  # Lists all files in /content/

# Load training data
def load_training_data(num):
    data = loadmat('cylinder_nektar_wake.mat')
    #data = loadmat("../dataset/cylinder_nektar_wake.mat")
    #obs2 = scipy.io.loadmat('/home/jupyter-mdiallo/Fawzoulazim_UCAD_AIMS_2024_June_4th_2024_Keur_Massar/cylinder_nektar_wake.mat') 
    U_star = data["U_star"]  # N x 2 x T
    P_star = data["p_star"]  # N x T
    t_star = data["t"]  # T x 1
    X_star = data["X_star"]  # N x 2
    N = X_star.shape[0]
    T = t_star.shape[0]
    # Rearrange Data
    XX = np.tile(X_star[:, 0:1], (1, T))  # N x T
    YY = np.tile(X_star[:, 1:2], (1, T))  # N x T
    TT = np.tile(t_star, (1, N)).T  # N x T
    UU = U_star[:, 0, :]  # N x T
    VV = U_star[:, 1, :]  # N x T
    PP = P_star  # N x T
    x = XX.flatten()[:, None]  # NT x 1
    y = YY.flatten()[:, None]  # NT x 1
    t = TT.flatten()[:, None]  # NT x 1
    u = UU.flatten()[:, None]  # NT x 1
    v = VV.flatten()[:, None]  # NT x 1
    p = PP.flatten()[:, None]  # NT x 1
    # training domain: X × Y = [1, 8] × [−2, 2] and T = [0, 7]
    data1 = np.concatenate([x, y, t, u, v, p], 1)
    data2 = data1[:, :][data1[:, 2] <= 7]
    data3 = data2[:, :][data2[:, 0] >= 1]
    data4 = data3[:, :][data3[:, 0] <= 8]
    data5 = data4[:, :][data4[:, 1] >= -2]
    data_domain = data5[:, :][data5[:, 1] <= 2]
    # choose number of training points: num =7000
    idx = np.random.choice(data_domain.shape[0], num, replace=False)
    x_train = data_domain[idx, 0:1]
    y_train = data_domain[idx, 1:2]
    t_train = data_domain[idx, 2:3]
    u_train = data_domain[idx, 3:4]
    v_train = data_domain[idx, 4:5]
    p_train = data_domain[idx, 5:6]
    return [x_train, y_train, t_train, u_train, v_train, p_train]



# Get the training data: num = 7000
[ob_x, ob_y, ob_t, ob_u, ob_v, ob_p] = load_training_data(num=7000)
ob_xyt = np.hstack((ob_x, ob_y, ob_t))
observe_u = dde.icbc.PointSetBC(ob_xyt, ob_u, component=0)
observe_v = dde.icbc.PointSetBC(ob_xyt, ob_v, component=1)



# Training datasets and Loss
data = dde.data.DataSet(
    [observe_u, observe_v],
    anchors=ob_xyt,
)


# Neural Network setup
layer_size = [3] + [50] * 6 + [3]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.nn.FNN(layer_size, activation, initializer)
model = dde.Model(data, net)


model = dde.Model(data, net)
model.compile("adam", lr=0.001)
losshistory, train_state = model.train(iterations=50000, display_every=1000)

dde.saveplot(losshistory, train_state, issave=True, isplot=True)

`


Could anyone provide any advice or suggestions on this matter? 
Thank you in advance

**Comment by 101AlexMartin** [comment]
@Mouhamedsaw get rid of the anchors argument in DataSet and it should work:
```
data = dde.data.DataSet(
[observe_u, observe_v])
```

**Comment by 101AlexMartin** [comment]
> Hello, everyone, [@lululxvi](https://github.com/lululxvi) [@cevheck](https://github.com/cevheck) [@Little7776](https://github.com/Little7776) [@DuterLAOHU](https://github.com/DuterLAOHU) [@zyb00](https://github.com/zyb00)
> 
> I'm currently learning how to utilize Deepxde to address practical chemical engineering problems. As mentioned in a similar issue by cevheck [@cevheck](https://github.com/cevheck) , when dealing with a tubular chemical reactor, we might only know part of the governing equations along with some inlet and outlet information. These inlet and outlet data are typically obtained under various operating conditions and are presented in pairs (e.g., inlet molar concentration and corresponding outlet molar concentration).
> 
> My question revolves around whether there is a relationship between the number of equations and additional supplementary data. For instance, does having fewer equations mean needing more varied types of data? Is it feasible to model a one-dimensional plug flow reactor (PFR) by supplementing missing equations with extra inlet and outlet information?
> 
> Following some readings and tests, I conducted a test case. However, the results from training show discrepancies between the trained solution and the real solution.
> 
> ```
> import deepxde as dde
> import numpy as np
> # from scipy.integrate import odeint
> from scipy.integrate import solve_ivp
> import matplotlib.pyplot as plt
> 
> # constants
> L = 1
> G = 4684 
> rhoB = 1300
> Mm = 29.48
> yA0 = 0.00924 
> yO2 = 0.208
> Cp = 1.047
> U = 345.686
> P = 101.325
> dt = 0.0254
> TJ = 580 
> # T0 = 700
> H1 = -1.285e+6
> H3 = -4.564e+6
> E1 = 1.1304e5 
> E2 = 1.315e5 
> E3 = 1.197e5
> R = 8.314 
> 
> Ac = np.pi * (dt/2)**2 
> Ft = G*Ac/Mm 
> us = 3600 
> rhog = G/us
> Ct = Ft/(Ac*us)
> FA0 = yA0*Ft
> CA0 = FA0/(Ac*us)
> 
> def equations(z, y):
>     CA, CB, CC = y
>     yA = CA/Ct
>     yB = CB/Ct
>     yC = CC/Ct
>     rA, rB, rC = rates(yA, yB, yC)
>     
>     dCAdz = rhoB*rA/us
>     dCBdz = rhoB*rB/us
>     dCCdz = rhoB*rC/us
>     
>     return [dCAdz, dCBdz, dCCdz]
> 
> def rates(yA, yB, yC):
>     T = 620.0
>     k1 = np.exp(-E1/(R*T) + 19.837)
>     k2 = np.exp(-E2/(R*T) + 20.86)
>     k3 = np.exp(-E3/(R*T) + 18.97)
>     
>     rA = -(k1+k3)*yA*yO2
>     rB = k1*yA*yO2 - k2*yB*yO2
>     rC = k2*yB*yO2 + k3*yA*yO2
>     
>     return rA, rB, rC
> 
> # inlet boundary condition list
> y0_list = [[CA0*0.9, 0, 0], 
>            [CA0*0.8, 0, 0], 
>            [CA0*0.7, 0, 0], 
>            [CA0*0.6, 0, 0], 
>            [CA0*0.5, 0, 0], 
>            [CA0*0.4, 0, 0]] 
> 
> xvals = np.linspace(0, L, 100)
> solutions = []
> 
> for y0 in y0_list:
>     solution = solve_ivp(equations, [0, L], y0, method='RK45', t_eval=xvals)
>     solutions.append(solution)
> 
> def gen_traindata(xvals, solutions):
>     end_indices = [0, len(xvals) - 1]
>     ob_x = np.array([[xvals[i]] for i in end_indices])
>     
>     ob_y1 = np.array([solutions[j].y[0, i] for j in range(len(solutions)) for i in end_indices])
>     ob_y2 = np.array([solutions[j].y[1, i] for j in range(len(solutions)) for i in end_indices])
>     ob_y3 = np.array([solutions[j].y[2, i] for j in range(len(solutions)) for i in end_indices])
>     
>     return ob_x, ob_y1, ob_y2, ob_y3
> 
> 
> # generate training data
> ob_x, ob_y1, ob_y2, ob_y3 = gen_traindata(xvals, solutions)
> 
> observe_y1 = dde.icbc.PointSetBC(ob_x, ob_y1, component=0)
> observe_y2 = dde.icbc.PointSetBC(ob_x, ob_y2, component=1)
> observe_y3 = dde.icbc.PointSetBC(ob_x, ob_y3, component=2)
> 
> def pde_system(x, y):
>     CA, CB, CC= y[:, 0:1], y[:, 1:2], y[:, 2:3]
>     const = y[:, 3:] # extra unknown variable
>     dy1_x = dde.grad.jacobian(y, x, i=0)
>     dy2_x = dde.grad.jacobian(y, x, i=1)
>     dy3_x = dde.grad.jacobian(y, x, i=2)
>     yA = CA / Ct
>     yB = CB / Ct
>     yC = CC / Ct
>     rA, rB, rC = rates(yA, yB, yC)
>     eq1 = dy1_x - const * rhoB * rA / us
>     eq2 = dy2_x - const * rhoB * rB / us
>     eq3 = dy3_x - const * rhoB * rC / us
>     return [eq1, eq2, eq3]
> 
> def boundary(x, _):
>     return dde.utils.isclose(x[0], 0)
> 
> geom = dde.geometry.Interval(0, L)
> bc1 = dde.icbc.DirichletBC(geom, lambda x: CA0, boundary, component=0)
> bc2 = dde.icbc.DirichletBC(geom, lambda x: 0, boundary, component=1)
> bc3 = dde.icbc.DirichletBC(geom, lambda x: 0, boundary, component=2)
> 
> data = dde.data.PDE(
>     geom, 
>     pde_system, 
>     [bc1, bc2, bc3, observe_y1, observe_y2, observe_y3], 
>     num_domain=100, 
>     num_boundary=2,
>     train_distribution="uniform",
>     # anchors=ob_x,
> )
> 
> layer_size = [1] + [50] * 3 + [4]
> activation = "tanh"
> initializer = "Glorot uniform"
> net = dde.nn.FNN(layer_size, activation, initializer)
> 
> model = dde.Model(data, net)
> model.compile("adam", lr=0.001)
> losshistory, train_state = model.train(iterations=20000)
> 
> dde.saveplot(losshistory, train_state, issave=True, isplot=False)
> 
> # postprocess
> data = np.loadtxt('loss.dat', comments='#')
> 
> step = data[:, 0]
> loss_train = data[:, 1]
> loss_test = data[:, 2]
> 
> plt.figure(figsize=(10, 6))
> 
> plt.semilogy(step, loss_train, label='Training Loss')
> plt.semilogy(step, loss_test, label='Testing Loss', linestyle='--')
> plt.title('Loss over Training Steps')
> plt.xlabel('Step')
> plt.ylabel('Loss')
> plt.legend()
> 
> plt.grid(True, which="both", ls="--")
> 
> plt.show()
> 
> data = np.loadtxt('test.dat', comments='#')
> 
> x = data[:, 0]
> y1_pred = data[:, 1]
> y2_pred = data[:, 2]
> y3_pred = data[:, 3]
> 
> plt.figure(figsize=(10, 6))
> 
> plt.plot(x, y1_pred, label='y1_pred', marker='x', linestyle='', color='red')
> plt.plot(x, y2_pred, label='y2_pred', marker='+', linestyle='', color='red')
> plt.plot(x, y3_pred, label='y3_pred', marker='x', linestyle='', color='red')
> 
> plt.xlabel('X')
> plt.ylabel('Y')
> plt.legend()
> 
> plt.grid(True)
> 
> plt.show()
> ```
> 
> ![Image](https://github.com/user-attachments/assets/5aa33102-a39f-4f35-829a-bbd24268250a)
> 
> ![Image](https://github.com/user-attachments/assets/f31a265c-516d-4356-8a4c-97a03e62b85a)
> 
> ![Image](https://github.com/user-attachments/assets/a98ca10c-0a83-4d2c-9c4e-a4d8d754226f)
> 
> Could anyone provide any advice or suggestions on this matter? Your guidance would be greatly appreciated.
> 
> Thank you very much!
> 
> Best regards,

@reactingflow Try increasing the number of boundary condition points you are using (i.e. `num_boundary`). That should provide more accurate results.

**Comment by Mouhamedsaw** [comment]
Hi @101AlexMartin,

Thank you for your suggestion. 

I got the following error when I remove anchors:

`AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 data = dde.data.DataSet(
      2 [observe_u, observe_v])

File ~/.local/lib/python3.9/site-packages/deepxde/data/dataset.py:29, in DataSet.__init__(self, X_train, y_train, X_test, y_test, fname_train, fname_test, col_x, col_y, standardize)
     16 def __init__(
     17     self,
     18     X_train=None,
   (...)
     26     standardize=False,
     27 ):
     28     if X_train is not None:
---> 29         self.train_x = X_train.astype(config.real(np))
     30         self.train_y = y_train.astype(config.real(np))
     31         self.test_x = X_test.astype(config.real(np))

AttributeError: 'list' object has no attribute 'astype'`
