### ISSUE TITLE
Stuck error at the order of 1e-1

### ISSUE THREAD

**Issue by jhssyb** [lululxvi/deepxde#49]
I appreciate the author shares his code with us, faciliating our exploration for PINN. Recently I tried to use the DeepXDE to model the potential flow over cylinder, a brief introduction can be found at https://en.wikipedia.org/wiki/Potential_flow_around_a_circular_cylinder. The governing equation is the Lapace equation in terms of flow potential (phi). I built the geometry using "geom = CSGDifference(rectangular, circle)", and set the Neuman boundary condition using for Rectangular of (u=1, v=0) and Circular(radial velocity of 0, and tangential velocity from analytic solution. The input is two dimensional coordinate and output is one variable(phi). However, when I trained the neural network, the error stuck at 0.1 even if I increased layers/neurons and training steps. None of these attempt succeeds, Hope to get some advice from you. 

The code is shown `below```
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

import deepxde as dde
from deepxde.geometry.csg import CSGDifference

def main():
    def pde(x, phi):
        du_xy = tf.gradients(phi, x)[0]
        du_x, du_y = du_xy[:, 0:1], du_xy[:, 1:]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        du_yy = tf.gradients(du_y, x)[0][:, 1:]
        return du_xx + du_yy

    def Rect_func(x):
        fun = np.concatenate((np.zeros((len(x), 1)) + 1, np.zeros((len(x), 1))), axis=1)
        return fun

    U = 1

    def Circle_fun(x):
        ux = 2 * U * x[1] ** 2 / (x[0] ** 2 + x[1] ** 2)
        uy = -2 * U * x[1] * x[0] / (x[0] ** 2 + x[1] ** 2)
        Ux = np.expand_dims(ux, axis=0)
        Uy = np.expand_dims(uy, axis=0)

        return np.concatenate((Ux, Uy), axis=1)

    circle = dde.geometry.Disk([0, 0], 0.5)
    rectangular = dde.geometry.Rectangle([-3, -2], [3, 2])
    geom = CSGDifference(rectangular, circle)

    def boundary_rect(x, on_boundary):
        return on_boundary and rectangular.on_boundary(x)

    def boundary_circle(x, on_boundary):
        return on_boundary and circle.on_boundary(x)

    bc_rect = dde.NeumannBC(geom, Rect_func, boundary_rect)
    bc_circle = dde.NeumannBC(geom, Circle_fun, boundary_circle)
    bcs = [bc_rect, bc_circle]

    
    data = dde.data.PDE(geom, pde, bcs, num_domain=2000, num_boundary=500, num_test=300)
    net = dde.maps.FNN([2] + [50] * 5 + [1], "sigmoid", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("rmsprop", lr=0.001)
    model.train(epochs=6000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()`

**Comment by lululxvi** [comment]
What is your BCs? The unknown is `phi`, and thus the BCs should be defined in `phi`.

**Comment by jhssyb** [comment]
Hi Lu, thanks for your prompt reply. My boundary conditions are defined in Rect_func(x) and Circle_fun(x), which used to define u=phi_x, v=phi_y for Rectangular and Circle. For the Cricle_fun(x), the x[0] and x[1] are used to express sin\theta and cos\theta, which performs tranformation between cylinder coordinate and catesian coordinate

**Comment by jhssyb** [comment]
![flowovercyilnder](https://user-images.githubusercontent.com/55566543/82985547-c99e0800-a026-11ea-8312-6568cb22822c.jpg)
The detailed information about the BC setup is shown in the picture. Hope to get your help

**Comment by lululxvi** [comment]
There are two BCs at the surface of cylinder, and thus you need to define them separately. For example, for the first BC at the surface of cylinder: `dphi/dx = f(theta)`. Because this BC is none of the standard Dirichlet, Neumann, Robin or Periodic, we should use a more general [`OperatorBC`](https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.OperatorBC)

```python
def func(inputs, outputs, X):
    # Compute theta from X using numpy or tensorflow. You need to be careful here
    theta = ... np.arctan2(X[:, 1:], X[:, 0:1]) ...
    # Compute dphi/dx as you do for the PDE
    dphi_dx = ...
    return dphi_dx - f(theta)

bc = dde.OperatorBC(geom, func, on_boundary)
```

The BCs for the outside rectangle can be defined similarly, and each BC should be defined separately.

**Comment by jhssyb** [comment]
Thanks for your reply, Lu. For the BC like dphi/dx = f(theta), it has the same form of Neumann BC. Why cannot we use this one? In the source code, Neumann is defined as:
`class NeumannBC(BC):
    """Neumann boundary conditions: dy/dn(x) = func(x).
    """

    def __init__(self, geom, func, on_boundary, component=0):
        super(NeumannBC, self).__init__(geom, on_boundary, component)
        self.func = func

    def error(self, X, inputs, outputs, beg, end):
        return self.normal_derivative(X, inputs, outputs, beg, end) - self.func(
            X[beg:end]
        )
`
Previously I just replaced y by \phi. From my understanding, if I use the Neumann BC defined in the source code, the code will automatically compute dphi_dx(dphi_xy[:,0:1]) and dphi_xy[:,1:], in a way like" dphix_xy=tf.gradients(phi,x)[0]". Anything wrong about my understanding?

**Comment by lululxvi** [comment]
Neumann BC is `du/dn = n * [du/dx, du/dy]` not `du/dx` or `du/dy`. Sometimes they are equal, but in general not.

**Comment by jhssyb** [comment]
Thanks. I rewrite the BC according to your suggestion, it gives an error when implementing "class OperatorBC(BC):" at line 136, which shows 
" return self.func(inputs, outputs, X)[beg:end]

TypeError: 'list' object is not callable"

My modified code is shown below:
`   def bc_circleX(x,phi):
        # Compute velocity in X direction
        ux = 2 * U * x[1] ** 2 / (x[0] ** 2 + x[1] ** 2)
        # Compute dphi/dx as for the PDE
        du_xy = tf.gradients(phi, x)[0]
        dphi_dx = du_xy[:, 0:1]
        return dphi_dx - ux
    
    def bc_circleY(x,phi):
        # Compute velocity in Y direction
        uy = -2 * U * x[1] * x[0] / (x[0] ** 2 + x[1] ** 2)
        # Compute dphi/dx as for the PDE
        du_xy = tf.gradients(phi, x)[0]
        dphi_dy = du_xy[:, 1:]
        return dphi_dy - uy
    

    def bc_rectX(x,phi):
        du_xy = tf.gradients(phi, x)[0]
        dphi_dx = du_xy[:, 0:1]
        return dphi_dx-(np.zeros(len(x))+1)
                    
    def bc_rectY(x,phi):
        du_xy = tf.gradients(phi, x)[0]
        dphi_dy = du_xy[:, 1:]
        return dphi_dy-np.zeros(len(x))
   

    circle = dde.geometry.Disk([0, 0], 0.5)
    rectangular = dde.geometry.Rectangle([-3, -2], [3, 2])
    geom = CSGDifference(rectangular, circle)

    def boundary_rect(x, on_boundary):
        return on_boundary and rectangular.on_boundary(x)

    def boundary_circle(x, on_boundary):
        return on_boundary and circle.on_boundary(x)

    bc_rect =  dde.OperatorBC(geom, [bc_rectX, bc_rectY], boundary_rect)
    bc_circle = dde.OperatorBC(geom, [bc_circleX,bc_circleY], boundary_circle)
    bcs = [bc_rect, bc_circle]`

**Comment by lululxvi** [comment]
FIrst, you need split `dde.OperatorBC(geom, [bc_rectX, bc_rectY], boundary_rect)` into two BCs: `dde.OperatorBC(geom, bc_rectX, boundary_rect)` and `dde.OperatorBC(geom, bc_rectY, boundary_rect)`

Second, the bc_rectX, bc_rectY, bc_circleX, bc_circleY should be
```python
def func(inputs, outputs, X):
    ...
```
see https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.OperatorBC

**Comment by jhssyb** [comment]
Thanks a lot. I changed my code based on your sample snippet, does this correction is right?
`
    def bc_circleX(inputs, outputs, _):
        # Compute velocity in X direction
        ux = 2 * U * inputs[:, 1:] ** 2 / (inputs[:, 0:1] ** 2 + inputs[:, 1:] ** 2)
        # Compute dphi/dx as for the PDE
        du = tf.gradients(outputs, inputs)[0]
        dphi_dx = du[:, 0:1]
        return dphi_dx - ux

    def bc_circleY(inputs, outputs, _):
        # Compute velocity in X direction
        uy = -2 * U * x[1] * x[0] / (x[0] ** 2 + x[1] ** 2)
        # Compute dphi/dx as for the PDE
        du = tf.gradients(outputs, inputs)[0]
        dphi_dy = du[:, 1:]
        return dphi_dy - uy

                 
    def bc_rectY(inputs, outputs, _):
        du = tf.gradients(outputs, inputs)[0]
        dphi_dy = du[:, 1:]
        return dphi_dy - np.zeros([tf.size(inputs),1])
    
    def bc_rectX(inputs, outputs, _):
        du = tf.gradients(outputs, inputs)[0]
        dphi_dx = du[:, 0:1]
        return dphi_dx - (np.zeros(tf.size(inputs))+1)

    circle = dde.geometry.Disk([0, 0], 0.5)
    rectangular = dde.geometry.Rectangle([-3, -2], [3, 2])
    geom = CSGDifference(rectangular, circle)

    def boundary_rect(x, on_boundary):
        return on_boundary and rectangular.on_boundary(x)

    def boundary_circle(x, on_boundary):
        return on_boundary and circle.on_boundary(x)

    bc_rectX =  dde.OperatorBC(geom, bc_rectX, boundary_rect)
    bc_rectY =  dde.OperatorBC(geom, bc_rectY, boundary_rect)
    bc_circleX = dde.OperatorBC(geom, bc_circleX, boundary_circle)
    bc_circleY= dde.OperatorBC(geom, bc_circleY, boundary_circle)
    bcs = [bc_rectX,bc_rectY, bc_circleX, bc_circleY]`

**Comment by lululxvi** [comment]
- `bc_circleY` is still wrong. no `x`
- `np.zeros([tf.size(inputs),1])` can be removed
- `np.zeros(tf.size(inputs))+1` is just `1`

**Comment by jhssyb** [comment]
Really appreciate your assistance, now it runs well, great help! But I have two small questions:
1) In all your codes, the gradients is written as "tf.gradients(outputs, inputs)[0]", but from the official document, there is no need to add [0], when I tried to remove [0], it reports an error. What is the purpose of using [0]?
2) For 2D problems, my understanding of  "dde.OperatorBC(geom, fun, boundary_rect)" is that the "fun" is a list like [fun(x),fun(y)] because the geom is defined in x and y. But it seems everytime it either deals with fun(x) or fun(y). 
Usually we write it like:
`bc_rectX =  dde.OperatorBC(geom, bc_rectX, boundary_rect)
bc_rectY =  dde.OperatorBC(geom, bc_rectY, boundary_rect)`
However, if I shift the order, say:
`bc_rectY =  dde.OperatorBC(geom, bc_rectY, boundary_rect)
bc_rectX =  dde.OperatorBC(geom, bc_rectX, boundary_rect)`
Does the program assign bc_rectY to BC(x-coordinate) or BC(y-coordinate)? Hope to get your instructions.

**Comment by lululxvi** [comment]
1. It is the issue of `tf.gradients`. The document is not clear, and it always returns a list.
2. The func is func(X), where X is (x, y), not func(x) or func(y). Thus the order does not matter.

**Comment by jhssyb** [comment]
Thanks for your kind help, it works well now.

**Comment by zonexo** [comment]
> Thanks for your kind help, it works well now.

Hi jhssyb,

Is it possible for you to share the working code?

Thank you!
