### ISSUE TITLE
Comparison between solutions given by FEM, Deepxde and exact solution 

### ISSUE THREAD

**Issue by Mouhamedsaw** [lululxvi/deepxde#493]
Hi Dr Lulu
First of all, thanks for your dedicated work and your contribution to Artificial Intelligence.
In your last paper at the subsection 2.5, You have done comparisons between FEM and PINNs.
Now do you have a code which shows the three solutions for the Burgers' equation in 1D.
Thanks for advance.
Cordialy.

**Comment by lululxvi** [comment]
It is standard FEM code. You should be able to find it online.

**Comment by Mouhamedsaw** [comment]
Thanks you Dr Lulu for your answer. Ok It's clear now
