### ISSUE TITLE
DeepXDE for 1D Time-dependent Wave Equation

### ISSUE THREAD

**Issue by engsbk** [lululxvi/deepxde#497]
I have published a paper about modeling a 1D wave equation with a single time-dependent source. It would be great to see it in the list of related publications.

**Comment by lululxvi** [comment]
What is the citation of the paper, the same format as those in https://deepxde.readthedocs.io/en/latest/user/research.html? Also a link to the paper.

**Comment by engsbk** [comment]
Alkhadhr S, Liu X, Almekkawy M (2021) Modeling of the Forward Wave Propagation Using Physics-Informed Neural Networks. In: 2021 IEEE Inter- national Ultrasonics Symposium (IUS), pp 1–4, https://doi.org/10.1109/ IUS52206.2021.9593574, iSSN: 1948-5727

**Comment by lululxvi** [comment]
@ChenxiWu123 Here is one.
