### ISSUE TITLE
Error in Shape of tensor

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#50]
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde

import tensorflow as tf

def main():
    
    def pde(x, y):
        
        phio = 0.1003
        kts = 2.49
        ktf = 0.6
        rhof = 1000
        cpf = 4200
        
        qs = 0
        
        kt = ( 1 - phio )* kts + phio * ktf
        
        
        y1, y2 = y[:, 0:1], y[:, 1:]
        
        y1 = np.zeros(x.shape)
        
        dy2_x = tf.gradients(y2 , x)[0]
        
        dy2_x, dy2_y = dy2_x[:, 0 : 1], dy2_x[:, 1:]
        
        dy2_xx = tf.gradients(dy2_x, x )[0][:, 0:1]
        
        dy2_yy = tf.gradients(dy2_x, x )[0][: , 1:]
        
        return [ y1 , -kt * ( dy2_xx + dy2_yy ) + rhof * cpf * y1 * ( dy2_x + dy2_y) - qs ]
        
        
    def func(x):
        
        
        return 473.15 * np.ones(x.shape)
        
    
    def func_n(x):
        
        return np.zeros((x.shape))

    geom = dde.geometry.Rectangle([0,0], [10,10])
    
    def boundary_l(x , on_boundary ):
        return on_boundary and np.isclose( x[0], 0 )
    
    def boundary_r(x , on_boundary):
        return on_boundary and np.isclose(x[0], 10)
    
    def boundary_upper(x, on_boundary ):
        return on_boundary and np.isclose(x[1] , 10)
    
    def boundary_lower(x , on_boundary ):
        return on_boundary and np.isclose(x[1], 0)
    
    
    bc_l = dde.DirichletBC( geom, func, boundary_l )
    bc_r = dde.DirichletBC( geom, func, boundary_r )
    bc_upper = dde.NeumannBC( geom, func_n, boundary_upper)
    bc_lower = dde.NeumannBC( geom, func_n, boundary_lower )
    
    
    data = dde.data.PDE( geom, pde, [bc_l, bc_r, bc_upper, bc_lower], 
                        num_domain = 1000,
                        num_boundary = 400,
                        num_test = 2500 )
    
    layer_size = [2] + [50]*2 + [2]
    
    activation = "tanh"
    
    initializer = "Glorot uniform"
    
    net = dde.maps.FNN( layer_size, activation, initializer )
    
    model = dde.Model( data, net )
    model.compile( "adam", lr = 0.001)
    model.train(epochs = 5000 )
    model.compile("L-BFGS-B")
    
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()

I am trying to run this code but I am getting error at 
y1 = np.zeros(x.shape)

I have replaced it with y1 = np.zeros((len(x),1) also.

error displayed as:   
  File "D:\PhD_Box\Code\Practice_Code\DEEPXDE\steady.py", line 36, in pde
    y1 = np.zeros(x.shape)

TypeError: __index__ returned non-int (type NoneType)

Kindly suggest me how to rectify it.

**Comment by lululxvi** [comment]
`y1` is the first network output. Why do you assign 0 to `y1`?

**Comment by SanjuSoni** [comment]
Actually, I have two system of PDE

first equation is equal to zero due to some parameters.

and second equation is using the value of y1 (=0)
.

I can formulate it into single equation also that will include only the y2
expression.

**Comment by lululxvi** [comment]
I am a little confused. Could you provide me the PDE?

**Comment by SanjuSoni** [comment]
![qf](https://user-images.githubusercontent.com/61820415/82981068-aebc9b00-a008-11ea-8d95-b7c86b1c8b39.PNG)


![T](https://user-images.githubusercontent.com/61820415/82981106-c8f67900-a008-11ea-901d-8694334441ac.PNG)


![parameter](https://user-images.githubusercontent.com/61820415/82981152-e1ff2a00-a008-11ea-8281-7d31e17150cd.PNG)



Above two PDE define a problem and the parameters are given in the table.

due to simplicity , value of qf set to zero.
i.e    qf  = 0


for geometry, we have a square of 20 x 20 (m^2) but I have set it equal to 10 x 10.

Dirichlet boundary at the left and right edge has been assigned.
( right edge has bc 473.15 for the steady problem).

Neumann boundary assigned to upper and lower edge of the square.

![boundary](https://user-images.githubusercontent.com/61820415/82981406-9e58f000-a009-11ea-98d3-9e2933d52943.PNG)



**We had a discussion with this problem but unfortunately due to some update in your module my result is totally different from the outcomes.**

**Comment by SanjuSoni** [comment]
We had a quality discussion before but now the results are not matching at all.

It might be my fault somewhere in coding.

Kindly comment on it.

Thanks.

**Comment by smao-astro** [comment]
Hi @SanjuSoni ,

> due to simplicity , value of qf set to zero.

could you make it clear that it is because some reason not specified in the PDE that you think qf is zero, or that you think the right hand side of first eq is zero so that qf is zero? I am just wondering why not simplify (manually) the PDE first and then feed to the neural network.

**Comment by SanjuSoni** [comment]
let me clarify, 
this is very simple model for convection process in porous medium.

This model belong to a paper in which they have assumed the value of qf = 0. 
(that is assigned y1 in the code)

For simplicity in solving the PDE and result comparision between FEM and Deep Collocation method.

if you allow me, I can give you the paper reference.

kindly comment something

**Comment by SanjuSoni** [comment]
Hello @smao-astro @lululxvi ,
I have simplified the problem and coded accordingly but the output result is not matching from the FEM result of that problem.

kindly suggest something.


`# -*- coding: utf-8 -*-
"""
Created on Wed May 27 19:54:09 2020

@author: SUMANT
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde

import tensorflow as tf


def main():
    def pde(x, y):
        
        
        phio = 0.1003
        kts = 2.49
        ktf =   0.6
        
        kt = ( 1- phio )*kts + phio*ktf
        
        
        dy_x = tf.gradients( y, x)[0]
        
        dy_x, dy_y = dy_x[:, 0:1 ], dy_x[:, 1:]
        
        dy_xx = tf.gradients( dy_x, x )[0][:, 0:1 ]
        
        dy_yy = tf.gradients( dy_y, x )[0][:, 1:]
        
        return -kt*( dy_xx + dy_yy )   

    

    def func(x):
        
        return 473.15* np.ones((len(x), 1))
    
    def func_n( x ):
        
        return np.zeros((len(x), 1))
    
    
    
    geom = dde.geometry.Rectangle([0,0], [10,10])
    
    def boundary_l(x , on_boundary ):
        return on_boundary and np.isclose( x[0], 0 )
    
    def boundary_r(x , on_boundary):
        return on_boundary and np.isclose(x[0], 10)
    
    def boundary_upper(x, on_boundary ):
        return on_boundary and np.isclose(x[1] , 10)
    
    def boundary_lower(x , on_boundary ):
        return on_boundary and np.isclose(x[1], 0)
    
    
    
    
    bc_l = dde.DirichletBC( geom, func, boundary_l )
    bc_r = dde.DirichletBC( geom, func, boundary_r )
    bc_upper = dde.NeumannBC( geom, func_n, boundary_upper)
    bc_lower = dde.NeumannBC( geom, func_n, boundary_lower )
    
    
    data = dde.data.PDE( geom, pde, [bc_l, bc_r, bc_upper, bc_lower], 
                        num_domain = 1000,
                        num_boundary = 400,
                        num_test = 2500 )
    
    layer_size = [2] + [50]*2 + [1]
    
    activation = "tanh"
    
    initializer = "Glorot uniform"
    
    net = dde.maps.FNN( layer_size, activation, initializer )
    
    model = dde.Model( data, net )
    model.compile( "adam", lr = 0.001)
    model.train(epochs = 15000 )
    model.compile("L-BFGS-B")
    
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
        `


output result after 15000 epoches 

![result1](https://user-images.githubusercontent.com/61820415/83043406-7c3e8c80-a060-11ea-9fef-1aedf6b4030e.PNG)

graphof test and train loss

![train loss](https://user-images.githubusercontent.com/61820415/83043420-7fd21380-a060-11ea-8ea3-8f1cf21ce25e.PNG)

different loss during steps

![train step](https://user-images.githubusercontent.com/61820415/83043430-83fe3100-a060-11ea-95d5-e7fb547f6ba8.PNG)



but the output value should be :

![result_FEM](https://user-images.githubusercontent.com/61820415/83043776-e9522200-a060-11ea-8ad2-852cbc71bf96.PNG)

**Comment by smao-astro** [comment]
@SanjuSoni your loss looks good, but the output does not meet with the ground truth. After having a look at your last plot (ground truth), I have a question: the value on the right and left boundary should be different (red vs blue), why did you use the same `func()` for bc_l and bc_r?

**Comment by SanjuSoni** [comment]
@smao-astro actually in the domain, the right verticle edge has bc  T_right = 473.15 - 10*t    per year.

Since, it is a steady heat transfer problem, that's why I neglect the term ( **-10* t** ) from Dirichlet BC for the right side edge. i.e func = 473.15 for left and right Dirichlet BC.

Now, I have changed the BC for the right edge T_right = 473.15 - 10*5 = 423.15 K
for five years.

But, again the result has a constant value 473.15 throughout the domain.

I am not getting, why it is so 

link of the research paper is https://www.sciencedirect.com/science/article/abs/pii/S2352152X19314318

**Comment by SanjuSoni** [comment]
![my_result](https://user-images.githubusercontent.com/61820415/83054148-8e73f700-a06f-11ea-8bd0-b777e254e90a.PNG)

Thanks @smao-astro  for pointing out my mistake. Finally, I got my output which look like the same output coming from FEM.

I'll modify further to get perfect picture.

**Comment by SanjuSoni** [comment]
one more thing I would like to ask @smao-astro 

- how to generate the output value over domain points after a completely trained Model.
like L-shaped poison example.

kindly suggest for the domain 10x10.

also for the case of a circle.

**Comment by smao-astro** [comment]
I do not have much experience on that, you can refer to file: examples/Burgers.py. Line 58:
>     y_pred = model.predict(X)
so briefly you want to generate a new sample of x (could be a grid) first, then feed to model.predict

**Comment by lululxvi** [comment]
@SanjuSoni : @smao-astro is right. You can choose the locations `X` that you want to predict (`X` is a Nx2 numpy array), and then use `model.predict()` to get the corresponding solutions.

Or you can check the saved `test.dat` file which contains the locations and solutions for those points for testing.

**Comment by SanjuSoni** [comment]
Thanks @lululxvi @lululxvi 

I have solved steady problem successfully.

**Comment by SanjuSoni** [comment]
@lululxvi @smao-astro 
I am trying to implement Dirichlet BC on the right verticle edge of the domain.

**T = 473.15 - 10*t**
where "t" is time.

I have coded it as:   

```
 def func_2(x):
        return 473.15* np.ones((len(x), 1)) - 10 * x[2]

```

x[2] has been assigned to time t.

but I am getting an error as:

  

> "DirichletBC should output 1D values. Use argument 'component' for different components."
> 
> RuntimeError: DirichletBC should output 1D values. Use argument 'component' for different components.


What is wrong with my code.

**Comment by lululxvi** [comment]
x is a Nx2 np array. It is
```python
 def func_2(x):
        return 473.15 - 10 * x[:, 1:2]
```

**Comment by SanjuSoni** [comment]
Thanks @lululxvi 
It works but unfortunately, the final result is something different from gradient type result:

![transient](https://user-images.githubusercontent.com/61820415/83107982-c36a6300-a0dc-11ea-8c7c-b7ad9bc38482.PNG)

its value should appear like:
![transient_5](https://user-images.githubusercontent.com/61820415/83108235-1a703800-a0dd-11ea-99a2-021206181c15.PNG)


I have defined the BC:
![boundary](https://user-images.githubusercontent.com/61820415/83108292-3247bc00-a0dd-11ea-84e8-a3c6717ee70e.PNG)

code for the above problem is defined as 


```
def main():
    def pde(x, y):
        
        
        phio = 0.1003
        kts = 2.49
        ktf =   0.6
        
        rhos = 2910.2
        cvs = 1000
        rhof = 1000
        cvf =   4200
        
        kt = ( 1- phio )*kts + phio*ktf
        
        rhocv = ( 1 - phio )*rhos* cvs + phio * rhof * cvf
        
        dy_x = tf.gradients( y, x)[0]
        
        dy_x, dy_y , dy_t = dy_x[:, 0:1 ], dy_x[:, 1:2], dy_x[:, 2:]
        
        dy_xx = tf.gradients( dy_x, x )[0][:, 0:1 ]
        
        dy_yy = tf.gradients( dy_y, x )[0][:, 1:2]
        
        return -kt*( dy_xx + dy_yy ) + rhocv * dy_t
    

    

    def func(x):
        
        return 473.15* np.ones((len(x), 1))
    
    def func_2(x):
        
        return 473.15* np.ones((len(x), 1)) - 10 * x[:, 2:]
   
    def func_n( x ):
        
        return np.zeros((len(x), 1))
    
        
    
    geom = dde.geometry.Rectangle([0,0], [20 , 20])
    
    timedomain = dde.geometry.TimeDomain( 0, 5 )
    
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)
    
    def boundary_l(x , on_boundary ):
        return on_boundary and np.isclose( x[0], 0 )
    
    def boundary_r(x , on_boundary):
        return on_boundary and np.isclose(x[0], 20)
    
    def boundary_upper(x, on_boundary ):
        return on_boundary and np.isclose(x[1] , 20)
    
    def boundary_lower(x , on_boundary ):
        return on_boundary and np.isclose(x[1], 0)
    
    
    
    
    bc_l = dde.DirichletBC( geomtime, func, boundary_l )
    bc_r = dde.DirichletBC( geomtime, func_2, boundary_r )
    bc_upper = dde.NeumannBC( geomtime, func_n, boundary_upper)
    bc_lower = dde.NeumannBC( geomtime, func_n, boundary_lower )
    
    ic = dde.IC(
            geomtime, lambda x: 473.15 * np.ones((len(x),1)) , lambda _,
            on_initial: on_initial
                )
    
    data = dde.data.TimePDE( geomtime, pde, [bc_l, bc_r, bc_upper, bc_lower , ic], 
                        num_domain = 1000,
                        num_boundary = 400,
                        num_initial = 100,
                        num_test = 2500  )
    
    layer_size = [3] + [50]*2 + [1]
```


I have solved for steady problem ( excluding time variable) and thanks @smao-astro for that.

Now, the result for the Transient problem is not matching.

kindly suggest something.
@lululxvi @smao-astro

**Comment by smao-astro** [comment]
Hi @SanjuSoni ,
A quick question, you are plotting V4 here, while previously (https://github.com/lululxvi/deepxde/issues/50#issuecomment-634829145) you seems used V3, what are they? What's the difference?

**Comment by SanjuSoni** [comment]
@smao-astro 
I have plotted predicted output through Tecplot which automatically rename the test data values ( in my case
 V1- x-axis  values,
V2 - y- axis values
V3 - t values
V4 - predicted output)

Since, I have solved steady problem (excluding time derivative) successfully which has 
V1- x-axis value
V2- y- axis value
V3- predicted output value)

all these V1, V2, V3, V4 are column wise vectors from    test.dat    file output after complete compilation of Model.

I am not getting my result according to the research paper outcome after FEM.

May be some implementation error by me.

**Comment by smao-astro** [comment]
Yes, I am just wondering why the scale of the colorbar does not even match the boundary condition?

**Comment by SanjuSoni** [comment]
@smao-astro, 
Yes, I am also confused at one stage.
the bc at right edge of domain has involved time variable also,
i.e T = 473.15 - 10*t

and here 10 is changing per year.

This is creating a confusion here.

I have solved  the same problem using FEM which has a good agreement with Transient and Steady problem both.

Also, using DeepXDE, I have solved steady problem but this transient problem is creating some problem.

**Comment by lululxvi** [comment]
- What is the loss value after training?
- Could you increase the number of points, e.g., `num_domain = 20**3, num_boundary = 4*20**2, num_initial = 20**2, num_test = 50**3`?

**Comment by SanjuSoni** [comment]
**Before scaling the problem:
& without increasing training points:**


train and test loss after 10000:
![trans_test_loss_10000](https://user-images.githubusercontent.com/61820415/83221682-118e6d80-a194-11ea-9714-1128238e8391.PNG)


train and test loss after  16874:

![train_loss_16874](https://user-images.githubusercontent.com/61820415/83222288-93cb6180-a195-11ea-89ac-32ee4fedb1ce.PNG)

intermediate train steps:

![tran_train_step](https://user-images.githubusercontent.com/61820415/83222372-ce34fe80-a195-11ea-9760-1e54faa831e3.PNG)


After scaling the problem and increasing all training points over boundary, domain and initial con

` net.outputs_modify(lambda x, y: y * 100)`

```
 data = dde.data.TimePDE( geomtime, pde, [bc_l, bc_r, bc_upper, bc_lower , ic], 
                        num_domain = 20**2,
                        num_boundary = 10**2,
                        num_initial = 8**3,
                        num_test = 20**4  )
```

training steps and loss function:

![trans2_scale](https://user-images.githubusercontent.com/61820415/83222715-a003ee80-a196-11ea-889d-d3d78c9ad40f.PNG)


the 
![trans_scale_output](https://user-images.githubusercontent.com/61820415/83223308-2d940e00-a198-11ea-9d9d-ac18c144e558.PNG)
result after scaling:



but the exact vertical gradient type output has not come.

Kindly comment something @lululxvi  @smao-astro

**Comment by lululxvi** [comment]
Your loss is too large. Re-scale your problem such that the initial loss is small.

**Comment by SanjuSoni** [comment]
thanks @lululxvi .

I'll learn to scale the problem and then I'll come back to solve this problem.

Thanks
