### ISSUE TITLE
About plot

### ISSUE THREAD

**Issue by TianjieZhang1993** [lululxvi/deepxde#503]
Hi Dr.Lu,
After I run the Poisson equation over L-shaped, I can get a 3D scatter plot of the test data. Would you like tell us how to get the same image(heatmap) shown in your paper?
<img width="700" alt="Screen Shot 2022-01-27 at 22 03 45" src="https://user-images.githubusercontent.com/95270677/151490334-73fd3d85-0db2-4ac7-b638-cceb4a38042c.png">

And I find in the 'train.dat' that there are only two columns (x,y), so does it mean the deepxde calcutes the solution of the poisson equation? If so, how could I get the solution?

Thanks!

**Comment by lululxvi** [comment]
See https://github.com/lululxvi/deepxde/issues/17, https://github.com/lululxvi/deepxde/issues/238,
