### ISSUE TITLE
Enforce additional inequalities

### ISSUE THREAD

**Issue by tsarikahin** [lululxvi/deepxde#504]
Dear Lu Lu,

As I have seen, all the examples are implemented based on homogenous or non-homogenous boundary conditions. How one can enforce this following inequality? This does not make any reasonable physics but I wonder how you will interpret the problem.

![lulu_image](https://user-images.githubusercontent.com/51532356/151518898-90453f21-c97d-469d-af6a-3614d8df3692.png)

Should here be used Lagrangian methods and the overall loss should be modified?

Thanks for your time!

Best regards,
Tarik

**Comment by lululxvi** [comment]
See https://epubs.siam.org/doi/10.1137/21M1397908
