### ISSUE TITLE
What's the PDE problem for Poisson_periodic_1d.py ?

### ISSUE THREAD

**Issue by tareqath** [lululxvi/deepxde#51]
Hey Lu I'd like to understand more about PeriodicBC, what's the PDE problem, specifically the BC for that program ? Also are there other Periodic problems you've seen using DeepXDE ? Thanks  !

**Comment by lululxvi** [comment]
It is Poisson equation: `-du_xx = np.pi ** 2 * sin(np.pi * x)` on 1D domain [-1, 1]. There are two BCs:
- Dirichlet `u(-1) = sin(-np.pi)`
- Periodic `u(1) = u(-1)`.

If you want to use high order derivative periodic `du/dx(-1) = du/dx(1)`,
```python
bc = dde.PeriodicBC(geom, 0, boundary_r, derivative_order=1)
```

**Comment by tareqath** [comment]
Thanks !

**Comment by 979736316** [comment]
> It is Poisson equation: `-du_xx = np.pi ** 2 * sin(np.pi * x)` on 1D domain [-1, 1]. There are two BCs:
> 
> * Dirichlet `u(-1) = sin(-np.pi)`
> * Periodic `u(1) = u(-1)`.
> 
> If you want to use high order derivative periodic `du/dx(-1) = du/dx(1)`,
> 
> ```python
> bc = dde.PeriodicBC(geom, 0, boundary_r, derivative_order=1)
> ```

Hi Lu, I'd like to understand about periodicBC. What's mean about component_x?  It refers to the independent variable, here it refers to x？
If the following equation satisfies the periodic boundary conditions, then is the periodic boundary set like this？
equation: ut-utxx+4u*ux-3ux*uxx-u*uxxx=0
> bc_u = dde.PeriodicBC(geomtime, 0, lambda _, on_boundary: on_boundary）

**Comment by lululxvi** [comment]
`component_x` is the component of inputs to be periodic. `component_x=0` is periodic in x; `component_x=1` is periodic in y.

What you wrote is correct.
