### ISSUE TITLE
A question in boundary condition

### ISSUE THREAD

**Issue by TianjieZhang1993** [lululxvi/deepxde#511]
Hi Prof.Lu,
How can I define the last boundary condition shown in the figure below? it's hx(t,-5)=hx(t,5)

<img width="498" alt="Screen Shot 2022-02-04 at 15 55 41" src="https://user-images.githubusercontent.com/95270677/152614330-c4ad77f2-fd8e-440c-b35b-41e5af3df351.png">

**Comment by lululxvi** [comment]
Check PeriodicBC.

**Comment by TianjieZhang1993** [comment]
Thanks !
