### ISSUE TITLE
problems with geometry_nd.Hypercube

### ISSUE THREAD

**Issue by fperiago** [lululxvi/deepxde#512]
Dear Prof. Lu, dear users,
I'm trying to solve a heat equation in dimension 5 and get an error associated to geometry_nd.Hypercube.
The error is 
random_boundary_points
    raise NotImplementedError(
NotImplementedError: Hypercube.random_boundary_points to be implemented

I don't know if there is a bug in deepxde.geometry.geometry_nd module or if I did something wrong in my code.
Here below there is the code.
May you please have a look?
Thank you in advance for your time and help.

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    kappa = 10. # thermal conductivity
    T= 0.5 # final time
    def pde(x, y): # heat equation
        dy_t = dde.grad.jacobian(y, x, i=0, j=5)
        dy_x0x0 = dde.grad.hessian(y, x, i=0, j=0)
        dy_x1x1 = dde.grad.hessian(y, x, i=1, j=1)
        dy_x2x2 = dde.grad.hessian(y, x, i=2, j=2)
        dy_x3x3 = dde.grad.hessian(y, x, i=3, j=3)
        dy_x4x4 = dde.grad.hessian(y, x, i=4, j=4)
        return dy_t -kappa*(dy_x0x0+dy_x1x1+dy_x2x2+dy_x3x3+dy_x4x4)

    def initial_temp(x): # initial temperature
        return np.sin(np.pi * x[:, 0:1])*np.sin(np.pi * x[:, 1:2])*np.sin(np.pi * x[:, 2:3])*np.sin(np.pi * x[:, 3:4])*np.sin(np.pi * x[:, 4:5])
            
    def boundary_x0_0(x, on_boundary): 
        return on_boundary and np.isclose(x[0], 0)    

    def boundary_x1_0(x, on_boundary):
        return on_boundary and np.isclose(x[1],0)
    
    def boundary_x1_1(x, on_boundary):
        return on_boundary and np.isclose(x[1], 1)
    
    def boundary_x2_0(x, on_boundary):
        return on_boundary and np.isclose(x[2], 0)
    
    def boundary_x2_1(x, on_boundary):
        return on_boundary and np.isclose(x[2], 1)
    
    def boundary_x3_0(x, on_boundary):
        return on_boundary and np.isclose(x[3], 0)

    def boundary_x3_1(x, on_boundary):
        return on_boundary and np.isclose(x[3], 1)
    
    def boundary_x4_0(x, on_boundary):
        return on_boundary and np.isclose(x[4], 0)
    
    def boundary_x4_1(x, on_boundary):
        return on_boundary and np.isclose(x[4], 1)

    def boundary_time0(x, on_boundary):
        return on_boundary and np.isclose(x[5], 0)
 
    geom = dde.geometry.geometry_nd.Hypercube(xmin=[0, 0, 0, 0, 0, 0], xmax=[1, 1, 1, 1, 1, T])
    
    bc_x0_0 = dde.DirichletBC(geom, lambda x: 0, boundary_x0_0)
    bc_x1_0 = dde.DirichletBC(geom, lambda x:0, boundary_x1_0)
    bc_x1_1 = dde.DirichletBC(geom, lambda x: 0, boundary_x1_1) 
    bc_x2_0 = dde.DirichletBC(geom, lambda x:0, boundary_x2_0)
    bc_x2_1 = dde.DirichletBC(geom, lambda x: 0, boundary_x2_1)
    bc_x3_0 = dde.DirichletBC(geom, lambda x:0, boundary_x3_0)
    bc_x3_1 = dde.DirichletBC(geom, lambda x: 0, boundary_x3_1)
    bc_x4_0 = dde.DirichletBC(geom, lambda x:0, boundary_x4_0)
    bc_x4_1 = dde.DirichletBC(geom, lambda x: 0, boundary_x4_1)
    bc_time0 = dde.DirichletBC(geom, initial_temp, boundary_time0)
    
    data = dde.data.PDE(
        geom, 
        pde, 
        [bc_x0_0, bc_x1_0, bc_x1_1, bc_x2_0, bc_x2_1, bc_x3_0, bc_x3_1, bc_x4_0, bc_x4_1, bc_time0], 
        num_domain=120, 
        num_boundary=12
        )

    net = dde.maps.FNN([6] + [50] * 4 + [1], "tanh", "Glorot uniform")
    model = dde.Model(data, net)

    model.compile("adam", lr=0.001)
    model.train(epochs=5000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    
if __name__ == "__main__":
    main()

**Comment by lululxvi** [comment]
The function `Hypercube.random_boundary_points` has not been implemented yet.

**Comment by fperiago** [comment]
Okay, thanks Lu. Are there other types of boundary points implemented in geometry_nd.Hypercube ?
Maybe uniform points ?
Thanks again!

**Comment by lululxvi** [comment]
`random_boundary_points` is implemented:

https://github.com/lululxvi/deepxde/blob/eece7e082f9f9139e4f0b05f9eb5aae5ab8f89db/deepxde/geometry/geometry_nd.py#L86

**Comment by fperiago** [comment]
Thanks Lu. This is working very nicely!!!
