### ISSUE TITLE
Handling of multiple solutions

### ISSUE THREAD

**Issue by oubhch** [lululxvi/deepxde#53]
Hey Lu !

I have two questions concerning a system with multiple soltuions (in my case: 6)

1. Is there a way to label them in the plotting ? All I get is the red-dotted graph, but I want to distinguish them. If it's too complicated or long I'd be content enough with just a reference to some plotting documentation that I can follow.   
2. After the prediction is done, how can I use the solutions ? Suppose the solutions are (y1,y2,y3,y4,y5,y6), how do I get for example y6(2) ?

Thank you so much, I appreciate your support !

**Comment by lululxvi** [comment]
- You can use the saved results `test.dat`. From the first column to the last column are x, y1, y2, ... . You can plot using any tool.
- Use the following code the get the solution at any point
```python
X = np.array([[x1], [x2], [x3]])  # e.g., need the solution at x1, x2, and x3
Y = model.predict(X)  # Y is 3 x 6 matrix, i.e., [[y1(x1), ..., y6(x1)], [y1(x2), ..., y6(x1)], [y1(x3), ..., y6(x3)]]
```

**Comment by oubhch** [comment]
Thanks man !
