### ISSUE TITLE
How to apply hard constraint for point boundary?

### ISSUE THREAD

**Issue by mlin26** [lululxvi/deepxde#542]
Hi Dr. Lu,

Could you tell me how we can apply hard constraints for points? 

Suppose we have a 2D Aluminum plate, how can we fix the displacement u(x,y) for the four corners? I have tried output transform, but it doesn't get the correct results for my problem.

```
geom = dde.geometry.Rectangle(xmin=[0, 0], xmax=[1, 1])
# apply hard constraint
def output_transform(x, u): 
    x1, x2 = x[:, 0:1], x[:, 1:2]
    u1, u2= u[:, 0:1], u[:, 1:2]
    u1_mod = ((1. - x1)*x1 + (1. - x2)*x2) * u1
    u2_mod = ((1. - x1)*x1 + (1. - x2)*x2) * u2 

    return tf.concat((u1_mod, u2_mod), axis=1)

net.apply_output_transform(output_transform)
```

I don't know if my transform function is wrong and whether there is a better way to apply point constraint? Could you tell me if there are difficulties for the neural network to train this kind of point boundary condition? Thanks!

**Comment by lululxvi** [comment]
The output transform seems correct.
