### ISSUE TITLE
<About freezing the weights of some certain layers in a neural network on DeepXDE>

### ISSUE THREAD

**Issue by zyz-rise** [lululxvi/deepxde#549]
Dear Dr. Lu，
@lululxvi 
Thanks for the provision of DeepXDE library !
I wonder if it is possible in DeepXDE to freeze the weights of some specific layers before training, so that the frozen layers are not updated with backpropagation? If so, how should it be adjusted in the code? Can you provide some advice?

**Comment by zyz-rise** [comment]
Thanks  @lululxvi , 
but there are some code problems，

if my neural network is structured like this： 
`net = dde.maps.FNN([2] + [20] * 3 + [1], "tanh",  "Glorot normal")`

then I want to freeze the first two layers of the hidden layer, what variables should I set? 

I set `tf.keras.layers.Dense(1).trainable = False`，but if I enter `tf.keras.layers.Dense(1).trainable` in the console, it returned `True`

Could you give me some more detailed advice please~

**Comment by lululxvi** [comment]
You may need to modify the source code of DeepXDE. Set it to False when you construct the network.

**Comment by zyz-rise** [comment]
Thanks~ I modified and solved it.
