### ISSUE TITLE
Inverse problem

### ISSUE THREAD

**Issue by ediemiglio** [lululxvi/deepxde#55]
Dear Lu, great work! I was taking a look at the inverse Lorenz example and I was wondering if it is possible to identify the parameters of the model using only some of the components of the solution (for example the first two components in the Lorenz case) ? Thanks in advance.
   Regards
      Edie

**Comment by lululxvi** [comment]
Hi Edie, using particle observations sometimes is possible, but it is case by case. For this Lorenz problem, I didn't test it and not sure what is the answer.

**Comment by ediemiglio** [comment]
I know that from the theoretical point of view it depends on the system. I was asking how it can be implemented.
Thanks
    Edie

**Comment by lululxvi** [comment]
The code is at https://github.com/lululxvi/deepxde/blob/master/examples/Lorenz_inverse.py.
```python
data = dde.data.PDE(..., [ic1, ic2, ic3, observe_y0, observe_y1, observe_y2], ...)
```
The observations for the three components are `observe_y0, observe_y1, observe_y2`, and you can just remove one of them.

**Comment by ediemiglio** [comment]
Thanks a lot. I have another question on the inverse Lorenz: is it possible to impose some constraints on the variables (for example to lie inside [0,1] or to be strictly positive) ? Thanks again.
Edie

**Comment by lululxvi** [comment]
Yes. If you want to a variable `C` to be possible, then use a trick like
```python
C = tf.math.exp(tf.Variable(1.0))
```
