### ISSUE TITLE
implementations of temperature-dependent parameter in heat transfer problem

### ISSUE THREAD

**Issue by lshil00** [lululxvi/deepxde#553]
Dear Lulu, sorry to bother you again, but now I want to solve a heat transfer problem with temperature-dependent material properties. 
**That is to say, some parameters set in PINN may change with different temperature. However, the problem is that temperature T is exactly what I want to calculate.** 
Is deepxde able to do it? If yes, what kind of function should I use?
Great thanks!

**Comment by lululxvi** [comment]
Use ``apply_output_transform``, See https://github.com/lululxvi/deepxde/issues/178

**Comment by lshil00** [comment]
> 

I have seen the details in #178, but I'm afraid it is not the same. 
My problem is still the forward problem, and it's just the parameter that changes with the temperature (output) in PDE.
![image](https://user-images.githubusercontent.com/47272107/158069374-0a063bd4-9470-4480-a69d-e306d2a7cec1.png)
Here lambda(u) is a linear function : lambda(u) = k*u , for example.
How can I handle this? Thank you!

**Comment by lululxvi** [comment]
u is one of the argument of the pde function you defined.

**Comment by lshil00** [comment]
> u is one of the argument of the pde function you defined.

Sorry, but I'm afraid I don't understand what you mean. u is the temperature, which is the output I want to get.

**Comment by lshil00** [comment]
@lululxvi Dear Lulu, I tried to change the source code of "auxiliary_var_function" and replaced its input(x) with output(u). But it gave me a NAN value of the PDE function.
I think it is due to the output(u), which is the temperature, doesn't have an initial value from the beginning,  so the lambda(u) in the PDE function is also NAN.
Is there any suggestions you could give me? Or how can I use "apply_output_transform"? 
Really appreciate that!

**Comment by lululxvi** [comment]
See example https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/ode.system.html, where we have y in the RHS.

**Comment by forxltk** [comment]
> See example https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/ode.system.html, where we have y in the RHS.

Hi, @lululxvi I have a similar problem that the coefficients of the PDE depend on the outputs. In fact, there are no RHS in this ODE example and I can't solve the problem . Could you have another example for the problem?
Many thanks!

**Comment by lululxvi** [comment]
I don't understand what the difficulty is.

**Comment by forxltk** [comment]
> I don't understand what the difficulty is.

Yes, you're right. I have been mislead by the preconceived notions of this issue. And it is even no a problem. Very apologize for waste your time!

**Comment by Moonguakes** [comment]
spatial_domain = dde.geometry.Interval(0, 1)
temporal_domain = dde.geometry.TimeDomain(0, 1)
geomtime = dde.geometry.GeometryXTime(spatial_domain, temporal_domain)


def pde(x, y):
    k,T = y[:,0:1], y[:,1:2]
    dT_t = dde.grad.jacobian(T, x, i=0, j=1)
    dT_xx = dde.grad.hessian(T, x, i=0, j=0)
    return [dT_t - (k/(cp*cho)) * dT_xx, k-0.01-0.99*T]

def left_boundary(x, on_boundary):
    return on_boundary and (np.isclose(x[0], 0))

def right_boundary(x, on_boundary):
    return on_boundary and (np.isclose(x[0], 1))
                            

bc_left = dde.icbc.DirichletBC(geomtime, lambda x: 0.0, left_boundary, component=1)
bc_right = dde.icbc.DirichletBC(geomtime, lambda x: 1.0, right_boundary, component=1)

ic2 = dde.icbc.IC(geomtime, lambda x: 0.0, lambda _, on_initial: on_initial, component=1)
data = dde.data.TimePDE(
    geomtime,
    pde,
    [bc_left, bc_right, ic2],
    num_domain=3000,
    num_boundary=1000,
    num_initial=1000
)


net = dde.nn.FNN([2] + [50] * 3 + [2], "tanh", "Glorot normal")
model = dde.Model(data, net)

model.compile("adam", lr=0.001)
model.train(epochs=50000)

Dear Lulu，I'm writing a case where the thermal conductivity changes with temperature, and temperature is the output. I referred to the ODE case you mentioned, but the result is quite different from the comsol simulation. Can you help me see if there is a problem with the code.

> I don't understand what the difficulty is.
