### ISSUE TITLE
How can we minimize the error in the numerical derivative of DeepXDE's output?

### ISSUE THREAD

**Issue by seyyah** [lululxvi/deepxde#557]
Dear Prof. Lu @lululxvi,

We have a problem similar to the Euler beam problem. We can solve a Euler beam problem with the DeepXDE by following the guide ([Euler Beam Problem Tutorial at Documentation site](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/eulerbeam.html)) . And our DeepXDE model predict quite well (low MSE) the `u` values. As part of the problem we need to look at the `u`'s derivative (![formula](https://render.githubusercontent.com/render/math?math=\frac{\partial%20u}{\partial%20x%20}%20), ![formula](https://render.githubusercontent.com/render/math?math=\frac{\partial^2%20u}{\partial%20x^2%20}%20), ![formula](https://render.githubusercontent.com/render/math?math=\frac{\partial^3%20u}{\partial%20x^3%20}%20), ...).

We use the following algorithm when calculating the derivative

1. We estimate `u` values with model help for `x` values in our domain

3. We apply numerical derivatives to the `u` and `x` pair. For this purpose, we benefit from `numpy.diff` and` numpy.gradient`.

Due to the nature of the numerical derivative, we get big error especially in the border values in derivative results.

Would you mind give me some advice?

Great thanks

**Comment by lululxvi** [comment]
You can use `model.predict` to predict the derivatives, see an example at
https://github.com/lu-group/gpinn/blob/d8ad93d598ba7348d73ce5b7887ae4a940386f71/src/function.py#L88

**Comment by seyyah** [comment]
Thank you very much for the perfect hint @lululxvi
