### ISSUE TITLE
A serious error on the pytorch backend

### ISSUE THREAD

**Issue by csuastt** [lululxvi/deepxde#558]
Error:
```bash
...
  File "ENV_PATH/lib/python3.9/site-packages/deepxde/model.py", line 225, in outputs_losses
    outputs_ = self.net(self.net.inputs)
...
  File "ENV_PATH/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Float but found Double
```

Solution:
modify `ENV_PATH/lib/python3.9/site-packages/deepxde/model.py` (line 225):
```python
            self.net.train(mode=training)
            self.net.inputs = torch.as_tensor(inputs)
            self.net.inputs.requires_grad_()
            outputs_ = self.net(self.net.inputs)
```
to:
```python
            self.net.train(mode=training)
            self.net.inputs = torch.as_tensor(inputs)
            self.net.inputs.requires_grad_()
            outputs_ = self.net(self.net.inputs.float()) # add this
```

Note:
- torch version: torch==1.10.2
- deepxde version: DeepXDE==1.1.1

**Comment by lululxvi** [comment]
Thank you for reporting this. The error is strange. I haven't had this error for PyTorch before. Could you provide more information:
- Which example did you use?
- Did you use float32 or float64?

**Comment by csuastt** [comment]
I have this problem in almost all examples. The default type is float64, and I didn't modify any code in the DeepXDE or the Pytorch backend. I'm guessing that this is related to the operating system or the GPU driver. However, I cannot gain further insights yet.

**Comment by lululxvi** [comment]
What is your OS? Could you try to run in CPU?

**Comment by csuastt** [comment]
Linux version 4.15.0-135-generic (buildd@lgw01-amd64-005) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
It's ok with CPU.

**Comment by lululxvi** [comment]
If CPU works, then it might be an issue of GPU driver. Have you tried another PyTorch version?

**Comment by csuastt** [comment]
Thanks a lot. I'll then try an older version. I remember that older stable versions of PyTorch worked well.
