### ISSUE TITLE
Unknown BC and optimization

### ISSUE THREAD

**Issue by xanderyin** [lululxvi/deepxde#56]

**Comment by xanderyin** [comment]
Hello Lu,

The toolbox is very useful. Now, can we define an uncertain BC using some unknown parameters which may be trainable. Then, if there is an objective function defined with the PDE and the unkown BC as constraints, how can we obtain the maximum/minium value of the objective function by specifying the optimal value of the BC which can be defined as an optimized parameter? thx.

**Comment by lululxvi** [comment]
Yes, we can do that. Can you provide me a simple example, and I can show you how to do it?

**Comment by xanderyin** [comment]
Hi Dr Lu,

I have written a simple example to show how to use the toolbox in solving parametric BC:
![2020-05-30_220427](https://user-images.githubusercontent.com/47574225/83339014-a04cd880-a2c1-11ea-8ac5-243b37c3bc91.jpg)
thank you!

**Comment by lululxvi** [comment]
It is very tricky if the geometry depends on the unknown parameters, although it is doable. For this problem, what is the BC? Is this case the problem you are trying to solve? Otherwise another problem with fixed geometry would be better, and the unknown parameters could be the parameters in BC.

**Comment by xanderyin** [comment]
Dear Lu,

I'm sorry for not making the problem clear. Now, I have revised them to make them more clear. The problems are of practical interest and have potential use in engineering optimization. Are there any available solvers for the problem (2) ?
![2020-05-31_140425](https://user-images.githubusercontent.com/47574225/83353123-3a576400-a348-11ea-8b5f-77942ef84c3d.jpg)

**Comment by lululxvi** [comment]
I think your problem has two components:
1. Have a model to compute `f(w1, w2) = \int (u - u^2)` which maps from `(w1, w2)` to the solution `u`, and then to the integration. This step involves solving PDE.
2. Compute `w*1, w*2 = argmin_{w1, w2} f(w1, w2)`. The second step is just a 2d optimization problem.

There are many possible ways for this problem. One approach is using Bayesian Optimization (BO) (https://github.com/fmfn/BayesianOptimization), and the black_box_function in the BO is `f(w1, w2)`, which calls DeepXDE to solve the PDE and return the integration.

**Comment by xanderyin** [comment]
Dear Lu,

Thank you for the helpful suggestion. The only problem now is if there is an \int function in your code or other code for calculating the integration?

**Comment by lululxvi** [comment]
The integration cannot be calculated exactly, and you can use any numerical integration to approximate it, e.g., uniform mesh.
