### ISSUE TITLE
BC problem with polygons

### ISSUE THREAD

**Issue by AAC8020** [lululxvi/deepxde#573]
Hello Dr.Lu,
I'm trying to assign BCs to the computation field, which is composed of an outer rectangle and an inner polygon, here's my code:

```python

import deepxde as dde

def pde(x,y):
    return x

def boundary(x,bdr):
    return bdr and inner.on_boundary(x)

outer = dde.geometry.Rectangle([-0.5,-0.5],[1,0.5])
inner = dde.geometry.Polygon([[0.0,0.0],[0.0,0.1],[0.1,0.1],[0.07,0.0]])
geo = dde.geometry.CSGDifference(outer,inner)
bc = dde.icbc.DirichletBC(geo,lambda x:0,boundary)

data = dde.data.PDE(geo,pde,bc,10,10)

```
But I got this error:
>Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/deepxde/icbc/boundary_conditions.py", line 47, in filter
    return X[self.on_boundary(X, self.geom.on_boundary(X))]
IndexError: arrays used as indices must be of integer (or boolean) type

But if I change the Polygon to a Rectangle:

```python
inner = dde.geometry.Rectangle([0.0,0.0],[0.1,0.1])
```
The code would work well, I have no idea if it is the problem of my code or the bug of DeepXDE.

**Comment by lululxvi** [comment]
The boundary of `CSGDifference` already includes the boundary of both geometries.

**Comment by AAC8020** [comment]
Thank you! I'll check it out

**Comment by HashiramaSenju14** [comment]
@AAC8020 did you manage to run your code with the Polygon? I have a similar geometry and got the same error. And I didn't understand the advice of @lululxvi.

I would also like to thank @lululxvi for his amazing job.

**Comment by AAC8020** [comment]
@HashiramaSenju14 I havn't solved this problem and currently using a circle instead. But I'll change to polygon soon and reinvestigate this problem.
