### ISSUE TITLE
Add a loss function

### ISSUE THREAD

**Issue by Siliegia** [lululxvi/deepxde#582]
Dear Lu Lu, great package! I would have a question. I am working on a problem to estimate the parameters of a simple ode of the form dx/dt = f(x), where x is N-dimensional and f(x) has N equations. I would like to add an additional loss function to enforce f(x) = 0 at t = T_endpoint. I tried to add a boundary condition to the code, but I don't quite understand how to enforce f(x) = 0 ONLY at the end time point. Is there a way to include this in the code? 

This is the boundary condition I tried to define: 

```
class SteadyStateBC(BC):
    """Steady state boundary conditions: func(outputs) = 0.

    Args:
        geom: ``Geometry``.
        func: A function takes arguments (`outputs`)
        on_boundary: (x, Geometry.on_boundary(x)) -> True/False.
    """

    def __init__(self, geom, func, on_boundary):
        super(SteadyStateBC, self).__init__(geom, on_boundary, 0)
        self.func = func

    def error(self, X, inputs, outputs, beg, end):
        return self.func(outputs[beg:end, :])
```

**Comment by lululxvi** [comment]
See FAQ "Q: More details and examples about initial conditions.", "Q: More details and examples about boundary conditions."
