### ISSUE TITLE
Reproductibility for sampler => Define a global DDESEED

### ISSUE THREAD

**Issue by pescap** [lululxvi/deepxde#585]
Hi, 
I figured out that 

https://github.com/lululxvi/deepxde/blob/707b0984312d0ad5f28522b2aa863fed923b424a/deepxde/geometry/sampler.py#L28

was giving different data points despite having previously defined ``set_random_seed``. I didn't notice this before as I was using `Rectangle` with `uniform` generator.

I obtain the same results if I set a proper seed here, e.g.,

```
seed = 11
set_random_seed(seed)
```

and 

``
np.random.default_rng(seed).
``

So far, I didn't test with other random generators. I also noticed that seeds appeared for the initializers: 

https://github.com/lululxvi/deepxde/blob/707b0984312d0ad5f28522b2aa863fed923b424a/deepxde/nn/initializers.py#L29

Yet, I didn't have issues with that. Initializers seem to be within the ``set_random_seed(seed)`` domain.

To properly set up everything, I propose to set a new global variable ``DDESEED`` with default value `None`. Then, if `DDESEED` is an integer, we would ``set_random_seed(seed)`` and call the seed value in sampler.py.

If you are ok with the idea, I will work on a PR, best!

**Comment by lululxvi** [comment]
Yes, good idea.

**Comment by pescap** [comment]
Isn't it more appropriate to use notation `DDE_BACKEND` and `DDE_SEED` instead of `DDEBACKEND` and `DDESEED`? 

It would be more similar to `CUDA_VISIBLE_DEVICES`.

**Comment by lululxvi** [comment]
Good point. But let us not change `DDEBACKEND` for now, or we may support both `DDEBACKEND` and `DDE_BACKEND`. Then we can remove the legacy support of `DDEBACKEND` in a future version, so the users can have a smooth transition.

**Comment by pescap** [comment]
> 

https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/backend/__init__.py#L68-L69

I'll set: 

```
if "DDEBACKEND" in os.environ:
    backend_name = os.getenv("DDEBACKEND")
elif "DDE_BACKEND" in os.environ:
    backend_name = os.getenv("DDE_BACKEND")
...
```

**Comment by pescap** [comment]
I am wondering where I should add the `DDE_SEED` set up. It would look like:

```
from config import set_random_seed
if "DDE_SEED" in os.environ:
    seed = os.getenv("DDE_SEED")
    set_random_seed(seed)
```

Options: 

1. Here: https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/__init__.py#L5

2. Or here: https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/backend/__init__.py#L86

**Comment by lululxvi** [comment]
> > 
> 
> https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/backend/__init__.py#L68-L69
> 
> I'll set:
> 
> ```
> if "DDEBACKEND" in os.environ:
>     backend_name = os.getenv("DDEBACKEND")
> elif "DDE_BACKEND" in os.environ:
>     backend_name = os.getenv("DDE_BACKEND")
> ...
> ```

Yes, sounds good.

**Comment by lululxvi** [comment]
> I am wondering where I should add the `DDE_SEED` set up. It would look like:
> 
> ```
> from config import set_random_seed
> if "DDE_SEED" in os.environ:
>     seed = os.getenv("DDE_SEED")
>     set_random_seed(seed)
> ```
> 
> Options:
> 
>     1. Here: https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/__init__.py#L5
> 
>     2. Or here: https://github.com/lululxvi/deepxde/blob/e4b48e0b76b7064c7a155a4ac7c1be8914d68c38/deepxde/backend/__init__.py#L86

I suggest add the seed at https://github.com/lululxvi/deepxde/blob/master/deepxde/config.py, similar as `real`
