### ISSUE TITLE
cylinder

### ISSUE THREAD

**Issue by HaoQian-vary** [lululxvi/deepxde#588]
Dear Dr. Lu Lu, Thanks for this incredible tool DeepXDE.I would like to ask how to draw a cylinder

**Comment by HaoQian-vary** [comment]
Dear Dr. Lu Lu,
            Thanks for this incredible tool DeepXDE.
            I am working on a fluid problem, There are various inlet boundary conditions. The inlet velocity = 1m/s, 4m/s, 8m/s......
            Do different models need to be trained for different inlet boundary conditions?Such training is slow, Is there a better way?

**Comment by lululxvi** [comment]
DeepXDE currently doesn't support cylinder yet. You have to implement a cylinder geometry by yourself.

See FAQ "Q: Solve parametric PDEs."
