### ISSUE TITLE
Multi-fidelity fusion of physical information

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#590]
Dear Dr.Lu:
  After I examined Deepxde's source code and the case of mf presented, I found no mention of how to incorporate physical information. As shown in the figure below, the ideas mentioned by Dr. Meng,  the loss term MSEfe of physical information can be added to the total loss function. However, in Deepxde, the MfFunc function class seems to mention only the mathematical functions that incorporate multi-fidelity and low-fidelity, and not how to incorporate physical information. 
![image](https://user-images.githubusercontent.com/52651366/161507918-0d733c68-872e-4f9a-bd43-8454abdd51b0.png)

![1649062388(1)](https://user-images.githubusercontent.com/52651366/161509371-532eda64-3776-4f77-a949-0a0a135acca3.jpg)

**Comment by haison19952013** [comment]
Physics-informed MFNN has not been implemented in deepXDE.. @979736316 ..

**Comment by 979736316** [comment]
> Physics-informed MFNN has not been implemented in deepXDE

Thank you for your reply, I look forward to the development of this feature.
