### ISSUE TITLE
Potential function and high order derivative and OperatorBC

### ISSUE THREAD

**Issue by chang-change** [lululxvi/deepxde#598]
Dear LuLu,
I  want to solve  parallel  plate flow problem using potential function. The code as follows:
`def pde(x,y):
    """
    定义无量纲形式质量方程，动量方程和能量方程

    """
    psi = y[:,0:1]
    T = y[:,1:2]
    p = y[:,2:3]
    
    u = dde.grad.jacobian(y, x, i = 0, j = 0)
    v = dde.grad.jacobian(y, x, i = 0, j = 1)
    
    du_x = dde.grad.jacobian(u,x,i = 0, j = 0)
    du_y = dde.grad.jacobian(u,x,i = 0, j = 1)
    dv_x = dde.grad.jacobian(v,x,i = 0, j = 0)
    dv_y = dde.grad.jacobian(y,x,i = 0, j = 1)
    
    du_xx = dde.grad.hessian(u, x, i = 0, j = 0)
    du_yy = dde.grad.hessian(u, x, i = 1, j = 1)
    dv_xx = dde.grad.hessian(v, x, i = 0, j = 0)
    dv_yy = dde.grad.hessian(v, x, i = 1, j = 1)
    
    dT_x = dde.grad.jacobian(y , x, i = 1, j = 0)
    dT_y = dde.grad.jacobian(y ,x , i = 1, j = 0)
    dT_xx = dde.grad.hessian(y,x, component=1,i = 0, j = 0)
    dT_yy = dde.grad.hessian(y,x, component=1,i = 1, j = 1)
    
    dp_x = dde.grad.jacobian(y,x,i = 2,j = 0)
    dp_y = dde.grad.jacobian(y,x,i = 2,j = 1)
    
    conservation_mass = du_x + dv_y
    conservation_mom_x = u*du_x + v*du_y  - (1/Re)*(du_xx + du_yy) + dp_x
    conservation_mom_y = u*dv_x + v*dv_y  - (1/Re)*(dv_xx + dv_yy) + dp_y
    conservation_energy = u * dT_x + v * dT_y -(1/Pe) * (dT_xx + dT_yy) 
    
    return [conservation_mass,conservation_mom_x,conservation_mom_y,conservation_energy]

def left_boundary(x,on_boundary):
    return on_boundary and np.isclose(x[0],0)
    
def bottom_boundary(x,on_boundary):
    return on_boundary and np.isclose(x[1],0)

def output_func(_,y):
    psi = y[:,0:1]
      
    T1 = y[:,1:2]
    T = tf.sigmoid(T1)
    
    p1 = y[:,2:3]
    p = tf.exp(p1)
    
    return tf.concat((psi,T,p), axis=1)    
  
def u_fun_left(x,y,_):

    
    return dde.grad.jacobian(y, x, i = 0,  j = 0) -1

def v_fun_leftbottom(x,y,_):
 
    return dde.grad.jacobian(y, x , i=0 , j = 1)

def u_fun_bottom(x,y,_):

    return dde.grad.jacobian(y,x,i = 0, j = 0)

u_left_bs = dde.icbc.OperatorBC(geom, u_fun_left, left_boundary)
v_left_bs = dde.icbc.OperatorBC(geom, v_fun_leftbottom, left_boundary)
T_left_bc = dde.icbc.DirichletBC(geom, lambda x: 1.0, left_boundary,component = 1)

u_bottom_bc = dde.icbc.OperatorBC(geom, u_fun_bottom,bottom_boundary)
v_bottom_bc = dde.icbc.OperatorBC(geom,v_fun_leftbottom,bottom_boundary)
T_bottom_bc = dde.icbc.DirichletBC(geom,lambda  x :0.0,bottom_boundary,component = 1)`
I wonder if the expression of higher derivatives and boundary conditions is correct?

**Comment by chang-change** [comment]
![BC](https://user-images.githubusercontent.com/45302365/161934025-517a986d-a6e4-4060-afa3-d0d0f3ba1dc9.jpg)

**Comment by lululxvi** [comment]
It looks good. You can use `dde.grad.jacobian` and `dde.grad.hessian` multiple times to compute high order derivatives.

**Comment by chang-change** [comment]
Thanks!
