### ISSUE TITLE
Bug in deepxde/boundary_conditions.py

### ISSUE THREAD

**Issue by kaluzaklein** [lululxvi/deepxde#6]
In the current master version, it looks like there is a bug in boundary_conditions.py .

I'm solving for multiple components. The error(...) function for DirichletBC checks for values.shape[1] != 1, even though we are allowed to use multiple components and allowed to specify which component the boundary value is for.

**Comment by lululxvi** [comment]
No, this is not a bug. One `DirichletBC` can only be used for one component. For example, the outputs have two components `(y1, y2)`, and both are DirichletBC. Then you should define two DirichletBC, one for y1, and one for y2, see [ODE system](https://github.com/lululxvi/deepxde/blob/master/examples/ode_system.py) as an example.
