### ISSUE TITLE
1D Terzaghi equation with NBC and RBC

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#60]
Hi Lu,
Thank you very much for sharing this amazing tool. I am trying to use this to solve the Terzaghi equation.
du/dt = Cv*（d2u/dx2）,
Two BCs are : u（0,t）=0,u'(H,t)=0
IC : u(x,0)=1 at all the points.

I want to ask you if my following code is written correctly?

Cv=4.86e-02
H=10

>     def pde(x, u):
>         du_x = tf.gradients(u, x)[0]
>         du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
>         du_xx = tf.gradients(du_x, x)[0][:, 0:1]
>         return du_t - Cv * du_xx
> 
>     geom = dde.geometry.Interval(0, H)
>     timedomain = dde.geometry.TimeDomain(0, 1)
>     geomtime = dde.geometry.GeometryXTime(geom, timedomain)
> 
>     def boundary_l(x, on_boundary):
>         return on_boundary and np.isclose(x[0], 0)
>     def boundary_r(x, on_boundary):
>         return on_boundary and np.isclose(x[0], H)
> 
>     bc1 = dde.DirichletBC(
>         geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: boundary_l
>     )
>     bc2 = dde.NeumannBC(
>         geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: boundary_r
>     )
>     ic = dde.IC(
>         geomtime, lambda x: np.full_like(x[:, 0:1], 1), lambda _, on_initial: on_initial
>     )
> 
>     data = dde.data.TimePDE(
>         geomtime, pde, [bc1,bc2,ic], num_domain=2540, num_boundary=80, num_initial=160,num_test=10000
>     )
> 
>     net = dde.maps.FNN([2] + [32] * 3 + [1], "tanh", "Glorot normal")
>     model = dde.Model(data, net)
> 
>     model.compile("adam", lr=1e-3)
>     model.train(epochs=50000)
>     model.compile("L-BFGS-B")
>     losshistory, train_state = model.train()
>     dde.saveplot(losshistory, train_state, issave=True, isplot=True)

My final result is strange

**Comment by lululxvi** [comment]
I looks good. What is your loss and results?

**Comment by smao-astro** [comment]
@979736316 I am wondering why is that your IC and BC is not consistent at (0, 0), which could make the problem do not have a solution and hard to train.

**Comment by 979736316** [comment]
> @979736316 I am wondering why is that your IC and BC is not consistent at (0, 0), which could make the problem do not have a solution and hard to train.

Oh, I was wrong, u(0,0) should be 0, other values are 1. But I don’t know how to set it

**Comment by 979736316** [comment]
> I looks good. What is your loss and results?
This is my final loss.
![image](https://user-images.githubusercontent.com/52651366/83718518-c7abf880-a667-11ea-87ef-0a91f44f38b1.png)

**Comment by qizhang94** [comment]
> > @979736316 I am wondering why is that your IC and BC is not consistent at (0, 0), which could make the problem do not have a solution and hard to train.
> 
> Oh, I was wrong, u(0,0) should be 0, other values are 1. But I don’t know how to set it

Hi, Do you know why in this case, in the terminal output, we have four values for train loss and four values for the test loss, but only one value of the test loss is zero? What did these values represent? 

By the way, @lululxvi I still get very wired results, as @979736316 mentioned. Thanks for your help!

**Comment by qizhang94** [comment]
> > @979736316 I am wondering why is that your IC and BC is not consistent at (0, 0), which could make the problem do not have a solution and hard to train.
> 
> Oh, I was wrong, u(0,0) should be 0, other values are 1. But I don’t know how to set it

This is what I have modified your initial condition, however, it doesn't improve the results.
`    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)*(1 - np.isclose(x[:, 0:1], 0))
    ic = dde.IC(
        geomtime, fun_init, lambda _, on_initial: on_initial
    )`

**Comment by 979736316** [comment]
> I looks good. What is your loss and results?
This is my final loss and results.
![image](https://user-images.githubusercontent.com/52651366/83723177-cfbc6600-a670-11ea-8174-eb2022f7f8c7.png)
![image](https://user-images.githubusercontent.com/52651366/83723340-1ca03c80-a671-11ea-92fe-ffa00148f0a1.png)

**Comment by lululxvi** [comment]
@979736316 You training loss is large. Check the FAQ "Q: I failed to train the network, e.g., the training loss is large." at https://deepxde.readthedocs.io/en/latest/user/questions_answers.html

**Comment by lululxvi** [comment]
@qizhang94 
- The first train loss is PDE loss, and the remaining are BC/ICs (the order is the same as the order defined in `dde.data.TimePDE`).
- The test loss is the same order as train loss, but we only test PDE loss.

What is your wired results?

**Comment by qizhang94** [comment]
<img width="740" alt="PDE" src="https://user-images.githubusercontent.com/43663334/83821469-4b271300-a683-11ea-97f9-6635b03984f3.png">

Hi, Lu
Thanks for your reply, I have attached an image which is a simpler version of the original PDE since the solution for original PDE is an infinite sum, here I just use the first term. It is similar to your **1d diffusion** example, the only difference is that here I have adopted Neumann boundary condition. The code is copied here:

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    def pde(x, u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx
    
    def func(x):
        psol = np.full_like(x[:, 0:1], 0)  # Analytical solution (dimensionelss)
        for m in range(1,3,2):
            psol += 4.0/(m*np.pi) * np.sin(np.pi * m * 0.5 * x[:, 0:1]) * np.exp(-x[:, 1:2]*np.pi*np.pi*m*m/4.0)
        return psol

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 0.5)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)
    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc1 = dde.DirichletBC(
        geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: boundary_l
    )
    bc2 = dde.NeumannBC(
        geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: boundary_r
    )

    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)*(1 - np.isclose(x[:, 0:1], 0))
    ic = dde.IC(
        geomtime, func, lambda _, on_initial: on_initial
    )


    # Hyperparameters that you can tune (the results for each run could also be different due to random initializations of NN)
    data = dde.data.TimePDE(
        geomtime, pde, [bc1,bc2,ic], 
        num_domain=100, num_boundary=50, num_initial=25, solution=func, num_test=10000
    )

    net = dde.maps.FNN([2] + [10] * 5 + [1], "sigmoid", "Glorot normal")
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3, metrics=["l2 relative error"], loss_weights = [1,1,1,1])
    losshistory, train_state = model.train(epochs=15000)
    # model.compile("L-BFGS-B", metrics=["l2 relative error"])
    # losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()`

As a result, the metric error is on the order of 1, which is not acceptable, but I don't know what goes wrong here. I am looking forward to your suggestions!

**Comment by lululxvi** [comment]
There is an error in your code about the BCs. It should be
```python
bc1 = dde.DirichletBC(geomtime, lambda x: np.zeros((len(x), 1)), boundary_l)
```
Similarly, bc2.

**Comment by 979736316** [comment]
> @979736316 You training loss is large. Check the FAQ "Q: I failed to train the network, e.g., the training loss is large." at https://deepxde.readthedocs.io/en/latest/user/questions_answers.html
Thank you very much I have read the FAQ.Let's multiply the network output by 10.

net = dde.maps.FNN(...)
net.outputs_modify(lambda x, y: y * 10)
![image](https://user-images.githubusercontent.com/52651366/83834978-32216f00-a722-11ea-91f3-35160095be4c.png)

The final result has been improved, but it is still not perfect. Is there any way to improve it?

**Comment by lululxvi** [comment]
Can you try the following:
- use more training points,
- a wider and shallower network, e.g., width 20, depth 3
- smaller learning rate

**Comment by qizhang94** [comment]
> There is an error in your code about the BCs. It should be
> 
> ```python
> bc1 = dde.DirichletBC(geomtime, lambda x: np.zeros((len(x), 1)), boundary_l)
> ```
> 
> Similarly, bc2.

Hi, Lu, thanks a lot! Now the result is okay. 

@979736316 , I have normalized the consolidation equation so the result is on the order of 1. Here is the link to my code, hope it can help you. 

https://drive.google.com/file/d/1VnhX5raAZrN8TBvQWVPhhMQb3aDMhwQ7/view?usp=sharing

**Comment by 979736316** [comment]
> > 您的有关BC的代码中有错误。它应该是
> > ```python
> > BC1  =  DDE。DirichletBC（geomtime，拉姆达 X：NP。零（（len个（X），1）），boundary_l）
> > ```
> > 
> > 
> > 同样，bc2。
> 
> 嗨，卢，非常感谢！现在结果还可以。
> 
> @ 979736316，我已经归一化了合并方程，因此结果大约为1。这是我的代码的链接，希望对您有所帮助。
> 
> https://drive.google.com/file/d/1VnhX5raAZrN8TBvQWVPhhMQb3aDMhwQ7/view?usp=sharing

Thank you very much for your help,I ran your code and got an error

**AttributeError: 'FNN' object has no attribute 'apply_output_transform**'

I changed this code
**net.outputs_modify(lambda x, y: y * x[:, 0:1])**

Are they the same?

**Comment by lululxvi** [comment]
They are the same, but you need to install the new version of DeepXDE

**Comment by qizhang94** [comment]
Hi, Lu

Sorry for bothering you again, for the network output transform, if we have two unknowns, and they are both functions of time and position, and we want to have different transforms, do you think the following code's syntax is correct?

def output_transform(x, y): # Transform network output
        y_transformed = y
        Rhat, that = x[:, 0:1], x[:, 1:2]
        uhat, phat = y[:, 0:1], y[:, 1:2]
        return tf.stack([uhat * that * Rhat, phat * that * (1 - Rhat)])

**Comment by lululxvi** [comment]
`y_transformed` seems unused. Is it `tf.stack(..., axis=1)`?

**Comment by qizhang94** [comment]
Thanks a lot! I will have a try.

**Comment by qizhang94** [comment]
Hi, Lu

I may need your help again. Now we have two unknowns _u_ and _p_, and they are functions of position _x_ and time _t_. However, the DeepXDE solution shows that both _u_ and _p_ will never change with time, to emphasize that, we have added non-zero time-dependent source terms in the PDEs, the description is given in the following figure, and we also attach the figures generated by the DeepXDE and the code sharable link: https://drive.google.com/file/d/1GtvbuA8L1LD2n0qJ0cCQ8tqaam-CJhon/view?usp=sharing

<img width="702" alt="PDE 2" src="https://user-images.githubusercontent.com/43663334/83962327-5cbe1580-a851-11ea-9c08-87966500071e.png">

![Figure_1](https://user-images.githubusercontent.com/43663334/83962378-a7d82880-a851-11ea-955e-88a75c1c9344.png)
![Figure_2](https://user-images.githubusercontent.com/43663334/83962379-a870bf00-a851-11ea-99e5-c65392c6cd3f.png)
![Figure_3](https://user-images.githubusercontent.com/43663334/83962380-a9095580-a851-11ea-96a5-c4106467e529.png)

I just don't know whether I have made something wrong in defining the coupled PDEs, so I will really appreciate it if you can give me some suggestions (I haven't tried network transformation here because the result is so strange, **it looks like the PINN is not trained at all**, but I have increased the weight for PDE loss, even though the results doesn't change at all).

**Comment by lululxvi** [comment]
- Do you have a reference solution?
- It is training as shown in the first plot, and from other plots, we can see that it satisfies IC and BC. But the total loss is still large. What is the loss for each component?
- Try to train for more iterations.

**Comment by qizhang94** [comment]
Hi, Lu

I **_intend to_** to design such IC, BC, and non-zeros source terms, in order to help me **_debug_**, unfortunately, I don't have a reference solution, but I think they should and must depend on _t_ because we can argue if they don't depend on _t_, for the second PDE, we will be only left with the second term, then if we use the output of DeepXDE (**p is linear in _x_**), then the LHS and RHS will never equal to each other.

The loss for each component is given as follows, it is also very strange that why the loss in the terminal is on the order of 10^-4 or 10^-5, but in the figure, it is only on the order of 10^-2? Is it because of the loss_weight? In any case, the NN only learns the initial and boundary condition, but not the PDE.
<img width="1634" alt="Loss" src="https://user-images.githubusercontent.com/43663334/83980311-8b77d280-a8c9-11ea-96d0-b2bc065e23d7.png">

**Comment by lululxvi** [comment]
- The loss in the plot is the weighted summation of all losses.
- For debug, I think you can first come up with the time-dependent solution, and thus plug into the PDE to get the right hand side term, and also BC/IC. In your case, the BC/IC are all `5(x-1)`, and it is hard to know what is the performance of the solution, and even there is no solution for this combination of BC/IC.

**Comment by qizhang94** [comment]
Thanks a lot, I will try your suggestion by first assuming the analytical solution and then get the RHS source terms.

I just want to make sure that I understand it correct: if we don't assume **loss_weight**, then the weight will be **_1_** by default? In addition, can you help me check there is no syntax error in my previous code (I have copied the link here): https://drive.google.com/file/d/1GtvbuA8L1LD2n0qJ0cCQ8tqaam-CJhon/view?usp=sharing

<img width="716" alt="PDE 3" src="https://user-images.githubusercontent.com/43663334/83981504-4bb5e880-a8d3-11ea-840b-dc5f3dc7a114.png">

Thanks a lot!

Qi Zhang

**Comment by lululxvi** [comment]
Yes, by default the loss_weight is 1. The code looks good.

**Comment by qizhang94** [comment]
Thanks a lot for your help!

**Comment by 979736316** [comment]
> re is an error in your code about t

**Comment by 979736316** [comment]
> ave normalized the consolidation equation so the result is on the order of 1. Here is the link to my code, hope it can help you.

Hi Lu，qizhang94
     Thanks to your help last time，I need your help again. I try to solve the following PDE.But my Python programming level is limited.Can you help me see if my code is correct?In fact, I don’t know how to express this exact solution.
![image](https://user-images.githubusercontent.com/52651366/84568787-62b57880-adb4-11ea-9273-ba4cce8ab37a.png)
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

b=2
c=3
def main():
    def pde(x, u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    def func(x):
        psol = np.full_like(x[:, 0:1], 0)  # Analytical solution (dimensionelss)
        n = np.exp(-b * x[:, 1:2])
        m = np.exp(-c * x[:, 1:2])
        for i in range(1,50,1): # You can increase '50' to a larger number
            q = np.sin(i * np.pi) * x[:, 0:1] / np.pi
            w = b / (np.power(np.pi * i, 2) - b)
            a = c / (np.power(np.pi * i, 2) - c)
            k = np.exp(-np.power(i * np.pi, 2) * x[:, 1:2])
            d = np.exp(np.power(i * np.pi, 2) * x[:, 1:2])
            psol += n+(m-n)*x[:, 0:1]+2*q*w*(n-k)-2*q*a*np.power(-1,i)*(m-d)
        return psol

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return np.exp(-b*x[:, 1:])

    def fun_initbc_all_b(x):
        return np.exp(-c*x[:, 1:])
    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, lambda _, on_boundary: boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, lambda _, on_boundary: boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic],
        num_domain=1500,
        num_boundary=450,
        num_initial=450,
        solution=func,
        num_test=10000,
    )

    net = dde.maps.FNN([2] + [50] * 5 + [1], "tanh", "Glorot normal")

    model = dde.Model(data, net)

    model.compile("adam", lr=0.00001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=10000)

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
```

This is my loss 
![image](https://user-images.githubusercontent.com/52651366/84568957-8d540100-adb5-11ea-808f-67b19a0e5e25.png)

**Comment by lululxvi** [comment]
Looks good.

**Comment by dpdclub** [comment]
Hi Lu,

Is the testing error showing  a double-well?

LinLin Fan

**Comment by 979736316** [comment]
> 看起来挺好的。

Hi Lu,I would like to ask you a question. In the case of "diffusion_1d" you gave, what does "test metric" mean after training? L2 relative error？
If I want to know the ”Mean residual“ in this case, how should the code be executed？

**Comment by lululxvi** [comment]
Check the example of Burgers.py for Mean residual.

**Comment by 979736316** [comment]
> 检查Burgers.py示例中的平均残差。
Thank you very much, and I would like to ask you again whether the following functions defined in Burgers.py are finite difference numerical solutions.
`def gen_testdata():
    data = np.load("dataset/Burgers.npz")
    t, x, exact = data["t"], data["x"], data["usol"].T
    xx, tt = np.meshgrid(x, t)
    X = np.vstack((np.ravel(xx), np.ravel(tt))).T
    y = exact.flatten()[:, None]
    return X, y`

If I have an analytical solution, how to define X to solve Mean residual？

**Comment by lululxvi** [comment]
Yes, it is the reference solution from other numerical methods, e.g., finite difference.

`X` is the location where you want to check the accuracy. See "Q: How can I use a trained model for new predictions?" in the FAQ,
