### ISSUE TITLE
Trained function from datasets before the PDEs

### ISSUE THREAD

**Issue by forxltk** [lululxvi/deepxde#606]
Hello @lululxvi ,
Thank you for your great library! It is always high accuracy with low running time!

I am trying to solve an 2D nonlinear solid mechanics problem with deepxde.

There are the momentum relations and the kinematic relations:
 `sxx_x+sxy_y=0`  `syy_y+sxy_x=0`

`exx-u_x=0` `eyy-v_y=0`

Due to the nonlinear, I'd like to approximate the constitutive relations with some datasets about the stress and infinitesimal stress tensor. It is quite easy to do according to demo `Function Approximation.`

Thus I have the function `sij=f(eij)`, and the PDEs can be solved.

However, it requires a trained model for datasets before the PDEs model that I have no proper solution. Or maybe I  can train them simultaneously?

Is it doable in the deepxde?
Many thanks!

**Comment by praksharma** [comment]
HI I am also use PINNs in structural mechanics. Can you be more specific here.
```
Due to the nonlinear, I'd like to approximate the constitutive relations with some datasets about the stress and infinitesimal stress tensor. It is quite easy to do according to demo Function Approximation.
```
 Feel free to write a long post.

**Comment by lululxvi** [comment]
Yes, you can train them simultaneously. Or you can also train `f` first, and then use it when using PDE, which seems doable, but I am not sure if technically it is easy to do.

**Comment by forxltk** [comment]
> HI I am also use PINNs in structural mechanics. Can you be more specific here.
> 
> ```
> Due to the nonlinear, I'd like to approximate the constitutive relations with some datasets about the stress and infinitesimal stress tensor. It is quite easy to do according to demo Function Approximation.
> ```
> 
> Feel free to write a long post.

Hi, the stress–strain relations for elasto-plasticity is hard to define in PINN, still less the incremental form. So I wanna to use purely data-driven network to fit the constitutive model instead of the PDE-base one. These data can be collected from experiment or high-fidelity simulation. And using existing data to approximate a nonlinear function is very easy, especially a time-independent one. 

Once we have the constitutive function, a elasto-plasticity problem will degenerate to a "linear elasticity" problem. That means the momentum relations and the kinematic relations are same as the linear elasticity. But for the constitutive relation, the linear elasticity use the Hooke's law with elastic Modulus and Poisson ratio, while the elasto-plasticity use a well-trained networks with parameters for the hidden layers.

This is my tentative solution for the elasto-plasticity problem.

**Comment by forxltk** [comment]
> Yes, you can train them simultaneously. Or you can also train `f` first, and then use it when using PDE, which seems doable, but I am not sure if technically it is easy to do.

Thanks! To the best of my knowledge, there are only examples for use the datasets `dde.data.DataSet` or the PDE `dde.data.PDE` alone. 
If possible, could you have an example for how to train them simultaneously? 

Best wishes
