### ISSUE TITLE
How can I get the get the differential values in my ODE or PDE

### ISSUE THREAD

**Issue by ZSTanone** [lululxvi/deepxde#611]
Dear Lu，
If I want to verify my results manually while solving ODEs, what method should I use to get the differential values in my differential equation.
For example ，in this forward problem
![image](https://user-images.githubusercontent.com/103397565/162864539-437c22db-8103-4e87-8fbd-61d45030ab50.png)
It's easy to get y1，y2 by using ` model.predict（t）` , but how  to get the value of dy1/dt , dy2/dt

**Comment by lululxvi** [comment]
```
def dy1(x, y):
    return dde.grad.jacobian(y, x, i=0)

model.predict(x, operator=dy1)
```

**Comment by ZSTanone** [comment]
> ```
> def dy1(x, y):
>     return dde.grad.jacobian(y, x, i=0)
> 
> model.predict(x, operator=dy1)
> ```

Thanks for your reply，but I still has some problems ，when I use code like
` 
    t = np.linspace(0, 1, 100)

    t = t.reshape(100, 1)
    sol_pred = model.predict(t)
    x_pred = sol_pred[:, 0:1]
    y_pred = sol_pred[:, 1:2]`

I finally get a new predict value which given input as t ,  how can I get the original output value of my network just as the red dashed line shows in this pic
![image](https://user-images.githubusercontent.com/103397565/163146120-997118df-b03f-4534-b226-6b395edd03d6.png)

`   
def y1(x, y):
        return [
            y[:, 0:1],
            y[:, 1:]
        ]
    
y = model.predict(x,operator=y1)`
I tried this one but don't get the right answer

**Comment by ZSTanone** [comment]
> ```
> def dy1(x, y):
>     return dde.grad.jacobian(y, x, i=0)
> 
> model.predict(x, operator=dy1)
> ```

Much appreciate for your reply
