### ISSUE TITLE
Boundary normal is [0,0] in 2D geometry

### ISSUE THREAD

**Issue by bdwhst** [lululxvi/deepxde#620]
After training a 2d polygon geometry, I find out the result was somewhat abnormal, after I printed the normal vector on boundary， I find out most of them are [0,0]
``` python
from math import *
deg_to_rad=1./180*pi
poly=dde.geometry.geometry_2d.Polygon([
                                        [3+3*sin(18*deg_to_rad),0],
                                        [3*cos(36*deg_to_rad),-3*cos(36*deg_to_rad)*1/tan(18*deg_to_rad)+3*cos(18*deg_to_rad)],
                                        [-3*cos(36*deg_to_rad),-3*cos(36*deg_to_rad)*1/tan(18*deg_to_rad)+3*cos(18*deg_to_rad)],
                                        [-3-3*sin(18*deg_to_rad),0],
                                        [0.,3*cos(18*deg_to_rad)],
                                    ])
geom=poly
timedomain=dde.geometry.TimeDomain(0., 1.)
geom_time=dde.geometry.GeometryXTime(geom,timedomain)

import matplotlib.pyplot as plt
xy=geom.random_boundary_points(100)
uv=geom.boundary_normal(xy)
print(uv)
fig = plt.figure(figsize=(10, 10), dpi=80)
plt.quiver(xy[:,0],xy[:,1],uv[:,0],uv[:,1])
plt.show()
```
![image](https://user-images.githubusercontent.com/60293727/163540093-dc7adc14-f411-4429-bf03-db81cfd5273b.png)
As you can see, normal vector are all zeros aparts from the bottom
How could I possibly fix this?

**Comment by lululxvi** [comment]
DeepXDE will first check if a point is on the boundary of the polygon; if not, then return `[0, 0]`.
https://github.com/lululxvi/deepxde/blob/5d5385ed986843214a9e477de1de43b3c783a748/deepxde/geometry/geometry_2d.py#L410

But this checking is sensitive to precision. Using double precision below will give you the correct answer
```python
dde.config.set_default_float("float64")
```

The check is the code
https://github.com/lululxvi/deepxde/blob/5d5385ed986843214a9e477de1de43b3c783a748/deepxde/geometry/geometry_2d.py#L517

We may modify the code so that it also works well in single precision.

**Comment by bdwhst** [comment]
> DeepXDE will first check if a point is on the boundary of the polygon; if not, then return `[0, 0]`.
> 
> https://github.com/lululxvi/deepxde/blob/5d5385ed986843214a9e477de1de43b3c783a748/deepxde/geometry/geometry_2d.py#L410
> 
> But this checking is sensitive to precision. Using double precision below will give you the correct answer
> 
> ```python
> dde.config.set_default_float("float64")
> ```
> 
> The check is the code
> 
> https://github.com/lululxvi/deepxde/blob/5d5385ed986843214a9e477de1de43b3c783a748/deepxde/geometry/geometry_2d.py#L517
> 
> We may modify the code so that it also works well in single precision.
> 
> Update: The code has been uploaded to support float32. Please use the updated code.

It works! Thanks a lot, but considering default precision setting will not work under this circumstance, maybe you could change the default presicion to be double or change is_on_line_segment function?
