### ISSUE TITLE
Sequential training of PINN

### ISSUE THREAD

**Issue by inodozi** [lululxvi/deepxde#628]
Hi 
I want to implement a sequential training of PINN with DeepXDE for a system of coupled PDEs.
I want to first optimize the network parameters of the first PDE with the fixed solution of the second PDE, then vice versa, and then iterate the process until convergence is achieved.

Can you please help me with how I can import the output of the first PINN as input to the next PINN?

**Comment by lululxvi** [comment]
Set the weight of the term that you don't want to train to 0. Read the code at https://github.com/lu-group/sbinn/tree/main/sbinn, and you will get a hint.

**Comment by dmaionchi** [comment]
Hi,
@inodozi did you get to implement your PDEs sequentialy? I am having the same problem. Maybe you could help me?

**Comment by inodozi** [comment]
Hi,
@dmaionchi 
Not exactly; I used a single NN to solve the system of coupled PDEs. But I am still working on it, and if I find a way for that, I will share it here.

**Comment by dmaionchi** [comment]
Thanks @inodozi 
In my case I have 15 coupled PDEs. I also implemented them in a single NN, but it is diverging.
Hope to hear from you soon.
