### ISSUE TITLE
求解多个拉普拉斯方程

### ISSUE THREAD

**Issue by wuwnnn** [lululxvi/deepxde#632]
陆路博士您好，我刚刚开始学习深度学习，我尝试用DeepXDE求解多个相关联的拉普拉斯方程，我尝试编了一些但是在运行过程中会报错，您能给我一些建议吗，我不知道这个方程能不能通过深度学习实现。
我的方程是：
![1650549393(1)](https://user-images.githubusercontent.com/101729396/164473939-a7b50d65-7fbd-462f-8ea8-cd4d1efb9969.jpg)
我的代码：
import deepxde as dde
import numpy as np

def pdes(x, y):
    y1, y2, y3 = y[:, 0:1], y[:, 1:2], y[:, 2:3]
    dy1_r = dde.grad.jacobian(y1, x, i=0, j=0)
    dy1_rr = dde.grad.hessian(y1, x, i=0, j=0)
    dy1_thetatheta = dde.grad.hessian(y1, x,  i=1, j=1)
    dy2_r = dde.grad.jacobian(y1, x, i=0, j=0)
    dy2_rr = dde.grad.hessian(y2, x, i=0, j=0)
    dy2_thetatheta = dde.grad.hessian(y2, x, i=1, j=1)
    dy3_r = dde.grad.jacobian(y1, x, i=0, j=0)
    dy3_rr = dde.grad.hessian(y3, x,  i=0, j=0)
    dy3_thetatheta = dde.grad.hessian(y3, x,  i=1, j=1)

    return [
            dy1_r*x[:, 0:1] + x[:, 0:1]**2*dy1_rr + dy1_thetatheta,
            dy2_r * x[:, 0:1] + x[:, 0:1] ** 2 * dy2_rr + dy2_thetatheta,
            dy3_r*x[:, 0:1] + x[:, 0:1]**2*dy3_rr + dy3_thetatheta-q(r),
           ]
def fun1(x,y):
    y3= y[:, 2:3]
    y2= y[:, 1:2]
    return y2 - y3
def fun2(x, y):
        y2 = y[:, 1:2]
        dy2_r = dde.grad.jacobian(y2, x, i=0, j=0)
        y1 = y[:, 0:1 ]
        dy1_r = dde.grad.jacobian(y1, x, i=0, j=0)
        return dy2_r - dy1_r
def fun3(x,y):
    y2= y[:, 1:2]
    dy2_thet = dde.grad.jacobian(y2, x, i=0, j=1)
    return dy2_thet
def boundary_1(x,on_boundary):
    return on_boundary and np.isclose(x[0],r3)
def boundary_2(x,on_boundary):
    return on_boundary and np.isclose(x[0],r2)
bc_1 = dde.icbc.OperatorBC(geom1, fun1, boundary_1)
bc_2 = dde.icbc.OperatorBC(geom1,fun2, boundary_2,)
![1650550256(1)](https://user-images.githubusercontent.com/101729396/164476879-b1d90a5c-e029-4c5d-8022-04cf86ef4c86.jpg)

**Comment by praksharma** [comment]
I don't know Chinese but the error is very simple. If you understand English here is the problem.
The function you defined `fun3()` takes in two input arguments i.e. `x` and `y`. But when you call this function you are passing 3 input arguments.

Now can't see where did you call `fun3()` exactly. Please paste the whole code using add code in the toolbar, so that it is readable.

**Comment by wuwnnn** [comment]
Thank you for your reply,Recently I made changes to my code.There is still an error giving three positional arguments.How do I define y1-y2 , dy2_r-dy1_r,dy2_thet-dy3_thet. Could you give me some comments on this ?Thank you.
the whole code

import deepxde as dde
import numpy as np

def pde1(x1, y):
   y1=y[:,0:1]
   dy1_r= dde.grad.jacobian(y1, x1, i=0, j=0)
   dy1_rr = dde.grad.hessian(y1, x1, i=0, j=0)
   dy1_thetatheta= dde.grad.hessian(y1, x1, i=1, j=1)
   return dy1_r*x1[:, 0:1] + dy1_thetatheta + dy1_rr*x1[:, 0:1]**2
def pde2(x2, y):
    y2 = y[:, 0:1]
    dy2_r = dde.grad.jacobian(y2, x2, i=0, j=0)
    dy2_rr = dde.grad.hessian(y2, x2, i=0, j=0)
    dy2_thetatheta= dde.grad.hessian(y2, x2, i=1, j=1)
    return dy2_r * x2[:, 0:1] + dy2_thetatheta + dy2_rr * x2[:, 0:1]**2
def pde3(x3, y):
   y3 = y[:, 0:1]
   dy3_r= dde.grad.jacobian(y3, x3, i=0, j=0)
   dy3_rr= dde.grad.hessian(y3, x3, i=0, j=0)
   dy3_thetatheta= dde.grad.hessian(y3, x3, i=1, j=1)
   return dy3_r*x3[:, 0:1] + dy3_thetatheta + dy3_rr*x3[:, 0:1]**2-q(r)
def y1(y):
    y1=y[:,0:1]
    return y1
def y2(y):
    y2 = y[:, 0:1]
    return y2
def y3(y):
    y3 = y[:,0:1]
    return y3
def boundary_1(x,on_boundary):
    return on_boundary and np.isclose(x[0],A)
def boundary_2(x,on_boundary):
    return on_boundary and np.isclose(x[0],B)
def boundary_3(x,on_boundary):
    return on_boundary and np.isclose(x[0],C)
def boundary_4(x,on_boundary):
    return on_boundary and np.isclose(x[0],D)
def boundary_5(x,on_boundary):
    return on_boundary and np.isclose(x[1],np.pi*2/42)
def boundary_6(x,on_boundary):
    return on_boundary and np.isclose(x[1],np.pi/2)

geom1 = dde.geometry.Rectangle(xmin=[B, np.pi/2-np.pi*2/42], xmax=[C, np.pi/2])
geom2 = dde.geometry.Rectangle(xmin=[C, 0], xmax=[D, np.pi*2])
geom3 = dde.geometry.Rectangle(xmin=[A, 0], xmax=[B, np.pi*2])
geom4 = dde.geometry.Rectangle(xmin=[B, np.pi/2-np.pi*2/42], xmax=[C, np.pi/2])
geom5 = dde.geometry.Rectangle(xmin=[B, 0], xmax=[C, np.pi/2-np.pi*2/42])
geom6 = dde.geometry.Rectangle(xmin=[B, np.pi/2], xmax=[C, np.pi*2])
def fun1(y):
    y2 = y[:,0:1]
    y3 = y[:, 0:1]
    return y2 - y3

def fun2(x1,x2,y):
    y1 = y[:, 0:1]
    dy1_r=dde.grad.jacobian(y1, x1, i=0, j=0)
    y2 = y[:, 0:1]
    dy2_r=dde.grad.jacobian(y2, x2, i=0, j=0)
    return dy2_r-dy1_r
def fun3(x2,y):
    y2 = y[:, 0:1]
    dy2_thet=dde.grad.jacobian(y2, x2, i=1, j=0)
    return dy2_thet
def fun4(x2,y):
    y2 = y[:, 0:1]
    dy2_r = dde.grad.jacobian(y2, x2, i=0, j=0)
    return dy2_r
def fun5(x3,y):
    y3 = y[:, 0:1]
    dy3_r = dde.grad.jacobian(y3, x3, i=0, j=0)
    return dy3_r
def fun6(x3,x2,y):
    y4 = y[:, 0:1]
    y2 = y[:, 0:1]
    dy3_thet = dde.grad.jacobian(y4, x3, i=0, j=0)

    dy2_thet = dde.grad.jacobian(y2, x2, i=0, j=0)
    return dy2_thet-dy3_thet

def fun7(x2,x1,y):
    y1 = y[:, 0:1]
    y2 = y[:, 0:1]
    dy2_r = dde.grad.jacobian(y2, x2, i=0, j=0)

    dy1_r = dde.grad.jacobian(y1, x1, i=0, j=0)
    return dy2_r-dy1_r

def fun8(x1,y):
    y1 = y[:, 0:1]
    dy1_thet=dde.grad.jacobian(y1, x1, i=1, j=0)
    return dy1_thet
bc_1 = dde.icbc.OperatorBC(geom1, fun1, boundary_3)
bc_2 = dde.icbc.OperatorBC(geom1, fun8, boundary_5)
bc_3 = dde.icbc.OperatorBC(geom1,fun8, boundary_6,)

bc_4 = dde.icbc.OperatorBC(geom2, fun6, boundary_2)
bc_5 = dde.icbc.OperatorBC(geom4, fun7, boundary_3)
bc_6 = dde.icbc.OperatorBC(geom5, fun4, boundary_3)
bc_7 = dde.icbc.OperatorBC(geom6, fun4, boundary_3)


bc_8 = dde.icbc.OperatorBC(geom4, fun6, boundary_2)
bc_9 = dde.icbc.OperatorBC(geom4, fun5, boundary_1)

data1 = dde.data.PDE(geom1, pde1, [bc_1,bc_2,bc_3] ,5000, 500, num_test=500)
data2 = dde.data.PDE(geom2, pde2, [bc_4,bc_5,bc_6,bc_7] ,5000, 500, num_test=500)
data3 = dde.data.PDE(geom4, pde3, [bc_8,bc_9] ,5000, 500, num_test=500)

layer_size = [2] + [50] * 4 + [5]
activation = "tanh"
initializer = "Glorot uniform"
net = dde.nn.FNN(layer_size, activation, initializer)

model1 = dde.Model(data1, net)
model2 = dde.Model(data2, net)
model3 = dde.Model(data3, net)
model1.compile("adam", lr=0.001)
losshistory, train_state = model1.train(epochs=1000)

**Comment by lululxvi** [comment]
Could you be more specific? What are you trying to implement? What is the error? Which line of the code throws the error?
