### ISSUE TITLE
On the accuracy of the parameters to be identified in the inverse problem

### ISSUE THREAD

**Issue by ZSTanone** [lululxvi/deepxde#633]
Your previous reply has helped me a lot. Recently， I had some problems solving the inverse problem.
How can I get higher accuracy output in the process of parameter identification.
Usually when identifying parameters, I can only see two decimal places
Code for defining parameters：
` f_ = dde.Variable(0.1) `
The results are shown in this pic
![image](https://user-images.githubusercontent.com/103397565/164719129-42b48eb3-a9eb-44cc-897f-c9e35b589662.png)
What should I do if I want to get more accurate information?
Much appreciate for your help

**Comment by 979736316** [comment]
> 

You can check the API documentation https://deepxde.readthedocs.io/en/latest/modules/deepxde.html. which has settings for precision. 
![image](https://user-images.githubusercontent.com/52651366/164862968-33ec0986-d4b9-4eb3-8e94-868cb51bfdc3.png)

**Comment by ZSTanone** [comment]
> > 
> 
> You can check the API documentation https://deepxde.readthedocs.io/en/latest/modules/deepxde.html. which has settings for precision. ![image](https://user-images.githubusercontent.com/52651366/164862968-33ec0986-d4b9-4eb3-8e94-868cb51bfdc3.png)

Thanks for your advice！
