### ISSUE TITLE
Implementing a hard constraint for the solution of PDEs with PINN.

### ISSUE THREAD

**Issue by inodozi** [lululxvi/deepxde#636]
I want to solve a PDE that its solution should be found in the interval of [0.5, 4].
How can we implement this hard constraint in PINN?
Is it possible to force the solution of the PDEs to belong to an interval, for example (a,b), and a<b?
Thank you

**Comment by riccardotomada** [comment]
I think it is possible, but I have never tried it in a physical problem. A possible strategy is similar as imposing the boundary conditions in the hard way. Assuming a single output network, you could try something like this (in tensorflow):

```python
def modify_output(X, Y):
   y = Y
   Y_new = tf.clip_by_value(y, clip_value_min = a, clip_value_max = b)      
   return Y_new
```
and then, assuming your network is defined as 'net':
```python
net.apply_output_transform(modify_output)
```
From tensorflow docs, about clip_by_value:

> Given a tensor t, this operation returns a tensor of the same type and shape as t with its values clipped to clip_value_min and clip_value_max. Any values less than clip_value_min are set to clip_value_min. Any values greater than clip_value_max are set to clip_value_max.

I'm not sure anyway if it is ok to force the PINN to find a solution using this method.

**Comment by lululxvi** [comment]
`clip_by_value` seems OK. You can also use other transforms such as `tanh`

**Comment by inodozi** [comment]
Thank you for your explanations.
How about if the network had three outputs and we wanted to apply the tf.clip_by_value function to just one of them?

**Comment by riccardotomada** [comment]
Suppose as in my case you have three outputs: u, v, p, and you want to force u to be constrained as you specified previously. Then:
```python
def modify_output(X, Y):
    u, v, p  = Y[:, 0:1], Y[:, 1:2], Y[:, 2:3]
    u_new = tf.clip_by_value(u, clip_value_min = a, clip_value_max = b)
    return tf.concat((u_new, v, p), axis=1)

net.apply_output_transform(modify_output)
```
