### ISSUE TITLE
A third-party library used by DeepXDE restricts dimensions to 40; DeepXDE使用的某个第三方库限制维度必须在40之内

### ISSUE THREAD

**Issue by Wulx2050** [lululxvi/deepxde#638]
Hi, lulu，
第一个问题，用 `data.train_next_batch(batch_size)` 获取数据，`batch_size` 参数无效。
**First question**, use `data.train_next_batch(batch_size) ` to get data, the parameter `batch_size ` is invalid.
```python
import deepxde as dde
import numpy as np

def pde(x, y):
    dy_x = dde.grad.jacobian(y, x, i=0, j=0)
    dy_t = dde.grad.jacobian(y, x, i=0, j=1)
    dy_xx = dde.grad.hessian(y, x, i=0, j=0)
    return dy_t + y * dy_x - 0.01 / np.pi * dy_xx

geom = dde.geometry.Interval(-1, 1)
timedomain = dde.geometry.TimeDomain(0, 0.99)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

bc = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: on_boundary)
ic = dde.icbc.IC(
    geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
)

data = dde.data.TimePDE(
    geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160
)

for i in [1, 10, 128]:
    print(data.train_next_batch(batch_size=i)[0].shape)
    print(data.test(batch_size=i)[0].shape)
```
最后三行的代码表明，`batch_size` 这个参数并没有被使用。输出是(3020, 2)，预期是(batch_size, 2)。
The last three lines of code indicate that this parameter `batch_size`  is not used. The output is (3020, 2), and the expected is (batch_size, 2).
为什么是3020，2540+80+160=2780，难道是2540+80*4+160=3020？
https://deepxde.readthedocs.io/en/latest/_modules/deepxde/data/data.html#Data
源码 class Data 和 class Tuple(Data) 中 `train_next_batch` 并没有实现。

第二个问题，deepxde文档中多数是1维示例，数据类型一般是(None, 1)、(None, 2)，能不能多添加一些高维(3, 10, 100, 1000)示例。例如这里的几个问题：
**Second question**, most of the deepxde documents are 1-dimensional examples, and the data types are generally (none, 1), (none, 2). Can you add more high-dimensional (3, 10, 100, 1000) examples. For example, here are some questions:
https://github.com/frankhan91/DeepBSDE

我对偏微分方程了解比较少，高维偏微分方程的数据生成部分对我来说很难。
I know little about partial differential equations, and the data generation part of high-dimensional partial differential equations is very difficult for me.

**Comment by lululxvi** [comment]
- `dde.data.Data` is an abstract base class. You should look at specific classes. Actually, `train_next_batch` is not designed to be called as a public function. 
- If you understand 1D/2D cases, then high-dimensional examples shouldn't be a problem.
- Use another way to sampling points,

```python
data = dde.data.PDE(..., train_distribution="pseudo")
```
