### ISSUE TITLE
Returning u_t and u_xx in the Burgers example

### ISSUE THREAD

**Issue by ddgpires** [lululxvi/deepxde#639]
Dear Lu Lu and DeepXDE team, 

Thank you for sharing your incredible work. I would like to know if there is a way to obtain the partials u_t and u_xx in the Burgers example you have [https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/burgers.html](here) once the solution is computed.

As described in the documentation, we can evaluate the solution u(x,t) at t=0.5 for x in [-1,1] executing the command
    
    x = np.linspace(-0.99, 0.99, 31)

    t = 0.5 * np.ones_like(x)

    X = np.vstack([x, t]).T

    u = model.predict(X)

    plt.plot(x, u)

I was wondering if there is a way to obtain something in the lines of 

    u, u_t, u_x, u_xx = model.predict(X)

so that I can plot

    plt.plot(x, u_t)

or 

    plt.plot(x, u_xx)

Thanks in advance.

**Comment by forxltk** [comment]
Use the  `operator`  with your interest value
For example,
```
def dux(x, y):
    return dde.grad.jacobian(y, x, i=0)

model.predict(x, operator=dux)
```

**Comment by ddgpires** [comment]
Thank you for your quick answer, @forxltk. Unfortunately, it appears to generate a mismatch between the tensors shapes that prevent the computation of the partials. I receive a similar error when trying to use callbacks.Callback.OperatorPredictor. Please find below a fully reproducible code that generates the error I mentioned using your suggestion. 

    import deepxde as dde
    import numpy as np
    import matplotlib.pyplot as plt

    def pde(x, y):
        dy_x = dde.grad.jacobian(y, x, i=0, j=0)
        dy_t = dde.grad.jacobian(y, x, i=0, j=1)
        dy_xx = dde.grad.hessian(y, x, i=0, j=0)
        return dy_t + y * dy_x - 0.01 / np.pi * dy_xx


    geom = dde.geometry.Interval(-1, 1)
    timedomain = dde.geometry.TimeDomain(0, 0.99)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)
  
    bc = dde.icbc.DirichletBC(geomtime, lambda x: 0, lambda _, on_boundary: on_boundary)
    ic = dde.icbc.IC(
        geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
    )
  
    data = dde.data.TimePDE(
        geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160
    )
    net = dde.nn.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")
    model = dde.Model(data, net)
    
    model.compile("adam", lr=1e-3)
    model.train(epochs=5000)
    model.compile("L-BFGS")
    losshistory, train_state = model.train()
    
    # PLOTTING
    x = np.linspace(-0.99, 0.99, 31)
    
    t = 0.5 * np.ones_like(x)
    
    X = np.vstack([x, t]).T
  
    def dux(x, u):
        return dde.grad.jacobian(u, x, i=0)
    
    dudx = model.predict(x, operator=dux)
    
    plt.plot(x, dudx)
