### ISSUE TITLE
Training Point Over A Perticular Region of Domain

### ISSUE THREAD

**Issue by SanjuSoni** [lululxvi/deepxde#64]
Dear @lululxvi 
- Can we add the training point over the domain at a particular position or direction rather than adding it uniformly or randomly over a domain?

for example: 

in the case of a square type of domain. 

- Only training point should be taken over a line y = x, or a circle type region inside the square geometry.

**Comment by SanjuSoni** [comment]
Thanks @lululxvi ,
for my case of square domain ( 2D geometry).


![unit square](https://user-images.githubusercontent.com/61820415/84493777-feb48680-acc5-11ea-8774-5190776a24e8.png)


- if I am trying to define anchor over a line  y = 0.5

then, X will be defined as 
X = np.array([ [0 , 0.5 ], [ 0.2, 0.5], [0.3 , 0.5], . . . , [1 , 0.5] ] ) 

If I am right, this will be correct way of defining an anchor.

Kindly, suggest me.

**Comment by lululxvi** [comment]
Yes, it is right.

**Comment by SanjuSoni** [comment]
Thanks @lululxvi

**Comment by bakhtiyar-k** [comment]
For example, If `num_domain = num_test = 0` and `anchors = np.array([ [0, 0.5 ], [ 0.2, 0.5], [0.3, 0.5], . . . , [1, 0.5] ] )`, training will use anchor points but what if I want test points to be the same as the training points?
