### ISSUE TITLE
System of coupled PDEs

### ISSUE THREAD

**Issue by inodozi** [lululxvi/deepxde#647]
I am trying to solve a system of coupled PDEs with PINN. But I am not getting a correct answer from one of the PDEs (y3=u_opt). 
I am pasting the PDEs here:

<img width="1165" alt="Screen Shot1" src="https://user-images.githubusercontent.com/71740055/166319029-3ff57f73-f31e-4f29-b4ba-14f227cb2f36.png">

I have questions about two things.
First is the exp function.

<img width="1498" alt="Screen Shot2" src="https://user-images.githubusercontent.com/71740055/166319480-8e1d5a2b-e40c-4224-a163-2bfe81bb60af.png">

Is it the correct way to use the exp function?

Second,
<img width="1492" alt="Screen Shot3" src="https://user-images.githubusercontent.com/71740055/166320049-e294e277-c2ce-4947-9c04-71ef6e958762.png">

Can I take derivative of function D1 and D2 respect to y3 (the output of PINN) with dde.grad.jacobian function?
    dD1_y3=dde.grad.jacobian(D1, y3)
    dD2_y3=dde.grad.jacobian(D2, y3)

Here are the residuals after 6000 epochs.

<img width="1530" alt="Screen Shot4" src="https://user-images.githubusercontent.com/71740055/166320317-6d6b9521-3b46-49da-9b13-db0346764f31.png">

**Comment by lululxvi** [comment]
Yes to both questions.

**Comment by inodozi** [comment]
Thank you.
I have one more question.
What range should the residual be so we can ensure that the PDEs are solved?
As you can see in the screenshot I pasted here, they are less than 10^-2? 
Should I run the PINN for more epochs, or is this residual acceptable?

**Comment by lululxvi** [comment]
> What range should the residual be so we can ensure that the PDEs are solved?

It is always problem dependent. In general, I would require the loss is decreased by 4 orders of magnitude.
