### ISSUE TITLE
Custom 3D geometry

### ISSUE THREAD

**Issue by Xtaltec** [lululxvi/deepxde#650]
Hi,

I am new to DeepXDE and after browsing through the documentation I am not sure if it is possible to define the geometric domain based on a custom 3D geometry (i. e. based on a triangular 3D mesh) or if it is only possible to do it based on primitive geometries.

Kind regards,
Xabier

**Comment by lululxvi** [comment]
Yes, it is possible. Use an arbitrary 3D geometry, but providing the 3D mesh nodes as `anchors` in `dde.data.PDE`

**Comment by Xtaltec** [comment]
Thank you for the help and for creating such a useful library!
