### ISSUE TITLE
New error since the last update? 

### ISSUE THREAD

**Issue by sashahexe** [lululxvi/deepxde#665]
Dear Lu Lu,

I am working with DeepXDE almost every day since a few months. Just recently here is an error appearing when trying to compile the model. Remarkably, I have this colab since a while and it used to work before. Today I didn't change anything but here is the error which I get:

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-bc50364cbf03>](https://localhost:8080/#) in <module>()
     92 model = dde.Model(data, net)
     93 loss_weights = [1, 1, 0.01, 0.1, 0.01]
---> 94 model.compile('adam', lr=0.001, loss_weights=loss_weights, external_trainable_variables=[k])
     95 
     96 variable = dde.callbacks.VariableValue([k], period=1000, filename="k.dat")

5 frames
[/usr/local/lib/python3.7/dist-packages/deepxde/icbc/boundary_conditions.py](https://localhost:8080/#) in normal_derivative(self, X, inputs, outputs, beg, end)
     52     def normal_derivative(self, X, inputs, outputs, beg, end):
     53         dydx = grad.jacobian(outputs, inputs, i=self.component, j=None)[beg:end]
---> 54         n = self.boundary_normal(X, beg, end)
     55         return bkd.sum(dydx * n, 1, keepdims=True)
     56 

TypeError: wrapper_nocache() missing 1 required positional argument: '_'
```

Could you please give me a hint what is missing?

Thanks!

____________________________________
UDATE:

1) Tried the same code in Spyder, same error occurs.
2) Checked a few of previously working colab files, all of them get the same error now, independently of whether it's a forward or an inverse problem.

Here I made a dummy colab for your convenience to see the problem:
https://colab.research.google.com/drive/1uDRugg1L7XJWcZ04fUPG9Bbg6P1t8E1m?usp=sharing

**Comment by lululxvi** [comment]
Ahh, it is a new bug. Just fixed. You can use the old version v1.2.0.

**Comment by sashahexe** [comment]
Great, thank you for the prompt fix!
