### ISSUE TITLE
Setting the data loss

### ISSUE THREAD

**Issue by Xtaltec** [lululxvi/deepxde#666]
Hi,

I'm working with a fluid flow dataset comprised solely of the velocity field. My data comes from an imaging modality and therefore has noise. I intend to enforce the Navier Stokes equations on my data to reduce the noise, so I need to combine the pde loss with the data loss, but I'm not sure if I'm implementing the latter correctly. At the moment, I am using `PointSetBC()` but I am not sure if this is how it is supposed to be used. I would also like to know if there is a way to split the training dataset into batches as I have not been able to do it through this function so far.

Kind regards,
Xabier

**Comment by lululxvi** [comment]
Yes, `PointSetBC` is the correct way. The residual points can be used in batches, but the points in `PointSetBC` will not be splited into batches.

**Comment by Xtaltec** [comment]
Okay, thank you very much! Right now, I am defining geometry through `Cuboid` with the following code:

```
# Load data
x,y,z,t,u,v,w,s = read_vti(masking=True,num=training_points)

# Define the geometry-time domain
geom = Cuboid([x.min(),y.min(),z.min()],[x.max(),y.max(),z.max()])
timedomain = dde.geometry.TimeDomain(0.0, 1.0)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

# Soft constrain velocity
xyzt = np.hstack((x,y,z,t))

obs_u = PointSetBC(xyzt, u, component=0)
obs_v = PointSetBC(xyzt, v, component=1)
obs_w = PointSetBC(xyzt, w, component=2)

# Time PDE
data = dde.data.TimePDE(geomtime,Navier_Stokes_3D,[obs_u,obs_v,obs_w],num_domain=nd,num_test=nt)
```

The imaging modality I have is 3D + t, but I have defined a region of interest through segmentation. If I add `anchors` to `dde.data.TimePDE` I understand that the residual point sampling will be performed exclusively in the points defined by the segmentation, correct?

**Comment by Xtaltec** [comment]
Therefore, if I am only interested in the flow within the domain defined by the segmentation I should define `num_domain=0`?

**Comment by Xtaltec** [comment]
Thank you very much for your help!
