### ISSUE TITLE
A small question about "apply_output_transform"

### ISSUE THREAD

**Issue by railleon** [lululxvi/deepxde#695]
I have a small question about "apply_output_transform", i.e. if the output of my model is close to 1e-4, how do I need to transform my output?

`net.apply_output_transform(lambda x, y: y*1e-4)?`

or

`net.apply_output_transform(lambda x, y: y*1e4)?`

**Comment by lululxvi** [comment]
The first.

**Comment by railleon** [comment]
Thank you very much!
