### ISSUE TITLE
Feature engineering

### ISSUE THREAD

**Issue by kaluzaklein** [lululxvi/deepxde#7]
Solving an electrostatics equation such as 
laplacian(phi) = f(x, y, z)
will be easier for the neural network if we are able to supply some engineered inputs such as
1.0/(x^2 + y^2 + z^2)**0.5

Furthermore, suppose we are solving an equation with several interacting electrons which have parameterized positions which could be represented by trainable tf.Variable's:
sum_i 1.0/(x-x_i)**2 + (y-y_i)**2 + (z-z_i)**2

Then, deepxde could be leveraging powerful tools of basis functions as well as neural networks.

Is this currently possible, or can this change be made?

**Comment by lululxvi** [comment]
I am not quite sure if I fully understand. Do you mean that it would be good if we can use more "feature" as the input besides (x, y, z), such as "r = 1/(x2 + y2 + z**2)**0.5". It seems a good idea. Could you provide more details about the equation to make it clear?

**Comment by kaluzaklein** [comment]
For example, if f(x, y, z) is a delta function centered on (0,0,0), then the solution of Poisson's equation is 1/r, where r is the distance from the (0,0,0). If the user could supply 1.0/(x^2 + y^2 + z^2)**0.5 as an input feature that depends on x, y, z, then the neural network could solve the problem with fewer parameters and layers.

If f(x,y,z) is the sum of several delta functions centered on coordinates(x_i, y_i, z_i), then the user could supply the feature  1/((x-x_i)^2 + (y - y_i)^2 + (z-z_i)^2)^0.5 for each value of i. Then, the NN would not have to learn these complicated features. It could learn to solve some other aspect of the problem. This could be useful in a problem with a more complicated PDE.

As for specifying some part of the solution that is parameterized with tf.Variable, that is more complicated, it would be some hybrid between neural network solution and traditional PDE solution.

**Comment by lululxvi** [comment]
Got what you mean, and good suggestion. I think it is possible. Basically we add r as an auxiliary input, and we can rewrite the PDE to make it aware of r. Do you know another example, except delta function, so it is easier to work to test?

**Comment by kaluzaklein** [comment]
I'm working on an code example that solves for a uniformly charged finite radius sphere, including the exact solution. It will be ready soon.

Auxiliary outputs might also be a good idea... this is similar to auxiliary inputs, but the network would not have to learn to leave the auxiliary inputs unperturbed. Each output component could be the neural network output for the component plus the auxiliary output for that component.

**Comment by kaluzaklein** [comment]
Auxiliary outputs would be useful for high-dimensional quantum mechanics problems where exact analytical solutions are known for related(simpler) problems. The NN would only have to learn the part that is not analytically solveable.

**Comment by lululxvi** [comment]
Thank you for introducing me these examples. I will try to add some simple examples, and you are welcome to contribute examples to demonstrate this.

**Comment by kaluzaklein** [comment]
This could help for testing:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

import deepxde as dde

def main():
    pi = 3.14159265358979
    charge = 1.0
    R = 2.0

    def pde(r, phi):
        phi = phi[:, 0]
        x = r[:, 0]
        y = r[:, 1]
        z = r[:, 2]

        # auxiliary inputs: radius^2 and inverse_radius
        radius = tf.sqrt(x*x + y*y + z*z)
        epsilon = 0.000001
        inverse_radius = 1.0 / (epsilon + radius)
        radius_square = radius*radius

        grad_phi = tf.gradients(phi, r, name="Efield")[0]
        dphi_xx = tf.gradients(grad_phi[:, 0], r)[0][:, 0]
        dphi_yy = tf.gradients(grad_phi[:, 1], r)[0][:, 1]
        dphi_zz = tf.gradients(grad_phi[:, 2], r)[0][:, 2]

        volume = 4.0/3.0*pi * R**3
        rho = charge/volume * (1.0 - tf.sigmoid(100.0*(x*x + y*y + z*z - R*R)))

        return -dphi_xx - dphi_yy - dphi_zz - 4.0*pi*rho

    def func(r):
        # r is (N, 3) numpy array for 3-dimensional data
        r2 = np.sum( r*r, axis=1).reshape(-1,1) # (N, 1)
        f = charge / np.sqrt(r2)
        return f
       
    def boundary(x, on_boundary):
        return on_boundary

    geom = dde.geometry.geometry_3d.Cuboid([-5.0, -5.0, -5.0], [5., 5., 5.])

    bc = dde.DirichletBC(geom, func, boundary)

    data = dde.data.PDE(
        geom, 1, pde, bc, num_domain=5000, num_boundary=1000, func=func, num_test=500
    )

    layer_size = [3] + [20]*4 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)
    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    losshistory, train_state = model.train(epochs=5000, display_every=100)

    # scan through (0,0,-Z) to (0,0,+Z) and compare to exact solution
    zs = np.linspace(-5.0, 5.0, 500)
    points = [[0.0, 0.0, z] for z in zs] # list

    def exact_solution(point):
        r = np.sqrt(p[0]*p[0] + p[1]*p[1] + p[2]*p[2])
        if r > R:
            return charge/r
        else:
            return charge/2.0*(3.0/R - r**2.0/R**3.0)
    exact = [exact_solution(p) for p in points] # list
    exact_array = np.array(exact)

    points_array = np.array(points)

    phi = model.predict(points_array)

    fig, ax = plt.subplots()
    ax.plot(points_array[:, 2], phi[:,0], label='model')
    ax.plot(points_array[:, 2], exact, label='exact solution')
    ax.legend(loc='best')
    ax.set_xlabel('r')
    ax.set_ylabel('Phi(r)')
    plt.tight_layout()
    plt.savefig('phi.png')

if __name__ == "__main__":
    main()
```

**Comment by lululxvi** [comment]
Thank you for the code. But the auxiliary inputs `inverse_radius` and `radius_square` seems never used.

**Comment by kaluzaklein** [comment]
The code is for testing the new feature, I have not yet investigated how to implement it.

**Comment by lululxvi** [comment]
#44 is an example of the feature engineering.
