### ISSUE TITLE
L-BFGS freezes with 'tensorflow'

### ISSUE THREAD

**Issue by pescap** [lululxvi/deepxde#701]
### Discussed in https://github.com/lululxvi/deepxde/discussions/700

<div type='discussions-op-text'>

<sup>Originally posted by **pescap** May 25, 2022</sup>
Hi, 
https://github.com/lululxvi/deepxde/blob/4cd2178dfc70e06c629c858870a5f64f622982b6/examples/pinn_forward/Poisson_Lshape.py#L25 freezes when using `tensorflow` as a backend, in CPU and GPU modes.

Example with 5000 ADAM epochs: 
```
'train' took 58.066181 s

Compiling model...
'compile' took 0.019574 s

Training model...

Step      Train loss              Test loss               Test metric
5000      [6.19e-04, 5.82e-04]    [6.10e-04, 5.82e-04]    [] 
```
and then, nothing.

</div>

**Comment by byoungj** [comment]
Hi! It doesn't seem like this is resolved? I've tried running L-BFGS-B with tensorflow backend(i.e. tf2), it I still see the freezing problem.

**Comment by byoungj** [comment]
Actually, this seems like it's not due to "freezing" but actually due to a long single optimization step as documented in line 680 of model.py
```
    def _train_tensorflow_tfp(self):
        # There is only one optimization step. If using multiple steps with/without
        # previous_optimizer_results, L-BFGS failed to reach a small error. The reason
        # could be that tfp.optimizer.lbfgs_minimize will start from scratch for each
        # call.
   ```
