### ISSUE TITLE
Linear elastic Mechanics PDE 

### ISSUE THREAD

**Issue by Ishrak-DataScience** [lululxvi/deepxde#71]
Dear Lululxvi,
I am trying to use deepxde for linear elastic mechanics. I tried to guess PDE formulation from your example. The PDE I want to solve is 
![Linear elastic mechanics](https://user-images.githubusercontent.com/42507424/85984039-84089c80-ba23-11ea-87cc-f7fc35a86236.PNG)
In  deepXDE  language,
![Deepxde linear mechanics](https://user-images.githubusercontent.com/42507424/85984182-c8943800-ba23-11ea-96fc-b917d566f25e.PNG)
Is it the correct way to say it in deepxde?

**Comment by lululxvi** [comment]
Looks good.

**Comment by Ishrak-DataScience** [comment]
Thanks

**Comment by Ishrak-DataScience** [comment]
I am trying to solve for geometry and boundary condition like this given below:
![Geometry](https://user-images.githubusercontent.com/42507424/86188865-ec1dc680-bb7a-11ea-87dd-5155b612756a.png)
![Boundary condition](https://user-images.githubusercontent.com/42507424/86188902-0192f080-bb7b-11ea-8212-5037700af951.PNG)

For geometry I did:
![Geometrydeepxde](https://user-images.githubusercontent.com/42507424/86188977-39019d00-bb7b-11ea-837d-ed751092d627.PNG)
I am thinking about how to implement this type of boundary condition in deepxde. Thanks in advance.

**Comment by Ishrak-DataScience** [comment]
I am trying to make a custom boundary condition to put constrain on stress term. For that, I need the derivative of the solutions and add them. Now I need to add the derivate of the solutions and make a constrain on it and use it as a boundary condition. How do I  make?  Any hint will be appreciated.  Thanks in advance.

I want to set boundary conditions like this.
du/dx+dv/dy =some constant 

![Boundary condition](https://user-images.githubusercontent.com/42507424/88025395-2fae9380-cb6f-11ea-850d-69e91c886733.PNG)

**Comment by lululxvi** [comment]
No need to define a new BC class. Use `OperatorBC`, see "Q: More details and examples about boundary conditions." at FAQ.

**Comment by Ishrak-DataScience** [comment]
Thank you for your help. I am trying to understand how to define boundary conditions in deepXDE for linear elastic mechanics problems. For this purpose, I want to understand this example. 
![example](https://user-images.githubusercontent.com/42507424/88254278-bf7b4b80-ccef-11ea-8a5d-27e99e618845.PNG)
I am guessing the PDE and the analytic solution is 
![Understanding](https://user-images.githubusercontent.com/42507424/88254613-bd65bc80-ccf0-11ea-999d-af474ad47f8d.jpg)
However, I could not understand the boundary conditions. How is it in the general symbol? Since I am new with PDE and deepXDE, it would be a great help if you explain briefly on the boundary conditions of this problem. Thank you.

**Comment by lululxvi** [comment]
There are 4 BCs:
1. `y(0) = 0`
2. `dy/dx (0) = 0`
3. `d^2 y/ dx^2 (1) = 0`
4. `d^3 y/ dx^3 (1) = 0`

**Comment by Ishrak-DataScience** [comment]
Thank you for your explanation.

**Comment by Ishrak-DataScience** [comment]
I am trying on 2D problem described above. The boundary conditions are:
![Boundary condition1](https://user-images.githubusercontent.com/42507424/88451433-9eeaf700-ce91-11ea-96c2-d09470a96a1f.PNG)
and 
![Stress_equlibrium](https://user-images.githubusercontent.com/42507424/88451547-70b9e700-ce92-11ea-975d-d578183a8b09.PNG)

I need a bit of help to understand how to describe the first boundary condition in deepxde.
![TRail1](https://user-images.githubusercontent.com/42507424/88451716-ea060980-ce93-11ea-91e5-31bce882e384.PNG)


Here q=1.5, E, and mu are constants. Is it the right way in deepxde?

**Comment by lululxvi** [comment]
No. The input of the `lambda` function is `X` and `U`, the same as the pde define.

**Comment by Ishrak-DataScience** [comment]
Thank you for your reply. I do not know if I had asked the question correctly. So for clarification, you are saying that the for the PDE from example (Euler beam) and the 2D problem 
![Linear elastic mechanics](https://user-images.githubusercontent.com/42507424/88501171-a6331180-d005-11ea-8e0d-25b48a916a7b.PNG)
with 
![Geometry](https://user-images.githubusercontent.com/42507424/88501204-b9de7800-d005-11ea-981a-436f8dcf1ea2.png)
![Boundary condition1](https://user-images.githubusercontent.com/42507424/88501216-c236b300-d005-11ea-9b8f-6af8caaad0d8.PNG)
has the same 1st boundary condition. Because to me, it is different. 
for the Euler beam problem, it is  dy/dx (0) = 0 and for the 2d linear elastic mechanics it is 
![Boundary condition question](https://user-images.githubusercontent.com/42507424/88502105-78030100-d008-11ea-8d19-7d669f205f41.jpg)

**Comment by lululxvi** [comment]
I am a little confused. Let us forget the Euler beam in the example. What is your current difficulty?

**Comment by Ishrak-DataScience** [comment]
Sorry. I am trying to solve a linear elastic mechanics problem from Prof. George Karniadakis's slide. It has the above geometry and boundary conditions.
![Capture](https://user-images.githubusercontent.com/42507424/88628239-93ddd400-d0e8-11ea-85e6-178b41fa3dc1.PNG)
I am trying to learn to solve PDE with your package. But I am stuck at defining boundary conditions. Can you briefly show how to define the 1st boundary? It would be of great help. Thank you. Sorry for making confused. I am able to define the PDE and geometry.

**Comment by Ishrak-DataScience** [comment]
I mean the stress term 
![Capture](https://user-images.githubusercontent.com/42507424/88762136-905f5100-d1ab-11ea-8a99-78cb6f0575a0.PNG)
How do I define it in deepxde?

**Comment by lululxvi** [comment]
There are a few ways to do it.
- First, if the network output is only `u` and `v`, and you need to find a equation to compute `sigma_x` from `x, y, u, v` and then define `sigma_x = q` in DeepXDE. In DeepXDE, this can be done by 'OperatorBC'.
- Second, if you can not find a equation to compute `sigma_x` from `x, y, u, v`, and then you can expand the network output. The network output should be `u, v, sigma_x, sigma_y`. Now you can define  `sigma_x = q` as a standard Dirichlet BC. But you need add the relationship between `sigma_x` and others into the governing equations.

**Comment by Ishrak-DataScience** [comment]
Thank you very much

**Comment by Ishrak-DataScience** [comment]
![Stress_equlibrium](https://user-images.githubusercontent.com/42507424/89612895-ec1c8f00-d8bb-11ea-99ae-c1c0c4c334e4.PNG)
For boundary conditions 1 to 3, I used this code. Is there any way to define the inner boundary (4th boundary condition):
![Code of boundary](https://user-images.githubusercontent.com/42507424/89613108-68af6d80-d8bc-11ea-8458-e8a0020d0c3a.PNG)
q=1.5

**Comment by lululxvi** [comment]
- Your bc has a bug. The `lambda` function always has three inputs, see the document at https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.boundary_conditions.OperatorBC
- For the inner boundary, it is the same as other boundaries, i.e., you need to define where is the boundary location, and what is the function on that boundary.
