### ISSUE TITLE
Questions on the implementation of transfer learning. 

### ISSUE THREAD

**Issue by PeihuaZhu0516** [lululxvi/deepxde#72]
Dear lulu,

Thank you for your paper on "Extraction of mechanical properties... " and your open source codes.  They provide me a novel approach to investigate mechanical issues. 
    
I have run your code and feel confused about how the transfer learning works. Specifically, I cannot find how the first training influences the second training of multi-fidelity NN in the code of nn.py.   

Thanks for your time and I am looking forward to your reply.

**Comment by lululxvi** [comment]
Could you ask this question in the GitHub of that paper?

**Comment by PeihuaZhu0516** [comment]
ok~
