### ISSUE TITLE
Boundary passing doesn't work for NeumannBC on geometry.Polygon

### ISSUE THREAD

**Issue by MarijanaKrivic** [lululxvi/deepxde#728]
Hi @lululxvi,

First of all, thank you for this amazing library :)

I noticed that with one of the recent updates the NeumannBC stopped working properly. The errors seem to point to the possibility that the boundary array (`X`) isn't being passed at all or it's being passed partially.

I noticed that:
- the same boundary setup works fine for DirichletBC
- the same boundary setup works fine for NeumannBC for geometry.Rectangle

Please have a look at the failing test case example below.

Thanks!

```
"""Backend supported: tensorflow.compat.v1, tensorflow, pytorch"""
import deepxde as dde


def pde(x, y):
    dy_xx = dde.grad.hessian(y, x, i=0, j=0)
    dy_yy = dde.grad.hessian(y, x, i=1, j=1)
    return -dy_xx - dy_yy - 1



geom = dde.geometry.Polygon([[0, 0], [1, 0], [1, -1], [-1, -1], [-1, 1], [0, 1]])
# geom =  dde.geometry.Rectangle(xmin=[0,0], xmax = [1,1])
bc = dde.icbc.NeumannBC(geom, lambda x: 0, lambda X, on_boundary: on_boundary and X[1] == 0)

data = dde.data.PDE(geom, pde, bc, num_domain=1200, num_boundary=120, num_test=1500)
net = dde.nn.FNN([2] + [50] * 4 + [1], "tanh", "Glorot uniform")
model = dde.Model(data, net)

model.compile("adam", lr=0.001)
model.train(epochs=50000)
model.compile("L-BFGS")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```

**Comment by lululxvi** [comment]
Yes, you are right. It is a bug introduced recently. It has been fixed. Please use the latest code. I will release v1.5.1 soon.

**Comment by MarijanaKrivic** [comment]
@lululxvi Thanks for the fix. Same problem with geometry.Triangle tho :)

**Comment by lululxvi** [comment]
I can run without any problem. Can you provide the code to reproduce the error?

**Comment by MarijanaKrivic** [comment]
Hey, sorry, this time it was my bad.

Thanks,
Marijana

**Comment by MarijanaKrivic** [comment]
`"""Backend supported: tensorflow.compat.v1, tensorflow, pytorch"""
import deepxde as dde
import numpy as np
from matplotlib import pyplot as plt 

from shape_func_poly_2 import on_segment


def pde(x, y):
    dy_xx = dde.grad.hessian(y, x, i=0, j=0)
    dy_yy = dde.grad.hessian(y, x, i=1, j=1)
    return -dy_xx - dy_yy - 1

x_debug =[]
y_debug = []
def on_segment(X, x_b, y_b):
    # print("in segment x_b " + str(x_b))
    # print("in segment y_b " + str(y_b))
    # default: rtol=1e-05, atol=1e-08
    rtol=1e-02
    atol=1e-04
    # NOTE: in some cases when the edges are sloped, the tolerance of isclose needs to be more 'liberal' to capture the points
    seg = np.isclose(X[0], x_b[0], rtol=rtol, atol=atol) if np.isclose(x_b[1], x_b[0], rtol=rtol, atol=atol) else np.isclose((X[1] - y_b[0]) - ((y_b[1] - y_b[0]) / (x_b[1] - x_b[0])) * (X[0] - x_b[0]), 0, rtol=rtol, atol=atol)
    # if seg:
    x_debug.append(X[0])
    y_debug.append(X[1])

    return seg


def debug_boundary():
    fig = plt.figure()
    ax = plt.axes()
    ax.plot(x_debug, y_debug, 'k.', ms=3)
    #print(x_debug)
    #print(y_debug)
    plt.show()


#geom = dde.geometry.Polygon([[0, 0], [1, 0], [1, -1], [-1, -1], [-1, 1], [0, 1]])
# geom =  dde.geometry.Rectangle(xmin=[0,0], xmax = [1,1])
p=1
vertices = np.array([[0, 0], [p, 0],  [p/2, p/2]]) # triangle
geom = dde.geometry.Triangle(vertices[0], vertices[1], vertices[2])
bc = dde.icbc.NeumannBC(geom, lambda x: 0, lambda X, on_boundary: on_boundary and on_segment(X, vertices[[1,2],0], vertices[[1,2],1]))
 

data = dde.data.PDE(geom, pde, bc, num_domain=1200, num_boundary=120, num_test=1500)
net = dde.nn.FNN([2] + [50] * 4 + [1], "tanh", "Glorot uniform")
model = dde.Model(data, net)
debug_boundary()

model.compile("adam", lr=0.001)
model.train(epochs=50000)
model.compile("L-BFGS")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)`


Using `debug_boundary()`, I'm plotting all the points that have been passed via `on_boundary` and then selecting the ones that are on the given segment. From the plot you can see that the only first edge of the triangle is actually passed.

**Comment by lululxvi** [comment]
Yes, it is a bug for float32. Just fixed. You can either use float64
```python
dde.config.set_default_float("float64")
```
or use the latest code.
