### ISSUE TITLE
This feels like it shouldn't be an issue :)

### ISSUE THREAD

**Issue by makeclean** [lululxvi/deepxde#73]
I feel super dumb, but how do I access the data in the trained PDE solution im working with your l_shaped domain example and I would like to plot the solution to the PDE from the NN.

**Comment by lululxvi** [comment]
The result is saved to `test.dat` with the first column `x`, the second column `y`, the third column `y_true`, and the fourth column `y_pred`. You can plot the result using any software you like.

**Comment by makeclean** [comment]
I see, sorry I was presuming there would be a builtin matplot lib wrapped function for it. Thanks for the response
