### ISSUE TITLE
More complex geometry

### ISSUE THREAD

**Issue by makeclean** [lululxvi/deepxde#74]
For arguments sake, lets say that i have a geometry composed of 3 different regions, which are say 3 rectangles, each joined by the short edge. 

```
*--------*-------*-------*
|        |       |       |
*--------*-------*-------*
```
In which I have different material properties - say different thermal conductivities, how would i represent this, would i modify the pde function to be aware of the parameters as function of (x,y) or would I modify on boundary? Thanks for your response on my other issue!

**Comment by lululxvi** [comment]
I think it should be OK to use only one rectangle, instead of three rectangles. But if you can provide the details of your problem (PDE, BC etc), I can give you better suggestions.

**Comment by makeclean** [comment]
![Untitled presentation(18)](https://user-images.githubusercontent.com/2439754/86238615-b508de80-bb95-11ea-9048-4019d5267874.png)
Here is the simplest version of what Im trying to achieve

**Comment by lululxvi** [comment]
You only need to define one geometry. The main thing is that when you define the PDE, the coefficient is a function of (x, y). In your case, it is a piecewise constant function, and this requires some TensorFlow grammar like `tf.where`.

**Comment by smurf-17** [comment]
@makeclean could you please share the code for the above problem.

**Comment by makeclean** [comment]
Someone is working on this currently, @alecjervis, Im sure when he's done he wouldnt mind sharing the code - we are having mixed success right now

**Comment by gaboperezayala** [comment]
@makeclean if you solved this issue can you please help me? after scripting my code I'm getting an error "TypeError: 'function' object is not subscriptable" and I don't know how to debug it. 
I have a code similar to the @alecjervis1 but still don't know to make it run properly

**Comment by w-venton** [comment]
Have you all solved this problem? I am also working on a related thermal problem, and I want to know whether the result of the solution after defining the region in this way is satisfactory: **the heat flux at the junction of different materials is continuous, that is, dT/dn is continuous?** If the solved T cannot meet this condition, do we need to set the BC constraint to meet the condition of continuous heat flow at the material junction?
