### ISSUE TITLE
Purpose of num_test argument in TimePDE

### ISSUE THREAD

**Issue by sibyjackgrove** [lululxvi/deepxde#753]
### Discussed in https://github.com/lululxvi/deepxde/discussions/750

<div type='discussions-op-text'>

<sup>Originally posted by **sibyjackgrove** June 20, 2022</sup>
Could you tell me how the `num_test  `argument is used in `TimePDE`? It seems even if I set it to 1 and call `data.test_x.` I still get a large number of test points.</div>

**Comment by amiralizadeh1** [comment]
If you search timePDE in DeepXDE documents, you'll see this:
"The number of functions for testing PDE loss. The testing functions for BCs/ICs are the same functions used for training. If None, then the training functions will be used for testing." 
With this argument set to 1, you'll get 1 point which the NN hasn't been trained on, as well as a large number of points, say 1000, which has already been used for training. Therefore, you're testing set would have 1001 points.
