### ISSUE TITLE
Inverse problem with Neumann BC

### ISSUE THREAD

**Issue by junkaiYANG** [lululxvi/deepxde#76]
Hello, Dear lululxvi,

Thanks for your amazing work on DeepXDE, I am now solving inverse heat transfer problem, with the magnititude of heat flux unknown. but I find that the neural network tends to decrease the heat flux to zero, instead of staying at the right value, do you have any suggestion to fix the problem?

the PDE system is below
![image](https://user-images.githubusercontent.com/42670013/86344055-17c3ae00-bc5a-11ea-999d-df7be7d0dcba.png)

at first I solve the direct problem and get good results, Then I use the results as observation to get the unknown neumann bc. but the inverse neumann bc will not stay at the same figure as that in the direct problem but go down to zero. I also tried to change the loss weights and  add more points around the neumann bc, but not help.
the code is below:

`
# a thermal conductivity problem in a plain 1800mm\*18mm\*900mm
# geometry has been normalized to [0,0,0][1,0.1,0.5]

    from __future__ import absolute_import
    from __future__ import division
    from __future__ import print_function

    import numpy as np
    import tensorflow as tf
    import pandas as pd

    import deepxde as dde
    
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D
    import matplotlib as mpl

    # code for results visualization  
    def Visualization(location, temperature,norm):
    
        x, y, z = location[:,0:1], location[:,1:2], location[:,2:3]
        ax = plt.subplot(111, projection='3d')
        cm = plt.cm.get_cmap('viridis')
        ax.scatter(x,y,z,norm = norm, c = temperature, cmap = cm)
        fig,ax = plt.subplots(figsize=(6, 1))
        fig.subplots_adjust(bottom=0.5)
        fig.colorbar(mpl.cm.ScalarMappable(norm=norm,cmap=cm),
                    cax = ax ,orientation='horizontal'
                    )
        plt.show()

    def main():
        geom = dde.geometry.Cuboid([0,0,0],[1,0.1,0.5])

        #the scale used to normalize coefficients in pde and bc
        X = 1800 #mm
        T = 250 #s

        # Define PDE a transient 3D poisson equation
        def pde(x,u):
            alpha = 17.758 # mm/s thermal diffusivity
            du_x = tf.gradients(u,x,name = 'dydx')[0]
            du_x, du_y, du_z, du_t = du_x[:,0:1], du_x[:,1:2], du_x[:,2:3],du_x[:,3:]
            du_xx = tf.gradients(du_x, x, name = 'dydxx')[0][:,0:1]
            du_yy = tf.gradients(du_y,x)[0][:,1:2]
            du_zz = tf.gradients(du_z,x)[0][:,2:3]
            return du_t -  alpha*(T/X**2) * (du_xx + du_yy + du_zz)

        # 5000W/m^2 on steel with thermal conductivity = 60.5 W/m*K
        def heatflux(x):
            return  5000/(60.5*(1000/X))* np.ones((len(x),1))

        # 5W/m^2*K convection
        def convection(x,y):
            return 5/(60.5*(1000/X)) *(25 * np.ones([len(x),1]) - y)

        #initial condition temperature = 25
        def initial(x):
            return 25*np.ones([len(x),1])

        #the location for heat flux
        def pad(x, on_boundary):
            return on_boundary and x[2]>200/X and x[2]<400/X and np.isclose(x[1],0)

        # location for convection
        def other(x,on_boundary):
            if not pad(x,on_boundary):
                return on_boundary 

        #time span from 0 to 250s
        timedomain = dde.geometry.TimeDomain(0,1)

        #combine the time with rectangle
        geotime = dde.geometry.GeometryXTime(geom, timedomain)

        #specify type of boundary condition
        conv = dde.RobinBC(geotime, convection, other)
        heat = dde.NeumannBC(geotime, heatflux, pad)
        ic = dde.IC(geotime,initial, lambda _, on_initial: on_initial)

        data  = dde.data.TimePDE(
            geotime, 1, pde, 
            [ic, heat, conv], 
            num_domain = 2000, 
            num_boundary=2000,
            num_initial =1000,
            # anchors=temp
            # anchors=anc  
        )
        

        net = dde.maps.ResNet(4,1,50,1, "tanh", "Glorot uniform")

        model = dde.Model(data, net)
        model.compile("adam",lr = 0.001, loss_weights = [1,1e-2,1e-3,1e-2])
        
        earlystop = dde.callbacks.EarlyStopping(
            min_delta = 0.001, patience = 1000
        )
        # variable = dde.callbacks.VariableValue(C, period = 500, filename="variables.dat")
        losshistory, train_state = model.train(epochs = 10000,callbacks=[earlystop],display_every = 250)#, callbacks=[checkpointer])
        dde.saveplot(losshistory, train_state, issave = True, isplot=True)

        # visualize the results
        x_test = geom.uniform_points(2000)
        x_test = np.hstack([x_test,np.full((len(x_test),1),1)])
        y = model.predict(x_test)
        print('model results')
        norm_m = mpl.colors.Normalize(vmin=min(y), vmax=max(y))
        Visualization(x_test,y,norm_m)

        
        #solve inverse pronlem
        #use the results above to simulate sensor data on surface of the plain
        x_observe = geotime.random_boundary_points(1000)
        y_observe = model.predict(x_observe)

        norm_m = mpl.colors.Normalize(vmin=min(y_observe), vmax=max(y_observe))
        Visualization(x_observe,y_observe,norm_m)
        #%%
        ptset = dde.bc.PointSet(x_observe)

        C = tf.Variable(20.0)#the variable is supposed to be 5000/(60.5*(1000/1800))/10 = 14.87
        def heatflux_inv(x):
            return 10*C*np.ones((len(x),1))

        ptset = dde.bc.PointSet(x_observe)
        observe = dde.DirichletBC(geotime, ptset.values_to_func(y_observe), lambda x, _: ptset.inside(x))
        heat_inv = dde.NeumannBC(geotime, heatflux_inv, pad)

        #add more points around heat flux, where the temperature gradient changes fast
        temp = geotime.random_points(4000)
        temp = temp[temp[:,2]>100/X]
        temp = temp[temp[:,2]<500/X]
        temp = temp[:min(len(temp),1000)]
        temp2 = geotime.random_boundary_points(10000)
        temp2 = temp2[temp2[:,2]>200/X]
        temp2 = temp2[temp2[:,2]<450/X]
        anc = temp2[:min(len(temp2),2000)]

        data2  = dde.data.TimePDE(
            geotime, 1, pde, 
            [ic, heat_inv, conv, observe], 
            num_domain = 2000, 
            num_boundary=2000,
            num_initial =1000,
            anchors=np.vstack([x_observe,anc,temp])
        )
        model = dde.Model(data2, net)

        model.compile("adam",lr = 0.001, loss_weights = [1,1e-2,1e-3,1e-2,1])

        variable = dde.callbacks.VariableValue(C, period = 500, filename="variables.dat")
        losshistory, train_state = model.train(epochs = 10000, display_every = 250, callbacks=[variable])
        dde.saveplot(losshistory, train_state, issave = True, isplot=True)
        
       # visualization
        print('model results')
        y = model.predict(x_observe)
        norm = mpl.colors.Normalize(vmin=min(y_observe), vmax=max(y_observe))
        Visualization(x_observe,y_observe,norm)

        print('bias')
        bias = y-y_observe
        norm5 = mpl.colors.Normalize(vmin=min(bias), vmax=max(bias))
        Visualization(x_observe,bias,norm5)

    if __name__ == "__main__":
        main()

the change of the magnititude of Neumann bc:
![image](https://user-images.githubusercontent.com/42670013/86346902-dcc37980-bc5d-11ea-8ca9-2c1025e58497.png)

the loss of inverse problem is
![Figure_1](https://user-images.githubusercontent.com/42670013/86350716-66297a80-bc63-11ea-88b9-44936b8c1d54.png)

Thank you for your help in advance.

**Comment by lululxvi** [comment]
Could you try to train for more iterations?

**Comment by junkaiYANG** [comment]
Thank you for your quick response, I have tried to train 26000 epochs, the variable has turned back, 
![image](https://user-images.githubusercontent.com/42670013/86473965-2a191700-bd42-11ea-859d-67672f46c8ff.png)

and I occasionaly find if I decrease the points in Neumann condition, it can convergence faster within 100000 epochs
![image](https://user-images.githubusercontent.com/42670013/86473884-03f37700-bd42-11ea-8405-45c0fe332186.png)

I cannot figure out why less points can conversely get faster convergence? Maybe the observation has now larger weights in training and can influence the value of unknown boundary condition more significantly?

**Comment by lululxvi** [comment]
It is interesting to see the faster convergence with less BC points. I am not sure why this happened, and some investigation is required.

**Comment by AlirezaPa** [comment]
Thank you so much @lululxvi for your library. My question could be related to this @junkaiYANG discussion. My following code is an inverse problem to identify the wave velocity C(x) in a semi-infinite domain. So, the code updates u(x,t) and C(x) in each iteration.  My concern is whether the values of C in Neumann BC command are updated in each iteration or not. Because, in def pde(x,y), I introduced C=y[:,1:2] but Neumann BC did not know this value, and I got an error "NameError: name 'C' is not defined". Then I wrote the line: C = dde.Variable(0.5) above that as initial values. So I do not know the Neumann BC command works well or not because the results are funny: u(x,t) is perfect and is matched to the exact solution, but the values of C(x) is very poor. Would you please look at my code and let me know whether my code is fine especially Neumann BC command with considering C = dde.Variable(0.5)? 
Thank you for your time.

import deepxde as dde
import numpy as np
from deepxde.backend import tf

def pde(x, y):
       u, C = y[:, 0:1], y[:, 1:2]
       du_tt = dde.grad.hessian(u, x, i=1, j=1)
       du_x = dde.grad.jacobian(u, x, j=0)
       du_xx = dde.grad.jacobian((C ** 2)*du_x, x, j=0)    
       return du_tt - du_xx

def boundary_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], 0)

geom = dde.geometry.Interval(0, 1)
timedomain = dde.geometry.TimeDomain(0, 5)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

C = dde.Variable(0.5)
bc = dde.NeumannBC(geomtime, lambda x: np.sin(x[:, 1:])/(C*C), boundary_l)

ic_1 = dde.IC(geomtime, lambda x: 0, lambda _, on_initial: on_initial)
ic_2 = dde.OperatorBC(geomtime, lambda x, y, _: dde.grad.jacobian(y, x, i=0, j=1), lambda x, _: np.isclose(x[1], 0))

observe_x = np.vstack((np.full((5001), 0.00), np.linspace(0, 5, num=5001))).T
data_exact = np.loadtxt('/content/gdrive/MyDrive/Colab Notebooks/Thesis-Examples/sint-c1-5s-20m.txt')
u_ex = data_exact[:,1]
u_ex1 = u_ex.reshape(5001,1)
observe_u = dde.icbc.PointSetBC(observe_x, u_ex1, component=0)

data = dde.data.TimePDE(geomtime, pde, [bc, ic_1, ic_2, observe_u], num_domain=800, num_boundary=100, num_initial=100, anchors=observe_x, num_test=10000)

net = dde.nn.FNN([2] + [10, 10] * 3 + [2], "tanh", "Glorot normal")

net.apply_output_transform(
lambda x, y : tf.concat(
[y[:, 1:2] , tf.layers.dense(tf.layers.dense(tf.layers.dense(tf.layers.dense(x[:,0:1], 10, tf.nn.tanh), 10, tf.nn.tanh), 10, tf.nn.tanh), 1, None)], axis = 1) )

model = dde.Model(data, net)
model.compile("L-BFGS", loss_weights=[0.1, 10, 10, 10, 10])

losshistory, train_state = model.train(epochs=10000)
dde.saveplot(losshistory, train_state, issave=True, isplot=True)

**Comment by lululxvi** [comment]
`dde.NeumannBC` doesn't allow trainable value.

**Comment by rodrigogdourado** [comment]
@junkaiYANG Hello, I'm working on IHTP in nonlinear problems. I think thermal conductivity is the most difficult parameter to estimate, because the thermal sensitivity is very low. Maybe you would like to discuss with me about inverse heat conduction problems using neural networks.

**Comment by rodrigogdourado** [comment]
Dr. @lululxvi  I'm trying to reproduce a similar boudary condition than @junkaiYANG, but I'm getting the error: 

  File C:\DOURADO\PYTHON_TREINAMENTO\3D_aquecedor.py:100 in <module>
    data = dde.data.TimePDE(

  File ~\anaconda3\lib\site-packages\deepxde\data\pde.py:287 in __init__
    super().__init__(

  File ~\anaconda3\lib\site-packages\deepxde\data\pde.py:111 in __init__
    self.train_next_batch()

  File ~\anaconda3\lib\site-packages\deepxde\utils\internal.py:37 in wrapper
    return func(self, *args, **kwargs)

  File ~\anaconda3\lib\site-packages\deepxde\data\pde.py:160 in train_next_batch
    self.train_x = self.bc_points()

  File ~\anaconda3\lib\site-packages\deepxde\utils\internal.py:37 in wrapper
    return func(self, *args, **kwargs)

  File ~\anaconda3\lib\site-packages\deepxde\data\pde.py:247 in bc_points
    x_bcs = [bc.collocation_points(self.train_x_all) for bc in self.bcs]

  File ~\anaconda3\lib\site-packages\deepxde\data\pde.py:247 in <listcomp>
    x_bcs = [bc.collocation_points(self.train_x_all) for bc in self.bcs]

  File ~\anaconda3\lib\site-packages\deepxde\icbc\boundary_conditions.py:50 in collocation_points
    return self.filter(X)

  File ~\anaconda3\lib\site-packages\deepxde\icbc\boundary_conditions.py:47 in filter
    return X[self.on_boundary(X, self.geom.on_boundary(X))]

IndexError: arrays used as indices must be of integer (or boolean) type

Maybe you could help me, please. Here is the code:

import deepxde as dde
import tensorflow as tf
import numpy as np

#%% parametros

Lx = 1;
Ly = 1;
Lz = 0.4;
Laqc = 0.4;
time =1;
q = 1;
T0 = 0;
k = 0.4;
rho = 1;
cp = 1;
alpha = k/(rho*cp)

#%% domain
geom = dde.geometry.Cuboid([0,0,0], [Lx,Ly,Lz])
timedomain = dde.geometry.TimeDomain(0, time)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

#%% PDE and BC
def pde(x,y):
    dy_xx = dde.grad.hessian(y, x, i=0,j=0)
    dy_yy = dde.grad.hessian(y, x, i=1,j=1)
    dy_zz = dde.grad.hessian(y, x, i=2,j=2)
    dy_t = dde.grad.jacobian(y, x, i=0,j=3)
    return dy_t-alpha*(dy_xx+dy_yy+dy_zz)

def boundary_q(x, on_boundary):
    return on_boundary and np.isclose(x[2],Lz) and x[0]<=Laqc and x[1]<=Laqc

def boundary_insulated(x, on_boundary):
    if not boundary_q(x, on_boundary):
        return on_boundary

data = dde.data.TimePDE(
    geomtime,
    pde,
    [bc_q,bc_iso,ic],
    num_domain=3000,
    num_boundary=1000,
    num_initial=1000,
    num_test=None,
    )

layer_size = [4]+[80]*2+[1]
net = dde.nn.RNN(layer_size,"tanh","Glorot normal")
#net = dde.nn.FNN(layer_size,"tanh","Glorot normal")
model = dde.Model(data,net)

model.compile("adam",lr=0.1e-3,loss_weights=[1,1,1,1])
losshistory, train_state = model.train(iterations=100000)

**Comment by lululxvi** [comment]
Could you first figure out which IC or BC makes the error?
