### ISSUE TITLE
About plotting the best result after training

### ISSUE THREAD

**Issue by ZSTanone** [lululxvi/deepxde#779]
Hi，Dr Lu @lululxvi 
Recently I used the “2 steps training” method to train my PINN to solve inverse problem. However，the final loss was bigger than the first train，although I can get the right prediction， the best model provided by software was reminded in first train epoch，so the `dde.saveplot`  can‘t plot the solution I want. I wonder if I can get the best model during the second train.
![image](https://user-images.githubusercontent.com/103397565/177126517-4c9acf66-9fe7-42f8-8a5a-2a0bd8147031.png)
Actually I think the max_epoch is bigger enough to get the solution. Can you give me some advice ,thanks a lot!!!!

**Comment by lululxvi** [comment]
Set `disregard_previous_best=True`, see https://deepxde.readthedocs.io/en/latest/modules/deepxde.html#deepxde.model.Model.train
