### ISSUE TITLE
Inhomogeneous Heat Equations

### ISSUE THREAD

**Issue by yangheart** [lululxvi/deepxde#78]
Hi Lu,

Thank you for your amazing works in numerical PDE. I am wondering whether this package can solve inhomogeneous heat equations. I tried an example like below:
                                                                            u_t-u_xx=-exp(-2t)*sinx,        0<x<pi, 0<t<1
                                                                            u(0,t)=u(pi,t)=0,
                                                                            u(x,0)=sinx.
But it did not work.  The problem is "NotImplementedError: Cannot convert a symbolic Tensor (mul:0) to a numpy array."
I have studied many examples provided by you, but none of them involves the inhomogenous term, like:"-exp(-2t)*sinx" in the above example. Could you help me figure it out?

Thank you in advance!

**Comment by lululxvi** [comment]
Do you use `tf.exp(-2*t) * tf.sin(x)`?

**Comment by yangheart** [comment]
Hi Lu,
Thanks, it works. But I have a further question on this issue. What if the right hand side function is not included in the Tensorflow package? For example, if the right hand side is a smoothed function based on some experimental data, then how to deal with this situation?

**Comment by lululxvi** [comment]
TensorFlow has quite a lot of math functions, and also support `if` statements, so basically you can construct your functions using these basic functions.
