### ISSUE TITLE
Is this the correct syntax for writing this equation ? 

### ISSUE THREAD

**Issue by athtareq** [lululxvi/deepxde#781]
Hello, I need to write the equation $u_t - div(\|\nabla u\|^{p-2}\nabla u)=f$ with u having two space variables and a time variable

Here's the code I used, is it correct ?

```
def pde (x , y) :
    grad_y = tf . gradients (y , x ) [0]
    dy_x , dy_y , dy_t = grad_y [: , 0:1] , grad_y [: , 1:2],grad_y [: , 2:]
    dy_xx = tf . gradients ( dy_x , x ) [0][: , 0:1]
    dy_yy = tf . gradients ( dy_y , x ) [0][: , 1:2]
    p_lap = tf.gradients(tf.abs(grad_y[: , 0:2])**(p-2)*grad_y[: , 0:2],x)[0]
    return dy_t - (p_lap[: , 0:1]+p_lap[: , 1:2]) - func(x[: , 0:1],x[: , 1:2],x[: , 2:])


```

Thanks !

**Comment by tsarikahin** [comment]
I think first you have to write them in tensor notation. I don't know which equation that is but if we assume that u is a vector grad(u) will be a 2D tensor. So you need a tensor product for that. But I think it is the norm, not the absolute value which makes more sense to me.  If this the case:

I assume you have two space and time as the input (order x_coor, y_coor and t) and u (1 output)

def pde(x,y):
     u_x = dde.grad.jacobian(y, x, i=0, j=0) # derivative of the the output wrt first input (x_coor)
     u_y = dde.grad.jacobian(y, x, i=0, j=1) # derivative of the the output wrt second input (y_coor)
     u_t = dde.grad.jacobian(y, x, i=0, j=2)  # derivative of the the output wrt third input (time)

     norm_gradu = tf.math.sqrt(tf.norm(u_x)**2 + tf.norm(u_x)**2 + tf.norm(u_x)**2)**(p-2) # It should be scalar

     u_x_norm_grad = u_x * norm_gradu
     u_y_norm_grad = u_y * norm_gradu
     u_t_norm_grad = u_t * norm_gradu
    
     u_x_norm_grad_x = dde.grad.jacobian(u_x_norm_grad, x, i=0, j=0)
     u_y_norm_grad_y = dde.grad.jacobian(u_y_norm_grad, x, i=0, j=1)
     u_t_norm_grad_t  = dde.grad.jacobian(u_t_norm_grad, x, i=0, j=2)

     return u_x_norm_grad_x + u_y_norm_grad_y + u_t_norm_grad_t
     
I am not so sure btw

**Comment by athtareq** [comment]
@tsarikahin seems about right, thank you very much !
