### ISSUE TITLE
Coefficients of PDE as points in grid

### ISSUE THREAD

**Issue by ForumWhiner** [lululxvi/deepxde#79]
Thank you for the great package. I have an economic problem to solve that is of the form below:
u_t + diffusion * u_xx + advection * u_x + linearTerm * u = 0; x=[0,1], t=[0,1]. 
Neumann condition: u_x=0 at x=0 and x=1
Initial condition: u=u0 at (x,t=0)

To clarify, x is the space domain and t is the time domain. The coefficients of PDE (diffusion, advection, and linear) are very complicated functions that are solved using fixed point and I have a vector of points as solutions. Given these coefficients, it is of interest to solve the PDE and obtain u as function of x and t. For example, the coefficients are (200 x 1) vector for 200 values of x discretized between 0 and 1. The initial value u0 is also a vector (200 x 1). Is there a way to include such discretized function values as coefficients and initial conditions? If some parts of code needs to be changed, kindly let me know. 

I have already solved it using implicit finite difference scheme but would like to solve using deepxde and compare the results. Thanks a ton!

**Comment by lululxvi** [comment]
Yes, this is doable in DeepXDE, but it requires some effort. Mainly, you need implement a continuous version of the discrete functions.

- For the IC, it is straightforward. You just need to implement a continuous function using numpy/scipy, e.g., using `scipy.interpolate.interp1d`.
- For the coefficients of PDE, the continuous function should be supported by TensorFlow. It seems that TensorFlow doesn't have a interpolate function, but there is `tfp.math.interp_regular_1d_grid`, which could be used (but I am not sure). It is also possible to use `tf.where` directly to manually construct a continuous function, e.g., piecewise linear function, but this requires some effort.

If you don't require to represent these functions exactly, then you can approximate them, e.g., using some polynomial series. This is easy for coding, but will loss some accuracy depending on how/what series you use.

**Comment by ForumWhiner** [comment]
> Yes, this is doable in DeepXDE, but it requires some effort. Mainly, you need implement a continuous version of the discrete functions.
> 
> * For the IC, it is straightforward. You just need to implement a continuous function using numpy/scipy, e.g., using `scipy.interpolate.interp1d`.
> * For the coefficients of PDE, the continuous function should be supported by TensorFlow. It seems that TensorFlow doesn't have a interpolate function, but there is `tfp.math.interp_regular_1d_grid`, which could be used (but I am not sure). It is also possible to use `tf.where` directly to manually construct a continuous function, e.g., piecewise linear function, but this requires some effort.
> 
> If you don't require to represent these functions exactly, then you can approximate them, e.g., using some polynomial series. This is easy for coding, but will loss some accuracy depending on how/what series you use.

Great, thanks. Interpolation idea sounds good. Why does it only work for initial condition? Is there a way for me to tweak the code so that coefficients can also be passed as interpolated functions using scipy? Many thanks!

**Comment by yangheart** [comment]
> Yes, this is doable in DeepXDE, but it requires some effort. Mainly, you need implement a continuous version of the discrete functions.
> 
> * For the IC, it is straightforward. You just need to implement a continuous function using numpy/scipy, e.g., using `scipy.interpolate.interp1d`.
> * For the coefficients of PDE, the continuous function should be supported by TensorFlow. It seems that TensorFlow doesn't have a interpolate function, but there is `tfp.math.interp_regular_1d_grid`, which could be used (but I am not sure). It is also possible to use `tf.where` directly to manually construct a continuous function, e.g., piecewise linear function, but this requires some effort.
> 
> If you don't require to represent these functions exactly, then you can approximate them, e.g., using some polynomial series. This is easy for coding, but will loss some accuracy depending on how/what series you use.


I have a similar question. In my case, the coefficients of PDE depend on both x and t and do not have specific formulas. So for example, they are (200 x 200) vector for 200 values of x and 200 values of t discretized between 0 and 1, then is there a way to construct a continuous function (or piecewise polynomial) to approximate such coefficients in DeepXDE ?

**Comment by lululxvi** [comment]
numpy/scipy only works for initial/boundary conditions, and doesn't work for defining the PDE, because in the current implementation, BC/IC takes the numpy array as inputs, while PDE takes the tensorflow array as inputs, and numpy/scipy cannot handle tensorflow array.

It is possible to modify the code to support using numpy/scipy to define PDE coefficients.
- In deepxde/data/pde.py, line 48, use the following
```python
f = self.pde(model.net.inputs, outputs, self.train_x)
```
- Then, when defining the PDE loss,
```python
def pde(x, y, x_np):
    # x and y are tf array, which should be used to compute gradients, etc
    # x_np is np array, which should be used to compute the coefficients
```

Let me know if this works.

**Comment by yangheart** [comment]
Dear Lu,

Thank you for your suggestions. I have tried what you said, but it still has some problems. For your convenience, I copied the program errors shown in the report below. If you need my codes, please let me know. I really appreciated what you have done!

Traceback (most recent call last):
  File "spde2.py", line 131, in <module>
    main()
  File "spde2.py", line 126, in main
    losshistory, train_state = model.train(epochs=80000, callbacks=[variable])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/utils.py", line 51, in wrapper
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/model.py", line 146, in train
    self._test(uncertainty)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/model.py", line 254, in _test
    self.train_state.loss_train, self.train_state.y_pred_train = self.sess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2652,1] vs. [7762,1]
	 [[node mul_4 (defined at spde2.py:74) ]]

Original stack trace for 'mul_4':
  File "spde2.py", line 131, in <module>
    main()
  File "spde2.py", line 122, in main
    model.compile("adam", lr=0.001)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/utils.py", line 51, in wrapper
    result = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/model.py", line 82, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deepxde/data/pde.py", line 48, in losses
    f = self.pde(model.net.inputs, outputs,self.train_x)
  File "spde2.py", line 74, in pde
    rhs =k_pf*r**1.5*(5*np.pi)-k_nf*r*(c+k_c*9)+D*dr_xx
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 984, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1283, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6091, in mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
    ret = Operation(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by lululxvi** [comment]
You are using the DeepXDE installed in the system. Uninstall the DeepXDE, and use the following:
```python
import sys
sys.path.insert(0, "path-to-deepxde")
import deepxde as dde
```
"path-to-deepxde" is the path to the DeepXDE which you modified.

**Comment by yangheart** [comment]
Dear Lu, 

I tried what you said, but it still showed the same problem.  For your convenience, I modified your code, an example of Burger's equation by adding a forcing term "c(x,t)". This function c(x,t) is obtained by interpolating (smoothing) the discretized data. Here is the code.


from __future__ import absolute_import
from __future__ import division
from __future__ import print_function 

import numpy as np
from scipy import interpolate
from scipy.interpolate import make_interp_spline, BSpline
import scipy as sp
import scipy.interpolate as interp
import sys
sys.path.insert(0,"/Users/sichenchen/deepxde/")
import deepxde as dde
from deepxde.backend import tf


def gen_testdata():
    data = np.load("dataset/Burgers.npz")
    t, x, exact = data["t"], data["x"], data["usol"].T
    xx, tt = np.meshgrid(x, t)
    X = np.vstack((np.ravel(xx), np.ravel(tt))).T
    y = exact.flatten()[:, None]
    return X, y

def main():
    def sol_C(x):                                                #This is an interpolation function
        x1=np.linspace(-1,1,21)
        t1=np.linspace(0,1,11)
        X, T = np.meshgrid(x1, t1)
        X= np.reshape(X, (-1, 1))
        T = np.reshape(T, (-1, 1))
        S=np.hstack((X, T))
        y=S[:,0]**2+S[:,1]**2
        Y = np.reshape(y, (-1, 1))
        spline = sp.interpolate.Rbf(S[:,0],S[:,1],Y,function='thin_plate',smooth=0, episilon=0)
        result=spline(x[:,0:1],x[:,1:])
        return result

    def pde(x, y,x_np):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:2]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        c=sol_C(x_np)
        return dy_t + y * dy_x - 0.01 / np.pi * dy_xx-c

    geom = dde.geometry.Interval(-1, 1)
    timedomain = dde.geometry.TimeDomain(0, 0.99)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(
        geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: on_boundary
    )
    ic = dde.IC(
        geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
    )

    data = dde.data.TimePDE(
        geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160
    )
    net = dde.maps.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3)
    model.train(epochs=15000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()
## end 


In the code, I defined sol_C as an interpolation function, which can make it easy to enter the experimental data. Also, you can see that I have extended "pde" to include 3 variables. However, it came out the similar problems. Here are the errors.


Traceback (most recent call last):
  File "inverseself.py", line 74, in <module>
    main()
  File "inverseself.py", line 65, in main
    model.train(epochs=15000)
  File "/Users/sichenchen/deepxde/deepxde/utils.py", line 51, in wrapper
    result = f(*args, **kwargs)
  File "/Users/sichenchen/deepxde/deepxde/model.py", line 146, in train
    self._test(uncertainty)
  File "/Users/sichenchen/deepxde/deepxde/model.py", line 277, in _test
    self.train_state.loss_test, self.train_state.y_pred_test = self.sess.run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2780,1] vs. [3020,1]
	 [[node sub (defined at inverseself.py:45) ]]

Original stack trace for 'sub':
  File "inverseself.py", line 74, in <module>
    main()
  File "inverseself.py", line 64, in main
    model.compile("adam", lr=1e-3)
  File "/Users/sichenchen/deepxde/deepxde/utils.py", line 51, in wrapper
    result = f(*args, **kwargs)
  File "/Users/sichenchen/deepxde/deepxde/model.py", line 82, in compile
    self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
  File "/Users/sichenchen/deepxde/deepxde/data/pde.py", line 48, in losses
    f = self.pde(model.net.inputs, outputs, self.train_x)
  File "inverseself.py", line 45, in pde
    return dy_t + y * dy_x - 0.01 / np.pi * dy_xx-c
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 984, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 10102, in sub
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3319, in _create_op_internal
    ret = Operation(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

##end



For my understanding, the problems come from the shape: 
Incompatible shapes: [2780,1] vs. [3020,1]
	 [[node sub (defined at inverseself.py:45) ]]

Could you help me to figure it out? Thank you so much!

**Comment by lululxvi** [comment]
I have modified the source code. You can download the updated code (not install through pip or conda).

**Comment by ForumWhiner** [comment]
Thanks a ton. It works now! I will close the issue. 

An unrelated question: Could you please let me know which tools did you use to draw figure 1 (schematic for pinn architecture diagram) from your paper? Thanks.

**Comment by lululxvi** [comment]
It would be great if you can either share me the code or open a pull request. (just a simple  problem to demonstrate the idea.)
I use Tikz.

**Comment by yangheart** [comment]
Dear Lu,

Sorry for the late response. It works pretty well. I tried a simple example by adding a forcing term in Burger's equation. This forcing term is obtained by interpolating (smoothing) the external data. I really appreciate your works and help. This problem has disturbed me for a long time, but now I am really happy to settle it down.

Here is my code, in which the interpolating function is called sol_C and the forcing term in the pde function is denoted by c.

I hope you stay safe and well!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
from scipy import interpolate
from scipy.interpolate import make_interp_spline, BSpline
import scipy as sp
import scipy.interpolate as interp
import pandas as pd
import sys
sys.path.insert(0,"/Users/sichenchen/Desktop/research/deepxde")
import deepxde as dde
from deepxde.backend import tf


def gen_testdata():
    data = np.load("dataset/Burgers.npz")
    t, x, exact = data["t"], data["x"], data["usol"].T
    xx, tt = np.meshgrid(x, t)
    X = np.vstack((np.ravel(xx), np.ravel(tt))).T
    y = exact.flatten()[:, None]
    return X, y


def main():
    def sol_C(x):
        x1=np.linspace(-1,1,21)
        t1=np.linspace(0,1,21)
        X, T = np.meshgrid(x1, t1)
        X= np.reshape(X, (-1, 1))
        T = np.reshape(T, (-1, 1))

        S=np.hstack((X, T))
        y= pd.read_csv("/Users/sichenchen/Desktop/research/pollenpy/example.csv", index_col = 0)
        Y = np.reshape(y, (-1, 1))
        spline = sp.interpolate.Rbf(S[:,0],S[:,1],Y,function='thin_plate',smooth=0, episilon=0)
        result=spline(x[:,0:1],x[:,1:])
        return result

    def pde(x, y,X):
        dy_x = tf.gradients(y, x)[0]
        dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:2]
        dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
        c=sol_C(X)
        return dy_t + y * dy_x - 0.01 / np.pi * dy_xx-c

    geom = dde.geometry.Interval(-1, 1)
    timedomain = dde.geometry.TimeDomain(0, 0.99)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc = dde.DirichletBC(
        geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: on_boundary
    )
    ic = dde.IC(
        geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
    )

    data = dde.data.TimePDE(
        geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160
    )
    net = dde.maps.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3)
    model.train(epochs=15000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)




if __name__ == "__main__":
    main()
##end

**Comment by yangheart** [comment]
Dear Lu,

Sorry for the late response. It works pretty well. I tried a simple example by adding a forcing term in Burger's equation. This forcing term is obtained by interpolating (smoothing) the external data. I really appreciate your works and help. This problem has disturbed me for a long time, but now I am really happy to settle it down.

Here is my code, in which the interpolating function is called sol_C and the forcing term in the pde function is denoted by c.

I hope you stay safe and well!

from future import absolute_import
from future import division
from future import print_function

import numpy as np
from scipy import interpolate
from scipy.interpolate import make_interp_spline, BSpline
import scipy as sp
import scipy.interpolate as interp
import pandas as pd
import sys
sys.path.insert(0,"/Users/sichenchen/Desktop/research/deepxde")
import deepxde as dde
from deepxde.backend import tf

def gen_testdata():
          data = np.load("dataset/Burgers.npz")
          t, x, exact = data["t"], data["x"], data["usol"].T
          xx, tt = np.meshgrid(x, t)
          X = np.vstack((np.ravel(xx), np.ravel(tt))).T
          y = exact.flatten()[:, None]
          return X, y

def main():
  def sol_C(x):
    x1=np.linspace(-1,1,21)
    t1=np.linspace(0,1,21)
    X, T = np.meshgrid(x1, t1)
    X= np.reshape(X, (-1, 1))
    T = np.reshape(T, (-1, 1))

    S=np.hstack((X, T))
    y= pd.read_csv("/Users/sichenchen/Desktop/research/pollenpy/example.csv", index_col = 0)
    Y = np.reshape(y, (-1, 1))
    spline = sp.interpolate.Rbf(S[:,0],S[:,1],Y,function='thin_plate',smooth=0, episilon=0)
    result=spline(x[:,0:1],x[:,1:])
    return result

def pde(x, y,X):
    dy_x = tf.gradients(y, x)[0]
    dy_x, dy_t = dy_x[:, 0:1], dy_x[:, 1:2]
    dy_xx = tf.gradients(dy_x, x)[0][:, 0:1]
    c=sol_C(X)
    return dy_t + y * dy_x - 0.01 / np.pi * dy_xx-c

geom = dde.geometry.Interval(-1, 1)
timedomain = dde.geometry.TimeDomain(0, 0.99)
geomtime = dde.geometry.GeometryXTime(geom, timedomain)

bc = dde.DirichletBC(
    geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: on_boundary
)
ic = dde.IC(
    geomtime, lambda x: -np.sin(np.pi * x[:, 0:1]), lambda _, on_initial: on_initial
)

data = dde.data.TimePDE(
    geomtime, pde, [bc, ic], num_domain=2540, num_boundary=80, num_initial=160
)
net = dde.maps.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")
model = dde.Model(data, net)

model.compile("adam", lr=1e-3)
model.train(epochs=15000)
model.compile("L-BFGS-B")
losshistory, train_state = model.train()
dde.saveplot(losshistory, train_state, issave=True, isplot=True)
if name == "main":
main()

##end

**Comment by helonayala** [comment]
For anyone interested on how to implement forcing terms or any other time-dependent data in your PDE / ODE see

https://github.com/lululxvi/deepxde/blob/master/examples/Lorenz_inverse_forced_Colab.ipynb
