### ISSUE TITLE
Is the DeepXDE scale-dependent?

### ISSUE THREAD

**Issue by spartan44L** [lululxvi/deepxde#794]
Hi, is the DeepXDE scale-dependent? I tried to use DeepXDE for a simple 1-D forward problem like this one dy^2/dx^2 = 0 with two Dirichlet Boundary. I found that for a small domain [0, 1] DeepXDE gives good results without using data inside the domain from the reference solution. But, it did not predict a good result with larger domain [0, 5], [0, 10], or [0, 100]. Even for the 1-D domain [0, 100], DeepXDE could not predict good result with 500 data from the reference solution. Following are simulations of some cases to make you understand my problem.

I also would like to know, can we use the installed DeepXDE package for domain discretization? So far, my understanding is that the user can only give geometry input and DeepXDE discretize the domain or find coordinated for prediction based on boundary coordinates and input data # from the reference solution.

**Case-1:**
Domain = [0, 1]
data = dde.data.PDE(geom, pde, bc, 0, 2, solution=func, num_test= 100)
![image](https://user-images.githubusercontent.com/67887543/178613566-9660d60f-50a0-461d-b24e-e8514f5ae466.png)

**Case-2:**
Domain = [0, 5]
data = dde.data.PDE(geom, pde, bc, 0, 2, solution=func, num_test= 100)
![image](https://user-images.githubusercontent.com/67887543/178613586-19e6d8c7-9315-4e9e-9fa1-4099a5a3a101.png)

**Case-3:**
Domain = [0, 5]
data = dde.data.PDE(geom, pde, bc, 5, 2, solution=func, num_test= 100)
![image](https://user-images.githubusercontent.com/67887543/178613604-a2ca545e-1245-4840-b495-7165cc2a1d79.png)

**Case-4:**
Domain = [0, 100]
data = dde.data.PDE(geom, pde, bc, 0, 2, solution=func, num_test= 100)
![image](https://user-images.githubusercontent.com/67887543/178613634-fd28cf75-0bc4-4f21-b7d3-b346eca12ece.png)

**Case-5:**
Domain = [0, 100]
data = dde.data.PDE(geom, pde, bc, 500, 2, solution=func, num_test= 100)
![image](https://user-images.githubusercontent.com/67887543/178613651-b12c68e0-a00e-41cf-acfd-9701ab626a99.png)

**Comment by lululxvi** [comment]
https://github.com/lululxvi/deepxde/discussions/793
