### ISSUE TITLE
Train loss converges (<1e-4) but test loss doesn't (>1e-1)

### ISSUE THREAD

**Issue by athtareq** [lululxvi/deepxde#799]
Hello, I run into this "issue" for some models, is it okay ? If not, how to fix it ? I have already tried to read the threads in the FAQ but to no avail. Batch training, and loss weights seem to work for some problems but are there any other workarounds ? Thanks !

**Comment by lululxvi** [comment]
If there is no bug in your code, then it seems over-fitting.

**Comment by athtareq** [comment]
@lululxvi thanks for your reply ! Any recommendations on how to fix it ?

**Comment by lululxvi** [comment]
You can read https://machinelearningmastery.com/introduction-to-regularization-to-reduce-overfitting-and-improve-generalization-error/

> the train loss quickly starts diminshing but the test loss quickly starts to increase

This sounds like over-fitting.

**Comment by athtareq** [comment]
Thanks @lululxvi !!
