### ISSUE TITLE
Error using Euler_beam.py

### ISSUE THREAD

**Issue by ThomasF121** [lululxvi/deepxde#8]
Hello!
I have got an error when using the Euler_beam.py code:

Traceback (most recent call last):
  File "<ipython-input-13-179c828221de>", line 53, in <module>
    main()
  File "<ipython-input-13-179c828221de>", line 43, in main
    net = dde.maps.FNN(layer_size, activation, initializer)
  File "C:\Users\ThomasFagart\Anaconda3\lib\site-packages\deepxde\maps\fnn.py", line 32, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "C:\Users\ThomasFagart\Anaconda3\lib\site-packages\deepxde\maps\initializers.py", line 93, in get
    "He normal": tf.variance_scaling_initializer(scale=2.0),
AttributeError: module 'tensorflow' has no attribute 'variance_scaling_initializer'

I am using tensorflow 2.0 and python 3.7.3. May that come from the new version of tensorflow?

**Comment by lululxvi** [comment]
Yes, the current code only supports tensorflow 1.

**Comment by ThomasF121** [comment]
Ok
Do you think you will upgrade it a near future (or less near)?

**Comment by lululxvi** [comment]
Yes, definitely, I will upgrade using TF2. But I cannot guarantee the timeline, because I am looking for jobs currently --_--

**Comment by ThomasF121** [comment]
Ah, if it is like the economic job market, you're not going to have time before long ^^
Ok, thanks for your answer Lu!

**Comment by lululxvi** [comment]
DeepXDE now supports TF2.
