### ISSUE TITLE
standardize=True in dataset.py

### ISSUE THREAD

**Issue by lkampoli** [lululxvi/deepxde#82]
Hello @lululxvi ,

I experience an error when running dataset.py with the argument standardize=True.

Traceback (most recent call last):
  File "dataset.py", line 32, in <module>
    main()
  File "dataset.py", line 16, in main
    standardize=True,
TypeError: __init__() got an unexpected keyword argument 'standardize'

If I comment, then is assumed by default False, and it runs ok.

Any hints?

Thank you,
Kind regards,
Lorenzo

**Comment by lululxvi** [comment]
Try the new version of DeepXDE

**Comment by lkampoli** [comment]
Hello, I'm using the last version.

**Comment by lululxvi** [comment]
I have no problem to run the code. Double check if your version is v0.8.3

**Comment by SanjuSoni** [comment]
> I have no problem to run the code. Double-check if your version is v0.8.3

Hello @lululxvi , when this version has been updated ( v 0.8.3)

**Comment by lululxvi** [comment]
Very recently.
