### ISSUE TITLE
How to solve _array_() takes 1 position argument but 2 were used?

### ISSUE THREAD

**Issue by shensummer** [lululxvi/deepxde#827]
Hi, thank you for your good job! I have encountered the  issue listed below, Could you please help me solve it? Thanks a lot.
I try to use DeepXDE to compute the inverse problem and to determine the coefficients CRC,KC,CTI,KB, and the wrong information is:

TypeError                                 Traceback (most recent call last)
<ipython-input-361-14ed15652481> in <module>
      1 net = dde.nn.FNN([1] + [40]*3 + [1], "tanh", "Glorot uniform")
      2 model = dde.Model(data,net)
----> 3 model.compile("adam",lr=0.001,external_trainable_variables = [CRC,KC,CTI,KB])
      4 variable = dde.callbacks.VariableValue( 
      5     [CRC,KC,CTI,KB],period = 600, filename = "variable.dat"

D:\Anaconda\lib\site-packages\deepxde\utils\internal.py in wrapper(*args, **kwargs)
     20     def wrapper(*args, **kwargs):
     21         ts = timeit.default_timer()
---> 22         result = f(*args, **kwargs)
     23         te = timeit.default_timer()
     24         print("%r took %f s\n" % (f.__name__, te - ts))

D:\Anaconda\lib\site-packages\deepxde\model.py in compile(self, optimizer, lr, loss, metrics, decay, loss_weights, external_trainable_variables)
    105 
    106         if backend_name == "tensorflow.compat.v1":
--> 107             self._compile_tensorflow_compat_v1(lr, loss_fn, decay, loss_weights)
    108         elif backend_name == "tensorflow":
    109             self._compile_tensorflow(lr, loss_fn, decay, loss_weights)

D:\Anaconda\lib\site-packages\deepxde\model.py in _compile_tensorflow_compat_v1(self, lr, loss_fn, decay, loss_weights)
    125 
    126         # Data losses
--> 127         losses = self.data.losses(self.net.targets, self.net.outputs, loss_fn, self)
    128         if not isinstance(losses, list):
    129             losses = [losses]

D:\Anaconda\lib\site-packages\deepxde\data\pde.py in losses(self, targets, outputs, loss, model)
    127         if self.pde is not None:
    128             if get_num_args(self.pde) == 2:
--> 129                 f = self.pde(model.net.inputs, outputs)
    130             elif get_num_args(self.pde) == 3:
    131                 if self.auxiliary_var_fn is None:

<ipython-input-356-72aac6ff337e> in pde(x, y)
      3 
      4     for i in range(0,3721):
----> 5         Db[i] = 6.0*voidg[i]/ai_pre[i]
      6         ur[i] = 0.2
      7         for j in range(1,25):

TypeError: __array__() takes 1 positional argument but 2 were given.

And I have defined the following pde:
def pde(x,y):     #x is the space coordinate
    ai_pre = y
    
    for i in range(0,3721):
        Db[i] = 6.0*voidg[i]/ai_pre[i]
        ur[i] = 0.2
        for j in range(1,25):
            ReD = rohl*ur[i]*Db[i]*(1.0-voidg[i])/muf
            Cde = 24.0*(1.0+0.1*ReD**0.75)/ReD
            ur[i] = (9.8*4.0*Db[i]*(1.0-voidg[i])/3.0/Cde)**0.5
            
        vgz[i]     = jglocal[i]/voidg[i]
        vfz[i]     = jl/(1.0-voidg[i])
        mum = muf/(1.0-voidg[i])
        vm  = (rohl*(1.0-voidg[i]))*vfz[i] + rohgz[i]*voidg[i]*vgz[i]/((rohl*(1.0-voidg[i])) + rohgz[i]*voidg[i])
        Rem = rohl*vm*Dh/mum
        fTW = 0.316*(mum/muf)**0.25/Rem**0.25
        e[i]= fTW*(vm**3.0)/2.0/Dh
        ut[i] = (e[i]**0.333333)*(Db[i]**0.333333)
            
        # the sink due to RC
        Temp1 = CRC*((voidg[i]/ai_pre[i])**2.0)*(ai_pre[i]**2.0)*(e[i])**0.3333333
        Temp2 = Db[i]**3.6666667*(voidgmax-voidg[i])
        Temp3 = Temp1/Temp2
        Temp4 = (Db[i]**5.0)*(rohl**3.0)*(e[i]**2.0)/sigma**3.0
        Temp5 = np.exp(-KC*(Temp4**0.16666667))
        SRC[i] = Temp3*Temp5
        
        # the source due to TI
        Temp6 = CTI*((voidg[i]/ai_pre[i])**2.0)*(ai_pre[i]**2.0)*(e[i])**0.3333333
        Temp7 = Db[i]**3.6666667*(voidgmax-voidg[i])
        Temp8 = Temp6/Temp7
        Temp9 = rohl*(Db[i]**1.6666667)*(e[i]**0.6666667)
        Temp10 = np.exp(-KB*sigma/Temp9)
        STI[i] = Temp8*Temp10
        
        
    dy_x = dde.grad.jacobian(y,x,i=0,j=0,component=0)
    
    Equ  = vg*dy_x + SRC - STI + (2.0*ai_pre*vg*dpdz/p0) 
    
    return Equ

The following model is used:
net = dde.nn.FNN([1] + [40]*3 + [1], "tanh", "Glorot uniform")
model = dde.Model(data,net)
model.compile("adam",lr=0.001,external_trainable_variables = [CRC,KC,CTI,KB])     
variable = dde.callbacks.VariableValue( 
    [CRC,KC,CTI,KB],period = 600, filename = "variable.dat"
)

**Comment by lululxvi** [comment]
Do not use `for` loop inside PDE, unless you are very clear about what you are doing in TensorFlow/PyTorch.

**Comment by shensummer** [comment]
Dear Doctor LuLu:
Thanks for your reply. Actually, I have fixed my code, which can run now. However, I have encountered another problem. The code have large PDE losses, and the losses of boundary is good. Moreover, I have read the FAQ, i.e., Q: I failed to train the network or get the right solution, e.g., large training loss, unbalanced losses. And I have done the following steps to improve my code:
(1)applying feature_transform(x) to scale my domain;
(2)applying net.apply_output_transform to scale the output.
Unfortunately, the code failed to converge still. The following is my complete code, could you please help me and give me some suggestions? Thank you for your time and kindness.

import deepxde as dde
import matplotlib.pyplot as plt
from scipy.integrate import solve_bvp
from deepxde.backend import tf
import numpy as np
dde.config.real.set_float32()

CRC  = dde.Variable(0.188)
KC   = dde.Variable(0.05)
CTI  = dde.Variable(0.264)
KB   = dde.Variable(0.001)

CRC = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))
KC  = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*100
CTI = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*0.1
KB  = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*100

geom = dde.geometry.Interval(0.3937,3.5814)

def pde(x,y):
    ai_pre = y
    
    #---------------------------------------------
    #define the initial and experiment condition
    rohg  = 1.02
    rohl  = 998.0
    sigma = 0.07278
    muf   = 0.001
    g     = 9.81
    Dh    = 0.0127
    z0    = 0.0127*31.0
    
    jl    = 1.0
    jg    = 0.463 
    p0    = 1.40372e5
    dpdz  = 9319.0
       
    
    
    #compute the axial pressure and noug 
    omegaz = 1.0 - (x - z0)*abs(dpdz/(p0 + 101330.0))
    pz     = (p0 + 101330.0)*omegaz
    rohgz  = rohg*omegaz
        
    #compute the void fraction
    C0      = 1.2 - 0.2*((rohg/rohl)**0.5)
    jglocal = jg*((p0 + 101330.0)/pz)   
    Vgj     = (2.0**0.5)*((sigma*9.8*(rohl-rohg)/(rohl**2.0))**0.25)    #*(1-voidg)**1.75
    voidg   = jglocal/( C0*(jglocal+ jl) + Vgj )    
    #compute turbulent disspate rate
    vgz     = jglocal/voidg
    vfz     = jl/(1.0-voidg)
    mum     = muf/(1.0-voidg)    
    vm      = (rohl*(1.0-voidg)*vfz + rohgz*voidg*vgz)/((rohl*(1.0-voidg)) + rohgz*voidg)
    Rem     = rohl*vm*Dh/mum
    fTW     = 0.316*(mum/muf)**0.25/Rem**0.25
    e       = fTW*(vm**3.0)/2.0/Dh
    # define two constant 
    voidgmax = 0.52
    vg       = 1.85
     
    # compute the source and sink terms    
    Db  = 6.0*voidg/ai_pre
    Cde = 2.0*Db*((1.0-voidg)**-0.5)*((g*(rohl-rohg)/sigma)**0.5)
    ur = (g*4.0*Db*(1.0-voidg)/3.0/Cde)**0.5
            
    ut = (e**0.333333)*(Db**0.333333)
     
    # the sink due to RC
    Temp1 = (voidg/ai_pre)**2.0
    Temp2 = CRC*Temp1*(ai_pre**2.0)*(e**0.3333333)
    Temp3 = Db**3.6666667*(voidgmax-voidg)
    Temp4 = Temp2/Temp3
    Temp5 = (Db**5.0)*(rohl**3.0)*(e**2.0)/sigma**3.0
    Temp6 = tf.exp(-KC*(Temp5**0.16666667))
    SRC   = Temp4*Temp6
    
    # the source due to TI
    Temp7  = (voidg/ai_pre)**2.0
    Temp8  = CTI*Temp7*voidg*(1.0-voidg)*(e**0.3333333)
    Temp9  = Db**3.6666667*(voidgmax-voidg)
    Temp10 = Temp8/Temp9
    Temp11 = rohl*(Db**1.6666667)*(e**0.6666667)
    Temp12 = tf.exp(-KB*sigma/Temp11)
    STI    = Temp10*Temp11
        
        
    dy_x = dde.grad.jacobian(y,x,i=0)
    
    Equ  = dy_x + SRC - STI - (2.0*ai_pre*vg*dpdz/(p0*3.0)) #vg*dy_x + SRC - STI - (2.0*ai_pre*vg*dpdz/(p0*3.0)) 
    return Equ

def feature_transform(x):    
    return tf.concat(x/3.5814)

ob_x        = np.array([1.9812])
ob_x        = np.reshape(ob_x,(-1,1))
ob_ai       = np.array([698.43])    
ob_ai       = ob_ai.reshape(-1,1)
observe_ai  = dde.PointSetBC(ob_x,ob_ai,component = 0)

def boundary_l(x, on_boundary):
    return on_boundary and np.isclose(x[0], 0.3937)

def boundary_r(x, on_boundary):
    return on_boundary and np.isclose(x[0], 3.5814)

def func(x):
    return 917.17
def funr(x):
    return 617.80

bc_l = dde.DirichletBC(geom,func,boundary_l,component = 0)
bc_r = dde.DirichletBC(geom,funr,boundary_r,component = 0)

data = dde.data.PDE(
    geom,
    pde,
    bcs=[bc_l,bc_r,observe_ai],   
    num_domain   = 3000,
    num_boundary = 2,
    train_distribution = "uniform",
    num_test = 3000,
)

net = dde.nn.FNN([1] + [125]*5 + [1], "swish", "Glorot uniform")
net.apply_output_transform(lambda x, y: y * 100 ) 
model = dde.Model(data,net)
model.compile("adam",lr=0.001,loss_weights=[0.0,1.0,1.0,1.0]) #,external_trainable_variables = [CRC,KC,CTI,KB]
variable = dde.callbacks.VariableValue( 
    [CRC,KC,CTI,KB],period = 600, filename = "variable.dat"
)

losshistory,train_state = model.train(epochs = 5000, callbacks = [variable])
model.compile("adam",lr=0.001,loss_weights=[1.0e-2,1.0,1.0,1.0]) losshistory,train_state = model.train(epochs = 80000, callbacks = [variable])

Step      Train loss                                  Test loss                                   Test metric
5000      [2.77e+02, 3.35e-08, 3.73e-09, 1.49e-08]    [2.77e+02, 3.35e-08, 3.73e-09, 1.49e-08]    []  
6000      [2.70e+02, 5.13e-01, 7.89e-02, 9.41e-02]    [2.70e+02, 5.13e-01, 7.89e-02, 9.41e-02]    []  
7000      [2.67e+02, 5.44e-01, 6.27e-02, 7.24e-02]    [2.67e+02, 5.44e-01, 6.27e-02, 7.24e-02]    []  
8000      [2.67e+02, 2.68e+01, 2.55e+01, 3.56e+01]    [2.67e+02, 2.68e+01, 2.55e+01, 3.56e+01]    []  
9000      [2.65e+02, 5.28e-01, 6.98e-02, 7.38e-02]    [2.65e+02, 5.28e-01, 6.98e-02, 7.38e-02]    []  
10000     [2.65e+02, 5.01e-01, 8.32e-02, 8.61e-02]    [2.65e+02, 5.01e-01, 8.32e-02, 8.61e-02]    []  
11000     [2.65e+02, 2.20e-02, 1.26e+00, 1.94e+00]    [2.65e+02, 2.20e-02, 1.26e+00, 1.94e+00]    []  
12000     [2.64e+02, 4.98e-01, 8.03e-02, 9.12e-02]    [2.64e+02, 4.98e-01, 8.03e-02, 9.12e-02]    []  
13000     [2.64e+02, 1.53e+00, 6.21e+00, 8.66e+00]    [2.64e+02, 1.53e+00, 6.21e+00, 8.66e+00]    []  
14000     [2.64e+02, 4.36e-01, 1.17e-01, 1.35e-01]    [2.64e+02, 4.36e-01, 1.17e-01, 1.35e-01]    []  
15000     [2.64e+02, 1.66e-01, 4.79e-01, 5.48e-01]    [2.64e+02, 1.66e-01, 4.79e-01, 5.48e-01]    []  
16000     [2.64e+02, 1.00e+00, 3.15e+00, 5.58e+00]    [2.64e+02, 1.00e+00, 3.15e+00, 5.58e+00]    []  
17000     [2.65e+02, 7.25e-01, 1.27e+00, 5.59e-01]    [2.65e+02, 7.25e-01, 1.27e+00, 5.59e-01]    []  
18000     [2.63e+02, 3.61e+00, 5.98e-02, 8.69e-01]    [2.63e+02, 3.61e+00, 5.98e-02, 8.69e-01]    []  
19000     [2.63e+02, 3.72e-01, 1.68e-01, 1.69e-01]    [2.63e+02, 3.72e-01, 1.68e-01, 1.69e-01]    []  
20000     [2.63e+02, 1.54e-02, 9.95e-01, 1.87e+00]    [2.63e+02, 1.54e-02, 9.95e-01, 1.87e+00]    []  
21000     [2.60e+02, 3.07e+01, 4.32e+00, 1.06e+01]    [2.60e+02, 3.07e+01, 4.32e+00, 1.06e+01]    []  
22000     [2.63e+02, 6.22e-01, 2.09e-03, 1.36e-02]    [2.63e+02, 6.22e-01, 2.09e-03, 1.36e-02]    []  
23000     [2.62e+02, 2.59e-01, 2.52e-01, 2.23e-01]    [2.62e+02, 2.59e-01, 2.52e-01, 2.23e-01]    []  
24000     [2.62e+02, 4.08e-01, 1.75e-01, 1.34e-01]    [2.62e+02, 4.08e-01, 1.75e-01, 1.34e-01]    []  
25000     [2.62e+02, 1.39e-01, 1.73e-01, 4.72e-01]    [2.62e+02, 1.39e-01, 1.73e-01, 4.72e-01]    []  
26000     [2.62e+02, 1.14e-01, 2.92e-01, 5.40e-01]    [2.62e+02, 1.14e-01, 2.92e-01, 5.40e-01]    []  
27000     [2.62e+02, 9.94e-01, 4.37e-03, 4.33e-03]    [2.62e+02, 9.94e-01, 4.37e-03, 4.33e-03]    []  
28000     [2.61e+02, 1.33e+00, 1.65e-01, 4.43e-02]    [2.61e+02, 1.33e+00, 1.65e-01, 4.43e-02]    []  
29000     [2.61e+02, 6.66e-02, 5.35e-01, 6.00e-01]    [2.61e+02, 6.66e-02, 5.35e-01, 6.00e-01]    []  
30000     [2.62e+02, 6.46e-01, 1.76e-01, 1.15e-01]    [2.62e+02, 6.46e-01, 1.76e-01, 1.15e-01]    []  
31000     [2.61e+02, 1.82e+00, 3.59e-02, 6.71e-02]    [2.61e+02, 1.82e+00, 3.59e-02, 6.71e-02]    []  
32000     [2.63e+02, 4.89e-01, 8.54e-02, 7.75e-02]    [2.63e+02, 4.89e-01, 8.54e-02, 7.75e-02]    []  
33000     [2.62e+02, 4.82e-01, 8.60e-02, 7.48e-02]    [2.62e+02, 4.82e-01, 8.60e-02, 7.48e-02]    []  
34000     [2.62e+02, 4.62e-01, 9.15e-02, 7.52e-02]    [2.62e+02, 4.62e-01, 9.15e-02, 7.52e-02]    []  
35000     [2.61e+02, 7.82e-02, 1.09e+00, 9.82e-01]    [2.61e+02, 7.82e-02, 1.09e+00, 9.82e-01]    []  
36000     [2.62e+02, 3.09e-01, 3.28e-02, 1.30e-01]    [2.62e+02, 3.09e-01, 3.28e-02, 1.30e-01]    []  
37000     [2.61e+02, 4.02e-01, 1.14e-01, 1.01e-01]    [2.61e+02, 4.02e-01, 1.14e-01, 1.01e-01]    []  
38000     [2.61e+02, 7.77e-01, 7.83e-03, 4.06e-06]    [2.61e+02, 7.77e-01, 7.83e-03, 4.06e-06]    []  
39000     [2.61e+02, 2.61e-01, 3.49e-01, 2.73e-01]    [2.61e+02, 2.61e-01, 3.49e-01, 2.73e-01]    []  
40000     [2.61e+02, 1.57e+00, 7.14e-02, 2.11e-01]    [2.61e+02, 1.57e+00, 7.14e-02, 2.11e-01]    []  
41000     [2.61e+02, 2.39e-01, 4.60e-01, 3.51e-01]    [2.61e+02, 2.39e-01, 4.60e-01, 3.51e-01]    []  
42000     [2.59e+02, 5.51e+00, 1.03e-01, 1.28e+00]    [2.60e+02, 5.51e+00, 1.03e-01, 1.28e+00]    []  
43000     [2.62e+02, 4.77e-01, 8.79e-02, 7.22e-02]    [2.62e+02, 4.77e-01, 8.79e-02, 7.22e-02]    []  
44000     [2.61e+02, 4.72e-01, 8.89e-02, 6.89e-02]    [2.61e+02, 4.72e-01, 8.89e-02, 6.89e-02]    []  
45000     [2.61e+02, 5.48e-01, 6.20e-02, 4.15e-02]    [2.61e+02, 5.48e-01, 6.20e-02, 4.15e-02]    []  
46000     [2.61e+02, 4.61e-01, 9.32e-02, 6.93e-02]    [2.61e+02, 4.61e-01, 9.32e-02, 6.93e-02]    []  
47000     [2.61e+02, 4.79e-01, 1.52e-01, 1.10e-01]    [2.61e+02, 4.79e-01, 1.52e-01, 1.10e-01]    []  
48000     [2.62e+02, 2.75e-01, 7.29e-02, 1.35e-01]    [2.62e+02, 2.75e-01, 7.29e-02, 1.35e-01]    []  
49000     [2.61e+02, 2.01e-01, 3.13e-01, 3.07e-01]    [2.61e+02, 2.01e-01, 3.13e-01, 3.07e-01]    []  
50000     [2.64e+02, 6.12e-01, 6.08e-01, 9.87e+00]    [2.64e+02, 6.12e-01, 6.08e-01, 9.87e+00]    []

**Comment by shensummer** [comment]
> Do not use `for` loop inside PDE, unless you are very clear about what you are doing in TensorFlow/PyTorch.
@lululxvi 
Dear Doctor LuLu:
Thanks for your reply. Actually, I have fixed my code, which can run now. However, I have encountered another problem. The code have large PDE losses, and the losses of boundary is good. Moreover, I have read the FAQ, i.e., Q: I failed to train the network or get the right solution, e.g., large training loss, unbalanced losses. And I have done the following steps to improve my code:
(1)applying feature_transform(x) to scale my domain;
(2)applying net.apply_output_transform to scale the output.
Unfortunately, the code failed to converge still. The following is my complete code, could you please help me and give me some suggestions? Thank you for your time and kindness.

import deepxde as dde
import matplotlib.pyplot as plt
from scipy.integrate import solve_bvp
from deepxde.backend import tf
import numpy as np
dde.config.real.set_float32()

CRC = dde.Variable(0.188)
KC = dde.Variable(0.05)
CTI = dde.Variable(0.264)
KB = dde.Variable(0.001)

CRC = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))
KC = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*100
CTI = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*0.1
KB = tf.math.softplus(tf.Variable(0, trainable=True, dtype=tf.float32))*100

geom = dde.geometry.Interval(0.3937,3.5814)

def pde(x,y):
ai_pre = y

#---------------------------------------------
#define the initial and experiment condition
rohg  = 1.02
rohl  = 998.0
sigma = 0.07278
muf   = 0.001
g     = 9.81
Dh    = 0.0127
z0    = 0.0127*31.0

jl    = 1.0
jg    = 0.463 
p0    = 1.40372e5
dpdz  = 9319.0
   


#compute the axial pressure and noug 
omegaz = 1.0 - (x - z0)*abs(dpdz/(p0 + 101330.0))
pz     = (p0 + 101330.0)*omegaz
rohgz  = rohg*omegaz
    
#compute the void fraction
C0      = 1.2 - 0.2*((rohg/rohl)**0.5)
jglocal = jg*((p0 + 101330.0)/pz)   
Vgj     = (2.0**0.5)*((sigma*9.8*(rohl-rohg)/(rohl**2.0))**0.25)    #*(1-voidg)**1.75
voidg   = jglocal/( C0*(jglocal+ jl) + Vgj )    
#compute turbulent disspate rate
vgz     = jglocal/voidg
vfz     = jl/(1.0-voidg)
mum     = muf/(1.0-voidg)    
vm      = (rohl*(1.0-voidg)*vfz + rohgz*voidg*vgz)/((rohl*(1.0-voidg)) + rohgz*voidg)
Rem     = rohl*vm*Dh/mum
fTW     = 0.316*(mum/muf)**0.25/Rem**0.25
e       = fTW*(vm**3.0)/2.0/Dh
# define two constant 
voidgmax = 0.52
vg       = 1.85
 
# compute the source and sink terms    
Db  = 6.0*voidg/ai_pre
Cde = 2.0*Db*((1.0-voidg)**-0.5)*((g*(rohl-rohg)/sigma)**0.5)
ur = (g*4.0*Db*(1.0-voidg)/3.0/Cde)**0.5
        
ut = (e**0.333333)*(Db**0.333333)
 
# the sink due to RC
Temp1 = (voidg/ai_pre)**2.0
Temp2 = CRC*Temp1*(ai_pre**2.0)*(e**0.3333333)
Temp3 = Db**3.6666667*(voidgmax-voidg)
Temp4 = Temp2/Temp3
Temp5 = (Db**5.0)*(rohl**3.0)*(e**2.0)/sigma**3.0
Temp6 = tf.exp(-KC*(Temp5**0.16666667))
SRC   = Temp4*Temp6

# the source due to TI
Temp7  = (voidg/ai_pre)**2.0
Temp8  = CTI*Temp7*voidg*(1.0-voidg)*(e**0.3333333)
Temp9  = Db**3.6666667*(voidgmax-voidg)
Temp10 = Temp8/Temp9
Temp11 = rohl*(Db**1.6666667)*(e**0.6666667)
Temp12 = tf.exp(-KB*sigma/Temp11)
STI    = Temp10*Temp11
    
    
dy_x = dde.grad.jacobian(y,x,i=0)

Equ  = dy_x + SRC - STI - (2.0*ai_pre*vg*dpdz/(p0*3.0)) #vg*dy_x + SRC - STI - (2.0*ai_pre*vg*dpdz/(p0*3.0)) 
return Equ
def feature_transform(x):
return tf.concat(x/3.5814)

ob_x = np.array([1.9812])
ob_x = np.reshape(ob_x,(-1,1))
ob_ai = np.array([698.43])
ob_ai = ob_ai.reshape(-1,1)
observe_ai = dde.PointSetBC(ob_x,ob_ai,component = 0)

def boundary_l(x, on_boundary):
return on_boundary and np.isclose(x[0], 0.3937)

def boundary_r(x, on_boundary):
return on_boundary and np.isclose(x[0], 3.5814)

def func(x):
return 917.17
def funr(x):
return 617.80

bc_l = dde.DirichletBC(geom,func,boundary_l,component = 0)
bc_r = dde.DirichletBC(geom,funr,boundary_r,component = 0)

data = dde.data.PDE(
geom,
pde,
bcs=[bc_l,bc_r,observe_ai],
num_domain = 3000,
num_boundary = 2,
train_distribution = "uniform",
num_test = 3000,
)

net = dde.nn.FNN([1] + [125]*5 + [1], "swish", "Glorot uniform")
net.apply_output_transform(lambda x, y: y * 100 )
model = dde.Model(data,net)
model.compile("adam",lr=0.001,loss_weights=[0.0,1.0,1.0,1.0]) #,external_trainable_variables = [CRC,KC,CTI,KB]
variable = dde.callbacks.VariableValue(
[CRC,KC,CTI,KB],period = 600, filename = "variable.dat"
)

losshistory,train_state = model.train(epochs = 5000, callbacks = [variable])
model.compile("adam",lr=0.001,loss_weights=[1.0e-2,1.0,1.0,1.0]) losshistory,train_state = model.train(epochs = 80000, callbacks = [variable])

Step Train loss Test loss Test metric
5000 [2.77e+02, 3.35e-08, 3.73e-09, 1.49e-08] [2.77e+02, 3.35e-08, 3.73e-09, 1.49e-08] []
6000 [2.70e+02, 5.13e-01, 7.89e-02, 9.41e-02] [2.70e+02, 5.13e-01, 7.89e-02, 9.41e-02] []
7000 [2.67e+02, 5.44e-01, 6.27e-02, 7.24e-02] [2.67e+02, 5.44e-01, 6.27e-02, 7.24e-02] []
8000 [2.67e+02, 2.68e+01, 2.55e+01, 3.56e+01] [2.67e+02, 2.68e+01, 2.55e+01, 3.56e+01] []
9000 [2.65e+02, 5.28e-01, 6.98e-02, 7.38e-02] [2.65e+02, 5.28e-01, 6.98e-02, 7.38e-02] []
10000 [2.65e+02, 5.01e-01, 8.32e-02, 8.61e-02] [2.65e+02, 5.01e-01, 8.32e-02, 8.61e-02] []
11000 [2.65e+02, 2.20e-02, 1.26e+00, 1.94e+00] [2.65e+02, 2.20e-02, 1.26e+00, 1.94e+00] []
12000 [2.64e+02, 4.98e-01, 8.03e-02, 9.12e-02] [2.64e+02, 4.98e-01, 8.03e-02, 9.12e-02] []
13000 [2.64e+02, 1.53e+00, 6.21e+00, 8.66e+00] [2.64e+02, 1.53e+00, 6.21e+00, 8.66e+00] []
14000 [2.64e+02, 4.36e-01, 1.17e-01, 1.35e-01] [2.64e+02, 4.36e-01, 1.17e-01, 1.35e-01] []
15000 [2.64e+02, 1.66e-01, 4.79e-01, 5.48e-01] [2.64e+02, 1.66e-01, 4.79e-01, 5.48e-01] []
16000 [2.64e+02, 1.00e+00, 3.15e+00, 5.58e+00] [2.64e+02, 1.00e+00, 3.15e+00, 5.58e+00] []
17000 [2.65e+02, 7.25e-01, 1.27e+00, 5.59e-01] [2.65e+02, 7.25e-01, 1.27e+00, 5.59e-01] []
18000 [2.63e+02, 3.61e+00, 5.98e-02, 8.69e-01] [2.63e+02, 3.61e+00, 5.98e-02, 8.69e-01] []
19000 [2.63e+02, 3.72e-01, 1.68e-01, 1.69e-01] [2.63e+02, 3.72e-01, 1.68e-01, 1.69e-01] []
20000 [2.63e+02, 1.54e-02, 9.95e-01, 1.87e+00] [2.63e+02, 1.54e-02, 9.95e-01, 1.87e+00] []
21000 [2.60e+02, 3.07e+01, 4.32e+00, 1.06e+01] [2.60e+02, 3.07e+01, 4.32e+00, 1.06e+01] []
22000 [2.63e+02, 6.22e-01, 2.09e-03, 1.36e-02] [2.63e+02, 6.22e-01, 2.09e-03, 1.36e-02] []
23000 [2.62e+02, 2.59e-01, 2.52e-01, 2.23e-01] [2.62e+02, 2.59e-01, 2.52e-01, 2.23e-01] []
24000 [2.62e+02, 4.08e-01, 1.75e-01, 1.34e-01] [2.62e+02, 4.08e-01, 1.75e-01, 1.34e-01] []
25000 [2.62e+02, 1.39e-01, 1.73e-01, 4.72e-01] [2.62e+02, 1.39e-01, 1.73e-01, 4.72e-01] []
26000 [2.62e+02, 1.14e-01, 2.92e-01, 5.40e-01] [2.62e+02, 1.14e-01, 2.92e-01, 5.40e-01] []
27000 [2.62e+02, 9.94e-01, 4.37e-03, 4.33e-03] [2.62e+02, 9.94e-01, 4.37e-03, 4.33e-03] []
28000 [2.61e+02, 1.33e+00, 1.65e-01, 4.43e-02] [2.61e+02, 1.33e+00, 1.65e-01, 4.43e-02] []
29000 [2.61e+02, 6.66e-02, 5.35e-01, 6.00e-01] [2.61e+02, 6.66e-02, 5.35e-01, 6.00e-01] []
30000 [2.62e+02, 6.46e-01, 1.76e-01, 1.15e-01] [2.62e+02, 6.46e-01, 1.76e-01, 1.15e-01] []
31000 [2.61e+02, 1.82e+00, 3.59e-02, 6.71e-02] [2.61e+02, 1.82e+00, 3.59e-02, 6.71e-02] []
32000 [2.63e+02, 4.89e-01, 8.54e-02, 7.75e-02] [2.63e+02, 4.89e-01, 8.54e-02, 7.75e-02] []
33000 [2.62e+02, 4.82e-01, 8.60e-02, 7.48e-02] [2.62e+02, 4.82e-01, 8.60e-02, 7.48e-02] []
34000 [2.62e+02, 4.62e-01, 9.15e-02, 7.52e-02] [2.62e+02, 4.62e-01, 9.15e-02, 7.52e-02] []
35000 [2.61e+02, 7.82e-02, 1.09e+00, 9.82e-01] [2.61e+02, 7.82e-02, 1.09e+00, 9.82e-01] []
36000 [2.62e+02, 3.09e-01, 3.28e-02, 1.30e-01] [2.62e+02, 3.09e-01, 3.28e-02, 1.30e-01] []
37000 [2.61e+02, 4.02e-01, 1.14e-01, 1.01e-01] [2.61e+02, 4.02e-01, 1.14e-01, 1.01e-01] []
38000 [2.61e+02, 7.77e-01, 7.83e-03, 4.06e-06] [2.61e+02, 7.77e-01, 7.83e-03, 4.06e-06] []
39000 [2.61e+02, 2.61e-01, 3.49e-01, 2.73e-01] [2.61e+02, 2.61e-01, 3.49e-01, 2.73e-01] []
40000 [2.61e+02, 1.57e+00, 7.14e-02, 2.11e-01] [2.61e+02, 1.57e+00, 7.14e-02, 2.11e-01] []
41000 [2.61e+02, 2.39e-01, 4.60e-01, 3.51e-01] [2.61e+02, 2.39e-01, 4.60e-01, 3.51e-01] []
42000 [2.59e+02, 5.51e+00, 1.03e-01, 1.28e+00] [2.60e+02, 5.51e+00, 1.03e-01, 1.28e+00] []
43000 [2.62e+02, 4.77e-01, 8.79e-02, 7.22e-02] [2.62e+02, 4.77e-01, 8.79e-02, 7.22e-02] []
44000 [2.61e+02, 4.72e-01, 8.89e-02, 6.89e-02] [2.61e+02, 4.72e-01, 8.89e-02, 6.89e-02] []
45000 [2.61e+02, 5.48e-01, 6.20e-02, 4.15e-02] [2.61e+02, 5.48e-01, 6.20e-02, 4.15e-02] []
46000 [2.61e+02, 4.61e-01, 9.32e-02, 6.93e-02] [2.61e+02, 4.61e-01, 9.32e-02, 6.93e-02] []
47000 [2.61e+02, 4.79e-01, 1.52e-01, 1.10e-01] [2.61e+02, 4.79e-01, 1.52e-01, 1.10e-01] []
48000 [2.62e+02, 2.75e-01, 7.29e-02, 1.35e-01] [2.62e+02, 2.75e-01, 7.29e-02, 1.35e-01] []
49000 [2.61e+02, 2.01e-01, 3.13e-01, 3.07e-01] [2.61e+02, 2.01e-01, 3.13e-01, 3.07e-01] []
50000 [2.64e+02, 6.12e-01, 6.08e-01, 9.87e+00] [2.64e+02, 6.12e-01, 6.08e-01, 9.87e+00] []
