### ISSUE TITLE
Training rate coefficients

### ISSUE THREAD

**Issue by lkampoli** [lululxvi/deepxde#83]
Hello,

I would like to train a network about for example the rate coefficients attached.
[kVTN2N2.txt](https://github.com/lululxvi/deepxde/files/4902969/kVTN2N2.txt)
The first column reports the temperature and the second the coefficient. 

I'm using exactly the dataset.py example just by changing the train and test (which is the same as the train without some random point) sets and I'm experiencing some difficultis that since the values are very big or very small.

I noticed that in general data is always somehow rescaled. Indeed, if I rescale between for example [0:1] both axes it converge well. 

Is it possible to keep the data as they are without rescaling them, get the convergence and also in the plot the original values?

Thank you,
Lorenzo

**Comment by lululxvi** [comment]
No, it would be difficult to train a network.

**Comment by lkampoli** [comment]
Why, is it difficult?

... but then I get a good training with the "rescaled" data, then if I come back to the "original" data, which are for example ~10^29 different, the discrepancy would be huge. 

Does any work-around exist?
In any case, how I can reconvert to original data after training?

**Comment by lkampoli** [comment]
Here, http://www.faqs.org/faqs/ai-faq/neural-nets/part2/, I found interesting answers to some doubts!

**Comment by lululxvi** [comment]
You can rescale your data as a pre-processing, and then train the network. For prediction, you rescale back the network outputs.
