### ISSUE TITLE
Unknown parameters on boundary conditions

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#86]
Recently, I encountered a problem when solving the inverse problem. When the equation is a known situation and the variables are on boundary conditions, how should I write my code in this case? The following figure is a small example, where the exact solution is known, and you want to solve α and β. Do you have any examples?
![image](https://user-images.githubusercontent.com/52651366/87417377-a7763e80-c602-11ea-80f7-d6851b6a4a91.png)

**Comment by lululxvi** [comment]
It is the same as the inverse problem where the unknown is in the PDE. You need to define a tf variable and then define the BC using the variable.

**Comment by 979736316** [comment]
> It is the same as the inverse problem where the unknown is in the PDE. You need to define a tf variable and then define the BC using the variable.

I made some changes according to the example "diffusion_1d_inverse" you provided, but it cannot be iterated. Why? When I run the example "diffusion_1d_inverse", it will also give an error, I run the other is normal

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    alpha = tf.Variable(4)
    beta = tf.Variable(3)

    def pde(x,u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    def func(x):
        v = 0.0
        Z,Tv = x[:,0:1],x[:,1:2]
        for i in range(1, 1000, 1):
            con = np.exp(-2 * Tv) + (np.exp(-3 * Tv) - np.exp(-2 * Tv)) * Z
            Nn = i * np.pi
            r = 2 / (Nn ** 2 - 2) * (np.exp(-2 * Tv) - np.exp(-Nn ** 2 * Tv))
            s = 3 / (Nn ** 2 - 3) * (np.exp(-3 * Tv) - np.exp(-Nn ** 2 * Tv))
            # t = (1 - (-1) ** i * (1 + eta)) / Nn * np.exp(-Nn ** 2 * Tv)

            v += (r - (-1) ** i * s) * 2 * np.sin(Nn * Z) / Nn

        u = con + v
        return u

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return np.exp(-alpha*x[:, 1:2])

    def fun_initbc_all_b(x):
        return np.exp(-beta*x[:, 1:2])
    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    observe_x = np.vstack((np.linspace(0, 1, num=10), np.full((10), 1))).T
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(func(observe_x)), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic, observe_y],
        num_domain=400,
        num_boundary=200,
        num_initial=100,
        anchors=observe_x,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [32] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([alpha, beta], period=1000,filename="variables.dat")
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
```

![image](https://user-images.githubusercontent.com/52651366/87512812-41dd8d00-c6aa-11ea-8c6c-c7e380bef202.png)

**Comment by 979736316** [comment]
> It is the same as the inverse problem where the unknown is in the PDE. You need to define a tf variable and then define the BC using the variable.
I tried to change my code based on the "diffusion_1d_inverse" example you provided. Unfortunately, it ran into an error. I have defined my α and β as variables, Can you help me see where is the problem?

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def main():
    alpha = tf.Variable(4)
    beta = tf.Variable(3)

    def pde(x,u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    def func(x):
        v = 0.0
        Z,Tv = x[:,0:1],x[:,1:2]
        for i in range(1, 1000, 1):
            con = np.exp(-2 * Tv) + (np.exp(-3 * Tv) - np.exp(-2 * Tv)) * Z
            Nn = i * np.pi
            r = 2 / (Nn ** 2 - 2) * (np.exp(-2 * Tv) - np.exp(-Nn ** 2 * Tv))
            s = 3 / (Nn ** 2 - 3) * (np.exp(-3 * Tv) - np.exp(-Nn ** 2 * Tv))
            # t = (1 - (-1) ** i * (1 + eta)) / Nn * np.exp(-Nn ** 2 * Tv)

            v += (r - (-1) ** i * s) * 2 * np.sin(Nn * Z) / Nn

        u = con + v
        return u

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return np.exp(-alpha*x[:, 1:2])

    def fun_initbc_all_b(x):
        return np.exp(-beta*x[:, 1:2])
    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    observe_x = np.vstack((np.linspace(0, 1, num=10), np.full((10), 1))).T
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(func(observe_x)), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic, observe_y],
        num_domain=400,
        num_boundary=200,
        num_initial=100,
        anchors=observe_x,
        solution=func,
        num_test=10000,
    )

    layer_size = [2] + [32] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([alpha, beta], period=1000,filename="variables.dat")
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()
```

![image](https://user-images.githubusercontent.com/52651366/87515784-f24d9000-c6ae-11ea-9970-213f8fbb8b7b.png)

And, I was running "diffusion_1d_inverse" and showed the following error: TypeError:'numpy.float32' object is not iterable

**Comment by lululxvi** [comment]
Try
```python
alpha = tf.Variable(4, dtype=tf.float32)
```
Similar for beta.

**Comment by 979736316** [comment]
> Try
> 
> ```python
> alpha = tf.Variable(4, dtype=tf.float32)
> ```
> 
> Similar for beta.
> 
> When operating on alpha or beta, use tensorflow, e.g., `tf.exp(-alpha*x[:, 1:2])`

Thanks,Now it can run normally. I have another question now. If I want to quickly get the values of all the residual points I set, is there any quick command? Is this: X = geom.uniform_points()?

I want to know how did you draw from the graph "Lorzne_inverse"? How do I get the x and y values in this figure？
![image](https://user-images.githubusercontent.com/52651366/87559415-d79a0c00-c6ec-11ea-9dad-8a726c5b8d35.png)

**Comment by lululxvi** [comment]
I am not sure why the residual points don't shown in the figure, as you can see [here](https://github.com/lululxvi/deepxde/blob/0bd5d1b209be313adef97c557972ab75850b2c12/deepxde/postprocessing.py#L51). The residual points for training is saved in "train.dat", and you can always plot using this file.

**Comment by 979736316** [comment]
> he residual points for training is saved in "train.dat", and you can always plot

Thank you for your reply. Does the data saved by "train.dat" represent the residual value of each residual point during training? When solving the inverse problem, I want to know the parameter value of each point during the inverse calculation, so as to describe the relationship of the inverse parameter value changing with the point. Are these inverse parameter values saved?

**Comment by lululxvi** [comment]
Yes, "train.dat" is the residual points.

Parameter values are saved in "variables.dat".

**Comment by 979736316** [comment]
> Yes, "train.dat" is the residual points.
> 
> Parameter values are saved in "variables.dat".

Unfortunately, I encountered a new problem. When I was solving the inverse problem based on measurement data, I encountered the following problem: "object of type'numpy.float64' has no len()"
The following is my code, my np.hstack((Z, Tv)).T dimension is [42,2], u dimension is [42,1], can you see what the problem is?

`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def gen_traindata():
    data = np.load("dataset/Terzaghi.npz")
    Z,Tv,u = data["arr_0"],data["arr_1"],data["arr_2"]
    return np.hstack((Z, Tv)).T,u

def main():
    alpha = tf.Variable(3, dtype=tf.float32)
    beta = tf.Variable(4, dtype=tf.float32)

    def pde(x,u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 100)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return tf.exp(-alpha * x[:, 1:2])

    def fun_initbc_all_b(x):
        return tf.exp(-beta * x[:, 1:2])

    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    observe_x, u =  gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(u), lambda x, _: ptset.inside(x)
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic, observe_y],
        num_domain=2000,
        num_boundary=100,
        num_initial=100,
        anchors=observe_x,
        num_test=50000,
    )

    layer_size = [2] + [50] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([alpha, beta], period=500, filename="variables.dat")
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
`

**Comment by 979736316** [comment]
> Yes, "train.dat" is the residual points.
> 
> Parameter values are saved in "variables.dat".

Unfortunately, I encountered a new problem. When I was solving the inverse problem based on measurement data, I encountered the following problem: "object of type'numpy.float64' has no len()"
The following is my code, my np.hstack((Z, Tv)).T dimension is [42,2], u dimension is [42,1], can you see what the problem is?


> ``from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def gen_traindata():
    data = np.load("dataset/Terzaghi.npz")
    Z,Tv,u = data["arr_0"],data["arr_1"],data["arr_2"]
    return np.hstack((Z, Tv)).T,u

def main():
    alpha = tf.Variable(3, dtype=tf.float32)
    beta = tf.Variable(4, dtype=tf.float32)

    def pde(x,u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 100)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return tf.exp(-alpha * x[:, 1:2])

    def fun_initbc_all_b(x):
        return tf.exp(-beta * x[:, 1:2])

    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    observe_x, u =  gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(u), lambda x, _: ptset.inside(x),component=0
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic, observe_y],
        num_domain=2000,
        num_boundary=100,
        num_initial=100,
        anchors=observe_x,
        num_test=50000,
    )

    layer_size = [2] + [50] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([alpha, beta], period=500, filename="variables.dat")
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()

``

**Comment by 979736316** [comment]
Unfortunately, I encountered a new problem. When I was solving the inverse problem based on measurement data, I encountered the following problem: "object of type'numpy.float64' has no len()"
The following is my code, my np.hstack((Z, Tv)).T dimension is [42,2], u dimension is [42,1], can you see what the problem is?

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np

import deepxde as dde
from deepxde.backend import tf

def gen_traindata():
    data = np.load("dataset/Terzaghi.npz")
    Z,Tv,u = data["arr_0"],data["arr_1"],data["arr_2"]
    return np.hstack((Z, Tv)).T,u

def main():
    alpha = tf.Variable(3, dtype=tf.float32)
    beta = tf.Variable(4, dtype=tf.float32)

    def pde(x,u):
        du_x = tf.gradients(u, x)[0]
        du_x, du_t = du_x[:, 0:1], du_x[:, 1:2]
        du_xx = tf.gradients(du_x, x)[0][:, 0:1]
        return du_t - du_xx

    geom = dde.geometry.Interval(0, 1)
    timedomain = dde.geometry.TimeDomain(0, 100)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    def fun_initbc_all_a(x):
        return tf.exp(-alpha * x[:, 1:2])

    def fun_initbc_all_b(x):
        return tf.exp(-beta * x[:, 1:2])

    def fun_init(x):
        return np.full_like(x[:, 0:1], 1)

    def boundary_l(x, on_boundary):
        return on_boundary and np.isclose(x[0], 0)

    def boundary_r(x, on_boundary):
        return on_boundary and np.isclose(x[0], 1)

    bc_a = dde.DirichletBC(geomtime, fun_initbc_all_a, boundary_l)
    bc_b = dde.DirichletBC(geomtime, fun_initbc_all_b, boundary_r)
    ic = dde.IC(geomtime, fun_init, lambda _, on_initial: on_initial)

    observe_x, u =  gen_traindata()
    ptset = dde.bc.PointSet(observe_x)
    observe_y = dde.DirichletBC(
        geomtime, ptset.values_to_func(u), lambda x, _: ptset.inside(x),component=0
    )

    data = dde.data.TimePDE(
        geomtime,
        pde,
        [bc_a, bc_b, ic, observe_y],
        num_domain=2000,
        num_boundary=100,
        num_initial=100,
        anchors=observe_x,
        num_test=50000,
    )

    layer_size = [2] + [50] * 3 + [1]
    activation = "tanh"
    initializer = "Glorot uniform"
    net = dde.maps.FNN(layer_size, activation, initializer)

    model = dde.Model(data, net)

    model.compile("adam", lr=0.001, metrics=["l2 relative error"])
    variable = dde.callbacks.VariableValue([alpha, beta], period=500, filename="variables.dat")
    losshistory, train_state = model.train(epochs=50000, callbacks=[variable])

    dde.saveplot(losshistory, train_state, issave=True, isplot=True)


if __name__ == "__main__":
    main()
```

![image](https://user-images.githubusercontent.com/52651366/87875598-f8bc6e80-ca04-11ea-894f-d10cf2142b9f.png)

**Comment by lululxvi** [comment]
Double check u. Is it 42 x 1 2d array or 42 1d array?

**Comment by 979736316** [comment]
> Double check u. Is it 42 x 1 2d array or 42 1d array?

Yes, I set "u = np.reshape(u, (-1, 1))", now there will be no errors, but I encountered a new error, as shown below:
![image](https://user-images.githubusercontent.com/52651366/87895358-cdbf3280-ca77-11ea-975b-b79a498afbc6.png)

**Comment by 979736316** [comment]
Thank you. Now I have solved this problem

**Comment by xiaowodaweiwang** [comment]
@LanPeng-94 , Have you ever process the problem successfully? I've tried to solve your problem by using the dde.Variable, but an error raised:
```UnimplementedError                        Traceback (most recent call last)
[/usr/local/lib/python3.11/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1406     try:
-> 1407       return fn(*args)
   1408     except errors.OpError as e:

10 frames
UnimplementedError: Cast string to float is not supported
	 [[{{node Adam_12/update_Variable_22/Cast_2}}]]

During handling of the above exception, another exception occurred:

UnimplementedError                        Traceback (most recent call last)
[/usr/local/lib/python3.11/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1424                     '\nsession_config.graph_options.rewrite_options.'
   1425                     'disable_meta_optimizer = True')
-> 1426       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1427 
   1428   def _extend_graph(self):

UnimplementedError: Graph execution error:

Detected at node 'Adam_12/update_Variable_22/Cast_2' defined at (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
    File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
    File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
    File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    File "<ipython-input-40-2cba9925109a>", line 1, in <cell line: 0>
    File "/usr/local/lib/python3.11/dist-packages/deepxde/utils/internal.py", line 22, in wrapper
    File "/usr/local/lib/python3.11/dist-packages/deepxde/model.py", line 140, in compile
    File "/usr/local/lib/python3.11/dist-packages/deepxde/model.py", line 199, in _compile_tensorflow_compat_v1
    File "/usr/local/lib/python3.11/dist-packages/deepxde/optimizers/tensorflow_compat_v1/optimizers.py", line 72, in get
Node: 'Adam_12/update_Variable_22/Cast_2'
Cast string to float is not supported
	 [[{{node Adam_12/update_Variable_22/Cast_2}}]]

Original stack trace for 'Adam_12/update_Variable_22/Cast_2':
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py", line 37, in <module>
  File "/usr/local/lib/python3.11/dist-packages/traitlets/config/application.py", line 992, in launch_instance
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelapp.py", line 712, in start
  File "/usr/local/lib/python3.11/dist-packages/tornado/platform/asyncio.py", line 205, in start
  File "/usr/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
  File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 510, in dispatch_queue
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 499, in process_one
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/kernelbase.py", line 730, in execute_request
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py", line 383, in do_execute
  File "/usr/local/lib/python3.11/dist-packages/ipykernel/zmqshell.py", line 528, in run_cell
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
  File "<ipython-input-40-2cba9925109a>", line 1, in <cell line: 0>
  File "/usr/local/lib/python3.11/dist-packages/deepxde/utils/internal.py", line 22, in wrapper
  File "/usr/local/lib/python3.11/dist-packages/deepxde/model.py", line 140, in compile
  File "/usr/local/lib/python3.11/dist-packages/deepxde/model.py", line 199, in _compile_tensorflow_compat_v1
  File "/usr/local/lib/python3.11/dist-packages/deepxde/optimizers/tensorflow_compat_v1/optimizers.py", line 72, in get
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/training/optimizer.py", line 508, in minimize
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/training/optimizer.py", line 747, in apply_gradients
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/training/optimizer.py", line 120, in update_op
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/training/adam.py", line 223, in _apply_dense
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/ops/math_ops.py", line 1021, in cast
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2130, in cast
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/op_def_library.py", line 796, in _apply_op_helper
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 2701, in _create_op_internal
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/framework/ops.py", line 1196, in from_node_def
```
Here is my code:
```
import numpy as np
import matplotlib.pyplot as plt
import deepxde as dde
from deepxde.backend import tf

T=1
geom=dde.geometry.Interval(0,1)
timedomain = dde.geometry.TimeDomain(0, T)
geotime = dde.geometry.GeometryXTime(geom, timedomain)

def pde(x,y):
  dy_t = dde.grad.jacobian(y,x,i=0,j=1)
  dy_xx = dde.grad.hessian(y,x,i=0,j=0)
  eq = dy_t-dy_xx
  return eq

alpha = dde.Variable(4.)
beta = dde.Variable(5.)

def boundary_l(x, on_boundary):
    return on_boundary and dde.utils.isclose(x[0], 0)


def boundary_r(x, on_boundary):
    return on_boundary and dde.utils.isclose(x[0], 1)


def func_bc_left(x):
  return tf.exp(-alpha*x[:,1:2])

def func_bc_right(x):
  return tf.exp(-beta*x[:,1:2])

bc1 = dde.icbc.DirichletBC(geotime, func_bc_left, boundary_l)
bc2 = dde.icbc.DirichletBC(geotime, func_bc_right, boundary_r)
ic = dde.icbc.IC(geotime, func_bc_left, lambda _, on_initial: on_initial)


data = dde.data.TimePDE(
    geotime,
    pde,
    [bc1,bc2,ic],
    num_domain=40,
    num_boundary=20,
    num_initial=10,
    num_test=10000
)

layer_size = [2] + [32]*3 + [1]
activation='tanh'
initializer = "Glorot uniform"
net = dde.nn.FNN(layer_size, activation, initializer)
model = dde.Model(data, net)

model.compile("adam", lr='0.001', external_trainable_variables=[alpha, beta])
variable = dde.callbacks.VariableValue([alpha, beta], period=1000)
losshistory, train_state = model.train(iterations=30000, callbacks=[variable])
```
I changed some codes eg. replace tf.Variable with dde.Variable, but doesn't work, could you help me? Thanks a lot!
