### ISSUE TITLE
More examples on mfnn, opnn and resnet

### ISSUE THREAD

**Issue by xanderyin** [lululxvi/deepxde#88]
Dear Dr Lu,

When learning the PDE for use, all most of the examples are using fnn, while examples on mfnn, opnn and resnet are lacking. Can you please provide some examples on them, i.e. the examples from your papers, to be included in the deepxde. thank you!

**Comment by lululxvi** [comment]
FNN is sufficient for most examples, and all the examples in the paper DeepXDE use FNN. Of course, you can also use ResNet.

MFNN and OpNN are used for multi-fidelity learning and operator learning, not PINNs.
