### ISSUE TITLE
TypeError: pde() got an unexpected keyword argument 'X'

### ISSUE THREAD

**Issue by smao-astro** [lululxvi/deepxde#89]
Hi Lu,

After update to the latest commit (0bd5d1b209be313adef97c557972ab75850b2c12), I encounter an error when running `examples/Burgers.py`

>  WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/losses.py:20: The name tf.losses.softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.softmax_cross_entropy instead.
> 
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/maps/map.py:13: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/maps/fnn.py:82: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.Dense instead.
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow_core/python/layers/core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `layer.__call__` method instead.
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/model.py:194: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
> 
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/model.py:196: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> 2020-07-17 17:48:42.421598: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-07-17 17:48:42.433106: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa1f2c192a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-07-17 17:48:42.433135: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> WARNING:tensorflow:From /Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/model.py:197: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
> 
> Traceback (most recent call last):
>   File "Burgers.py", line 59, in <module>
>     main()
>   File "Burgers.py", line 44, in main
>     model.compile("adam", lr=1e-3)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/utils.py", line 51, in wrapper
>     result = f(*args, **kwargs)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/model.py", line 82, in compile
>     self.losses = self.data.losses(self.net.targets, self.net.outputs, loss, self)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/data/pde.py", line 75, in losses
>     return tf.cond(tf.equal(model.net.data_id, 0), losses_train, losses_test)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1224, in cond
>     orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1061, in BuildCondBranch
>     original_result = fn()
>   File "/Users/kyika/.venvs/deepxde/lib/python3.6/site-packages/deepxde/data/pde.py", line 49, in losses_train
>     f = self.pde(model.net.inputs, outputs, X=self.train_x)
> TypeError: pde() got an unexpected keyword argument 'X'

Maybe it is introduced from 3d06caeb0e31d8c769d24268cd0c63e6379d181e?

**Comment by lululxvi** [comment]
Yes, it is a bug. I have fixed it.

**Comment by smao-astro** [comment]
Thanks, I will close the issue.
