### ISSUE TITLE
how to enforce some hard boundary conditions 

### ISSUE THREAD

**Issue by jjtwwdei** [lululxvi/deepxde#92]
Hello, 

I have a problem of implementing a special boundary condition. For example I have (x, y) maps to (u, v). One boundary condition is when x = 0, u = y(0.4 -y). Since boundary condition is hard to train in as soft one. If I want to make it hard boundary condition, how can I do that. The tricky thing is that it involves the output in the condition. Do you know any ways to do this.

Thanks,
jjtwwdei

**Comment by lululxvi** [comment]
see "Q: By default, initial/boundary conditions are enforced in DeepXDE as soft constraints. How can I enforce them as hard constraints?" at FAQ.

**Comment by jjtwwdei** [comment]
The thing is that the hard boundary requires the output of NN to be a function of inputs, not a constant for example, 0. I will take a example that N(x, y) = U. We would like that on the boundary of of x =0, let u = y^2, which indicates N(0, y) = y^2. I am not sure how enforce this kind of hard constraints. For the constant case, I have read the repo you mentioned. Thanks.

**Comment by lululxvi** [comment]
It is the same. Let `NN(x, y)` be the network with inputs `x` and `y`, then the output transform could be `x * NN(x, y) + y**2`. The transform is not unique, and this is just a possible example.

**Comment by jjtwwdei** [comment]
This is a smart trick. I have never think of this. Thanks.
