### ISSUE TITLE
Argument ‘sigmas’ in ‘dde.nn.MsFFN’ for a 2D (time-independent) problem

### ISSUE THREAD

**Issue by ach14012022** [lululxvi/deepxde#923]
Hello @lululxvi and other researchers. 
There is a 1D example for Multi-scale Fourier feature networks in:
https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/poisson.1d.multiscaleFourier.html
It is not clear how to give values to the argument ‘sigmas’ in ‘dde.nn.MsFFN’. I have in mind to apply MsFFN to a 2D (time-independent) problem. Any idea, please?
Tnx so much.

**Comment by praksharma** [comment]
Do you know what a Fourier feature is? Or have you looked into the [source code](https://github.com/lululxvi/deepxde/blob/03931b15948395c4642849fd6dd5eab07e4ae1a4/deepxde/nn/tensorflow_compat_v1/msffn.py#L6)?

The `sigmas` are the list of standard deviation of the distribution of fourier feature embeddings. This is not the full implementation of Fourier network from the original paper. I suggest you reading the paper to understand what it means. You can skip the derivation section in the [paper](https://bmild.github.io/fourfeat/).

**Comment by ach14012022** [comment]
Thank you.
I solved it.
