### ISSUE TITLE
A question about the code in Docs

### ISSUE THREAD

**Issue by jianchiz** [lululxvi/deepxde#936]
why the Robin boundary condition in the example( Poisson equation in 1D with Dirichlet/Robin boundary conditions) is 
bc_r = dde.icbc.RobinBC(geom, lambda X, y: y, boundary_r)
.For Neumann boundary condition in the example(Poisson equation in 1D with Dirichlet/Neumann boundary conditions) is 
bc_r = dde.icbc.NeumannBC(geom, lambda X: 2*(X+1), boundary_r) .
not is 
bc_r = dde.icbc.NeumannBC(geom, lambda X,y: 2*(X+1), boundary_r)

**Comment by praksharma** [comment]
Can you please format the post?

Why the Robin boundary condition in [Poisson equation in 1D with Dirichlet/Robin boundary conditions](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/poisson.1d.dirichletrobin.html) is 
```
bc_r = dde.icbc.RobinBC(geom, lambda X, y: y, boundary_r)
```
For Neumann boundary condition in [Poisson equation in 1D with Dirichlet/Neumann boundary conditions](https://deepxde.readthedocs.io/en/latest/demos/pinn_forward/poisson.1d.neumanndirichlet.html) is 
```
bc_r = dde.icbc.NeumannBC(geom, lambda X: 2*(X+1), boundary_r) 
```
but not 
```
bc_r = dde.icbc.NeumannBC(geom, lambda X,y: 2*(X+1), boundary_r)
```

**Comment by praksharma** [comment]
I think you should learn how `lambda` works.

**Comment by jianchiz** [comment]
@praksharma This is my first time to use github. Thank you for your advice on format.
I roughly know the usage of lambda function.I found that my problem had nothing to do with the use of lambda function.This should be the code format used for different boundary conditions in DeepXDE
For example,in the `Docs,`classdeepxde.icbc.boundary_conditions.RobinBC(geom, func, on_boundary, `component=0)`,
It say "Robin boundary conditions: dy/dn(x) = func(x, y).",so for Robin boundary,it need " X and y."
but for `classdeepxde.icbc.boundary_conditions.NeumannBC(geom, func, on_boundary, component=0)`,
It say"Neumann boundary conditions: dy/dn(x) = func(x)."
so it only need "X”？
But I don't know if using"X" and" Y" are correct in NeumanBC

**Comment by jianchiz** [comment]
@praksharma Thank you for your advice.
