### ISSUE TITLE
Integral PDE

### ISSUE THREAD

**Issue by yangheart** [lululxvi/deepxde#95]
Dear Lu,
 
I studied your example about the IDE which solves the ODE involving integral of the unknown function. I am wondering if this method can be applied to solve PDE involving integral of the unknown function?

For example, consider the following PDE for the unknown function y(x,t), where x is in [0, pi/2] and t is in [0,1]. The integral is only with respect to the space-variable x from 0 to pi/2. The exact solution is y(x,t)=e^{-t} sin(x). 

y_t = y_xx + \int_{0}^{pi/2} y(x_1,t) dx_1 - e^{-t},
y(0,t) = 0, y(pi/2,t) = e^{-t},
y(x,0)=sin(x).

I tried to apply your IDE method to this problem. Firstly, since the current integral domain is fixed from 0 to pi/2 but the integral domain in your IDE example is from 0 to x. I modified your code in IDE to fit the integral domain according to the Gaussian quadrature method and I believed the modification is suitable. However,  there are still some other problems. Could you help me to figure this out? Thank you for your time! Here is my code. 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import sys
sys.path.insert(0,"/Users/sichenchen/Desktop/research/deepxde")
import deepxde as dde
from deepxde.backend import tf

def main():
    def ide(x, y, int_mat):
        lhs = tf.matmul(int_mat, y)
        y_x = tf.gradients(y, x)[0]
        dy_x, dy_t = y_x[:,0:1], y_x[:, 1:2]
        dy_xx = tf.gradients(y_x, x)[0][:, 0:1]
        rhs = dy_t - dy_xx + tf.exp(-x[:,1:2])

        return rhs[: tf.size(lhs)]-lhs

    def func1(x):
        return np.exp(-x)
    def func2(x):
        return np.sin(x)
    def boundaryl(x, on_boundary):
        return  on_boundary and np.isclose(x[0], 0)
    def boundaryr(x, on_boundary):
        return on_boundary and np.isclose(x[0], np.pi/2)
    def sol(x):
        return np.exp(-x[:, 1:2])*np.sin(x[:, 0:1])

    geom = dde.geometry.Interval(0, np.pi/2)
    timedomain = dde.geometry.TimeDomain(0, 1)
    geomtime = dde.geometry.GeometryXTime(geom, timedomain)

    bc_l = dde.DirichletBC(geomtime, lambda x: np.zeros((len(x), 1)), lambda _, on_boundary: boundaryl, component=0)
    bc_r = dde.DirichletBC(geomtime, lambda x: func1(x[:,1:2]), lambda _, on_boundary: boundaryr, component=0)
    ic = dde.IC(geomtime, lambda x: func2(x[:, 0:1]), lambda _, on_initial: on_initial)
    quad_deg = 16
    data = dde.data.IDE(
        geomtime, ide, [bc_l,bc_r, ic], quad_deg = 16, num_domain=2000, num_boundary=100, solution=sol
    )
    net = dde.maps.FNN([2] + [20] * 3 + [1], "tanh", "Glorot normal")
    model = dde.Model(data, net)

    model.compile("adam", lr=1e-3)
    model.train(epochs=15000)
    model.compile("L-BFGS-B")
    losshistory, train_state = model.train()
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)

if __name__ == "__main__":
    main()

Traceback (most recent call last):
  File "pdeint.py", line 60, in <module>
    main()
  File "pdeint.py", line 45, in main
    data = dde.data.IDE(
  File "/Users/sichenchen/Desktop/research/deepxde/deepxde/data/ide.py", line 44, in __init__
    super(IDE, self).__init__(
  File "/Users/sichenchen/Desktop/research/deepxde/deepxde/data/pde.py", line 44, in __init__
    self.train_next_batch()
  File "/Users/sichenchen/Desktop/research/deepxde/deepxde/utils.py", line 23, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sichenchen/Desktop/research/deepxde/deepxde/data/ide.py", line 92, in train_next_batch
    self.train_x = np.vstack((x_bc, self.train_x, x_quad))
  File "<__array_function__ internals>", line 5, in vstack
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 2 has size 1

**Comment by lululxvi** [comment]
Unfortunately, currently DeepXDE does not support integral PDE. The reason is that to handle the integral operator, we have to do a numerical discretization, which is case by case. If you read the algorithm part of DeepXDE paper, you will see that the idea is straightforward, although the coding could be tricky and dirty. If you want, you can modify the source code, and we can discuss if you have questions.

**Comment by yangheart** [comment]
Dear Lu,
I tried to modify the codes in order to achieve my goals. However, I have a question about the Gaussian quadrature, like how to calculate the value of y corresponding to the allocation points in the Gaussian quadrature method.

**Comment by lululxvi** [comment]
It may be helpful to look at the `train_next_batch()` on how to generate the input points to the network.

**Comment by yangheart** [comment]
Thank you so much for your suggestions! Based on that, I have solved the integral problem in my case. I am going to close it.

**Comment by Sakshi21299** [comment]
@yangheart I have a similar problem and I am facing an error while implementing IPDEs. I have tried changing the ide code but I am getting an error. Could you share how you modified ide code to accommodate IPDEs in deepxde? 
Any help is much appreciated.

**Comment by yangheart** [comment]
Hi, I am just a newbie in coding so that I still cannot change codes in the package. I just use lu's ideas and write a simple code to implement my equation.

**Comment by Sakshi21299** [comment]
Dear Yangheart, 
Thanks for your response. I have fixed my code to accommodate for IPDEs. However, I don't understand how we can change the integration limits from 0 to x to something else. Say I want to change it to x to L where L is a constant. As you had mentioned earlier that you could fix this could you throw some light upon how to make this change?

**Comment by yangheart** [comment]
Hi, sorry for the late response. You need to change the code here:
def quad_points(self, X):
        def get_quad_points(x):
            return (self.quad_x + 1) * x / 2

        return np.hstack(list(map(lambda xi: get_quad_points(xi[0]), X)))[:, None]

    def get_int_matrix(self, training):
        def get_quad_weights(x):
            return self.quad_w * x / 2
 in ide.py

If your upper bound is a constant, let it to b, x/2 should be b/2.(because the lower bound is 0)
If your lower bound is not 0, then x/2 should be (a+b)/2 according to the gaussian quadrature.

**Comment by allbluelai** [comment]
Dear @lululxvi  ,
Hello. In the demo [Volterra_IDE.py](https://github.com/lululxvi/deepxde/blob/master/examples/Volterra_IDE.py), the integral on the left side is $\int_0^x K(x, t) y(t) dt$. If I want to change $K(x, t)$ into $K(x_0, t)$. **How do I assign a value $x_0$ to $K(x, t)$?**
x_0 ∈ Definition Domain

**Comment by allbluelai** [comment]
> Dear @lululxvi ,
> Hello. In the demo [Volterra_IDE.py](https://github.com/lululxvi/deepxde/blob/master/examples/Volterra_IDE.py), the integral on the left side is $\int_0^x K(x, t) y(t) dt$. If I want to change $K(x, t)$ into $K(x_0, t)$. **How do I assign a value $x_0$ to $K(x, t)$?**
> x_0 ∈ Definition Domain

Dear @lululxvi ,
Sorry, my question is incorrectly stated. I want to assign a value $t_0$ to $y(t)$. **How do I modify the code?**

**Comment by lululxvi** [comment]
Do you try to solve for $\int_0^x K(x, t) y(t_0) dt$?

**Comment by allbluelai** [comment]
> Do you try to solve for $\int_0^x K(x, t) y(t_0) dt$?

No. t_0 is the Gaussian quadrature point.
Actually, my integral function is $\int_0^{2π}\int_{-1}^{1} y(h,θ',φ')P(θ,φ,θ',φ')sin(θ')dθ'dφ'$
θ'∈[0,2π], φ'∈[-1,1] and θ', φ' are the Gaussian quadrature point.
In the integral function, h, θ and φ are the independent variable. 

**How can I assign the Gaussian quadrature point (θ' and φ') to y(h,θ',φ')**?
![MommyTalk1629267541262](https://user-images.githubusercontent.com/37734505/129847807-d052a081-42d1-492a-8859-edffc1fd78b2.png)

**Comment by lululxvi** [comment]
I see. You need the double integral. It is doable. The basic idea is to write the double integral as a sum. You can check the code of 1d IDE.

Actually, you can check the paper https://epubs.siam.org/doi/abs/10.1137/18M1229845, where we have double integral in 2D, and the code is here https://github.com/lululxvi/deepxde/blob/master/deepxde/data/fpde.py

**Comment by JunaidAkhter** [comment]
Hi, 
I am new to PINNS and to IDE. I would be grateful if you could answer few of my basic question:
Where does the matrix (int_mat) come from and how is it created. As far as I can see, the matrix multiplication between this matrix and y (the solution) is actually the representation of the integral in the IDE right? Can you suggest me some resources where I can read about it?
Second, it would be great if you could write the documentation for IDE section similar to what you have nicely done for forward and inverse problems. It will help a lot. 

Kind regards, 
Junaid.

**Comment by lululxvi** [comment]
> Where does the matrix (int_mat) come from and how is it created. As far as I can see, the matrix multiplication between this matrix and y (the solution) is actually the representation of the integral in the IDE right? Can you suggest me some resources where I can read about it? 

Yes, see DeepXDE paper.
