### ISSUE TITLE
Using x as array index

### ISSUE THREAD

**Issue by cxz260** [lululxvi/deepxde#97]
Hi Lu, thanks for the great library--sorry this is not an issue, I just have a question which has held me for a while:

I have a global constant 1D array  C, whose index will be my 1-D ode's input x(which are integers), how can I achieve dy/dx=C[x]*y? 

When I try sth like:

ix=tf.math.floor(x)
rhs=C[ix]*y

The error msg: "Cannot convert a symbolic Tensor (add:0) to a numpy array"

Thanks for your help,

Eddie

**Comment by lululxvi** [comment]
`lx` is tf tensor, and `C` is np array. np array cannot accept tf tensor. See https://github.com/lululxvi/deepxde/issues/79 how to use both np and tf to define PDE.

**Comment by cxz260** [comment]
Thank a lot, will try it out.

**Comment by cxz260** [comment]
Thank you very much, Lulu. It worked!
