### ISSUE TITLE
New example runs incorrectly

### ISSUE THREAD

**Issue by 979736316** [lululxvi/deepxde#98]
I'm concerned that you uploaded a new example, "fractional_Poisson_1d," but I showed an error at runtime.
![image](https://user-images.githubusercontent.com/52651366/89307283-7a69f880-d6a3-11ea-90bc-51a61cb63190.png)
In fact, I've put the "fpde.py" in the "deepxde.data" list.
![image](https://user-images.githubusercontent.com/52651366/89307548-ccab1980-d6a3-11ea-892b-734cb813f42c.png)

**Comment by lululxvi** [comment]
You need to download the latest version from Github, not pip or conda.

**Comment by 979736316** [comment]
> You need to download the latest version of DeepXDE from Github, not pip or conda.

Yes, I tried. I downloaded the "zip file" again in GitHub, but unfortunately, it failed.

**Comment by lululxvi** [comment]
Do you set the correct path of DeepXDE?

**Comment by 979736316** [comment]
> Do you set the correct path of DeepXDE?

Yes, I run other examples that work correctly.

**Comment by lululxvi** [comment]
Reinstall the old version, and try again?

**Comment by 979736316** [comment]
> Uninstall the old version from pip and conda, and try again?

Thanks for your advice, I reinstalled Deepxde. He still failed

**Comment by lululxvi** [comment]
Does this https://github.com/lululxvi/deepxde/issues/3 help?

**Comment by 979736316** [comment]
> 这[＃3有](https://github.com/lululxvi/deepxde/issues/3)帮助吗？

Thank you. When I added those two lines, it can run now.
