### ISSUE TITLE
计算域中障碍物的设置问题

### ISSUE THREAD

**Issue by ZHSLZ** [lululxvi/deepxde#981]
LULU博士，您好。我是一个DEEPXDE的新手，我在模拟一维浅水波问题（一维渠道下游存在一个三角形的障碍物）时不知道怎么去设置计算域来进行计算。我想咨询一下您，图示中的算例我该怎么去设置红框标注处（三角形障碍物）的geometry呢？万分感谢希望能够得到您的解答。

![image](https://user-images.githubusercontent.com/116650342/197784580-c23577fe-2ba5-4cb9-b01d-2e0e51f1f458.png)

**Comment by lululxvi** [comment]
`dde.geometry.Triangle` https://deepxde.readthedocs.io/en/latest/modules/deepxde.geometry.html#deepxde.geometry.geometry_2d.Triangle
